src/game_battle.cpp
src/game_event.cpp
src/game_event.h
src/game_interpreter.cpp
src/game_interpreter_map.cpp
src/game_message.cpp
src/game_message.h
src/scene_debug.cpp
src/window_message.cpp

~~I'll do something more here, so do not pull yet.~~
* Fix #335 
* Fix #367
* Fix #368
* The debug window (where you can change variables and switches) will now refresh the map events

Fix some bugs

---

src/bitmap.cpp
src/game_battle.cpp
src/game_battle.h
src/game_battler.cpp
src/game_battler.h
src/game_interpreter_battle.cpp
src/game_interpreter_battle.h
src/game_interpreter_map.cpp
src/game_screen.cpp
src/game_screen.h
src/scene_battle.cpp
src/scene_battle.h
src/scene_battle_rpg2k.cpp
src/scene_battle_rpg2k3.cpp
src/window_battlemessage.cpp
src/window_message.cpp

Battle events and animations

---

builds/vs2010/EasyRPG.vcxproj
builds/vs2010/EasyRPG.vcxproj.filters
src/Makefile.am
src/game_battler.cpp
src/game_event.cpp
src/game_interpreter.cpp
src/game_interpreter_map.cpp
src/game_map.cpp
src/game_message.cpp
src/game_message.h
src/game_party.cpp
src/game_party.h
src/player.cpp
src/scene_battle.cpp
src/scene_item.cpp
src/sprite_timer.cpp
src/sprite_timer.h
src/spriteset_battle.cpp
src/spriteset_battle.h
src/spriteset_map.cpp
src/spriteset_map.h
src/window_message.cpp

This closes 5 issues:
#402 - #406

Timers & Battle fixes

---

builds/android/src/org/easyrpg/player/EasyRpgPlayerActivity.java
builds/android/src/org/easyrpg/player/Utilitary.java
builds/android/src/org/easyrpg/player/virtual_buttons/GameButton.java
builds/android/src/org/easyrpg/player/virtual_buttons/Utilitary.java
builds/android/src/org/easyrpg/player/virtual_buttons/VirtualButton.java
builds/android/src/org/easyrpg/player/virtual_buttons/VirtualCross.java
builds/android/src/org/libsdl/app/SDLActivity.java
src/sdl_ui.cpp

Hi everyone !
So this is my work related to #438 . All the Button Mapping has been rebuild :
:+1: The code is now clearer
:+1: Modular
:+1: Ready to implement #288 :smiley: 
:+1: The Buttons now display the letter associated (always to be ready for #288 )
I also fixed #437 , you can now move your character by sliding your finger on the Virtual Cross, and there is no more "infinite race" when you slide out the Virtual Cross ! I think players will enjoy that features :smile: .

Button mapping rebuild + Fix #437

---

builds/android/src/org/easyrpg/player/virtual_buttons/ButtonMappingActivity.java

As suggested by Ghabry, I used directly the value of keycode. I tested on a test project : everything is alright.

Android : Fix the SDK compatibility of the Button Mapping System

---

src/game_character.cpp
src/game_character.h
src/game_map.cpp
src/game_map.h
src/game_player.cpp
src/game_player.h
src/game_vehicle.cpp
src/sprite_airshipshadow.cpp
src/sprite_character.cpp
src/tilemap_layer.cpp
src/window.cpp

* Jumps will now go through the same arc at the same speed they do in rpg maker
* If a failed move triggers a collision event, the stop_count is reset. This makes easier some collision-based combat games.
Not ready for merge yet.

Remake jump, add looping maps and other changes

---

src/filefinder.cpp
src/game_actor.cpp
src/game_battlealgorithm.cpp
src/game_character.cpp
src/game_event.cpp
src/game_interpreter.cpp
src/game_interpreter_battle.cpp
src/game_interpreter_map.cpp
src/game_message.cpp
src/game_picture.cpp
src/player.cpp
src/player.h
src/scene_battle.cpp
src/scene_debug.cpp
src/scene_menu.cpp
src/sprite_battler.cpp
src/sprite_timer.cpp
src/spriteset_battle.cpp
src/window_battlecommand.cpp
src/window_battlestatus.cpp
src/window_menustatus.cpp
src/window_numberinput.cpp
src/window_skill.cpp

Something unexpected happened: RPG2k3 v1.10 was released.
For now I detect the new engine version by testing for "ultimate_rt_eb.dll" in the game directory. I assume this version will diverge from the original RPG2k3 sooner or later...
Cherry said that he will implement ```ThisEvent``` in the next update. This fix is not breaking anything because RPG_RT was displaying an error when doing this.
TODO

Rpg2k3 v1.10

---

src/game_picture.cpp
src/game_picture.h
src/platform/filefinder.php
src/sprite_battler.cpp
src/sprite_character.cpp
src/sprite_character.h
src/spriteset_map.cpp
src/spriteset_map.h

Yeah I moved two lines around with horrible consequences... :(
They are now at there old position :)
Please test (the emscripten) games if this unbroke everything.
Don't merge yet, want to fix some potential race conditions in the async code tomorrow.

Fix Tilemap z-layer bug in async-loading.

---

src/async_handler.cpp
src/battle_animation.cpp
src/game_event.cpp
src/game_map.cpp
src/sprite_battler.cpp

Another Async fix (Battle Animations).
Parallel events didn't start after save loading and the battle in EHR doesn't deadlock anymore :)

Final 0.3 blockers

---

builds/android/res/layout/main.xml

Of course this works only in game, not in other activities.
(Android programmation is so easy, just one xml parameter oO).

Fix #493 : Screen doesn't shutdown in game anymore

---

src/game_character.cpp

Fixes #486 .
Maybe it affects #501, I haven't looked into it.

Let characters in lower layer move below the hero

---

src/platform/emscripten-shell.html

Fix undefined spinnerElement warning
Prevent exception when pressing full screen button if js function is not ready
Remove some controls, place full screen button on right and make it more discrete
Vertically align canvas and fix 1X-2X resizing when the width is lesser than 640px

Emscripten: shell improvements

---

src/bitmap.cpp
src/screen.cpp

Basicly same as #494 but also works when oversaturated
Fixes #357
*Note* Don't merge yet. We are discussing currently faster alternatives (at least for under-saturate)

Fix screen saturation

---

builds/android/src/org/easyrpg/player/MainActivity.java

.nomedia file added, works like a charm ! Thanks to the user who send the message :).
The app now also create all the necessary folders, this will be usefull for everyone :).

.nomedia file + directory creation at startup

---

builds/android/src/org/easyrpg/player/MainActivity.java
builds/android/src/org/easyrpg/player/game_browser/GameBrowserActivity.java

@fdelapena , does it resolve the problem ?

Try to force Samsung's device to show the action overflow button

---

src/game_actor.cpp
src/game_actor.h
src/game_battler.cpp
src/game_interpreter.cpp
src/game_interpreter.h
src/game_party.cpp
src/game_temp.cpp
src/game_temp.h
src/scene_map.cpp
src/scene_menu.cpp

#524 and #525
Also refreshes the menu scene now because the changed values were not visible :/

Item Scene: Fix using of medicine and material items

---

src/game_character.cpp
src/game_event.cpp
src/game_event.h
src/game_interpreter.cpp
src/game_interpreter.h
src/game_interpreter_map.cpp
src/game_party.cpp
src/game_player.cpp
src/scene_map.cpp

Support multiple pending events and other fixes

---

builds/android/src/org/easyrpg/player/button_mapping/ButtonMappingActivity.java
builds/android/src/org/easyrpg/player/player/EasyRpgPlayerActivity.java

Fixes #536 
It should work now :).

Fix openOptionsMenu on Samsung devices

---

.gitignore
CMakeLists.txt
Makefile.am
builds/easyrpg-player.6.adoc
configure.ac

Add a manual page

---

CMakeLists.txt
README
builds/android/res/values-es/strings.xml
builds/android/res/values/strings.xml
builds/wii/meta.xml
configure.ac
resources/osx/Info.plist
resources/player.rc
src/options.h

And last minute Android explanation fix

Version 0.3.1

---

src/game_character.cpp
src/game_character.h
src/game_enemy.cpp
src/game_interpreter_map.cpp
src/game_map.cpp
src/game_player.cpp
src/game_switches.h
src/game_variables.h
src/rtp_table_bom.h
src/scene_battle.cpp
src/sprite.cpp
src/window_command.cpp
src/window_command.h

A bunch of tiny code issues collected together, mostly to fix UB or warnings. Should have no effect at all on any games.

Miscellanea

---

src/game_character.cpp
src/game_character.h
src/game_event.cpp
src/game_interpreter.cpp
src/game_interpreter.h
src/game_interpreter_map.cpp
src/game_interpreter_map.h
src/game_message.cpp
src/game_message.h
src/game_vehicle.cpp
src/game_vehicle.h
src/scene_battle.cpp
src/window.cpp
src/window_message.cpp

* Fixes #538 
* Fixes #589
* Fixes #618
and more.

Improve the game message system and fix some bugs

---

.tx/config
builds/android/res/values-de/strings.xml
builds/android/res/values-es/strings.xml
builds/android/res/values-fr/strings.xml
builds/android/res/values-zh/strings.xml
builds/android/res/values/strings.xml

This modified a lot of whitespace, use this URL https://github.com/EasyRPG/Player/pull/617/files?w=0 to only show "real" changes.

Transifex integration

---

builds/android/jni/src/org_easyrpg_player_player_EasyRpgPlayerActivity.cpp
builds/easyrpg-player.6.adoc
src/graphics.cpp
src/graphics.h
src/player.cpp
src/player.h
src/sdl_ui.cpp

Implement new FPS display behaviour

---

Makefile.am
src/game_interpreter.cpp
src/game_interpreter_map.cpp
src/game_map.cpp
src/game_player.cpp
src/utils.cpp
src/window_message.cpp

Includes some C++11 code, let's see if jenkins likes it.
* Fixes #636
* Fixes #433 (again)

Minor bug fixes

---

src/platform/sdl_audio.cpp

Emscripten: init SDL mixer frequency based on Web Audio API information

---

src/game_battle.cpp
src/game_interpreter_battle.cpp
src/game_interpreter_map.cpp
src/game_party.cpp
src/game_player.cpp
src/game_player.h
src/platform/sdl_audio.cpp
src/window_battlestatus.cpp

Fix #611, #652, #653, #654, #656, #659

---

src/al_audio.cpp
src/audio.h
src/game_character.cpp
src/game_event.cpp
src/game_interpreter_map.cpp
src/game_player.cpp
src/game_player.h
src/platform/al_audio.cpp
src/platform/al_audio.h
src/platform/sdl_audio.cpp
src/platform/sdl_audio.h

Fix #631, #655, #665, #667 and #669

---

src/platform/sdl_audio.cpp
src/scene_map.cpp
src/scene_map.h
src/spriteset_map.cpp

Fix OGG playback when system frequency is 48k and OGG 44.1k (same as the WAV bug)

Fix OGG in emscripten (hopefully)

---

.tx/config
builds/android/res/values-pt-rBR/strings.xml

Thanks Kennedy Cirino da silva and Daniel Paim de Mattos!

Add Portuguese (Brazil) translation.

---

src/game_interpreter.cpp
src/game_interpreter_map.cpp
src/game_interpreter_map.h
src/game_map.cpp
src/game_temp.cpp
src/game_temp.h
src/scene_battle.cpp

Fix #685 
Fix #688 
Just stuff that should be in 0.4 ...

Fix Inn and ChangeEquip

---

builds/android/jni/Application.mk
builds/android/jni/SDL2/Android.mk
builds/android/jni/SDL2_mixer/Android.mk
builds/android/jni/src/Android.mk
builds/android/res/values-de/strings.xml
builds/android/res/values-es/strings.xml
builds/android/res/values-hu/strings.xml
builds/android/res/values-ja/strings.xml
builds/android/res/values-pt-rBR/strings.xml
builds/android/res/values-zh/strings.xml
builds/android/res/values/strings.xml
builds/android/src/org/easyrpg/player/game_browser/GameBrowserHelper.java
builds/android/src/org/libsdl/app/SDLActivity.java

Fix #698 (needed toolchain recompile, nothing changed in Player)
Fix #699 (toolchain issue, cpufeatures lib hanged in 4.0.3)
Fix #413 (mostly toolchain :P, but needed changes to Player build system)

Android: Recursive games-subdirectory scan and mips/armeabi

---

src/sdl_ui.cpp

Fix vsync with OS X

---

src/game_interpreter_map.cpp
src/window_battlestatus.cpp

You must also check for a Victory handler when there is a Escape case
Fix #678 
Fix #702

Wadanohara: Fix the Battle against Orca

---

builds/vs2015/EasyRPG.sln
builds/vs2015/Player.vcxproj
builds/vs2015/PropertySheet.props

Easier then programming for Android :P
Don't merge yet. Have to recompile all dependencies for ARM on the server and manually enable ARM in the PR builder.

MSVC: Add ARM support

---

builds/android/res/values-de/strings.xml
builds/android/res/values-es/strings.xml
builds/android/res/values-fr/strings.xml
builds/android/res/values-hu/strings.xml
builds/android/res/values-ja/strings.xml
builds/android/res/values-pt-rBR/strings.xml
builds/android/res/values-zh/strings.xml

Just a friendly reminder what happens when you directly change the language source files and do not care about external translations…
Seems like the "How to Use" message completely disappeared from some languages.

Reminder: merge in translations from transifex 

---

src/game_actor.cpp
src/game_actor.h
src/game_battle.cpp
src/game_battlealgorithm.cpp
src/game_battler.cpp
src/game_battler.h
src/game_interpreter.cpp
src/game_party.cpp
src/game_party.h
src/output.cpp
src/output.h
src/player.cpp
src/scene_actortarget.cpp
src/scene_battle.cpp
src/window_actortarget.cpp
src/window_equip.cpp
src/window_shopparty.cpp
src/window_skill.cpp

Should handle all corner cases now.
Fixing bugs in the algorithms of used items/skills is not scope of this PR but I fixed some UseItem/UseSkill bugs.

Fix Skill/Item usability

---

builds/android/res/layout/settings_activity.xml
builds/android/res/values/strings.xml
builds/android/src/org/easyrpg/player/button_mapping/ButtonMappingActivity.java

Android: Fix #777 and #778

---

src/audio.cpp
src/audio.h
src/audio_al.cpp
src/audio_al.h
src/audio_sdl.cpp
src/audio_sdl.h
src/game_event.cpp
src/game_interpreter.cpp
src/sprite_battler.cpp

Fix #344, #744, #764

---

src/game_actor.cpp
src/game_actor.h
src/game_party.cpp
src/scene_battle.cpp
src/scene_battle_rpg2k3.cpp
src/scene_equip.cpp
src/scene_equip.h
src/scene_item.cpp
src/scene_menu.cpp
src/scene_skill.cpp
src/window_item.cpp
src/window_item.h
src/window_menustatus.cpp
src/window_menustatus.h

Also handles fixed equipment now :)

Battle: Fix item/skill usage check and equipment in battle test

---

src/game_character.cpp
src/player.cpp

This fixes the game-breaking bug reported by pee kiyo at the end of のび太戦記ACE (Nobisen ACE).

Minor fix before 0.4.1

---

src/game_actor.cpp

Weather Forecast: Bit cloudy with the sun shining!

Don't trust the SaveGameActor::ID anymore because of strange savegames

---

builds/android/res/values-de/strings.xml
builds/android/res/values-es/strings.xml
builds/android/res/values-ja/strings.xml
builds/android/res/values-ko/strings.xml

Let's keep this open, maybe there will be some late additions before the new version.

Add some new/missing strings before 0.4.1

---

src/battle_animation.cpp
src/game_actor.cpp
src/game_actor.h
src/game_battle.cpp
src/game_battlealgorithm.cpp
src/game_battlealgorithm.h
src/game_battler.cpp
src/game_battler.h
src/game_enemy.cpp
src/game_enemy.h
src/scene_battle_rpg2k3.cpp
src/scene_battle_rpg2k3.h
src/sprite.h
src/sprite_battler.cpp
src/sprite_battler.h
src/spriteset_battle.cpp
src/spriteset_battle.h

A bug in the newly added Attribute damage Multiplier returned 0 under certain circumstances :(

Fix Battle system regressions :/

---

src/game_battlealgorithm.cpp

attributes_set.size could be very hight 12> even if there is just one attribute "true"
So it needs to count how much attributes are "true"

fixes #840

---

Makefile.am
builds/vs2015/Player.vcxproj
builds/vs2015/Player.vcxproj.filters
src/midiprogram.h
src/midisequencer.cpp
src/midisequencer.h
src/midisynth.cpp
src/midisynth.h

Add fmmidi sources

---

src/background.cpp
src/cache.cpp
src/cache.h
src/frame.cpp
src/game_actor.cpp
src/game_battlealgorithm.cpp
src/game_interpreter_map.cpp
src/scene_battle.cpp
src/scene_battle.h
src/spriteset_battle.cpp
src/spriteset_battle.h

Two further oversights in the attribute multiplier :(
And that "Feuer um Mitternacht EX" problem with the non usable skill.

Fix battle bugs

---

builds/3ds/cia_builder/README.md

3DS: Removed hex_set reference in README.md

3DS: Removed hex_set reference in README.md

---

builds/android/app/src/main/res/values-th/strings.xml

Add Thai translation for Android app
I hope Easy-RPG Player will render Thai character correctly.
Cheer!

android app - Thai translation

---

src/async_handler.cpp

Should fix the Wannabe Smash Bros

URL encode % and #

---

builds/android/app/src/main/java/org/easyrpg/player/SettingsActivity.java
builds/android/app/src/main/res/layout/generic_separator.xml
builds/android/app/src/main/res/layout/settings_activity.xml

Hi everybody, 
here's a new pull request with my previous correction. I hope this time everything is alright! ^^

Some minor changes on layout and a function (v2) 

---

src/3ds_decoder.cpp
src/3ds_decoder.h

3DS: Added MP3 support and debug code for MIDI tracks.

3DS: Added MP3 support and debug code for MIDI tracks.

---

src/3ds_ui.cpp

3DS: Bugfix for games that use shift (Like Ib).

3DS: Bugfix for games that use shift (Like Ib).

---

src/game_character.cpp
src/game_character.h
src/game_event.cpp
src/game_event.h
src/game_map.cpp
src/game_map.h
src/game_player.cpp
src/game_player.h
src/game_vehicle.cpp
src/game_vehicle.h

Also fixes [gadesx's issue with character movement](https://community.easyrpg.org/t/problem-moving-various-events-at-time/260).
It does _not_ fix #884 in the case that one of the characters is a vehicle. I didn't even test whether a vehicle will trigger early updates (but it seems likely). Will wait for a testcase for that.

Fix #703, #884

---

builds/vs2015/PlayerLib.vcxproj
builds/vs2015/PlayerLib.vcxproj.filters
builds/vs2015/PropertySheet.props

MSVC: Use libsndfile, speexdsp resampler and ogg decoder

---

tests/filefinder.cpp

...which fixes the CMake build.

Add missing #include <cassert>

---

src/game_character.cpp
src/game_event.cpp
src/game_event.h
src/game_interpreter.cpp
src/game_interpreter.h
src/game_map.cpp
src/game_party.cpp
src/game_party.h
src/game_player.cpp
src/game_system.h
src/sprite_timer.cpp

* Fix #903
* Fix #927 
* Fix #929
* Fix #935
* Fix the first issue of #886, so please do not close it yet.

Fix some interpreter bugs

---

src/game_actor.cpp
src/game_actor.h
src/game_battlealgorithm.cpp

Fix regression introduced in 81c910a (SP cost calculation)

---

src/game_event.cpp
src/game_map.cpp

* Fixes the moving statue of the Yellow Space randomly disappearing
* Fixes hang after Garry heads up the stairs after the the Disturbing Doll room (thanks to android user Ren)

Fix two bugs in Ib

---

src/game_enemy.cpp
src/game_interpreter.cpp
src/sprite_battler.cpp
src/window_battlestatus.cpp

Fix battle issues in Embric

---

configure.ac
src/decoder_mpg123.cpp
src/decoder_mpg123.h
src/decoder_wildmidi.cpp
src/decoder_wildmidi.h

This should be replaced by some callback mechanism in the future, but works so far.

Add Audio decoder initialization locks

---

builds/android/app/src/main/java/org/easyrpg/player/game_browser/GameBrowserActivityAPI15.java
builds/android/app/src/main/res/layout/browser_api15_game_card_vertical.xml

Hello everyone, I improved the Gamebrowser when the size of the screen only permit to display one game per line, this is inspired by the @ItsSchoko 's mockup.
Hi hope you'll like this, here's a screenshot :

[Android] Improve the game browser for phone in vertical mode

---

src/player.cpp
src/window_gamelist.cpp

Fix Player #885 
Engine heuristic:　https://github.com/EasyRPG/Player/compare/master...Ghabry:encdetect?expand=1#diff-dc52f162280289dd2d4d97d82658362dR650
Language heuristic: https://github.com/EasyRPG/Player/compare/master...Ghabry:encdetect?expand=1#diff-dc52f162280289dd2d4d97d82658362dR834

Improve encoding detection and engine detection heuristics

---

src/game_battle.cpp
src/game_battle.h
src/game_party.cpp
src/scene_battle.cpp
src/scene_battle_rpg2k.cpp
src/scene_battle_rpg2k3.cpp
src/scene_battle_rpg2k3.h

see commit descriptions.
What still doesn't work is "fatigue" page condition because the formula is wrong.

Implement RPG2k3 interpreter logic

---

Makefile.am
builds/vs2015/PlayerLib.vcxproj
builds/vs2015/PlayerLib.vcxproj.filters
src/game_battler.cpp
src/game_map.cpp
src/game_map.h
src/game_party.cpp
src/game_player.cpp
src/game_player.h
src/game_targets.cpp
src/game_targets.h
src/scene.cpp
src/scene.h
src/scene_map.cpp
src/scene_skill.cpp
src/scene_teleport.cpp
src/scene_teleport.h
src/window_teleport.cpp
src/window_teleport.h

Basicly besides video the only two events that were not fully implemented ;) (okay the events were implemented already but not the skills to use them).
Probably due to lazyness, only took two hours to get this coded.
That TerrainTag commit unrelated, just observed this while testing and is easy fix.

Implement Skills Teleport and Escape

---

builds/android/app/src/main/jni/src/Android.mk

Needed for EasyRPG/buildscripts#11.

Android: add expat for XML parsing

---

src/game_interpreter.cpp
src/game_interpreter.h
src/game_player.cpp
src/window_message.cpp

e0a216f fixes #940 (now really)
43d2821 fixes the bug in Vampire X Knight reported by Florian
The remaining commits fix #989

Fix some minor bugs

---

src/font.cpp

NULL does not need to be casted

---

src/bitmap.cpp
src/bitmap.h
src/cache.cpp
src/image_bmp.cpp
src/image_bmp.h
src/image_png.cpp
src/image_png.h
src/image_xyz.cpp
src/image_xyz.h

This ends what @carstene1ns started :+1:

Image refactor

---

src/audio.cpp
src/game_battle.cpp
src/game_battle.h

Small one, but really annoying warnings :angry:

Resolve some GCC -pedantic warnings

---

builds/android/app/src/main/AndroidManifest.xml
builds/android/app/src/main/java/org/easyrpg/player/player/EasyRpgPlayerActivity.java
builds/android/app/src/main/res/layout/activity_settings_main.xml
builds/android/app/src/main/res/menu/player.xml
builds/android/app/src/main/res/values/strings.xml

At least on my Android 4.0.3 :+1: 
Minor UX improvement: Edit layout while ingame :o
Fixes #1012.

Android: Fix Drawer rendering error in the PlayerActivity and minor UX improvements

---

src/scene_item.cpp
src/scene_skill.cpp
src/scene_teleport.cpp
src/scene_teleport.h

This fixes an oversight in #690 and the switch handling is a bonus.
Final bugfix for 0.5...

Handle Items that invoke a Skill of type Switch, Teleport or Escape

---

README.md
builds/vs2015/PropertySheet.props
src/game_actor.cpp
src/game_battlealgorithm.cpp
src/rtp_table.cpp
src/window_keyboard.cpp
src/window_message.cpp

And fix a bug detected by the debug crt.

MSVC: Use utf8 compiler argument introduced in VS2015.2

---

src/game_party.cpp

Sorry!
data.item_ids is actually not sequential, so you can't use i to index Data::items (can be even seen in line 199).

Regression fix for item_usage

---

src/game_actor.cpp
src/game_actor.h
src/game_character.cpp
src/game_event.cpp
src/game_interpreter.cpp
src/game_party.cpp
src/game_party.h
src/game_player.cpp
src/game_switches.cpp
src/game_variables.cpp
src/scene_order.cpp
src/window_item.cpp

All of them are minor stuff. See commit logs.

Fix #716, #920, #962, #1072 and #1082

---

builds/wii/Makefile
src/output.cpp

Expected build failure
**Dont't merge needs buildscripts update & recompile**

Wii: Use ICU. Buildfix for latest devkitPPC

---

builds/3ds/Makefile

also add WildMidi for later use

3ds buildfix: use citro3d

---

src/plane.cpp
src/tilemap_layer.cpp

More fixes to follow up #1098
* Black should now be drawn out of bounds of the map (fixes #1101)
* Parallax backgrounds now shake too (before they didn't). The behavior is different for looping maps and non-looping maps. For non-looping maps, basically any area of the screen that is drawn black because it is out of the map bounds is still drawn black (regardless of if the panorama loops). The panorama covers everything else.

Screen shake fixes

---

builds/android/app/build.gradle

[Android] Return to Compile SDK Version 23

---

src/game_character.cpp
src/game_interpreter.cpp
src/game_player.cpp
src/scene_file.cpp
src/scene_save.cpp
src/scene_shop.cpp
src/sdl_ui.cpp
src/window_shopnumber.cpp

Fix #1051, #1110, #1114 (dupe of #658) , #1118, #1119 & Wii build

---

CMakeLists.txt
Makefile.am
builds/android/app/src/main/java/org/easyrpg/player/button_mapping/ButtonMappingActivity.java
builds/android/app/src/main/java/org/easyrpg/player/button_mapping/ButtonMappingManager.java
builds/android/app/src/main/java/org/easyrpg/player/button_mapping/VirtualButton.java
builds/android/app/src/main/java/org/easyrpg/player/button_mapping/VirtualButtonRectangle.java
builds/android/app/src/main/res/values/strings.xml
builds/vs2015/PlayerLib.vcxproj
builds/vs2015/PlayerLib.vcxproj.filters
src/drawable.h
src/fps_overlay.cpp
src/fps_overlay.h
src/graphics.cpp
src/graphics.h
src/input_buttons.h
src/input_buttons_desktop.cpp
src/input_buttons_gekko.cpp
src/message_overlay.cpp
src/player.cpp
src/player.h
src/scene_gamebrowser.cpp

This adds speedup (x3) via F and x10 via F+PLUS.
Fix #1010

Add fast forward option

---

src/plane.cpp

I introduced this bug
in fc546f70. The rendering problem is caused by the bug and the interaction between a vertically looping map, transparent tiles, and a parallax BG. Details are in the commit message.
Quick PR to fix it.

Fix BG bug introduced in fc546f70

---

builds/android/app/src/main/res/values-be/strings.xml
builds/android/app/src/main/res/values-de/strings.xml
builds/android/app/src/main/res/values-es/strings.xml
builds/android/app/src/main/res/values-hu/strings.xml
builds/android/app/src/main/res/values-ja/strings.xml
builds/android/app/src/main/res/values-pt-rBR/strings.xml
builds/android/app/src/main/res/values-ru/strings.xml
builds/android/app/src/main/res/values-uk/strings.xml
builds/android/app/src/main/res/values-zh-rTW/strings.xml

(let this stay open until release, maybe we get some new strings until then)

Update translations for 0.5.1

---

src/3ds_ui.cpp
src/3ds_ui.h
src/audio_3ds.cpp
src/audio_3ds.h
src/filefinder.cpp
src/registry_wine.cpp
src/system.h

Video of the only new feature:
[![video](https://picload.org/image/rclwrilw/thumb.png)](https://my.mixtape.moe/aiegxa.webm)
---
3DS PR builder passed: https://ci.easyrpg.org/view/Pull%20Requests/job/player-3ds-pr/27/console

3DS: cleanup and bug fixing

---

builds/vs2015/PlayerLib.vcxproj
builds/vs2015/PlayerLib.vcxproj.filters
builds/vs2015/PropertySheet.props
src/filefinder.cpp
src/registry.cpp

Add xmplite and wildmidi. Fix ARM build.
Not ready yet. My final build test isn't finished :)
Checklist what I have tested by now:
x86 Debug
x86 Release
amd64 Debug
amd64 Release
ARM Debug
ARM Release

MSVC: Update to latest buildscript version.

---

src/decoder_opus.cpp

opus: add seek, tell and close callbacks

---

src/audio_decoder.cpp
src/audio_generic.cpp
src/audio_sdl_mixer.cpp
src/decoder_fmmidi.cpp

Fix flawed conditionals

---

src/battle_animation.cpp
src/battle_animation.h

Handle selection of Battle & Battle2 animations correctly

---

src/game_character.cpp
src/game_event.cpp

See commit message
Tested with: Nobihazard 2, Material Game and DirectionTest (see #1020)

Fix EHR & Desolate city cutscene (issue 1226)

---

src/game_interpreter.cpp
src/game_player.cpp

Fix KeyInput related issues 1109 & 1217

---

src/game_event.cpp
src/game_event.h

Fix walking through the east gate (#1132) in VH1

---

src/game_map.cpp

lcf vNext Step one point one: Fix screen scrolling which I broke in 1269f70.

---

src/game_interpreter.cpp
src/game_interpreter.h

Fix #1002 (Aurora Wing). Limit the variable range to [-999999,999999] for RPG Maker 2000 games.

---

src/cache.cpp
src/player.cpp
src/scene_name.cpp
src/window_keyboard.cpp
src/window_keyboard.h

Based on a table used in a forum fork.
~~~~Untested yet. Please review ;)~~~~

Add Simplified Chinese support in hero name input

---

src/game_player.cpp
src/sprite_timer.cpp

Fix #1064 (Celestial Silfade Story (シルフェイド幻想譚)) and timer rendering

---

builds/android/app/src/main/res/values-be/strings.xml
builds/android/app/src/main/res/values-de/strings.xml
builds/android/app/src/main/res/values-es/strings.xml
builds/android/app/src/main/res/values-hu/strings.xml
builds/android/app/src/main/res/values-ja/strings.xml
builds/android/app/src/main/res/values-ru/strings.xml
builds/android/app/src/main/res/values-uk/strings.xml
builds/android/app/src/main/res/values-zh-rTW/strings.xml

btw. I have an additional patch that moves the library flags to another location and such does not spew the warnings we get currently. However, this one should be simple for faster review and merge, so not included: https://paste.xinu.at/oYe/

Android translations

---

src/sprite_character.cpp

Fix #1228 
Another day the Bitmap::Create function should be fixed ^^

Fix incorrect black event tile rendering when the filename is empty

---

src/audio_sdl_mixer.cpp

Quick hack, just to get it building again.

Fix building with sdl2_mixer 2.0.2

---

src/game_picture.cpp
src/game_screen.cpp
src/player.cpp
src/scene_map.cpp
src/scene_map.h

Fix #1296, #1298, #1299

---

src/game_interpreter.cpp
src/game_picture.cpp
src/graphics.cpp
src/graphics.h
src/scene.cpp
src/scene.h
src/scene_map.cpp
src/scene_map.h
src/tilemap_layer.cpp

https://my.mixtape.moe/gswfhe.webm

Fix Frozen triggers

---

src/game_interpreter.cpp
src/graphics.cpp
src/graphics.h
src/player.cpp
src/scene.cpp
src/scene.h

Refactors the Graphic system to fix the incorrect stack management.
Fixes a memory corruption during Player::Exit in RPG2k3E.

Fix regressions introduced by Frozen Trigger patch

---

builds/psvita/Makefile
builds/psvita/vpk_builder/build.bat
src/psp2_ui.cpp

Untested since i'm unable to compile Vita build due to non standard vita2d usage.
Up for testing if someone can give me a compiled version of this.

[PSVITA] Extended available heap size to 330MB.

---

.gitignore
builds/3ds/Makefile
builds/android/app/src/main/AndroidManifest.xml
builds/android/app/src/main/java/org/libsdl/app/SDL.java
builds/android/app/src/main/java/org/libsdl/app/SDLActivity.java
builds/android/app/src/main/java/org/libsdl/app/SDLAudioManager.java
builds/android/app/src/main/java/org/libsdl/app/SDLControllerManager.java
builds/android/app/src/main/jni/Application.mk
builds/android/app/src/main/jni/SDL2/Android.mk
builds/psvita/Makefile
builds/wii/Makefile

Update Makefiles & co. to match buildsystem update

---

src/graphics.cpp
src/utils.cpp
src/utils.h

Here it is. I left a note in both files (graphics.h and graphics.cpp explaining my choices).

Implement Random Blocks transition

---

builds/android/app/app.iml
builds/android/app/build.gradle

Bump SDK Version to 28, Resolves #1323
Tested and works.

Bump Android SDK Version

---

src/game_interpreter.cpp

**Please find ways to deadlock this** :)
Ensure that the interpreter that runs after a Erase/ShowScreen is the… invoker of the transition.
In RPG_RT transition affects are blocking but we can't do this because of emscripten support.
wait_count was moved down because the wait cycles don't decrement while a transition is executed.

Fix issue 1416

---

src/game_battlealgorithm.cpp

@carstene1ns You might want to take this one for 5.4 release

Fix crash when using Switch Skills in rm2k battle

---

src/game_actor.cpp

I've confirmed this behavior matches with latest rm2k3 steam.

Use System::equipment_setting for Game_Actor::IsItemUsable()

---

src/game_actor.cpp
src/game_interpreter.cpp
src/game_map.cpp
src/game_map.h
src/game_targets.cpp
src/game_targets.h
src/scene_save.cpp

Depends on https://github.com/EasyRPG/liblcf/pull/277
List of variables we will have to get right in `Player`
* `SaveSystem::screen` 0x1
* `SavePartyLocation::processed` 0x4B
* `SaveMapEvent::stop_count` 0x34
* `SaveMapEvent::anim_count` 0x35

SaveGame Fixes

---

src/game_battler.cpp

[Regression] AddState: Fix out of bounds write, simplify code

---

src/game_actor.cpp
src/game_actor.h
src/scene_menu.cpp
src/window_actorinfo.cpp
src/window_menustatus.cpp

Depends on: https://github.com/EasyRPG/liblcf/pull/283
Resolves: #1444

Fix SaveActor::row

---

src/game_actors.cpp

Fix issue 1514: Fixup wasn't called for last actor (off-by-1)

---

CMakeLists.txt
Makefile.am
builds/vs2015/PlayerLib.vcxproj
src/scene_status.cpp
src/window_equipstatus.cpp
src/window_equipstatus.h
src/window_paramstatus.cpp
src/window_paramstatus.h

Fixes one of the bugs in #1443

Align Scene_Status stats with HP

---

src/game_battlealgorithm.cpp
src/game_battler.cpp
src/game_interpreter_battle.cpp

Use RPG::State::kDeathID

---

src/utils.cpp

Log the RNG seed

---

src/audio_sdl.cpp
src/audio_sdl_mixer.cpp
src/scene.cpp

Could be Hardware depended result for me:
When using SDL_Mixer everything worked, but with SDL it was broken.
Moved both backends to the new SDL_OpenAudio API.

Wasapi audio fixes

---

src/game_battlealgorithm.cpp
src/game_battler.cpp
src/game_battler.h
src/scene_battle.cpp

(this is a post-0.5.4 regression)

BUGFIX: battle 2k3 regressions

---

src/game_interpreter.cpp
src/game_interpreter.h
src/game_interpreter_map.cpp
src/game_map.cpp
src/game_map.h
src/game_player.cpp
src/game_temp.cpp
src/game_temp.h
src/scene_map.cpp

Interpreter Fixes

---

src/window_shopparty.cpp

* Algorithm was wrong
* Support 2 weapon characters

Fix shop equipment arrows

---

src/scene_item.cpp
src/scene_skill.cpp
src/scene_skill.h
src/scene_teleport.cpp
src/scene_teleport.h

From #1401 
In TransitionOut I added an else case, otherwise the new transition would be overwritten...
These two look legit.

Generate Skill sound for Escape & Teleport (+Transition). Albeleon 1/2

---

src/game_interpreter.cpp

Add parallel wait message handling to input number command

---

src/filefinder.cpp

Closes #1530 and probably #1383 and #839, by implementing normalization in place of lower-casing per @Ghabry's patch in #839.
Has to be accepted together with [the related liblcf pull request](https://github.com/EasyRPG/liblcf/pull/292) (EasyRPG/liblcf#292).
Requires more thorough testing, but is confirmed to work against the Yume2kki example in #1530.
***
Also needs to be tested that it doesn't break everything on [non-Mac platforms which use NFC as opposed to NFD](https://gist.github.com/JamesChevalier/8448512).

Composite Characters Fix

---

src/window_actorinfo.cpp

Use most recent rm2k3e names in Status menu

---

builds/switch/Makefile
src/audio_switch.cpp
src/audio_switch.h
src/baseui.cpp
src/decoder_wildmidi.cpp
src/filefinder.cpp
src/output.cpp
src/player.cpp
src/switch_ui.cpp
src/system.h

Video of it in action: https://my.mixtape.moe/nmxwvp.webm
Waiting for feedback here: https://gbatemp.net/threads/release-easyrpg-player-rpg-maker-2k-2k3-emulator-for-switch.497328/page-5#post-8490126

Polish Switch Port a bit, use GL

---

src/game_battler.cpp
src/game_battler.h
src/scene_battle_rpg2k.cpp
src/scene_battle_rpg2k3.cpp

~~No idea if this fixes any open issue.~~
Fix #1276
(yes I know that 2k3 needs a refactor but not now :p)

Battle 2k3: Fix automatic state healing, the counter is global

---

src/filefinder.cpp
src/game_map.cpp
src/scene_gamebrowser.cpp

This \ vs / handling is confusing.
In the vfs branch I will consider to normalize all filenames to "/" for internal processing.

Fix 1383 & minor fixes

---

src/game_interpreter.cpp

Fix Crash in show choice when cancel idx > last valid choice idx

---

src/game_interpreter.cpp

The unset broke due to my sanity checks.
Related #759

Change Class: Fix unsetting class (regression fix) and remove all equipment

---

README.md
src/player.cpp
src/scene_load.cpp
src/scene_save.cpp
src/version.h

Filled with 600 to reflect 0.6.0 savegame type.

Support EasyRPG Savegame version chunk

---

CMakeLists.txt
README.md
builds/switch/Makefile
builds/wii/meta.xml
configure.ac
resources/osx/Info.plist
resources/player.rc
src/filefinder.cpp
src/version.h
src/window_battlestatus.cpp

EasyRPG Player 0.6.0 - Preemptive Attack

---

builds/android/app/build.gradle
builds/android/app/src/main/res/layout/player_activity.xml

Now I just need a billing address to send Google the invoice

Android: Set black background

---

src/scene_battle_rpg2k.cpp

Use accurate shake in battle 2k

---

builds/amiga/Makefile
src/system.h

MorphOS and AmigaOS4 build fix

---

src/game_interpreter.cpp
src/game_interpreter_map.cpp
src/window_message.cpp

A few fixes for message boxes,
Including critical fix for the DBZ 1 HP bug
Fix #1685 
Messages need a proper refactor, but is TBD

Message quick fixes

---

src/game_event.cpp

Spinning events should keep the configured frame

---

src/game_character.cpp

Fix event screen x and y to match RPG_RT

---

src/game_commonevent.cpp
src/game_commonevent.h
src/game_event.cpp
src/game_interpreter_map.cpp
src/game_interpreter_map.h
src/game_map.cpp

Depends on https://github.com/EasyRPG/liblcf/pull/311

Rename event interpreter chunks (liblcf#311)

---

src/game_interpreter.cpp

Depends on #1628 
Fixes: #1613

Branch loop limit workaround

---

src/game_battle.cpp

Fix battle events page triggering

---

src/game_character.cpp
src/game_character.h
src/game_event.cpp
src/game_event.h

Refactor move towards / away from player

---

src/game_event.cpp
src/game_interpreter.cpp
src/game_map.cpp
src/game_party.cpp
src/game_party.h
src/scene_battle.cpp
src/scene_map.cpp
src/sprite_timer.cpp
src/sprite_timer.h

~~Depends on #1628~~
Fix #1662
Fix #1702

Fix Screen Effects + Timers

---

src/game_battler.cpp
src/game_interpreter.cpp
src/game_party.cpp
src/scene_actortarget.cpp

Item + Shake fixes

---

src/game_interpreter_map.cpp

Depends: https://github.com/EasyRPG/liblcf/pull/324

Remove SaveExecFrame:commands_size (liblcf #324)

---

src/cache.cpp
src/game_map.cpp
src/message_overlay.cpp
src/output.cpp

Fix (Android) crashes 10 and 11

---

src/game_player.cpp

Fix crash with TriggerSet and trigger == -1

---

src/scene_logo.cpp
src/scene_logo.h
src/scene_title.cpp
src/scene_title.h

Fix black title graphic regression and system graphic flicker in TestPlay mode

---

src/game_map.cpp

* Matches RPG_RT behavior
* Panorama doesn't animate during pre-update
Fix: #1704

Update panorama at the end of update routine

---

src/drawable.cpp
src/drawable.h
src/game_character.cpp
src/sprite_airshipshadow.cpp

Render flying events (airship) above all others

---

src/game_map.cpp
src/game_vehicle.cpp
src/game_vehicle.h
src/player.cpp

Vehicle chunk fixes

---

src/game_character.cpp

Fix event screen coordinates rounding bug

---

src/battle_animation.cpp
src/game_switches.cpp
src/game_variables.cpp

Battle anim flash + other small fixes

---

src/sprite_battler.cpp
src/sprite_battler.h
src/spriteset_battle.cpp

Fix Battler Z ordering

---

src/game_party.cpp

Depends: https://github.com/EasyRPG/liblcf/pull/331

Remove items_size chunk

---

src/game_party.cpp
src/game_party.h
src/player.cpp
src/window_item.cpp

Fix: #1799 
Depends: #1798 
Depends: #1797

Sort the inventory

---

src/game_battlealgorithm.cpp

Fix Crash in Apply() for battle actions which have no target.

---

src/game_battlealgorithm.cpp
src/game_battlealgorithm.h
src/scene_battle.cpp
src/scene_battle.h
src/scene_battle_rpg2k.cpp
src/scene_battle_rpg2k.h

Battle2k: Handle enemies with no actions + Death timing fixes

---

src/game_character.cpp
src/game_character.h
src/game_event.cpp
src/game_event.h
src/game_map.cpp

Fixes (some of?) #1827 
Other smaller code cleanups and virtual optimizations

Allow disembark on events with no page + Game_Character cleanups

---

Makefile.am
src/3ds_ui.h
src/psp2_ui.h
src/switch_ui.h

Towards a proper fix for #1753, workaround for now with the traditional way so far, add guard headers to keep compiler building properly for other ports.

Add missing dist files

---

src/game_party.cpp

Depends on: https://github.com/EasyRPG/liblcf/pull/337

Remove SaveInventory::party_size

---

src/game_interpreter.cpp
src/game_interpreter.h
src/game_map.cpp
src/game_map.h
src/game_player.cpp
src/game_player.h
src/scene_map.cpp
src/teleport_target.h

Fix: #1778
~~Depends on: #1740~~
Test case 4 requires #1779

Improved support for SetVehicleLocation() teleport..

---

src/game_interpreter.cpp
src/game_map.cpp

Vehicle teleport crash fix

---

src/game_actor.cpp

Clamp stat mod values to match RPG_RT

---

src/game_battle.cpp
src/game_character.cpp
src/game_character.h
src/game_event.cpp
src/game_interpreter.cpp
src/game_player.cpp
src/game_system.cpp
src/game_vehicle.cpp
src/game_vehicle.h

Depends on: https://github.com/EasyRPG/liblcf/pull/334

Vehicle Sprites + Misc LSD chunks

---

src/game_battle.cpp
src/game_battle.h
src/game_battlealgorithm.cpp
src/game_interpreter.cpp
src/scene.h
src/scene_battle.cpp
src/scene_battle.h
src/scene_battle_rpg2k.cpp
src/scene_battle_rpg2k.h
src/scene_battle_rpg2k3.cpp
src/scene_battle_rpg2k3.h
src/spriteset_battle.cpp

No functional changes here, just some cleanups and small refactors.

Battle code improvements

---

resources/emscripten/emscripten-post.js

Fix emscripten audio playback on newer Chrome versions

---

src/game_battle.cpp
src/game_battle.h
src/game_interpreter_map.cpp
src/game_map.cpp
src/game_map.h
src/game_temp.cpp
src/game_temp.h
src/scene_battle_rpg2k.cpp
src/scene_battle_rpg2k3.cpp
src/scene_debug.cpp
src/scene_map.cpp

Fix: #1648 
~~Depends on: https://github.com/EasyRPG/liblcf/pull/340~~
~~Depends on: #1881~~

Implement 2k3 Death Handlers

---

src/game_interpreter.cpp
src/game_interpreter_map.cpp
src/game_message.cpp
src/game_message.h
src/window_message.cpp

Fix text color for inn choices

---

src/spriteset_map.cpp
src/tilemap_layer.cpp
src/tilemap_layer.h

see commit messages for more details.

Fix FastBlit edge cases

---

src/game_interpreter.cpp
src/game_map.cpp
src/game_map.h

* RPG_RT will return highest event id, even if the event
erased itself.
* Optimize the code by not allocating a vector to do this
operation.

Fixes for CommandStoreEventID

---

src/player.cpp
src/scene.cpp
src/scene.h
src/scene_end.cpp
src/scene_gameover.cpp
src/scene_map.cpp

* New Game -> 60 frames
* Load Game -> 60 frames
* Return to Title -> 20 frames
Fix: #1939

Add RPG_RT compatible scene delays

---

src/game_event.cpp
src/game_interpreter.cpp
src/game_interpreter_map.cpp
src/game_map.cpp
src/game_map.h
src/input.cpp
src/input.h
src/scene_save.cpp

Fix: #1932 
Fix: #1935 
I reconfirmed the sample test game
@Br4ssman Please confirm fixed on your side

Fixes for KeyInputProc, Pan Screen, and Save Games

---

src/battle_animation.cpp
src/game_character.cpp
src/game_character.h
src/game_vehicle.cpp
src/game_vehicle.h

Fix #1938 
Fix #1937 
Fix #1936 
@Br4ssman  Please confirm fixes in your game

Jump fixes

---

src/game_interpreter.cpp
src/game_picture.cpp
src/game_picture.h

Depends on: https://github.com/EasyRPG/liblcf/pull/347

Improved LSD chunks (needs liblcf#347)

---

src/battle_animation.cpp
src/game_screen.cpp
src/game_screen.h

These use the screen pan_x and pan_y chunks.
Fix: #1951
Fix: positioning issue punted from #574

Fix positioning of entire map battle animations

---

src/game_interpreter.cpp

Messages block picture commands in < English release engines

---

src/game_interpreter.cpp
src/game_map.cpp
src/game_map.h
src/game_picture.cpp
src/game_picture.h
src/game_screen.cpp
src/game_screen.h
src/scene_map.cpp
src/scene_map.h
src/sprite.cpp
src/sprite.h

~~Depends on: #1949~~
Fix: #1703 
Fix: #1125
Fix: #1943

Correctness fixes for Pictures

---

src/bitmap.cpp

Fix picture flash / BlendBlit() glitch

---

CMakeLists.txt
builds/cmake/Modules/FindSDL2.cmake

Cmake fixes for MSVC 2019 and SDL 2.0.10

---

CMakeLists.txt
Makefile.am
resources/shinonome/generate_cxx_font.rb
resources/wenquanyi/gen_wqy_font_cpp.py
src/bitmapfont.h
src/bitmapfont_glyph.h
src/bitmapfont_rmg2000.h
src/bitmapfont_ttyp0.h
src/bitmapfont_wqy.h
src/font.cpp
src/shinonome_gothic.h
src/shinonome_mincho.h
tests/bitmapfont.cpp

Make bitmapfont objects constexpr

---

src/tone.h

Fix: #1944
@Br4ssman please confirm

Fix tone Blending calculation

---

src/sprite_character.cpp
src/sprite_character.h
src/window_shopparty.cpp

Window_ShopParty: render custom charset image sizes correctly

---

src/weather.cpp
src/weather.h

Optimize weather rendering - Drawables 3' of N

---

src/audio_switch.cpp
tests/wordwrap.cpp

Switch + macOS fix

---

src/player.cpp

Fix Variable max initialization bug in 2k

---

tests/output.cpp

Output test: cleanup singletons

---

src/game_battle.cpp
src/game_interpreter.cpp
src/game_interpreter_map.cpp
src/game_map.cpp
src/game_party.cpp
src/game_party.h
src/game_player.cpp
src/game_system.cpp
src/game_system.h
src/player.cpp
src/player.h
src/scene_map.cpp
src/scene_menu.cpp
src/scene_save.cpp
src/scene_title.cpp

A step towards #1954 and #1581

Party and System singleton improvements

---

src/sprite_character.cpp
src/sprite_character.h
src/spriteset_map.cpp

Update tile sprite events when chipset changes

---

src/game_actor.cpp
src/game_actor.h
src/game_party.cpp
src/game_party.h
src/game_player.cpp

Fix: #2030
Depends on: https://github.com/EasyRPG/liblcf/pull/356

Fix actor transparency

---

src/image_bmp.cpp

Support BITMAPCOREHEADER for bmp format

---

src/player.cpp
src/scene_import.cpp
src/scene_load.cpp
src/scene_title.cpp
src/scene_title.h

Fix reload title cache behavior

---

src/game_screen.cpp
src/game_screen.h
src/weather.cpp
src/weather.h

Depends on #2004 
This is really an approximation. No idea how to make this perfect.

Implement Sandstorm particles

---

src/compiler.h
src/game_actor.cpp
src/game_actor.h
src/game_interpreter.cpp
src/game_interpreter.h
src/pending_message.h
src/scene_battle.cpp
src/scene_battle_rpg2k.cpp
src/scene_battle_rpg2k3.cpp
src/window_actortarget.cpp
src/window_base.cpp
src/window_base.h
src/window_battlestatus.cpp
src/window_menustatus.cpp
src/window_message.cpp
src/window_message.h
src/window_skillstatus.cpp

Fix 2k3 class change + Face graphic fixes

---

src/game_battle.cpp
src/game_interpreter.cpp
src/game_map.cpp
src/game_map.h
src/game_picture.cpp
src/game_picture.h
src/game_screen.cpp
src/game_screen.h
src/scene_battle.cpp
src/scene_map.cpp
src/scene_save.cpp

Depends on: #1989
Fix: #1488 
Fix: #1263
Progress on: #1954

Implement Pictures and Weather in Battle

---

bench/bitmap.cpp
src/bitmap.cpp
src/bitmap.h
src/cache.cpp
src/game_screen.cpp
src/pending_message.cpp

Minor Blitting optimizations - Bitmaps 3 of N

---

src/game_picture.cpp
src/game_picture.h
src/game_screen.cpp

Fix crash when loading save games with pictures

---

src/game_system.cpp

Depends on: https://github.com/EasyRPG/liblcf/pull/357
Fix: #2049

Fix transition chunks defaults

---

src/async_op.h
src/game_interpreter.cpp
src/game_interpreter.h
src/game_map.cpp
src/game_player.cpp
src/game_player.h
src/player.cpp
src/scene_map.cpp
src/scene_map.h
src/scene_title.cpp
src/teleport_target.h

~~Depends on #2041~~
Fix: #2043 
Fix: #1864 
Fix: #1641 
Fix: #1778 
Fix: #2048

Implement asynchronous vehicle teleports + Bgm fixes + Choice fix

---

src/game_battler.cpp
src/game_interpreter.cpp
src/game_party.cpp
src/game_targets.cpp
src/game_targets.h
src/main_data.cpp
src/main_data.h
src/player.cpp
src/scene_item.cpp
src/scene_save.cpp
src/scene_skill.cpp
src/window_teleport.cpp

Towards #1954 
Also fixes some incompatibilities with targets save data and ordering

Refactor Game_Targets

---

src/decoder_oggvorbis.cpp
src/decoder_oggvorbis.h
src/filefinder.cpp
src/game_clock.cpp
src/platform.cpp
src/player.cpp
tests/platform.cpp

Small fixes for 3DS and warnings

---

src/platform.cpp
src/weather.cpp
tests/platform.cpp

Use SFINAE for d_type detection - fix OSX and BSD

---

src/filefinder.cpp
src/platform.cpp

Fixes of fixes.

---

src/drawable_list.cpp
src/drawable_list.h
src/game_interpreter.cpp
src/game_system.cpp
src/game_system.h
src/graphics.cpp
src/graphics.h
src/player.cpp
src/scene.cpp
src/scene_battle.cpp
src/scene_debug.cpp
src/scene_debug.h
src/scene_gameover.cpp
src/scene_item.cpp
src/scene_map.cpp
src/scene_skill.cpp
src/scene_teleport.cpp
src/scene_title.cpp
src/transition.cpp
src/transition.h

Depends on #2050
Fix transition rendering
Fix: #1445
Fix: #1600
Fix: #1801 (both issues, + opacity issue in hh3 mentioned, + lufia glitch #1840 mentioned)
Fix: #1931
Fix: #1934
Fix: #1715
TBD:

Transition graphical fixes - MainLoop 4 of N

---

CMakeLists.txt
Makefile.am
src/3ds_clock.cpp
src/3ds_clock.h
src/3ds_ui.cpp
src/game_clock.cpp
src/game_clock.h
src/main_data.cpp
src/platform_clock.h
src/player.cpp
src/psp2_clock.cpp
src/psp2_clock.h
src/psp2_ui.cpp
src/psp2_ui.h
src/std_clock.h
src/switch_clock.cpp
src/switch_clock.h
src/switch_ui.cpp
src/system.h

Add custom clocks for 3ds, vita, and switch

---

src/game_character.cpp
src/game_interpreter.cpp
src/game_interpreter.h
src/game_interpreter_battle.cpp
src/game_interpreter_map.cpp
src/game_map.cpp
src/game_map.h
src/game_party.cpp
src/game_player.cpp
src/player.cpp
src/scene_debug.cpp
src/scene_item.cpp
src/scene_map.cpp
src/scene_map.h
src/scene_skill.cpp
src/window_message.cpp

Fixing things from #1859 
I also found another windows debug assertion missed by the last PR and so added it here.
Tested:

Interpreter todo items + more windows fixes

---

src/window_message.cpp

RPG_RT v1.11 fixes

---

src/switch_ui.cpp
src/switch_ui.h

Issue notified over IRC.
TODO (after release): Integrate properly into input handling instead of hardcoding into
keyboard values.

Switch: Enable left thumbstick, fix using B button

---

builds/cmake/Modules/ConfigureWindows.cmake
resources/easyrpg-player.6.adoc
resources/unix/bash-completion/easyrpg-player
src/audio.cpp
src/audio_libretro.cpp
src/audio_secache.cpp
src/baseui.cpp
src/baseui.h
src/cache.cpp
src/fps_overlay.cpp
src/fps_overlay.h
src/game_clock.cpp
src/game_clock.h
src/game_interpreter.cpp
src/graphics.cpp
src/graphics.h
src/libretro_ui.cpp
src/output.cpp
src/player.cpp
src/player.h
src/scene_gamebrowser.cpp
src/scene_map.cpp
src/sdl2_ui.cpp

Depends on: #1973 
This refactors the player main loop to free the game update (60 fps) from rendering (any fps). It also cleans up the main loop code significantly, making it easier to understand and measure.

Refactor MainLoop and FPS - MainLoop 6 of N

---

src/filefinder.cpp
src/system.h

Search for installed RTPs in XDG locations

---

builds/android/app/src/main/java/org/libsdl/app/HIDDevice.java
builds/android/app/src/main/java/org/libsdl/app/HIDDeviceBLESteamController.java
builds/android/app/src/main/java/org/libsdl/app/HIDDeviceManager.java
builds/android/app/src/main/java/org/libsdl/app/HIDDeviceUSB.java
builds/android/app/src/main/java/org/libsdl/app/SDLActivity.java
builds/android/app/src/main/java/org/libsdl/app/SDLAudioManager.java
builds/android/app/src/main/java/org/libsdl/app/SDLControllerManager.java
builds/android/app/src/main/jni/Application.mk

Compiles for me (tm). Not tested if Play Store accepts this.
Fix #1911

Android: Remove armeabi, add x86_64, SDL 2.0.12

---

src/game_screen.cpp
src/scene_battle.cpp

Initialize screen and picture graphics on battle test

---

src/input.cpp
src/input.h
src/input_buttons.h
src/input_source.cpp
src/input_source.h
src/player.cpp

Separate system keys from game keys

---

src/window_selectable.cpp
src/window_selectable.h

Add Arrows to Item, Skills, and Shop

---

src/game_actor.cpp
src/game_actor.h
src/game_actors.cpp
src/game_actors.h
src/game_battle.cpp
src/game_battlealgorithm.cpp
src/game_battlealgorithm.h
src/game_battler.cpp
src/game_battler.h
src/game_enemy.cpp
src/game_enemy.h
src/game_enemyparty.cpp
src/game_interpreter.cpp
src/game_party_base.cpp
src/game_party_base.h
src/scene_battle.cpp

see commits
Fix: #2102
Fix: #2123

Various battle fixes

---

src/game_actor.cpp

Fix crash in ChangeClass without message box

---

src/window_message.cpp

Fix: #2144 
I tested the game and the newline issue is fixed

Window_Message: fix empty line handling

---

src/game_screen.cpp
src/game_screen.h
src/pixel_format.h
src/weather.cpp
src/weather.h

This PR is to add further improvements to weather emulation.
Fix: #2069 
Fix: #1737 
TBD:

Accurate Weather effects

---

src/game_interpreter.cpp

Not fully tested it yet but that should be it >.>
#2127 already implemented 2k Value! properly (by ignoring the 2k3 code path) but the key input was still broken for games created with RPG Maker 2003 < 1.05
Fix #2140
Here some testing. 2k3 has the same behaviour for all versions. 2k gained new stuff with "Value!".
The D means that the "Direction flag" (Arg 2) is 1.
|  Bytes | 2kDon | 2kE              |                           2k3 |                 Param  |
|--------|-------|------------------|-------------------------------|------------------------|
|   5D   |  Dir  | Dir              | Dir                           |   42 1 1 1 0    |
|   5    |       |                  |                               |       |
|   6D   |  Dir  | Shift            | Dir,Num                       |    42 …

KeyInputProc: Use correct behaviour depending on engine version

---

src/game_actor.cpp

Depends on https://github.com/EasyRPG/liblcf/pull/365

Liblcf: rename grid variables and SaveSystem::transparent

---

builds/psvita/Makefile

Fixup for #2160.
(Relevant line is [R37](https://github.com/EasyRPG/Player/pull/2165/files#diff-8f7d62970d52c3fc3505305b84e8b934R37))

PSVita: Fix Makefile, add include directory

---

src/game_pictures.cpp

Fix rounding bug in scroll with map picture offset adjustment

---

CMakeLists.txt
configure.ac
src/baseui.cpp
src/baseui.h
src/game_interpreter.cpp
src/platform/3ds/3ds_ui.cpp
src/platform/3ds/3ds_ui.h
src/platform/libretro/libretro_ui.cpp
src/platform/libretro/libretro_ui.h
src/platform/psvita/psp2_ui.cpp
src/platform/psvita/psp2_ui.h
src/platform/switch/switch_ui.cpp
src/platform/switch/switch_ui.h
src/sdl2_ui.cpp
src/sdl2_ui.h
src/sdl_ui.cpp
src/sdl_ui.h

These are a set of commits which remove dead and old code from our UI classes and cleanup various things.

DisplayUI cleanups - Config 1 of N

---

CMakeLists.txt
Makefile.am
src/platform/wii/wii_clock.cpp
src/platform/wii/wii_clock.h
src/std_clock.h

Add Wii Platform Clock

---

builds/amiga/Makefile
builds/amiga/amigaos4/cmath
src/sdl2_ui.cpp
src/system.h

I managed to switch to SDL2 on MorphOS with some outside help. The same will happen for AmigaOS4 once I'm able to test it myself. There's still no SDL2 for AROS.

Amiga build fix

---

src/input_buttons_desktop.cpp
src/platform/libretro/libretro_input_buttons.cpp
src/platform/opendingux/opendingux_input_buttons.cpp
src/platform/psp/psp_input_buttons.cpp
src/platform/wii/wii_input_buttons.cpp

Array syntax error. `,` should be placed after each element.

Fix syntax error in libretro port

---

src/game_battle.h
src/game_battlealgorithm.cpp
src/game_interpreter.cpp

Fix Variance algorithm for effects

---

src/game_battler.cpp
src/state.cpp
src/state.h

All states are removed except
- "Persists after" with 0% healing rate
- Equipment state with "Persists after"

States were incorrectly removed when the battle ended (regression)

---

src/game_actor.cpp
src/game_battlealgorithm.cpp
src/scene_battle_rpg2k3.cpp

DynRPG Info:
0x49B4E1 is where the math is done

Fix Physical attack to hit algorithm + class EXP + crit flash

---

src/game_interpreter.cpp
src/game_interpreter_map.cpp
src/game_interpreter_map.h
src/game_map.cpp
src/game_map.h
src/game_message.cpp
src/game_message.h
src/pending_message.h
src/scene_map.cpp
src/scene_map.h
src/window_message.cpp
src/window_message.h

Fixes inn when costs money being skipped.

Add support for async message ops - Fix broken inn sequence

---

src/game_pictures.cpp
src/game_pictures.h

Fix: #2198
DynRPG info:
| Address | Class | Name |
| -- | -- | -- |
| 004C1C20 | Picture | Update() |

Fix accuracy bugs in picture rotation algorithm

---

tests/rtp.cpp

See https://github.com/onqtam/doctest/issues/126

Fix unit tests on macos

---

src/game_interpreter.cpp
src/game_pictures.cpp

Picture save game fixes + variable fix

---

src/game_battle.cpp
src/game_battle.h
src/game_event.h
src/game_interpreter.cpp
src/game_interpreter.h
src/game_map.cpp
src/game_map.h
src/game_variables.cpp
src/game_variables.h
src/scene_debug.cpp
src/scene_debug.h
src/window_varlist.cpp
src/window_varlist.h

Scene_Debug: refactor + call map and battle events

---

builds/android/app/src/main/java/org/easyrpg/player/game_browser/GameInformation.java
builds/android/app/src/main/java/org/easyrpg/player/game_browser/GameScanner.java

Hello :)
With this pull request, the android port will sort the game list alphabetically.

Android : sort the game list alphabetically

---

CMakeLists.txt
Makefile.am
src/game_battle.cpp
src/game_pictures.cpp
src/game_pictures.h
src/game_screen.cpp
src/game_screen.h
src/scene.cpp
src/scene.h
src/scene_battle.cpp
src/scene_map.cpp
src/sprite.cpp
src/sprite.h
src/sprite_picture.cpp
src/sprite_picture.h
src/weather.cpp

Pictures and Screen: optimize and remove UpdateGraphics() method + fix debug battle pics / weather

---

src/audio_generic.cpp
src/audio_sdl_mixer.cpp

This is workaround for #1356 because users still complain about this nag.
I propose this for backport to stable.

Change Warning to Debug on SE playback failure

---

src/game_pictures.cpp
src/player.cpp
src/player.h

first commit extracted from #2282.
This one is worth backporting.

Warn when DynRPG or ManiacPatch are detected

---

src/game_interpreter.cpp
src/plane.cpp

Performance considerations:
For the range > 1 case there is an extra random number generator call now.
https://easyrpg.org/play/pr2292/?game=niwatori-benchmark&engine=rpg2k3e

Fix Niwatori benchmark

---

src/cmdline_parser.cpp
src/player.cpp
tests/cmdline_parser.cpp

Fix CmdLine Parser: Crashes when argc was 0

---

src/scene.cpp
src/scene.h
src/scene_load.cpp
src/scene_save.cpp
src/scene_save.h

Save game compatibility fixes for regtesting

---

src/weather.cpp

Minor accuracy adjustments for weather colors

---

src/player.cpp
src/scene_end.cpp

Fade BGM on new game and load game

---

CMakeLists.txt

fixes this annoyance that the test results are invisible...

testrunner: Force console on Windows

---

src/game_actor.cpp
src/game_actor.h
src/game_battlealgorithm.cpp
src/game_battler.cpp
src/game_battler.h
src/game_enemy.cpp
src/game_enemy.h
src/game_interpreter.cpp
src/game_interpreter_battle.cpp
src/game_party.cpp
src/game_player.cpp
tests/game_actor.cpp
tests/game_enemy.cpp

~~Depends on #2339~~
Testing
----------

Actor parameter cleanups / optimizations - prep for battle algo refactor

---

src/scene_debug.cpp
src/scene_debug.h
src/window.cpp
src/window.h

Add left and right arrow support to window classes

---

src/game_map.cpp
src/game_map.h
src/scene_save.cpp
src/sprite_character.cpp

Depends on: https://github.com/EasyRPG/liblcf/pull/403

Remove SaveMapInfo Setup and Fixup - depends on liblcf #403

---

src/sprite_timer.cpp
src/sprite_timer.h
src/spriteset_battle.cpp
src/spriteset_map.cpp

Remove SpriteTimer::Update

---

src/scene_gamebrowser.cpp

Fix crash in Scene_GameBrowser

---

src/game_battlealgorithm.cpp
src/scene_battle.cpp
src/scene_battle_rpg2k3.cpp
src/scene_battle_rpg2k3.h

This PR tries to fix #2357 and bullet point 1 from #1277. It adds the battle start and initiative messages and the frame delays in RPG Maker 2003 battles.

Battle 2k3: Add battle start message and frame delays

---

src/sprite_battler.cpp

Depends on: https://github.com/EasyRPG/liblcf/pull/406
Tested in #2399

Use new CBA chunk names - liblcf #406

---

src/game_battle.cpp

Allow battle animations on both actors and enemies simultaneously

---

src/spriteset_map.cpp
src/tilemap.cpp
src/tilemap.h
src/tilemap_layer.cpp
src/tilemap_layer.h

Tilemap: remove Update() function

---

README.md
resources/emscripten/emscripten-post.js
resources/emscripten/emscripten-pre.js
resources/emscripten/emscripten-shell.html

Hello there!
first and foremost: What a great project you have built over the years. Astonishing. 
I was deploying some RM2k games and looked deeper into the HTML/JS part. I've beautified the shell HTML file slightly and would be happy if the following changes sound good to you, too:
**Changes incorporated**:
- prevent pinching, zooming and other gestures on touch-input based devices by setting `touch-action` to `none`
- remove unnecessary meta tags for HTML5 environments
- use button instead of input element to improve semantics
- essential CSS button resets
- embed SVG icon `expand` from [Teenyicons](https://teenyicons.com/):
- use `image-rendering: crisp-edges` as fallback, since Firefox supports `crisp-edges` but not `pixelated` and Chrome supports `pixelated` but not `crisp-edges` …

Update Emscripten shell with ES6 flavour, icon, fixes and more

---

CMakeLists.txt
Makefile.am
src/lcf/data.cpp
src/lcf/data.h
src/player.cpp
src/scene_save.cpp
src/scene_title.cpp

Depends on https://github.com/EasyRPG/liblcf/pull/409
This is a temporary fix to allow merging 409 to liblcf without creating rebase hell in Player.

Migrate lcf::Data from liblcf to Player

---

src/window.h
src/window_base.cpp
src/window_savefile.h

This PR is a retry of #2452. I had overreacted and prematurely closed the old PR. After getting a clear mind I decided to try it again. This contains the fix intended by #2451 too.

Disallow system updates on closing windows (retry)

---

builds/switch/Makefile
src/platform/switch/switch_ui.cpp

- Only tested in emulator (yet).
- needs toolchain update

Switch: Update for libnx 4.0 (hid refactor)

---

src/dynrpg_easyrpg.cpp

Fix #2377
@elsemieni fixed it for you :)

Fix DynRPG sample function @easyrpg_output

---

builds/android/app/src/main/java/org/libsdl/app/HIDDeviceManager.java
builds/android/app/src/main/java/org/libsdl/app/HIDDeviceUSB.java
builds/android/app/src/main/java/org/libsdl/app/SDL.java
builds/android/app/src/main/java/org/libsdl/app/SDLActivity.java
builds/android/app/src/main/java/org/libsdl/app/SDLAudioManager.java
builds/android/app/src/main/java/org/libsdl/app/SDLControllerManager.java

Android: Update SDL to 2.0.14

---

src/game_ineluki.cpp
src/game_system.cpp
src/input_source.cpp
src/translation.cpp
src/utils.cpp
src/utils.h

Fix translation reading on Windows

---

src/audio_generic.cpp
src/audio_generic.h
src/decoder_wav.cpp
src/decoder_wav.h

See commit messages
Thanks to Jan (Deep8) for reporting the GenericAudio bug. Must be one of the few persons who has a game without BGM music xD

Audio fixes

---

builds/psvita/Makefile
src/platform/psvita/psp2_ui.cpp

Changes so far:
- Fixed building when TOOLCHAIN_DIR is not defined.
- Moved to vita-pack-vpk (part of vitasdk) for the final vpk creation.
- Added VSync support.
- Moved to wide analogs range for better analogs precision.

PSVita: QoL changes and VSync support

---

src/game_system.cpp
src/scene_shop.cpp

Fix newlib build issues

---

src/battle_animation.cpp
src/battle_animation.h

This PR intends to fix the flash and shake effects on battle animation sprites.
Fixes: #2479

Battle 2k3: Fix flash and shake effects on battle animation sprites

---

CMakeLists.txt
Makefile.am
src/game_actor.cpp
src/game_battlealgorithm.cpp
src/game_battlealgorithm.h
src/game_battler.cpp
src/game_battler.h
src/scene_battle_rpg2k3.cpp
src/sprite_actor.cpp
src/sprite_actor.h
src/sprite_weapon.cpp
src/sprite_weapon.h

This PR implements the CBA melee weapons in RPG Maker 2003 battles.

Battle 2k3: Add CBA melee weapons

---

src/async_handler.cpp
src/utils.cpp
src/utils.h
src/window_message.cpp
tests/utils.cpp

- Regression fix: Path was not made canonical anymore
- Replace regex with a replace function

Emscripten bugfixes

---

src/game_battler.cpp
src/state.cpp
src/state.h

When Death "Ends after Battle" set the HP to 1 in case of dead.

---

builds/android/app/src/main/java/org/easyrpg/player/MainActivity.java

This change load settings on standalone games and consequently enable the sound of these apps.

Enable sound on standalone game

---

src/game_battlealgorithm.cpp
src/game_battlealgorithm.h
src/scene_battle_rpg2k3.cpp
src/sprite_actor.cpp
src/sprite_actor.h

~TODO: Figure out the transparency values.~
I made the API a bit more flexible: You can set how many afterimages you want :).
See #1269
Slightly exaggerated picture (manually set it to 10 images ;))

Battle 2k3: Implement CBA Afterimage

---

resources/emscripten/emscripten-post.js
src/game_system.cpp
src/platform.cpp
src/player.cpp

totally forgot that the volume is also part of the save data, making our saves incompatible with RPG_RT.
That PR fixes this.

Fix 3ds and Vita build. Fix emscripten regression. Do not overwrite volume chunks.

---

src/player.cpp

Sorry, emscripten is always a bit finicky...
Fix #2558

Emscripten: Create save folder before CLI parser

---

src/graphics.cpp

Fix Issue 2179

---

src/audio_decoder_midi.cpp

MidiOut: Fix inn infinite loop

---

CMakeLists.txt

Fixes libretro build
Finally a simple commit by me ;)

macOS: Link against AudioToolbox and AudioUnit frameworks

---

src/game_actor.cpp

Fix #2603
(Yes, this fixes everything here, no idea why Armor and Helmet were unequipped o_O)

Only respect two_handed for Weapons

---

src/audio_sdl.cpp

The frequency change code was missing.
Also changed the emscripten format to F32, this is the native format and maybe a bit faster.

Port some audio code from SDL2 Mixer to SDL2

---

src/scene_debug.cpp
src/scene_debug.h
src/window_varlist.cpp
src/window_varlist.h

This PR allows the levels of the party members being changed in the debug scene.

Debug scene: Add level settings

---

src/cache.cpp
src/graphics.cpp
src/player.cpp
src/scene.cpp

Fix #2601
Bet this was omitted before due to some sideeffects but it seems to work by now.
(Not tested on Android yet though)

Clear system graphic when clearing the cache

---

src/filefinder.cpp
src/filefinder.h
src/filesystem.cpp
src/platform.cpp
src/platform/psvita/psp2_ui.cpp

ListDirectory receives in some cases an empty string here which will return the files of the working directory on most platforms and succeed.
On the Vita however this fails.
Fix #2682 
Fix #2683

Filesystem: Use Exists instead of ListDirectory to check whether a FilesystemView is valid

---

configure.ac
src/platform/wii/wii_input_buttons.cpp

buildfix and wii fast forward

---

src/scene_map.cpp
src/scene_map.h

Cancel the Inn music after 10 seconds.

---

src/directory_tree.cpp
src/filesystem.cpp
src/sprite_character.cpp

Luckily this was debuggable without using Emscripten :D
The first commit fixes e.g. a folder called "music" not being found when launching directly from the game dir. So this was not found by our Android users just because the project-path there is a path with one directory component in it.
-------
The 3rd commit is not an emscripten fix but it resolves an assert on Linux

Emscripten related fixes

---

src/audio.h
src/audio_generic.cpp
src/audio_generic.h
src/audio_secache.cpp
src/audio_secache.h
src/game_system.cpp
src/platform/3ds/3ds_audio.cpp
src/platform/3ds/3ds_audio.h

Fixes a performance regression (unnecessary opening of file handles)
Fix #2582

Move AudioSeCache handling to Game_System.

---

src/directory_tree.cpp
src/directory_tree.h
src/dynrpg.cpp
src/filefinder.cpp
src/game_actor.cpp
src/player.cpp
src/rtp.cpp

Fix translation loading when project_path is not the current directory and other fixes

---

resources/easyrpg-player.6.adoc
src/async_handler.cpp
src/async_handler.h
src/cache.cpp
src/cache.h
src/game_actor.cpp
src/game_actor.h
src/game_actors.cpp
src/game_actors.h
src/game_map.cpp
src/game_map.h
src/graphics.cpp
src/player.cpp
src/player.h
src/scene.cpp
src/scene.h
src/scene_gamebrowser.cpp
src/scene_logo.cpp
src/scene_map.cpp
src/scene_map.h
src/scene_title.cpp
src/scene_title.h
src/translation.cpp
src/translation.h

Also do not unload the system graphic string anymore here.
Fix #2691
~~Waiting for Jan (Deep8) to confirm that this is working as translation change on map is not something that is normally possible :)~~
https://user-images.githubusercontent.com/1331889/154381192-1fa4377d-5417-4e2c-99a2-56dc09c5ed30.mp4

Translation enhancements

---

resources/easyrpg-player.6.adoc
src/decoder_fluidsynth.cpp
src/decoder_fluidsynth.h
src/filefinder_rtp.cpp
src/player.cpp

The ``--soundfont`` arg will be also used by Android  Player

Fluidsynth: More flexible soundfont configuration 

---

src/game_interpreter.cpp

Fixes #2737
_(After lots of issues, at least one PR contribution should be good. Hope it will be good. :) )_

Fix for #2737 Using stream FS for Maniacs savefile operations

---

src/pending_message.cpp

Make it easier for multiplayer version to include some cpp17 headers.
No side effects.

Compatible with cpp17

---

CMakeLists.txt

This allows for `make package` (or `cmake --build build-xxx/ --target package`) to create zip archives like we do on jenkins the manual way currently.
default:
```console
[1/1] Run CPack packaging tool...
CPack: Create package using ZIP
CPack: Install projects
CPack: - Install project: EasyRPG_Player []
CPack: -   Install component: debug
CPack: -   Install component: wii
CPack: Create package
CPack: - package: xxx/build-wii/easyrpg-player-0.7.0-wii-debug.zip generated.
CPack: - package: xxx/build-wii/easyrpg-player-0.7.0-wii.zip generated.
```
`PLAYER_VERSIONED_PACKAGES=OFF` can be used on jenkins to keep name static:
```console
[1/1] Run CPack packaging tool...
CPack: Create package using ZIP
CPack: Install projects
CPack: - Install project: EasyRPG_Player []
CPack: -   Install …
```

Homebrew: CPack for distribution/debug archives

---

builds/cmake/Modules/FindSDL2.cmake

-
Tested working on 10.15. Is the oldest version I have around.

Support building on newer versions of macOS

---

src/scene_battle_rpg2k3.cpp
src/scene_battle_rpg2k3.h

This PR remembers the ATB order now if two or more actors have a full ATB gauge.
Fixes: #2775

Remember ATB order

---

resources/emscripten/emscripten-pre.js

Workaround bug in chrome developer console

---

.github/workflows/stable-compilation.yml

Now lives here: https://ci.easyrpg.org/job/player-flatpak/

Move flatpak build from GitHub Actions to Jenkins

---

src/filesystem_zip.cpp
src/filesystem_zip.h

Note that the implementation is not 100% correct.
Bit 3 of the general purpose flag is not checked, would need to forward this bit until the Local dir is read.
Also I bet there is at least one program that does not set the Bit ;)

ZIP: Support Windows Compressed Folders

---

src/translation.cpp

Support translation of Actor Name in ConditionalBranch

---

src/game_character.cpp
src/game_character.h
src/game_interpreter.cpp
src/game_interpreter.h
src/game_map.cpp
src/game_player.cpp
tests/game_character.cpp
tests/game_character_move.cpp
tests/move_route.cpp

[liblcf#444](https://github.com/EasyRPG/liblcf/pull/444)
First breaking change to liblcf this release. :)
@gamizard
FYI. When you update the Player after this PR gets merged you must also update liblcf. As we did some breaking changes here. :)

Update to new liblcf chunk names  liblcf #444

---

src/scene_battle_rpg2k3.cpp

Battle system.. Fix one issue, add two more ;)
The previous fix was incomplete. In some cases the battle was still stuck in traditional layout because the actor stayed permanently active :/.
rueter suggest moving the fix to line 1284. This worked only partially: It was better than my original fix but still triggered the assert.
My new solution: Moved the check now before ``IsBattleActionPending()``. Everything appears to work now.

Battle 2k3: (2nd try) Fix hang in traditional layout because no actor became ready

---

CMakeLists.txt
builds/android/app/src/main/java/org/libsdl/app/SDLActivity.java
builds/android/app/src/main/java/org/libsdl/app/SDLSurface.java
resources/emscripten/emscripten-shell.html

Android: Support SDL 2.26 & more lib fixes

---

resources/windows/player.manifest

Not on Windows right now.
Can someone quickly test if 32bit and 64bit Player from this PR start?

Windows: Fix Manifest for x64

---

Makefile.am

Add all missing files to the tarball

---

builds/android/app/src/main/res/values-be/strings.xml
builds/android/app/src/main/res/values-ca/strings.xml
builds/android/app/src/main/res/values-de/strings.xml
builds/android/app/src/main/res/values-es/strings.xml
builds/android/app/src/main/res/values-fr/strings.xml
builds/android/app/src/main/res/values-in/strings.xml
builds/android/app/src/main/res/values-it/strings.xml
builds/android/app/src/main/res/values-pl/strings.xml
builds/android/app/src/main/res/values-zh-rTW/strings.xml
builds/android/app/src/main/res/values/strings.xml

Wondered why they still show up in our weblate. Found the reason >.>

Android: Change translate attribute to the correct one (translatable)

---

src/game_interpreter.cpp
src/game_pictures.cpp
src/game_switches.cpp
src/game_switches.h
src/game_variables.cpp
src/game_variables.h
src/player.cpp
src/scene_debug.cpp
tests/switches.cpp
tests/variables.cpp

Thats really the last stuff in Player I will fix...

Maniac fixes

---

src/game_interpreter.cpp
src/game_interpreter.h
src/game_map.cpp
src/game_map.h
src/game_player.cpp
src/game_player.h
src/platform/sdl/sdl2_ui.cpp
src/player.cpp
tests/dynrpg.cpp
tests/game_character.cpp
tests/game_character_moveto.cpp
tests/game_player_input.cpp
tests/mock_game.cpp
tests/test_main.cpp
tests/test_mock_actor.h
tests/test_move_route.h

As discussed in https://github.com/EasyRPG/liblcf/issues/265

Encounter Rate/Steps Chunk Renaming  liblcf #456

---

CMakeLists.txt
src/filesystem_root.cpp

noticed this while updating the core on the libretro buildbot

Android: Fix libretro core build

---

src/cache.cpp
src/game_interpreter.cpp
src/game_player.cpp
src/game_system.cpp
src/game_system.h
src/game_windows.cpp
src/player.cpp
src/sprite.cpp

Maniac Feature Fixes

---

src/platform/3ds/ui.cpp

The new code is likely slower (not measured).
Fix #2981

3DS: Transitions are not blue anymore

---

src/game_interpreter.cpp
src/scene.cpp
src/scene_battle_rpg2k.cpp
src/scene_debug.cpp
src/scene_debug.h
src/scene_map.cpp
src/scene_map.h
src/window_settings.cpp

Fixes related to Input

---

src/audio_decoder_midi.cpp
src/game_character.cpp
src/game_character.h
src/tilemap_layer.cpp
src/utils.cpp

most of the warnings are harmless (but still UB). First commit solved now bugs imo.
The GetScreenZ overflow however is a real bug that messes with the rendering order somehow is not noticable, likely because it only happens at the left and top borders in very few edge cases.

Fix undefined behaviour found by UBSan

---

src/game_map.cpp
src/game_map.h
src/game_player.cpp

Please review carefully. I looked 3 times at the code and imo this is correct.
----------
Returns now an empty sentinel when a map info is missing. Also added endless loop prevention where it was missing.
Fix #2756
Fix #3013

Refactor MapInfo API

---

CMakeLists.txt
builds/cmake/Modules/FindOpusFile.cmake
resources/emscripten/emscripten-shell.html
src/audio_generic_midiout.h
src/font.cpp
src/font.h
src/game_player.cpp
src/game_system.h
src/input.cpp
src/input.h
src/output.cpp
src/scene.cpp
src/string_view.h
src/text.cpp
src/translation.cpp

Fixes various minor stuff.
Fix #2998

Various minor fixes

---

src/game_interpreter_control_variables.cpp
src/player.cpp
src/scene_map.cpp
src/scene_map.h
src/window_message.cpp

https://cachi01.itch.io/ipomoeaigmc

Support game Ipomoea

---

src/game_pictures.cpp
src/sprite_picture.cpp
src/sprite_picture.h

Only affected Maniac Patch as is a MP feature

Picture: Consider spritesheet when calculating the origin

---

src/game_actor.cpp
src/game_battler.cpp
src/sprite_enemy.cpp

@mimigris also added the ChangeEquip fix here. Pls test if it solves 2kki.

7thjojo battle fixes

---

src/game_config.cpp
src/game_config.h
src/player.cpp
src/player.h
src/window_settings.cpp

Hello!
With this commit, we add an option to change the speed of fast fowwawd, just like in the andwoid vewsion.
An appwopwiate Ini vawiable is created
```ini
[Input]
SpeedModifier=4
SpeedModifierPlus=11
```
It's pwetty minow...
Can you mewge pwease >.<

Makes speed_modifiew supew dupew fast xD 🎶🎶🎶

---

src/game_interpreter.cpp

Interpreter buildfix (lacked a rebase it seems)

---

src/async_handler.cpp
src/async_handler.h
src/audio.cpp
src/filefinder.cpp
src/game_interpreter.cpp
src/game_map.cpp
src/game_strings.cpp
src/input_buttons.h
src/platform/sdl/sdl2_ui.cpp
src/platform/sdl/sdl2_ui.h
src/platform/sdl/sdl_ui.cpp
src/platform/sdl/sdl_ui.h
src/scene.cpp
src/scene_debug.cpp
src/scene_settings.cpp
src/window_settings.cpp

small stuff not worth individual PRs

Small fixes

---

src/enemyai.cpp
src/game_interpreter_battle.cpp
src/game_interpreter_battle.h
src/scene_battle.cpp
src/scene_battle_rpg2k.cpp

@zankplus please test.
-----------
Also added sanity checks to the battle interpreter to resolve crashes when invalid enemies or actors are specified. We do these checks since years in the map interpreter.

Battle fixes

---

src/cache.cpp

Sorry this one was really sloppy :/

EasyRpg Flag: Move bmp.reset call to the correct location

---

src/async_handler.cpp
src/audio_decoder_midi.cpp
src/dynrpg_textplugin.cpp
src/game_interpreter.cpp
src/game_interpreter_map.cpp
src/game_strings.cpp
src/game_strings.h
src/maniac_patch.cpp
src/scene_battle_rpg2k.cpp
src/scene_battle_rpg2k3.cpp
src/scene_equip.cpp
src/scene_skill.cpp
src/scene_skill.h
src/scene_status.cpp
src/scene_status.h
src/sprite_airshipshadow.h
src/sprite_character.h
src/spriteset_map.cpp
src/utils.cpp

also cleaned up some compiler warnings (though this concrete weird C++ behaviour was not warned about -_-)

Regression fix of the Scene refactor: Battle skills were not listed correctly

---

.github/dependabot.yml
.github/gcc_comment_matcher.json
.github/labeler.yml
.github/workflows/pr_labels.yml
.github/workflows/stable-compilation.yml

- Automatically [label pull requests](https://github.com/actions/labeler)
- Hilight some warnings in the output
- Keep actions updated

Make our life on GitHub easier:

---

CMakeLists.txt
src/game_screen.cpp
src/scene_equip.cpp
src/window_equipitem.cpp

Small (regression) fixes

---

src/decoder_oggvorbis.cpp
src/game_interpreter_map.cpp

Fix 3ds build

---

src/game_interpreter.cpp

ChangeSpriteAssociation: Fix OOB reads

---

src/game_map.cpp

Added comments to warn about not ever doing this again.
Fix #3333
----
Test case (start the game and walk left/right in the starting room)
BAD: https://easyrpg.org/play/master/?game=yume_nikki&game-resolution=widescreen
GOOD: https://easyrpg.org/play/pr3334/?game=yume_nikki&game-resolution=widescreen

Partial revert of e7767ffb (the code that replaced min/max with clamp)

---

builds/android/app/src/gamebrowser/org_easyrpg_player_game_browser.cpp
builds/android/app/src/main/java/org/easyrpg/player/Helper.java
builds/android/app/src/main/java/org/easyrpg/player/game_browser/Game.java
builds/android/app/src/main/java/org/easyrpg/player/game_browser/GameBrowserActivity.java
builds/android/app/src/main/java/org/easyrpg/player/game_browser/GameBrowserHelper.java
builds/android/app/src/main/java/org/easyrpg/player/game_browser/GameScanner.java
builds/android/app/src/main/java/org/easyrpg/player/settings/SettingsAudioActivity.java
builds/android/app/src/main/java/org/easyrpg/player/settings/SettingsFontActivity.java
builds/android/app/src/main/java/org/easyrpg/player/settings/SettingsGamesFolderActivity.java
builds/android/app/src/main/res/values/strings.xml
src/filesystem_lzh.cpp

~Draft because I do not want to cause conflicts in the QOL PR~

Android: Add button to open save directory and better "open folder" experience

---

src/game_interpreter.cpp
src/game_interpreter_battle.cpp
src/game_interpreter_map.cpp
src/game_interpreter_shared.h

Fixes an Issue similar to https://github.com/EasyRPG/Player/pull/3320
Wasn't able to reproduce it, but here are some complains about this issue from other users:
Maniacs new editor menus seems to be creating annoying OOB command patterns in different places...

Fix OOB reads 

---

src/audio_generic.cpp
src/fileext_guesser.cpp
src/game_ineluki.h
src/maniac_patch.cpp
src/scene_gamebrowser.cpp
src/translation.h
src/utils.cpp
src/utils.h
src/window_input_settings.cpp
tests/json.cpp

Will this ever end >.>
Required for [liblcf#499](https://github.com/EasyRPG/liblcf/pull/499)

Various Fixes

---

src/sprite_picture.cpp

Clear flash on non-flash pictures

---

CMakeLists.txt
builds/android/gradle.properties
configure.ac
docs/AUTHORS.md
docs/BUILDING.md
docs/TRANSLATORS.md
src/version.cpp

[Source](https://www.youtube.com/watch?v=fTcW5l666UE)

Release 0.8.1 "Stun"

---

.github/workflows/stable-compilation.yml
CMakeLists.txt
README.md
configure.ac
docs/BUILDING.md
src/platform/sdl/sdl2_ui.cpp

Just the dependency bumps for now.

Started working on #3375

---

src/filesystem_lzh.cpp
src/filesystem_lzh.h

Fix LZH encoding detection not working

---

CMakeLists.txt
builds/android/gradle.properties
configure.ac
docs/BUILDING.md
resources/unix/easyrpg-player.metainfo.xml
src/version.cpp

~~(ignore the additional commits, will rebase when everything is cherry-picked, missing are only #3411 and #3423 )~~

Release 0.8.1.1
