- src/game_interpreter.cpp
Hi,
This is a bug fix for a problem with "Variable Reference" functionality of rpgmaker 2003.
This one:
Here's an example project that shows the bug:
https://dl.dropboxusercontent.com/u/55372319/TestVariables.zip
Talking to the dog in RPG_RT.exe returns this:
In easyrpg-player returns this:
> Fix bug with variable indexing.

- builds/android/AndroidManifest.xml
- builds/android/project.properties
- builds/android/src/org/easyrpg/player/GameBrowserActivity.java
- builds/android/src/org/libsdl/app/SDLActivity.java
- src/player.cpp
- src/sdl_ui.cpp
RESOLVED: One bug left: After ending one game logcat is spammed with "W/dalvikvm(19986): Exception thrown (Ljava/lang/NullPointerException;) while throwing internal exception (Ljava/lang/NullPointerException;)" when closing the first game and then no other game starts anymore...
and no game starts anymore. I assume SDL doesnt terminate correctly.
RESOLVED:
On some devices (Samsung e.g.) the game is reddish. This is a SDL 2.0.3 bug.
https://bugzilla.libsdl.org/show_bug.cgi?id=2291 
Workaround: Disable hardware overlays in the developer options of your device :(
> Android: Update SDLActivity to 2.0.3

- src/game_enemy.cpp
- src/game_enemy.h
- src/game_enemyparty.cpp
- src/game_enemyparty.h
- src/scene_battle_rpg2k.cpp
- src/scene_battle_rpg2k3.cpp
This should fix #398. Also fixes a related problem where the Gold/EXP/Level Up messages don't show at the end of an RPG2k3 battle. I'm not sure if there's a better way to do that last part though.
> Add enemy drops after battle

- src/game_battlealgorithm.cpp
- src/game_party.cpp
- src/game_party.h
When using an item, only one "use" should be used up now.
A quick test in RM2K showed
* the number of uses resets when an item is removed
* the number of uses stays the same when an item is added, even if the player already had x99 of the item
Also, for the same reason as #399, using a special item in battle consumes a number of uses equal to the number of targets, currently.
> Implement multi-use items.

- src/audio.cpp
- src/graphics.cpp
- src/output.cpp
- src/player.cpp
- src/scene.cpp
- src/sdl_ui.cpp
- src/system.h
Trying to play it at https://easy-rpg.org/jenkins/job/player-js-pr/ws/easyrpg-player.html
> Emscripten playground

- src/emscripten-post.js
- src/filefinder.cpp
- src/filefinder.h
- src/game_interpreter.cpp
- src/game_interpreter.h
- src/game_interpreter_map.cpp
- src/game_interpreter_map.h
- src/graphics.cpp
- src/graphics.h
- src/player.cpp
- src/scene.cpp
- src/scene_file.cpp
- src/scene_load.cpp
- src/scene_map.cpp
- src/scene_map.h
- src/scene_save.cpp
- src/scene_title.cpp
> Emscripten: Support command line, transitions and saves

- src/game_character.cpp
- src/game_map.cpp
- src/game_player.cpp
Fixes the errors I noticed in the Rainbow Treasure OP.
Some events are drawn off by one pixel. Caused by the formula in `Game_Character::GetScreenX()` and `Y()`. Changed to take the difference in pixels, not real coordinates, which I _think_ is correct. Can someone check?
The pan drags behind the characters during the OP. Changed just by increasing the pan speed, but also changed to use `SCREEN_TILE_WIDTH / 128` instead of `2`, like for characters, I think it goes here too: @Ghabry, you made that change for character speed, what do you think?
Caused by the pan in `Game_Character` being reset too early. I think this also fixes a bug where the pan is lost when teleporting within the same map (?).
Manganese's OP uses a parallax background to make it look like she's walking, but it goes the …
> Fixes for Rainbow Treasure OP

- builds/android/res/values-de/strings.xml
- builds/android/src/org/easyrpg/player/GameBrowserActivity.java
There were crashes in the dev console reported originating from a null-ini-file.
I have no idea how that can happen, the app doesnt list games that lack an ini file.
I guess this happens when the ini file got deleted (no idea why anybody does this).
Games without INI Files are now supported and a file is created if necessary. Hopefully this fixes that crash...
Also adds German translation.
> Android: Fix crash in ini access

- src/game_character.cpp
- src/game_character.h
- src/game_player.cpp
- src/game_vehicle.cpp
- src/game_vehicle.h
- src/spriteset_map.cpp
Some very minor fixes on the heels of #434.
2dfa0d5 adds a "stepping speed" to decouple the rate that characters do their left-middle-right-middle animation from their movement speed, but since it's actually the _player_'s movement speed that's faster when riding a vehicle, an alternative would be to set all the vehicle's move speeds to 1/8 and move the switch to choose higher move speeds when riding vehicles to the line changed by e7880d8. I don't think the vehicles' move speed actually affect anything but their stepping animation does it?
Was everyone ok with 10455da?
> Minor vehicle fixes

- src/game_system.cpp
- src/graphics.cpp
- src/graphics.h
- src/output.cpp
- src/player.cpp
- src/player.h
- src/scene.cpp
- src/scene_battle_rpg2k.cpp
- src/scene_map.cpp
- src/scene_title.cpp
- src/window_message.cpp
The new code takes into account that the non-graphic updates take some time, too and only when there is time in the current frame left the graphic is rendered. The game logic always runs at 60 updates per sec.
Don't merge before I verified that this works under emscripten ;)
> Improve frame skipping code. Fixes #287

- CMakeLists.txt
@take-cheeze review please?
The 'string(TOUPPER ${i} i)' directive ensures correct inclusion
of all found packages except Boost, where the variable name has
to stay in its original mixed case form (not 'BOOST' but 'Boost').
To generalize this, just include both uppercase path variables
and normal case ones.
Before, I just added 3 extra lines that find_package()'d and included boost manually, but this approach looks more general.
This patch also includes passing the `-std=c++0x` flag to the compiler, which for some reason doesn't happen on my system automatically.
> CMakeLists.txt: Fix boost paths and C++11 compilation

- .gitignore
- configure.ac
- src/game_actor.cpp
- src/game_character.cpp
- src/game_event.cpp
- src/game_interpreter_battle.cpp
- src/game_party.cpp
- src/sprite.cpp
Fixes a slowdown since convenience libtool library building for tests landed because it builds both static and shared versions by default. Building only a static libeasyrpg-player.a version is enough.
Also, updated forgotten to include .gitignore files since libtool landing.
Silenced some strict warnings.
> Autotools: disable libtool shared build by default and silence some warnings

- src/game_character.cpp
- src/game_character.h
- src/game_event.cpp
- src/game_event.h
- src/game_interpreter.cpp
- src/game_interpreter_map.cpp
- src/game_map.cpp
- src/game_map.h
- src/game_player.cpp
- src/game_player.h
- src/game_vehicle.cpp
- src/game_vehicle.h
- src/sprite_character.cpp
Fixes:
* MoveForward acts in the right direction with events with facing locked
* The action key works correctly if the hero's facing is locked.
* Autotile 46 is now passable
* Animation speeds are a lot more accurate
* Control Variable Command can now use vehicles' map id as value
* Control Variable Command works correctly when using a event's direction as value: Down -> 2, Left -> 4, Right -> 6, Up -> 8.
> Fix some character movement issues and use cleaner code

- src/game_map.cpp
- src/game_map.h
- src/game_player.cpp
- src/spriteset_map.cpp
Panoramas that 
- are larger than 320x240 
- in non-looping maps
- without the "horizontal/vertical pan" option
scroll in a very special manner. It chooses a parallax scroll speed such that it'll show the entire panorama when crossing the map, but never faster than 16 pixels per step. For this reason, we have to delay the panorama initialization until we know the image size (in spriteset_map.cpp).
These two commits should fix the opening of Link's Awakening (the RM2k3 port).
It seems that in RPG_RT if a looping maps has a large enough panorama, it isn't aligned with the top left corner. However, I won't have time in the next couple weeks to fix that.
> Fix pan speed and larger than 320x240 panoramas

- src/image_bmp.cpp
- src/image_xyz.cpp
This should fix the following warning:
```
warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
```
> check fread's return value

- src/game_character.cpp
- src/game_character.h
- src/game_event.cpp
- src/game_event.h
- src/game_interpreter.cpp
- src/game_interpreter.h
- src/game_interpreter_map.cpp
- src/game_player.cpp
- src/game_player.h
You can now play everyone's favourite: the Nasu minigame of Yume Nikki!
The hardest issue is, without breaking anything, avoiding restarting an action-triggered event when one of its last commands is a KeyInputProc waiting for the action key. There're three relevant moments that run in the following order: the update of the main interpreter, the update of the event and the update of the game player. Suppose we have an event running a KeyInputProc waiting for the action key. This is what it should happen:
Frame | Main Interpreter | Event | Game Player
-------- | -------------------- | ------- | ----------------
1 | Player presses Action Key. Event reaches command end. | - | Action key triggers event. The interpreter ran commands from this event in this frame, so its commands are not loaded …
> Improve KeyInputProc behaviour

- src/game_actor.cpp
- src/game_actor.h
- src/game_battle.cpp
- src/game_battle.h
- src/game_battlealgorithm.cpp
- src/game_battlealgorithm.h
- src/game_battler.cpp
- src/game_battler.h
- src/game_enemy.cpp
- src/game_enemy.h
- src/game_enemyparty.cpp
- src/game_enemyparty.h
- src/game_interpreter_map.cpp
- src/game_party.cpp
- src/game_party_base.cpp
- src/game_party_base.h
- src/game_screen.cpp
- src/game_switches.h
- src/game_variables.h
- src/scene_battle.cpp
- src/scene_battle_rpg2k.cpp
- src/scene_battle_rpg2k3.cpp
- src/scene_map.cpp
- src/sprite_battler.cpp
- src/sprite_battler.h
- src/window_message.cpp
Adds:
- Single Target skills for enemy
- States respect probability (A-E)
- States are respected
- Transparent msgbox for rpg2k3
- Hidden enemies
- Enemy self destruct
- enemy escape
- Enemy charge
- Enemy defend
- Only consume multi-target skills once
Unrelated: Resizing of switch/variable array when oob
Missing: Autoheal of states after time / after hit
#477,  #330 and #399
> Battle improvments

- src/game_picture.cpp
- src/sprite_character.cpp
- src/spriteset_map.cpp
- src/tilemap_layer.cpp
Always regenerate the tile cache. Should fix "Change Tilemap"-command and emscripten black tilemap. Make tilemap "important" to make fade-in more beautiful (not black)
> Fix "Change Tilemap"-command and emscripten tilemap

- src/game_battler.cpp
- src/game_character.cpp
- src/game_character.h
- src/game_interpreter.cpp
- src/game_interpreter.h
- src/game_interpreter_map.cpp
- src/game_interpreter_map.h
- src/game_map.cpp
- src/game_map.h
- src/game_player.cpp
- src/player.cpp
bd7e451 simplifies how pending movements work. It was a bit confusing with all that move_route_owner thing, which wasn't necessary. If a move route wasn't completed, but its interpreter owner did no longer exist, HaltAllMovement wouldn't stop this move route. Now all the move routes are registered in Game_Map and removed when they finish.
9bf5d9a and 0d9f17f together fix #433.
6a623cba includes the removal of Main_Data::game_data.party_location.Fixup() and Main_Data::game_data.screen.Fixup(). These Fixups aren't necessary and will be removed soon from liblcf. EasyRPG/liblcf@e119c051
> Restructure pending movements and fix some emulation bugs

- src/filefinder.cpp
On Windows, `\\` must not be converted into `/`, however `\` when used in some patched RPG Maker editors must be converted into `/` on UNIX filesystems.
> Filefinder: Fix subfolder finding on non-win32 filesystems

- src/game_character.cpp
- src/game_vehicle.cpp
- src/sprite_airshipshadow.cpp
- src/tilemap_layer.cpp
- src/tilemap_layer.h
> Fix tilemap drawing and airship ascending/descending animation

- Makefile.am
- builds/autoconf/aminclude/doxygen.am
This actually removes the doxygen output folder (doc) when running the *clean targets.
Also the timestamp is actually generated now, otherwise the documentation will be regenerated every time.
Related: #322 #323
> autotools: Fix doxygen magic

- src/background.cpp
- src/game_map.cpp
- src/graphics.cpp
- src/scene_title.cpp
- src/spriteset_map.cpp
- src/window.cpp
Also prevents warnings when no title/chipset/backdrop is used.
This fixes ゆめ２っき (Yume2kki) which fade-out the screen and displays a message box which never closes because the Draw code is never called.
> Fix hang introduced in 0.3.1 release

- src/cache.cpp
- src/sprite_character.cpp
- src/spriteset_map.cpp
- src/tilemap.cpp
Problem was that autotile cache read out of bounds, a black tilemap is now generated to work around all issues.
My fix in 0.3.2 had some bugs :/
> Fix crash when empty chipset is used

- src/game_commonevent.cpp
- src/game_event.cpp
- src/game_interpreter.cpp
- src/game_interpreter.h
- src/game_interpreter_battle.cpp
- src/game_interpreter_map.cpp
- src/game_map.cpp
- src/game_player.cpp
- src/game_screen.cpp
Thanks to c5093e5, the game player will be blocked if the main interpreter executed a command in its last update. Any non-empty auto starting event will block completly the game player as long as it runs. This fixes #629, [a bug where the player would trigger an event after a KeyInputProc](https://easy-rpg.org/forums/viewtopic.php?f=4&t=599) and surely other unreported bugs.
e88b886 fixes one of the bugs reported by Mr.Faq2014 [in the forums](https://easy-rpg.org/forums/viewtopic.php?f=4&t=605).
>Up to now, in EasyRPG 0.3.2 after seeing the intro (one of the backgrounds doesn't scroll properly(...)
> Fix more emulation bugs

- src/game_commonevent.cpp
- src/game_commonevent.h
- src/game_map.cpp
- src/output.cpp
- src/platform/sdl_audio.cpp
" 	When the start condition (switch) of a parallel common event is not met the interpreter is now suspended instead of destroyed. Parallel common events continue where they got suspended the last time. "
> Fix Issue 453 (parallel interpreter resume) and common event save writing

- src/game_character.cpp
- src/game_player.cpp
- src/graphics.cpp
- src/graphics.h
- src/main_data.cpp
- src/output.cpp
- src/player.cpp
- src/scene.cpp
- src/scene_load.cpp
- src/scene_map.cpp
- src/screen.cpp
- src/tilemap_layer.cpp
Fixes #426
Fixes #449
Fixes #620
Fixes a crash when pressing F12 if the player was runned with --load-game-id or --new-game
Fixes a bug where event 121 in map 4 of Monigote Fantasy would start during the opening cutscene. Kudos to Ghabry, his event tracer has been very useful for this.
> Improve return to title screen (F12) and fix some bugs

- src/game_interpreter.cpp
- src/game_interpreter_map.cpp
- src/game_player.cpp
- src/scene_map.cpp
* 3015228 fixes #684 and #683 .
* 7559b6d fixes #548.
* 28957a5 fixes an annoying bug in multiple games when, after a teleport, the hero will make a step even if no key is pressed at that moment (specially annoying when using the stairs in OFF). 
* 63d03e0 fixes a bug where you get stuck in an infinite loop when speaking with Marin (the girl that saves you) in Zelda: Link's Awakening.
> Fix some bugs before 0.4

- src/game_battlealgorithm.cpp
- src/game_battler.cpp
- src/game_interpreter_map.cpp
More battle bugs: The gauge was updated for invisible enemies, resulting in Eisen to attack directly after spawning. Eisen only has a heal spell but was handled wrong and killed him. The Battle interpreter does not expect that this can happen and does not really kill the actor before next turn -> crash if one enemy killed himself that way and somebody attacked him.
#723 
Vampires Dawn 2 one was really simple, just a out-of-bounds array read. This also explains why it was fixed in a different release. Just luck.
#724
> Fix #723 (OFF) and #724 (VD2)

- builds/android/res/menu/game_browser_supported_key.xml
- builds/android/res/menu/player.xml
- builds/android/res/values/strings.xml
- builds/android/src/org/easyrpg/player/button_mapping/ButtonMappingActivity.java
- builds/android/src/org/easyrpg/player/game_browser/GameBrowserHelper.java
- builds/android/src/org/easyrpg/player/game_browser/ProjectInformation.java
- builds/android/src/org/easyrpg/player/player/EasyRpgPlayerActivity.java
- src/output.cpp
Fix #726 
Also adds logic to copy saves from game dir to save dir if save dir has no saves yet. (otherwise people will complain that saves got lost after copying games to external storage)
Also adds bug Report function to ingame menu
> Android: Fix write detection

- src/game_commonevent.cpp
- src/game_event.cpp
- src/game_event.h
- src/game_interpreter.cpp
- src/game_interpreter.h
- src/game_interpreter_map.cpp
- src/game_player.cpp
- src/game_player.h
Implement branching on ["Triggered by decision key"](https://github.com/EasyRPG/Player/blob/d41ead91ef98cefa4f3a6aae984b65f754a0ec28/src/game_interpreter_map.cpp#L1974). This fixes the second issue in #692. You can now stand on the stepladder near the conference room.
This patch just threads a bool from `Game_Player::CheckActionEvent` through `Game_Event` to `Game_Interpreter`.
> Branch on "Triggered by decision key"

- CMakeLists.txt
Building with CMake is broken, because C++11 is used, but `CXX_STANDARD` isn't specified.
This does bump the minimum required version of CMake though.
> Specify C++11 for CMake

- src/platform/sdl_audio.cpp
The previous patch used the same function name but different parameter count and order. Now we have an official function since SDL_mixer 2.0.2.
> Emscripten: use new Mix_OpenAudioDevice from SDL_mixer 2.0.2 API

- src/game_character.cpp
- src/game_character.h
- src/game_commonevent.cpp
- src/game_commonevent.h
- src/game_event.cpp
- src/game_event.h
- src/game_interpreter.cpp
- src/game_interpreter_map.cpp
- src/game_map.cpp
- src/game_map.h
- src/game_player.cpp
- src/scene_gamebrowser.cpp
- src/scene_map.cpp
- src/spriteset_map.cpp
The most important bit is in Game_Map::Update. The process in which all the events are updated is now more convoluted, but also more accurate to the output of the event tracer plugin. To make the code more digestible, I've changed the container of the events and common events from std::map<int, EASYRPG_SHARED_PTR<Game_(Common)Event>> to std::vector<Game_(Common)Event>. This means a linear search, but we don't ever search common events and there are few maps with more than a thousand events.
Some facts about the game logic update thanks to the event tracer.
1. The order of event update is: Parallel common event, parallel event, non-parallel event, non-parallel common event.
2. A keypress starts an event in the same frame it gets detected by KeyInputProc command.
3. If a parallel (common) …
> Improve order of event updates

- src/baseui.cpp
- src/baseui.h
- src/game_character.cpp
- src/game_character.h
- src/game_commonevent.cpp
- src/game_commonevent.h
- src/game_event.cpp
- src/game_interpreter.cpp
- src/game_interpreter.h
- src/game_interpreter_map.h
- src/game_map.cpp
- src/game_picture.cpp
- src/game_player.cpp
- src/game_player.h
- src/graphics.cpp
- src/scene_map.cpp
- src/sdl_ui.cpp
- src/sdl_ui.h
- src/window_shopparty.cpp
0ff788e and 7fb61a7 fix the issue reported by omochi-man by email.
> Fix some nasty bugs

- src/audio_sdl.cpp
Fix #710. Also, remove remaining stray `\n` symbols in warning messages.
> Don't free from Mix_LoadMUS_RW() and play ADPCM with BGS_Play

- src/audio_sdl.cpp
- src/game_interpreter.cpp
- src/game_interpreter_map.cpp
- src/game_temp.cpp
- src/game_temp.h
- src/scene_end.cpp
- src/scene_gamebrowser.cpp
- src/scene_menu.cpp
- src/scene_title.cpp
- src/window_base.cpp
Fixes some crashes (opening the menu in some cases, reported via Android bug mails...).
Adds saving/loading the ATB flag.
End Game returns to game browser now and music fade out works for ADPCM files (SDL ~.~)
> Crash fixes + ATB

- src/game_battlealgorithm.cpp
As descipted in #397 spell "Blutsaugen" in "Vapires Dawn" should restore sp.
But currently it restores HP.
> Fix AbsorbingSP regenerates HP (#397)

- src/game_battlealgorithm.cpp
now drain sp spells can fail if there is no more sp on target
also it shows currentTargets  SP if its lower then spells SP-Effect
> fix spell drain #809

- src/filefinder.cpp
Now my question is, why did MSVC not blow up on the PR builder for this one?
It should really not have cached the `filefinder.cpp`, as the file changed in cc2d2e67453caa7d3db32c8b85635089b801285b.
> Fix the windows build.

- builds/android/src/org/easyrpg/player/player/EasyRpgPlayerActivity.java
So, that's the fix for #812.
I've add the function OnRestart() which is called each time the user return on the app after exiting the application (without destroying it). So the display is now in full and not only five pixels on the top.
> Fix for the restarted screen display

- Makefile.am
- src/filefinder.h
- tests/directorytree.cpp
The initialization of FileFinder has been very slow. Games with more than ten thousand of files may take a couple seconds just creating the directory tree. It might take even longer in the least powerful devices we support. This has to change.
I've added a new test with the purpose of benchmarking FileFinder's directory tree creation. Then I've compared three containers using perf. For that I've created two test projects that you can [download here](https://dl.dropboxusercontent.com/u/30277047/directorytree%20tests.7z). Both projects have 8000 files in the folder Picture, but directorytree-1 has them in multiple subfolders, while in directorytree-2 they're all in the same folder.
``` perf stat -r 20 -d ./directorytree --project-path ~/easyrpg/directorytree-1 ```
| boost::flat_map    | …
> Replace boost::flat_map in FileFinder

- src/game_battlealgorithm.cpp
- src/game_battler.cpp
- src/game_battler.h
- src/scene_battle_rpg2k.cpp
- src/scene_battle_rpg2k3.cpp
Conditions are applied to battle_actors now.
GainMoneyMessage only shown if money >0
I only tested it with rpg Maker 2k but should work on 2k3...
> Conditions in Battles

- src/game_actor.cpp
- src/game_actor.h
- src/game_battlealgorithm.cpp
- src/game_battlealgorithm.h
- src/game_battler.cpp
- src/game_battler.h
- src/game_enemy.cpp
- src/game_enemy.h
- src/game_interpreter.cpp
#821 
fixes #820 
Items: Consuming SP
Items: crit
Items: Conditions
Items: Ignore Dogerate
Items: Attributes increase/decrease Damage
Defending/Charged: On Dead stoped
Interpreter: ConditionChange Dead reduces HP to 0 now
Spells: Attributes increase/decrease Damage
Conditions: Silence and Hit fixed
> BattleFixes 

- src/battle_animation.cpp
- src/battle_animation.h
- src/game_actor.cpp
- src/game_battlealgorithm.cpp
- src/game_battler.cpp
- src/game_enemy.cpp
- src/scene_battle_rpg2k.cpp
- src/scene_battle_rpg2k3.cpp
- src/sprite.h
- src/sprite_battler.cpp
- src/sprite_battler.h
This basicly fixes all issues reported in the E-Mail. Really bad bugs :(, but great that finally somebody helped us finding them. Few hours before 0.4.1.
> No enable to select the right char for items or skills in battle
VD2 does not have a cursor graphic for ally select in System2. RPG_RT also flashes, the flash was added. This needed a change to the BattleAnimation drawable because I needed a Sprite that can flash.
> healing a charakter in battle could give an dead char life. So if it is his turn the battle stops and you couldnt do something.
Reviving dead actors was not resetting the dead state correctly. It was also possible that a dead actor had a full gauge (because he died the same time his turn is), then the dead actor will deadlock the game when his Action starts.
Also VD2s …
> Fix deadlocks in RPG2k3 battle and other VD2 battle problems

- builds/wii/Makefile
- src/filefinder.h
- src/output.cpp
- src/sdl_ui.cpp
- src/system.h
- Using `vsnprintf()` and `snprintf()` with g++ 4.8.2 is possible, but because of a quirk only with gnu extensions enabled.
- RTTI is not a C feature, so move it to `CXXFLAGS`
- Debug information might be interesting sometimes and the `boot.dol` gets them stripped anyway, so enabling (`-g`)
- `<cstdio>` is needed for `FILE*`, the jenkins script did that change for quite some time, so was forgotten :expressionless:
- Some variables were not used, so moving them or at least silence the compiler
> Fix the Wii port compilation and warnings

- builds/android/res/layout/settings_activity.xml
- builds/android/res/values/strings.xml
- builds/android/src/org/easyrpg/player/SettingsActivity.java
- builds/android/src/org/easyrpg/player/game_browser/GameBrowserHelper.java
Yosh ! 
I just pushed the option in setting to disable sounds , by using the "--disable-audio" that was mentioned in the  #575 issue. I hope that fits with what was asked. 
Oui-Oui baguette. Cf BlisterB haha
> Adding the possibility to disable sounds in app settings

- builds/vs2015/Player.vcxproj
- builds/vs2015/Player.vcxproj.filters
- src/bitmap.cpp
- src/bitmap.h
- src/cache.cpp
- src/filefinder.cpp
- src/filefinder.h
- src/graphics.cpp
- src/graphics.h
- src/message_overlay.cpp
- src/scene.cpp
- src/scene.h
- src/scene_map.cpp
- src/scene_map.h
- src/scene_title.cpp
- src/scene_title.h
- src/sprite.cpp
- src/sprite.h
- src/spriteset_map.cpp
- src/tilemap.cpp
- src/tilemap.h
- src/tilemap_layer.cpp
- src/tilemap_layer.h
See the commit messages for detailed info.
I also measured hard light with and without lookup table. The lookup is cache unfriendly (64kb) but is faster then direct calculation because Hard light has a 50% branch prediction miss chance per color...
For saturation would be more tricky because RGB are combined here, I "only" saved an alloc and a blit here.
Fill (AddBackground, called once per frame) is also faster now by using OP_SRC which doesn't handle alpha correctly but that doesn't matter in this case.
Branch Pred: https://stackoverflow.com/questions/11227809/why-is-processing-a-sorted-array-faster-than-an-unsorted-array
Fixes #846
> Make HardLight, Saturation, Fill and FileFinder faster

- Makefile.am
- builds/vs2015/Player.vcxproj
- builds/vs2015/Player.vcxproj.filters
- src/filefinder.cpp
- src/rtp_table.cpp
- src/rtp_table.h
Change init strategy of rtp table from recursive std::initializer_list to seperate init_lists. This fixes a crash on emscripten and other platforms (3DS). Fix #854.
I read somewhere that this can segfault because the inner std::init_lists are a temporary. But I can't find the link anymore :(
> Fix emscripten (!)

- builds/android/app/src/main/jni/src/Android.mk
- builds/vs2015/PropertySheet.props
- builds/wii/Makefile
- configure.ac
- src/font.cpp
This makes freetype automagic on when available. Otherwise it defaults to off (I hope, copy-pasted from that gentoo article *g*)
Removed freetype from Wii, not sure if we will ever need it for this platform...
> Make freetype an optional dep

- src/game_event.cpp
- src/rtp_table.cpp
- src/window_keyboard.cpp
VS2015 wants a BOM now otherwise it will compile utf8 strings incorrectly :(.
This worked in older Version of VS :/
Also fix that div/0 that carstene1ns encountered in UiD
> crash fix in stop_count + utf8 on Windows

- builds/android/app/src/main/java/org/easyrpg/player/SettingsActivity.java
So, that may be just a little mess from me ('cause, i've got some problems when things are not really logical), but for me, it's really impractical to not be able to modify the button layout directly after having create it. Until now, when the users want to create a layout, they need to click on "Add an input layout", create the layout and click again on an other button to edit the layout. With just adding the edit after the creation, you save time and it's like... More practical ? 
(For now, i've only test it with the android emulator 'cause my phone hate me, but i plan to test it with an other phone, though that should work).
> Android: Add the direct edit of the buttons layout after creation

- CMakeLists.txt
- Makefile.am
- builds/cmake/Modules/FindHarfbuzz.cmake
- configure.ac
Added in automagic mode and will won't be enabled if FreeType is disabled.
> Add HarfBuzz support to Autotools and CMake

- Makefile.am
- configure.ac
- src/audio_decoder.cpp
- src/audio_resampler.cpp
- src/audio_resampler.h
- src/decoder_libsndfile.cpp
- src/decoder_libsndfile.h
- src/system.h
Hello,
As explained before in the [forum](https://easy-rpg.org/forums/viewtopic.php?f=4&t=633)  these are two additions to the audio layer of the player:
- decoder_libsndfile to enable wav playback without sdl (depends on libsndfile)
- audio_resampler to enable arbitrary resampling (depends on libspeexdsp, or libsamplerate)
The AudioResampler is meant to wrap any AudioDecoder and intersects if SetFormat or SetPitch are called.
I haven't changed anything in the sdl audio files so these changes only affect background music as sound effects don't use the AudioDecoder class.
> Added optional dependency to libsndfile and libspeexdsp

- src/audio_resampler.cpp
The FMMIDI frequency was already being halved from 44100 to 22050. The line removed was halving MIDI again (22050 to 11025 Hz), doing FMMIDI playback too much phone-like.
The half frequency in FFMIDI is for performance purposes on low end ports (used for synthesizing, saves a lot of CPU), not needing to be resampled later (which spends additional CPU).
> Don't half fmmidi frequency twice

- src/decoder_libsndfile.cpp
Fixes the bug described in the second post of issue #910 - NOT the original bug in the issue.
Explanation of the bug:
libsndfile_decoder was not properly reverting the finished flag when the stream was reverted, therefore the code in `audio_decoder.cpp` triggered an endless recursion when calling itself after rewinding :
```cpp
int AudioDecoder::Decode(uint8_t* buffer, int length) {
if (paused) {
memset(buffer, '\0', length);
return length;
}
int res = FillBuffer(buffer, length);
if (res < 0) {
memset(buffer, '\0', length);
} else if (res < length) {
memset(&buffer[res], '\0', length - res);
}
if (IsFinished() && looping) {
++loop_count;
Rewind();
if (length - res > 0) {
int res2 = Decode(&buffer[res], length - res);
if (res2 <= 0) {
return res;
}
return res + res2;
}
}
return res;
}
```
> Fixes a bug in libsndfile_decoder

- src/battle_animation.cpp
- src/battle_animation.h
- src/font.h
- src/game_actor.cpp
- src/game_actor.h
- src/game_battle.cpp
- src/game_battlealgorithm.cpp
- src/game_battlealgorithm.h
- src/game_battler.h
- src/game_enemy.cpp
- src/game_enemy.h
- src/game_interpreter.cpp
- src/player.cpp
- src/scene_battle_rpg2k.cpp
- src/scene_battle_rpg2k3.cpp
- src/sprite_battler.cpp
- src/utils.cpp
- src/utils.h
- src/window_battlestatus.cpp
- src/window_skill.cpp
To explain the not so obvious Things:
Due to changes to make the z-value working correctly only the last anim Frame was rendered. The BattleAnimation inherits from Sprite now which allows direct drawing on the Screen in that for-loop.
Seems to work fine only had to rename some conflicting functions.
The RNG Change:
I had a skill with 50% hit rate that basicly almost missed. I read on stackoverflow that rand with modulo can result in a bad Distribution. Therefore I switched this to the modern C++11 Api.
> More battle fixes

- src/game_actor.cpp
- src/game_actor.h
- src/game_battlealgorithm.cpp
- src/game_battler.cpp
- src/game_battler.h
- src/window_base.cpp
- src/window_equipitem.cpp
Classes are handled silly in RPG Maker 2003. The class settings don't matter at all on startup (it only shows the class name in the status scene), everything else is only applied when "Change Class" event is used...
The naming in liblcf is really inconsistent what do you think about adjusting this?
mighty_guard <-> super_guard
lock_equipment <-> fix_equipment
two_weapon <-> two_swords_style
> Class handling

- Makefile.am
- configure.ac
- src/audio_decoder.cpp
- src/audio_decoder.h
- src/audio_resampler.cpp
- src/audio_resampler.h
- src/decoder_fmmidi.h
- src/decoder_libsndfile.cpp
- src/decoder_libsndfile.h
- src/decoder_mpg123.cpp
- src/decoder_mpg123.h
- src/decoder_oggvorbis.cpp
- src/decoder_oggvorbis.h
- src/decoder_wildmidi.cpp
- src/decoder_wildmidi.h
What this does in detail:
- adds another decoder for midi (based on libwildmidi)
- sounds mostly like timidity from `sdl_mixer`, but supports pitch changes through our `audio_resampler`
- disabled by default (needs additional magic to find configuration file)
- adds an ogg vorbis decoder (based on either libtremor or libogg, libvorbis and libvorbisfile)
- can use fallback decoders, when initializing a library fails
- currently only works for mpg123 and wildmidi
- ogg can be played by `libsndfile` if the oggvorbis decoder is unavailable
- mp3 will be played by `sdl_mixer` (if smpeg/libmad is available), if mpg123 fails
- reworked the other `audio_decoder`s a bit to fix some coding style and hide all internal structures.
> Additional Audio decoders

- src/game_character.cpp
Fixes the regression in 葬 (and probably many others :) from #913.
(Sorry!)
> Fix regression when original_index = 0

- src/3ds_decoder.cpp
Seems like ov_pcm_total is not reliable for audio size calculation. I noticed during lpp-3ds developing that it can cause major issues leading to wrong audio size as output (bigger then it should, leading to random audio garbage being reproduced by the audio device). This commit is a little temporary fix which is less accurated (some samples will be probably dropped in some ogg files) but which is confirmed to work as intended.
> 3DS: Fix for random audio corruption with libTremor

- src/audio.cpp
- src/audio.h
- src/audio_3ds.cpp
- src/audio_3ds.h
- src/audio_al.cpp
- src/audio_al.h
- src/audio_decoder.cpp
- src/audio_decoder.h
- src/audio_resampler.cpp
- src/audio_resampler.h
- src/audio_sdl.cpp
- src/audio_sdl.h
- src/decoder_fmmidi.cpp
- src/decoder_fmmidi.h
- src/game_interpreter_map.cpp
- src/game_system.cpp
Another bigger change is that now full paths are passed to the audio interface instead of the api using file finder. This is needed to support ineluki properly (will do another PR for this later).
And need to compile test OpenAL and 3ds.
> Fix some audio issues

- src/scene_debug.cpp
- src/scene_debug.h
- src/scene_map.cpp
- src/scene_map.h
- src/scene_menu.cpp
- src/scene_menu.h
- src/window_varlist.cpp
Related #948 
All applies to TestPlay mode only:
This makes accessing our debug scene easier, when in TestPlay mode a "Debug" item will be shown in the normal menu.
The debug sceen also got 2 new options (besides var and switch editing): Save and Load, they do what the name says (and ignore "save forbidden" setting).
Some games forbid menu calling but don't worry, this can be overriden with "Shift+5x B" (when SHIFT is not pressed anymore the counter is reset).
> Add Debug option to Scene Menu (TestPlay only)

- src/audio_decoder.cpp
- src/filefinder.cpp
- src/filefinder.h
- src/game_system.cpp
- src/utils.cpp
- src/utils.h
Differences to the real patch because we use the BGM Api directly:
- It uses our BGM Api directly, this means compared to the real patch it will not overaly with the normal BGM which must be stopped manually (Needs testing in games if this is a problem)
- The Patch allows playing multiple MP3s at the same time, but who needs this. (and Disharmony fixed this problem)
- No support for the "loop" statement on line 2, it will always loop.
- Our code does not care about the format, it can play all formats we support (but nobody uses this obviously).
This patch is enabled for all games, I see no risk in doing this. In the unlikely case a game really uses a filename with ".link" and then fails, we will see this in an Android bug report ;)
Algorithm:
When .link found it reads the first line and …
> Add support for Inelukis MP3 Patch

- Makefile.am
- configure.ac
- resources/unix/bash-completion/easyrpg-player
- Options expecting arbitrary arguments (invoke parsing lcf) are not completed of course.
- `--load-game-id` and `--start-map-id` do not complete currently, because they do not respect the `--project-dir` and `--save-dir` settings yet. Therefore they are useless for out of folder invocation and disabled.
- CMake integration was not worth for now, as this is being refactored currently.
> shell completion for BASH

- src/scene_battle_rpg2k.cpp
- src/sprite_battler.cpp
Now everything fades out again and Battle 2k system had a bad timing issue: Damage and Kill animation were without a pause, looked wrong, the kill animation waits now for damage.
> Battle: Fix problems with non-fading out enemies

- src/filefinder.cpp
- src/game_actor.cpp
- src/game_actor.h
This game is stupid and has invalid inventory in the slots.
The weapon contains a switch e.g., RPG_RT filters this and the editor shows it as (None) but the database still contains the value. Way to go Enterbrain!
Furthermore this 350 MB games saves tons of space *cough* by crossreferencing files via
Panorama\\..\\Title\\Title3, nice, that path is now rewritten to Title\\Title3 by the FileFinder.
I also tested files directly in the root directory (Panorama\\..\\Title3), becomes Title3 :+1: 
That strange feature is only used when filefinder path != canonical, so only happens when "." or ".." is a path component which can't happen when using the editor without hex editing.
> Fix Yume2kki ugliness

- builds/android/app/src/main/jni/src/Android.mk
Needed by EasyRPG/buildscripts#10.
> Android: Remove libmad linkage

- src/audio_decoder.cpp
- src/audio_decoder.h
- src/audio_psp2.cpp
- src/decoder_wav.cpp
- src/decoder_wav.h
- src/utils.cpp
- src/utils.h
This fixes some flaws in the FASTWAV implementation:
- Seek always returned false when "file_" was set, resulting directly in a crash in OpenAL, otherwise during the first rewind (assert triggered)
- Bits per sample was read from the wrong field, was off by 6 bytes.
- "data" chunk was not always found because the code assumed that the chunk position is 4-byte-aligned
- Chunks after "data" would play as noise
- Code was not big endian aware
The audio decoder will now only go 10 recursions deep when trying to refill the buffer after a Rewind. This fixes a typical stack overflow case.
Fix #992
> Fix FastWAV issues and crash in AudioDecoder-loop

- src/bitmap.cpp
- src/plane.cpp
- src/plane.h
- src/scene_battle.cpp
- src/scene_battle.h
- src/scene_map.cpp
- src/scene_map.h
- src/screen.cpp
- src/screen.h
- src/spriteset_battle.cpp
- src/spriteset_battle.h
- src/spriteset_map.cpp
- src/spriteset_map.h
- src/tilemap.cpp
- src/tilemap.h
- src/tilemap_layer.cpp
- src/tilemap_layer.h
- src/weather.cpp
- src/weather.h
Tone change of the screen is now calculated per sprite. This means the tone is only calculated once and afterwards the Blit is normal speed as if no tone is changed. Special case is a "gradient change", when the tone changes per frame. In that case it uses the old behaviour because is faster for that case.
Gives a significant speed boost on slow hardware for that case obviously ;)
> Tone: Performance improvements

- Makefile.am
- builds/vs2015/PlayerLib.vcxproj
- builds/vs2015/PlayerLib.vcxproj.filters
- src/audio_resampler.h
- src/audio_sdl.cpp
- src/audio_sdl.h
- src/audio_secache.cpp
- src/audio_secache.h
- src/scene_gamebrowser.cpp
- src/scene_title.cpp
Audio SE cache. Sound effects are cached now in a ~~5~~ 1 MB cache, only the first access does a cache miss. Afterwards it takes the decoded buffer directly. This also gives AudioDecoder for SE the first time. Should fix 24bit Pom Gets Wifi SEs and gives proper playback speed for the Wii that has a broken SDL resampler \o/.
3DS and PSVita don't use the cache yet.
Cache clearing strategy:
When the cache limit is reached all entries not being accessed in the last 10 seconds are removed.
Fixes #895.
> Audio SE performance improvements

- src/game_event.cpp
- src/game_interpreter.cpp
- src/game_player.cpp
Visual demonstration of the off-by-two:
https://easyrpg.org/play/master/?test-play&start-position=8%201&new-game
Fixed:
https://easyrpg.org/play/pr1020/?test-play&start-position=8%201&new-game
Hold STRG (for walk everywhere) and one tile to the right. You will notice a minor scroll of two pixel which doesn't happen anymore in my PR.
And smash bros: https://easy-rpg.org/play/master/?game=smashbros
Fixed: https://easy-rpg.org/play/pr1020/?game=smashbros
Try to fall out of the bottom of the arena.
**The 2nd commit** "Don't change direction when"... has a test case here: 
[Project5.zip](https://github.com/EasyRPG/Player/files/443094/Project5.zip)
Online master: https://easyrpg.org/play/master/?game=issue_1020
Online fixed: https://easyrpg.org/play/pr1020/?game=issue_1020
In the old player the …
> Fix interpreter problems in smashbros, Doraemon 2,  特に理由 and Win' Wind' Windy'

- builds/android/app/src/main/java/org/easyrpg/player/game_browser/GameBrowserActivity.java
- builds/android/app/src/main/java/org/easyrpg/player/player/EasyRpgPlayerActivity.java
- builds/android/app/src/main/java/org/easyrpg/player/settings/SettingsAudioActivity.java
- builds/android/app/src/main/java/org/easyrpg/player/settings/SettingsGamesFoldersActivity.java
- builds/android/app/src/main/java/org/easyrpg/player/settings/SettingsInputActivity.java
- builds/android/app/src/main/java/org/easyrpg/player/settings/SettingsVideoActivity.java
- src/scene_title.cpp
No idea how this happens, probably Android memory management stuff.
I reinit now the settings when the gamebrowser (re)loads.
I ask everybody to install the Jenkins APK on your device and then just touch around and check if the "Game folders" list is empty.
Fix #1021
> Android: Try to fix strange crashes (SettingsActivity = null)

- src/cache.cpp
- src/plane.cpp
- src/sprite_battler.cpp
Instead of using weak_ptr is now shared_ptr and gives a 10 MB cache. Otherwise behaviour is the same as before. This prevents tons of cache misses (e.g. every frame during gauge battle) we usually get.
Cache clearing strategy:
When the cache limit is reached all entries not being accessed in the last 10 seconds are removed.
**Debug output is enabled** to better showcase that the cache works. will disable this before merging.
> Improve Bitmap cache

- builds/android/app/src/main/res/values-be/strings.xml
- builds/android/app/src/main/res/values-de/strings.xml
- builds/android/app/src/main/res/values-es/strings.xml
- builds/android/app/src/main/res/values-fr/strings.xml
- builds/android/app/src/main/res/values-hu/strings.xml
- builds/android/app/src/main/res/values-it/strings.xml
- builds/android/app/src/main/res/values-ja/strings.xml
- builds/android/app/src/main/res/values-ko/strings.xml
- builds/android/app/src/main/res/values-pt-rBR/strings.xml
- builds/android/app/src/main/res/values-ru/strings.xml
- builds/android/app/src/main/res/values-th/strings.xml
- builds/android/app/src/main/res/values-uk/strings.xml
- builds/android/app/src/main/res/values-zh-rTW/strings.xml
- builds/android/app/src/main/res/values-zh/strings.xml
- This adds `Belarusian`, `Ukrainian` and `Russian`
- Ignore the whitespace change in `Thai`, it was simply forgotten to change before...
- One string is still missing in `Chinese (Taiwan)`, hope this gets added before the deadline (will rebase this then)
- GitHub does not render the `Korean` symbols for me here. I can assure they are there in the file/repository.
Note, that I removed some `how_to_use_easy_rpg_explanation` strings... These have been outdated for roughly 8 months. I added an issue on transifex shortly after the app could read from multiple folders and would recurse in subfolders, but these were never changed over half a year later. I think having a complete and correct english text is better than having a broken and outdated translation in the main "FAQ".
This only affects …
> Android: Update all translations for 0.5

- builds/3ds/Makefile
- src/player.cpp
Because this crashes on many normal firmwares... :( and DSP works flawless anyway.
> Nintendo 3DS: Disable khax

- src/bitmap.cpp
Fixes the Aëdemphia crash.
Invalid pixels were accessed when a Tone changed CharSet had less than the expected pixel size.
This was also the reason why it occured almost nowhere: The game needed tone change AND a charset of wrong size.
> Add sanity check to ToneBlit.

- src/game_interpreter_map.cpp
- src/game_screen.cpp
0.5 or 0.5.1? In my opinion 0.5 is in feature freeze... but the maintainers can decide.
Conflicts are unlikely because the picture IDs are huge, added debug output to become aware of it. DynRPG doesn't touch this region either (and we don't support it)
Today I learned: The PPP supports pointing Wait, Zoom and Transparency, too.
We can solve this in our editor by simply allowing \V everywhere ^^
Test case (Master): https://easyrpg.org/play/master/?game=picpointer
Test case (PR): https://easyrpg.org/play/pr1035/?game=picpointer
> Implement PicPointer Patch.

- src/bitmap.cpp
- src/game_map.cpp
- src/graphics.cpp
- src/input_buttons.h
- src/input_buttons_desktop.cpp
- src/scene_file.cpp
- src/window_selectable.cpp
- Menu in *Mystic Star* is accessible
- Background in *Embric* changes correctly
- FPS counter is more visible on bright background
- Scrolling through long lists is now easier with `Page up`/`Page down` buttons
> Fix some little annoyances

- src/game_interpreter.cpp
- src/game_map.cpp
- src/game_map.h
- src/scene_map.cpp
See commit description
Also fixes the following case:
```
Teleport to Map2
HideScreen
ShowScreen
Wait 0
HideScreen
ShowScreen
```
Delete Map 2 and run that event parallel. The error "Map 2 not found" is executed at the Wait 0.0 position (before it appeared after the first HideScreen)
> Fix Razas battle start (Transitions in parallel interpreters)

- src/game_actor.cpp
- src/game_battlealgorithm.cpp
- src/player.cpp
- src/player.h
Some RPG2k battle messages are incorrect. Also, lots of Japanese messages are broken.
Wine + RPG_RT.exe:
Unpatched ("会心の一撃！！" is expected in this game, not "痛恨の一撃！！"):
Patched:
Wine + RPG_RT.exe:
Unpatched (Broken Japanese message. Also, "攻撃力 (ATK)" is incorrect):
Patched:
> RPG2k battle message fixes

- src/game_battlealgorithm.cpp
- src/game_party.cpp
Finally...
Concerning hitrate if not obvious:
Before the code evaluated as (100 - (100 - hit_chance)) * REST because was in 2 different lines.
But correct order is 100 - (100 - hit_chance) * REST, so the 100 - is the last.
The requirement for "std::ceil" can be tested via: Actor has 0/0 SP and check is for 34-100% exhaust. When HP is full is 33.3% exhaust, but RPG_RT triggers the 34% case.
> Battle: Fix Hitrate calculation for normal attacks and Fatigue

- builds/opendingux/Makefile
- builds/opendingux/gcw-zero/run.sh
- src/utils.cpp
I had to add a header in utils.cpp to make it compile on the GCW0. The new GCW0 toolchain has support for SDL2 so let's use that instead. Since the old script no longer worked, i modified it so it loads RTPs and Games from the home folder instead. Let me know if there are any issues.
> Fix GCW0 port

- resources/easyrpg-player.6.adoc
- resources/unix/bash-completion/easyrpg-player
- src/filefinder.cpp
- src/filefinder.h
- src/player.cpp
- src/player.h
This adds RPG2k >= 1.50 and RPG2k3 >= 1.05 detection (Related: #1031).
Usage:
```cxx
if (Player::IsMajorUpdatedVersion()) {
// RPG2k >= 1.50 / RPG2k3 >= 1.05
} else {
// RPG2k < 1.50 / RPG2k3 < 1.05
}
```
Engine overrides:
option|version
---|---
--engine rpg2kv150|RPG2k v1.50 - 1.51
--engine rpg2k3v105|RPG2k3 v1.05 - v1.09a
> RPG2k >= 1.50 and RPG2k3 >= 1.05 detection

- src/sprite_character.cpp
This recovers large CharSet support removed since #137 fix,
allowing CharSet files starting with a dollar sign to be
calculated by 4x2 SpriteSets. This differs from VX Ace behavior.
The purpose of using large 4x2 spritesets instead individual
spritesets like VX Ace does is to keep reduced file access
on games wanting to use multiple large characters.
Also keeps code lesser complicated for this custom feature.
Test case to use with the PR:
[largecharset.zip](https://github.com/EasyRPG/Player/files/559675/largecharset.zip)
> Add large CharSet support

- src/battle_animation.cpp
- src/bitmap.cpp
- src/screen.h
Simple solution based on the work of @kakurasan until I have time to polish #1062. And easier to review ;)
Screen to 2500 is save, there was nothing between pictures and screen, the next are battle windows at 3000.
Pictures are at 1050 and battleanim at 2400 for major updated, so gives buffer for more then 1000 pictures.
> Place BattleAnim above Picture when "MajorUpdated" engine detected

- src/bitmap.cpp
This is a regression introduced with the performance optimisations for bitmap blits.
In this case getting rid of the fast path doesn't hurt much because is only taken when a rotation happens.
Related: #898
> Fix lack of transparency after rotating

- src/scene_battle_rpg2k.cpp
1) Segfault when selecting a previous actor when one of the skipped actors was dead.
2) The wrong battle algorithm was removed (from the front, but actually the latest is at the back). This is the famous "Has no action but got a turn"-bug.
Fix #933
I removed the sanity check because the only way to trigger this is a bug in the code (which is found now).
> Battle 2k: Fix bugs when selecting a previous actor.

- src/game_actor.cpp
- src/game_actor.h
- src/game_interpreter.cpp
- src/game_party.cpp
- src/game_player.cpp
- src/game_vehicle.cpp
- src/scene_equip.cpp
- src/window_equip.cpp
- src/window_item.cpp
- src/window_shopparty.cpp
Vehicles with custom event routes were not moving at all, one function call missing.
This fixes "Dunkle Schatten" - The ship never reached our heros.
The equipment command has a function "unequip all", for some reason this was never implemented :o
This removes our "Item -1 is invalid" debugmsg ;). "Item 0 is invalid" is still generated when a variable is really 0, that's correct.
> Interpreter: Fix Equipment command and Vehicle movement

- src/game_actor.cpp
- src/game_actor.h
- src/game_battlealgorithm.cpp
- src/game_battlealgorithm.h
- src/game_battler.cpp
- src/game_battler.h
- src/game_enemy.cpp
- src/game_interpreter_battle.cpp
- src/scene_battle.cpp
- src/scene_battle_rpg2k.cpp
- src/scene_battle_rpg2k3.cpp
- src/scene_battle_rpg2k3.h
- src/sprite_battler.cpp
Enable combo simply repeats the whole action and reduces a counter.
Skill reflect is a bit more "fun" but was surprisingly easy to implement in the BattleAlgorithm (good API design): GetTarget lies to the caller and returns the source when reflected. Therefore battleAlgorithm will handle the whole damage calc and applycation automatically correct. 
The only exception is PlayAnimation because the animation is played twice: Once normal and once on the reflected target.
(De)buffing is that [x] Reduce Resistance option. When checked this buffs or debuffs the Attack Elements by 1/-1. Maximum shift is +-1 and when e.g. an actor is buffed with +1 and the enemy debuffs it becomes 0.
Related: #821
Bonus:
2k3: Damage numbers "jump" now
Multitarget attacks did not target all actors when one was dead …
> Battle 2k3: Implement "Enable Combo", skill reflection, (de)buff and minor things

- src/game_battle.cpp
- src/game_battler.cpp
- src/game_party.cpp
- src/scene_actortarget.cpp
The test for Battle Commands was completely wrong (only worked for 1st actor)
The subskill fix is the same one used in other places: The check must be >=.
The diff is a mess because of the identation change, the only relevant change is from
```
case RPG::Skill::Type_normal:
case RPG::Skill::Type_subskill:
```
to
```
if (skill.type == RPG::Skill::Type_normal || skill.type >= RPG::Skill::Type_subskill) {
```
The item_usage change will cause minor issues when loading EasyRPG savegames: Items with more than one use will have an incorrect usage count until the usage limit is reached once.
Unlimited and Single use items are not affected. Unlimited doesn't care about uses at all and Single will wrap on first use (because 2 >= 1)
> Fix some issues in Wolfenhain

- src/game_interpreter_map.cpp
This makes RPG_RT more happy when loading our savegames
(Stream read error)
To reproduce use a "Speicherstein" in Vampires Dawn and save in EasyRPG.
Load in RPG_RT: Old version: Stream read error. New version: Loads fine.
I'm quite sure ```int RawStruct<RPG::EventCommand>::LcfSize``` in liblcf has the same bug because reencoding with lcf2xml results in "Stream read error" again.
> Fix lcf-size calculation for non-ascii-strings in event commands

- .gitignore
- Makefile.am
When trying to work with gnome-builder, this issue emerged. The change in Makefile.am seems to fix this.
Also adds the gnome-builder .buildconfig to .gitignore.
> Fix asciidoc manpage generation when using a different working folder

- builds/psvita/Makefile
- src/psp2_ui.cpp
- src/psp2_ui.h
This pull will do four different things:
- Adds filters (aka shaders) support (at the moment there are 4 shaders available: None, Sharp Bilinear, LCD 3x, xBR). These will be interchangeable during player execution by the user by swinging the touchscreen left/right.
- Increases GPU, GPU crossbar and BUS clocks (from 111 mhz to 222 mhz) allowing shaders to get the best results.
- Disables vsync. This will produce a slight frameboost without any bad conseguence.
- Fix some typo errors and updates Makefile for new vitasdk compatibility.
> Overclocked GPU/BUS,added shaders,disabled vsync.

- src/background.cpp
- src/battle_animation.cpp
- src/game_battler.cpp
- src/game_battler.h
- src/game_map.cpp
- src/game_map.h
- src/game_player.cpp
- src/game_screen.cpp
- src/sprite_battler.cpp
Implements screen shaking. Fixes #565 (finally lol).
-----
Actually updating the shake variables is already done in `Game_Screen` (yay!), so I just had to wire them up to the coordinate calculations.
It's a bit hard to tell, but on the battle screen in RPG_RT, timers, damage counters, and battle animations look like they are _not_ affected by screen shaking. So I only made shaking affect the background and the enemies/heroes.
> Shaking things up

- src/async_handler.cpp
- src/game_actor.cpp
- src/game_battler.cpp
- src/game_character.cpp
- src/game_enemy.cpp
- src/game_enemyparty.cpp
- src/game_event.cpp
- src/game_interpreter.cpp
- src/game_map.cpp
- src/game_party_base.cpp
- src/game_screen.cpp
- src/player.cpp
- src/utils.cpp
- src/utils.h
The intention of this PR is to make random number generation totally portable by:
Replacing `rand() % a` with `GetRandomNumber(0, a-1)` generally, but also
* I changed [this line](https://github.com/EasyRPG/Player/compare/master...scurest:rand?expand=1#diff-34f34f675ce52452da855f1469fc5421R728) which was probably a bug
* `rand() / (RAND_MAX / a + 1)` was replaced with `Utils::GetRandomNumber(0, a - 1)` (is this right?)
* I also added `ChanceOf` for the common case of getting a bool with a certain probability (this could also be used for the battle algorithms)
The algorithm it uses isn't part of the standard.
My first idea was to copy the `uniform_int_distribution` from (say) GCC's stdlib here, but it's a _lot_ of code, and it's complicated because it has to deal with RNGs with …
> Make RNG portable

- src/game_event.cpp
- src/game_map.cpp
Fixes #1086, fixes #1084. Although in the latter, there are still issues besides the soft-lock.
Also fixes yet another bug in `MakeWay` :(
> Don't activate touch trigger when the player is on top of an event on the same layer

- resources/easyrpg-player.6.adoc
- resources/unix/bash-completion/easyrpg-player
- src/input_buttons.h
- src/input_buttons_desktop.cpp
- src/keys.h
- src/options.h
- src/player.cpp
- src/player.h
- src/scene_file.cpp
- src/sdl_ui.cpp
- src/sdl_ui.h
- src/system.h
- src/window_battlecommand.cpp
- src/window_battleoption.cpp
- src/window_battlestatus.cpp
- src/window_selectable.cpp
- src/window_shop.cpp
- src/window_shopnumber.cpp
_The touch part is not tested, as I do not have such device._
(Maybe @fdelapena tries this out with his iPhone 😼)
> Basic Mouse/Touch support

- src/game_interpreter_map.cpp
- src/game_picture.cpp
- src/game_picture.h
- src/game_screen.cpp
- src/game_screen.h
Fixes #1046, fixes #1063. There are also some other small fixes to picture behavior.
`Game_Picture` was refactored substantially. `Command{Show,Move}Picture` now have much less responsibility, and the public surface area of `Game_Picture` was reduced. Some tiny changes to PicPointerPatch handling were also made.
> Refactor/Bug fixes for Pictures

- src/game_actor.cpp
- src/game_actor.h
- src/game_battle.cpp
- src/game_battle.h
- src/game_commonevent.cpp
- src/game_event.cpp
- src/game_interpreter.cpp
- src/game_interpreter_battle.cpp
- src/game_interpreter_map.cpp
- src/game_interpreter_map.h
- src/game_map.cpp
- src/scene_battle_rpg2k.cpp
- src/scene_battle_rpg2k.h
- src/scene_battle_rpg2k3.cpp
- src/scene_battle_rpg2k3.h
See issues #1127 and #1129 
Additionally this fixes the tutorial. Bug in "CHange Class" command (thx @carstene1ns)
Fixed the Event 10005 is invalid problem after loading a savegame. See https://community.easyrpg.org/t/some-little-player-bugs/352/8
Also removed some unused battle functions (just some cleanup)
> Fix game breaking bugs in "The Huntress of the Hollow" and "ThisEvent" savegame loading issue

- src/game_interpreter_map.cpp
Reported by mail, fighting the woodchopper in eternal legends repeats endlessly.
This basicly means that the abort handling code in the interpreter was broken since years but was dead code until I fixed the abort case for huntress of the hollow :D
When "Abort Battle" is used and there is no other handler (Victory, Escape or Defeat) for the battle moving the interpreter to "End Battle" failed and the battle repeated. The interpreter is now advanced by one line when this happens.
Also fixed this for the defeat and the escape handler but here the bug is only possible through a malformed database because the "Execute handler" settings are part of the Enemy encounter dialog, so they are always generated when these options are on.
This fixes a regression introduced in commit 11246f2a
> Fix regression when "Abort Battle" command is used and the Encounter-command has no handler

- src/scene_battle_rpg2k.cpp
- src/scene_battle_rpg2k.h
When starting a battle through an event command, the last checkbox (Preemptive Attack in official 2k translation, First Strike in Don’s) allows to prevent enemies from attacking during the first turn.
This didn’t seem to had been implemented, so I’ve added it.
> Implement Pre-Emptive attack for RM2k battle

- src/game_interpreter.cpp
- src/game_map.cpp
- src/game_map.h
- src/game_player.cpp
- src/spriteset_map.cpp
The `parallax_*` values in the SaveMapInfo object are currently treated as "the current value of the parallax parameteres", but in RPG_RT they seem to be treated as an override, and the values in the map properties should be used if they aren't set. This PR implements this, which fixes #1071.
There's also a general refactor of the parallax handling into one namespace, more docs, and readability improvements for `Scroll{Left,Right,Up,Down}`.
> Refactor and fix for parallax BGs

- src/game_map.cpp
http://devopsreactions.tumblr.com/post/74372071314/the-code-refactoring-trap
Related #1147 (Note that the misalignment of the background on game start is not fixed by this - even exists in 0.5. What is fixed is the map after the tent-dialog-cutscene)
This also fixes the bugreport by Undertale and Earthbound lover in "Continue Stop Rise" (report was: some doors entrances are now in walls instand of the door)
> Fix regression in horizontal scrolling introduced in 7f83a3bf

- src/psp2_ui.cpp
Such call is completely useless since rescheduling is already performed with sceKernelWaitSema calls and produces unnecessary slowdowns in the renderer thread.
> Removed useless delay thread call in renderer thd.

- src/game_map.cpp
This was caused by a bad refactor. Essentially, when I refactored to handle scrolling up as scrolling down by a negative distance, I neglected to replace `min` by `max`. See the commit message for details.
7f83a3bf has caused a bit of trouble, huh? ><;;
> Fix #1160; regression from 7f83a3bf

- src/scene_name.cpp
- src/scene_name.h
- src/window_keyboard.cpp
- src/window_keyboard.h
This is a workaround which fixes #364.
The proposed approach displays hiragana and katakana for CP932 games and basic latin and symbols for the rest of encodings. Japanese games lose access to the symbol table, but original RPG_RT also does not support this.
This also adds limited Hangul script to the scene.
> Use hiragana and katakana only for Japanese games in hero name scene and support Hangul

- resources/emscripten/emscripten-post.js
- src/player.cpp
This allows replacing the storage used by simply editing the index.html emscripten shell (Module.EASYRPG_FS = MY_FS) and implementing MY_FS.
Motivation: This allows somebody who hosts our Player to provide e.g. a web based storage (session based) instead of the default local storage.
Mostly for rmarchiv because it wants to provide server-baked storage.
Bonus:
Reference client implementation of a FS doing AJAX via VanillaJS to transmit save files. The server part is more work ;)
Format is in both directions.
```json
{
"1": "BASE64 OF SAVE01.LSD",
"14": "BASE64 OF SAVE14.LSD"
}
```
Request URL hardcoded to "/save"
```javascript
var SAMPLEFS = {
mount: function(mount) {
// reuse all of the core MEMFS functionality
return MEMFS.mount.apply(null, arguments);
},
to_binary: function(dataURI){ …
```
> Emscripten: Allow replacing the filesystem used for "Save" folder

- src/game_character.cpp
This is basicly a copy-paste of all the Face-related stuff in MoveTypeCustom into BeginJump. (When a Jump is performed most commands are ignored, except Move and Face it seems)
> Fix #1171: Respect Turn commands when calculating the Jump direction.

- src/sprite_character.cpp
- src/sprite_character.h
This fixes the first part of #1169, with the invisible event. I'm PRing it separately because this one should be much easier to review than the fix for the second part.
> Always draw event sprites, even for tile_id = 0

- src/game_character.cpp
- src/game_character.h
- src/game_event.cpp
- src/game_event.h
- src/game_map.cpp
This fixes (or at least improves) the second bullet point (and only the second bullet point) in #1115. Events with movement type cycle now prefer moving forward, if possible. Basically, the algorithm is now
1. When we're ready to move, try moving forward (or in the default direction if we're facing the wrong way: Right for Left-Right, Down for Up-Down)
2. If that failed for 20 frames, keep trying to move forward, but if it fails, now try moving the opposite way too.
3. If that fails for 40 more frames, try going forward and if it fails, now move (don't just try to move) in the opposite way, and reset
By "try to move" I mean to do the same thing as doing a `Move` in a move route with the "Ignore if can't be moved" option toggled on. It turned out, though, that this also behaved differently …
> Improve Movement Type Cycle

- resources/easyrpg-player.6.adoc
- src/game_actor.cpp
- src/game_actor.h
- src/game_battlealgorithm.cpp
- src/game_battlealgorithm.h
- src/game_interpreter_map.cpp
- src/game_message.cpp
- src/game_message.h
- src/player.cpp
- src/player.h
- src/scene_battle_rpg2k.cpp
- src/scene_battle_rpg2k.h
- src/utils.cpp
- src/utils.h
- src/window_battlemessage.cpp
- src/window_battlemessage.h
- src/window_message.cpp
- src/window_message.h
This pull request adds support for placeholders (%S, %O, %V, %U) and word-wrapping introduced in the English release of RPG Maker 2000 v. 1.61.
Word-wrapping is currently **still measuring** invisible codes like ``\C[x]``, ``\S[x]``, ``\<``, so ``\C[2]\S[5]Hello`` is longer than ``Hello``. This is what RPG Maker 2000 is doing, so I’m not introducing new incompatibility here. The current code for displaying messages (e.g. for parsing parameters) has too many side effects, and changing it was a bit too complex for me, so I’ve decided not to do it right now.
Word-wrapping is currently only applied to the battle messages, like in RPG Maker 2000 v. 1.61. However, in future it can be used in other cases:
* When game translatability with LcfTrans is finished (#797), it would make sense to enable …
> Support RM2k v.1.61 (placeholders and word-wrapping)

- src/window_keyboard.cpp
On Windows (+ RPG_RT) there is not "を" or "ヲ" in the "Enter Hero name" scene and there is "ヴ" instead.
Hiragana:
Katakana:
EasyRPG Player (unpatched)
This patch replaces "を" and "ヲ" with "ヴ", and allows users to input "ヴ".
EasyRPG Player (patched)
> Replace "を" and "ヲ" with "ヴ" in the "Enter Hero name" scene

- resources/emscripten/emscripten-shell.html
fixes unwanted scrolling on Arrowkey press and spacebar.
For older Chrome Versions and some other browsers this fix disables the browser functions for f1 to f12
> WebPlayer: fixes unwanted scrolling on Arrowkey press

- src/game_battlealgorithm.cpp
Sorry, I’ve found a bug in my critical hit message code (it swapped %O and %S and didn’t have %O). This should be correct now.
> Fix placeholders in 'critical hit' message in RPG2kE

- CMakeLists.txt
- Makefile.am
- README.md
- builds/cmake/Modules/FindOpus.cmake
- configure.ac
- src/audio_decoder.cpp
- src/decoder_opus.cpp
- src/decoder_opus.h
- src/filefinder.cpp
This tries to add Opus decoder support to Player (fix #1159).
The FillBuffer code is probably wrong currently. There are no crashes with current settings here so far.
It currently does some minor buffer related noise, I guess it gets unhappy with the resampler buffering mechanism, somewhere the buffer may be too tight or some delay involved in underruns.
Amendments to this PR are totally welcome.
> Add opus support

- src/background.h
- src/battle_animation.cpp
- src/drawable.h
- src/fps_overlay.cpp
- src/frame.h
- src/game_character.cpp
- src/game_picture.cpp
- src/game_player.cpp
- src/game_player.h
- src/message_overlay.cpp
- src/scene_battle.cpp
- src/scene_battle_rpg2k.cpp
- src/scene_battle_rpg2k3.cpp
- src/screen.h
- src/sprite_airshipshadow.cpp
- src/sprite_battler.cpp
- src/sprite_character.cpp
- src/sprite_timer.cpp
- src/spriteset_map.cpp
- src/tilemap_layer.cpp
- src/weather.h
- src/window.cpp
- src/window_base.cpp
- src/window_battlemessage.cpp
- src/window_keyboard.cpp
- src/window_message.cpp
- src/window_numberinput.cpp
- src/window_savefile.cpp
I hope I got all Z layer usages and didn't break something :/
The Z layers are now categorized in categories and the category marker are the upper 8 bit minus the sign bit. So 127 categories are possible (like a IPv4 Class A network ;)).
I didn't touch the Map Z layer stuff because I don't want to break the event order rendering... (but is in theory possible to figure out now because is all in PriorityMap)
The order has some limitations. See game_picture.cpp comments.
Fix #1195
> De-magic-numbify some Z layer settings and BattleAnim-Picture-Render Order

- src/game_map.cpp
- src/game_map.h
- src/game_player.cpp
- src/game_player.h
I think this is ready....
Keep track of how much we've actually panned so we know not to go past where the pan should be.
Should fix #1169. It don't think it fixes _any_ other panning problems though. Matching RPG_RT turned out to be a nightmare -_-;;
I needed a non-negative mod function. Ghabry added a proper one in 59b4b54, so the `mod` function I added should be changed to use that whenever both of them make in into master.
> Fix off-screen panning

- src/audio_generic.cpp
- src/audio_sdl_mixer.cpp
- src/filefinder.cpp
- src/filefinder.h
- src/font.cpp
- src/game_interpreter_map.cpp
- src/game_message.cpp
- src/game_party.cpp
- src/game_system.cpp
- src/graphics.cpp
- src/graphics.h
- src/message_overlay.cpp
- src/message_overlay.h
- src/output.cpp
- src/player.cpp
- src/sdl_ui.cpp
- src/utils.cpp
- src/utils.h
- tests/output.cpp
^----- Proposed screenshot for the blogpost
New features:
- The message overlay can now collect all messages since startup (Graphics::Init was moved to the beginning of Player::Init) and shows them when the Ui is ready (e.g. the NDSP error message on the 3DS)
- For file-log and on-screen similiar messages increment now a counter [x10] which is appended to the line. For the file-log a message is always written twice: The 1st time it happens and a 2nd time how often it was duplicated (this is to ensure that something is logged in case of crashes), (see screenshot)
- The FileFinder got a new function to strip path components outside of the game path (see screenshot, look at the filenames reported). When the path is outside the game path it does nothing, so RTP paths are not touched.
- …
> Improve the Output system

- .gitignore
- src/game_actor.cpp
- src/game_battler.cpp
- src/game_battler.h
- src/game_enemyparty.cpp
- src/game_event.cpp
- src/game_interpreter.cpp
- src/game_interpreter_battle.cpp
- src/game_map.cpp
- src/game_player.cpp
- src/scene_battle_rpg2k.cpp
- src/scene_battle_rpg2k.h
- src/scene_logo.cpp
- src/sprite.cpp
- src/sprite_battler.cpp
- src/sprite_battler.h
- src/utils.cpp
- src/utils.h
- src/window_message.cpp
- src/window_message.h
Additionally fixes some compiler warnings (ReplacePlaceholders had a bug)
And some ASAN error in battle of Wolfenhain.
Monster in 2k that can't act don't act anymore. ^^
Fixed a regression introduced in #1062
> Bug squashing (#987, #1111, #1112, #1145, #1176, #1180, #1186, #1191)

- src/scene_item.cpp
Fixes a bug introduced in 0c7cbac3cf13.
The wrong constructor of `Scene_ActorTarget` was used which lead to `actor_index` being the `item_index` instead, which lead to items used as skills with out-of-bounds IDs.
> Allow item usage again instead of crashing

- src/game_map.cpp
- src/game_map.h
Fixes the VD-encounter bug reported through IRC
> Fix default case of battle encounters terrain tag check

- src/game_actor.cpp
- src/game_map.cpp
- src/game_party.cpp
- src/game_picture.cpp
- src/game_screen.cpp
- src/game_vehicle.cpp
- src/scene_save.cpp
Replace +=, -=, ++, -- operations on and referencing of liblcf data fields.
This is required for the liblcf vNext rewrite and my automatic converter can't handle these special cases.
The big commit (https://github.com/Ghabry/easyrpg-player/commit/8d21a02b91397a47280fd6ce67820e1fd8bcfbde) follows in a month or two when the JSON code is more ready.
> lcf vNext Step one: Rewrite some data access on liblcf fields

- src/game_map.cpp
- src/game_map.h
- src/game_player.cpp
The only games affected by this are the two japanese Dragon Quest fangames DQ列伝 and DQ2悪霊の勇者・製品版
Fix #1253
The two new functions in Game_Map could be used in some other places, too but I'm too afraid to break something...
> Redirect Teleport and Escape skills that target areas to the owning map

- src/game_interpreter.cpp
- src/game_map.cpp
- src/game_vehicle.cpp
- src/game_vehicle.h
- src/message_overlay.cpp
- src/spriteset_map.cpp
See the comments in the sourcecode.
The "Panorama" problem was observed in the game reported by Penguin "Oech" Dude directly at the beginning.
And the MessageOverlay problem was observed while testing the SetVehicle warnings I added :D.
> Implement obscure SetVehicle behaviour (and 2 minor fixes)

- src/player.cpp
This was caused by a liblcf API change that requires a istream now to do encoding detection for the database.
Otherwise this will only detect the passed string (rpg_rt.ldb) which is correctly detected as UTF-8.
> Fix encoding detection. 

- src/game_commonevent.cpp
- src/game_event.cpp
- src/game_event.h
- src/game_interpreter.cpp
- src/game_interpreter.h
- src/game_interpreter_battle.cpp
Works across all engines - EraseEvent is handled in a special way to prevent regressions.
I decided to make these commits independend of my RPG2k3 1.12 PR because this makes the reviewing easier and doesn't depend on any new liblcf chunks.
Fix #1201
> Support ThisEvent in CommonEvents

- src/player.cpp
- src/player.h
- src/scene_name.cpp
- src/window_keyboard.cpp
- src/window_keyboard.h
Not very elegant (RuLatn and Letter are almost identical), but useful for many games.
Can also be used for the following languages with no known games: Belarusian, Bulgarian, Crimean Tatar, Ukrainian (although those will feel second-class citizens as the extra letters are below Russian and not in their alphabetic places).
**NOT** useful for Serbian and Macedonian (too many extra letters). There are no known games in Serbian and Macedonian, but we’d eventually need to devise an encoding-independent way of specifying a language for such things. (Also needed for UTF-8 support.)
> Add Russian name input

- src/scene_name.cpp
- src/scene_name.h
- src/window_keyboard.cpp
- src/window_keyboard.h
Seems to work for me, please test.
Feedback is welcome. I’m particularly not happy with the forward declaration of ``struct Keyboard_Layout;``.
---
EDIT by @carstene1ns: Fixes #1272.
> Allow re-using name-input layouts for different languages

- src/bitmap.cpp
- src/game_character.cpp
- src/game_character.h
- src/game_event.cpp
- src/game_interpreter.cpp
- src/game_player.cpp
- src/game_player.h
- src/message_overlay.cpp
This includes a fix for #1268, a fix for #1198, and adds support for two undocumented(?) GetActors uses.
This was split from #1287, so the testcase for this (which proves said GetActors calls exist) is there.
The future suggestion-aka-nitpick referring to this part is:
"`IsStopping` in Player ought to be something like `IsReadyToMove`?"
> Various fixes (#1268, #1198, two undocumented GetActors uses, Bitmap::Create(w, h, col). Split from other PR)

- src/game_interpreter.cpp
SetVehicleLocation actually supports changing the map without doing a transition (not as thought in #1257) while the party is boarded but only when the target map has an event with the same event ID.
Because this sounds more like a bug than intended behaviour this was implemented using a normal teleport and without a check if the target map has a valid event. Doesn't match the RPG_RT behaviour due to the transition but this bug is strange and only used by a few VIPRPG games, not worth implementing perfectly.
The patch is good enough to fix the test case. I hope not even worse offenders appear. I reordered the code a bit so it matches other teleport code. Moved the vehicle reposition code after the "return false" in the if-block to ensure that the vehicle isn't moved before a teleport can …
> Implement even more obscure SetVehicleLocation behaviour

- src/scene_name.cpp
- src/window_keyboard.cpp
- src/window_keyboard.h
Thanks to @kane159 for the glyph table 👍
> Traditional Chinese support for name input scene

- src/game_actor.cpp
- src/game_actor.h
- src/game_interpreter.cpp
This hopefully fixes Class BattleCommands issues.
A potential further improvement would be to research what happens when battle commands space is exhausted, but as this should almost never come up, I believe my current solution (sacrifice the Row command first, then just give up and become non-compliant with the 7 length bound) works.
Test cases to be used with Ib English Translation's RPG_RT v1.1.0 for comparison against Player, along with documentation on more or less what they do:
https://20kdc.duckdns.org/PR1TestCase.zip
Recommended further steps (maybe nitpicky, but still):
In Player:
ChangeClass logic to SetClass: that's for if/when SetClass gets an `std::vector<uint32_t>` return value or something, necessary because the skill list needs to be preserved.
In liblcf:
`changed_class` …
> Class / BattleCommands -related fixes

- builds/opendingux/Makefile
- builds/opendingux/gcw-zero/readme.txt
- src/decoder_fmmidi.cpp
- src/system.h
This fixes the GCW0 port, again.
I switched back to using SDL 1.2 because it runs faster on the GCW0 than the SDL2 version.
(etnaviv, the 3D driver, still sucks on it and will probably stay that way. SDL2 version works fine tho)
Let me know if that's an issue.
I also added some headers to some files (i think they got removed ? not sure) because these are required for compiling. 
Switching to using -Wl,--no-as-needed because it does not compile with -as-needed.
I tried it on my GCW0 and it works okay. It seems smoother too.
Btw, it also requires this pull request too : [here](https://github.com/EasyRPG/liblcf/pull/220).
> Fixes for GCW0 port

- src/color.cpp
- src/color.h
- src/game_actor.cpp
- src/game_battler.cpp
- src/game_enemy.cpp
- src/game_interpreter.cpp
- src/game_interpreter.h
- src/game_interpreter_map.cpp
- src/game_party.cpp
- src/sprite_battler.cpp
- src/sprite_battler.h
Required for https://github.com/EasyRPG/liblcf/pull/222
Only required on Wii, Vita and 3DS.
Didn't break Color, tone change still works.
> Change types from int to int32_t where necessary for liblcf compat

- src/filefinder.cpp
Checks now for "_DIRENT_HAVE_D_TYPE" (defined by the dirent_win.h header, checked this) which is the documented way to test for this extension.
DT_UNKNOWN is handled now correctly for filesystem that don't provide the file type without stat'ing.
> Improve portability for "dirent->d_type"

- src/game_actors.cpp
Reported here https://twitter.com/oech3/status/978183636699684864
>  Fix crash when loading a savegame where "savegame actor arraylen < LDB actor arraylen"

- src/game_character.cpp
- src/game_character.h
- src/game_event.cpp
- src/game_player.cpp
Tested with various move types and only "Continious" move types have this issue.
The others already work for some reason / or the behaviour doesn't apply to them.
> Movement related fixes

- src/game_battle.cpp
Finally something simple to review ;)
Due to an oversight GetAllowEscape was used to check if random encouter escapes are allowed but this flag is only for escape spells, Escaping is always possible in random encouters >.>
Iirc this was reported via mail as a bug in Vampires Dawn, but can't find it anymore.
> Battle 2k: Always allow escape escaping from random encounters

- src/cache.cpp
- src/filefinder.cpp
- src/scene_logo.cpp
Sorry for using FindImage(".", "ExFont") instead of adding a new FindImage("ExFont") and that strange check in FileFinder for the root directory, but I'm currently heavily modifying filefinder.cpp and don't want to reapply gigantic changes ^^.
Related: #1349
> Allow loading of custom ExFont file if available in the game directory

- src/scene_map.cpp
Otherwise parallel events are running for one frame but their visual changes are not visible until the transition is finished.
Won't work properly in emscripten.
Fix #1358
> Update map spriteset before a transition.

- src/scene_battle_rpg2k.cpp
- src/scene_battle_rpg2k.h
This PR intends for, in the initial messages about enemy appearances, not including the ones that are hidden just like RM2000. For this:
- A "Game_EnemyParty::GetVisibleEnemies" function is created.
- A variable with the visible enemies is initialized right after "enemies" and saved in .cpp. Here I'm not sure whether it should be a private attribute in the header instead, please tell me which one is better.
- Change in Scene_Battle_Rpg2k the references to GetEnemies for GetVisibleEnemies.
> Initial Enemy appearance message: Only visible enemies.

- src/game_party.cpp
- src/game_party.h
- src/game_player.cpp
Problem: When stepping in damaged terrain and there's more than 0 damage, there's no flash indicating it.
Solution: Put that flash after trial and error getting the exact color, power and time. Also, no need to invoke the damage function to the party when the damage is 0.
> Generate quick light red translucid flash when step on damaged terrain.

- src/window_message.cpp
Problems:
1. If you put in a message "\n[x]" whose name is also "\n[x]" it generates a loop problem.
2. If "\n[x]" or "\v[x]" result in smaller characters (i.e. a/0) and they are the last characters in the message, it will generate an out-of-range error because the actor_replacement_start will be bigger than the replaced message.
Solutions:
1. The actor_replacement_start should not be the end of the number, but code_start.
2. actor_replacement_start should clamp with the size of the string after being replaced to avoid these problems.
3. "start_code - 2", the -2 while it doesn't really bother it's pointless and the function is clearer without it (not a function that needs efficiency over simplicity).
> Windows_Message::ApplyTextInsertingCommands fix

- src/game_interpreter.cpp
- src/game_system.cpp
- src/game_system.h
Problem: An option where, if an (OFF), Empty or filename in parenthesis is called, makes all the sound effects stop (SE_Stop). This also happened in instances outside "CommandPlaySound" (where the creator puts it intentionally), for example in Battle sound animations for effects that include anything but a flash, and generated sound cuts everywhere.
Solution: Add in SePlay and OnSeReady an optional input bool "stop_sounds" (by default "false") that only stop all sounds if it's true, with the OnSeReady input being dependent of the SePlay input. We also put SePlay in CommandPlaySound with stop_sounds = true, the only case where we want it to.
> [Regression fix] Stop sounds (OFF) / (...) only when CommandPlaySound is called.

- builds/android/app/src/main/java/org/easyrpg/player/MainActivity.java
- builds/android/app/src/main/java/org/easyrpg/player/player/AssetUtils.java
Add support for reading the game from a ZIP file (game.zip) in standa…lone mode instead of a plain directory.
This addresses issues with filenames containing umlauts or other special characters not being allowed into AssetManager's asset bundle.
Also allows for compression to save space.
> ZIP file support for standalone mode on Android.

- src/scene_menu.cpp
Solution: If the character can't act when they're selected for the skill menu, reproduce a Buzzer sound and do nothing else.
> Restrict access to Skill Menu if character has "Do Nothing" restriction.

- src/game_actor.cpp
- src/game_actor.h
- src/game_party.cpp
- src/game_party.h
- src/game_player.cpp
> Step State Damage: "Implement HP and SP decrease by a state on map" and "Prevent Terrain Damage"

- src/player.cpp
- src/scene_battle.cpp
also, improve Win9x emulation with a proper message ;)
The proposed fix adds a black background before displaying the browser quit message by allowing transition out on battle quit when the battle test flag is set. Better approaches are welcome.
> Fix missing background on battle test quit in emscripten

- src/background.cpp
- src/background.h
- src/battle_animation.cpp
- src/bitmap.cpp
- src/bitmap.h
- src/game_character.h
- src/game_event.cpp
- src/game_interpreter_map.cpp
- src/game_player.cpp
- src/game_vehicle.cpp
- src/screen.cpp
- src/sprite.cpp
- src/spriteset_battle.cpp
- src/spriteset_map.cpp
- src/weather.cpp
The issues: ToneBlit is not very efficient, Battle tones and Gradual TintScreen are tinted differently, and Sprite flashes.
ToneBlit is very heavy performance-wise, which forces us to use two different ways to implement tintscreen in our screen:
1. We use ToneBlit for any individual tile, background and sprite when they're drawn.
2. After all the drawables are drawn, we use ToneBlit to the screen.
- The 1st method, with a little modification, allows us to generate Sprite flashes that ignore the tintscreen (for example, a white flash with a dark-red tintscreen, it should appear completely white instead of red-ish). The 2nd doesn't allow that.
- The 1st method is more efficient when the tintscreen remains static, but slower when the tone screen is gradually changing.
- The 2nd is used for …
> ToneBlit performance and Method Implementation, Sprite Flashes, other fixes

- src/game_actor.cpp
- src/game_character.cpp
- src/game_character.h
- src/game_event.cpp
- src/game_player.cpp
I discovered the bogus level sanity check when loading one of the savegames bundled with Shitigadianzu (they are > max_level).
The GetReal -> GetSprite change is the first step for my fix of the collision tests in #886 but the function renaming alone doesn't hurt imo.
> Fix Kanga Punch (1413), Shitigadianzu (1412) and minor stuff

- builds/cmake/Modules/FindSDL2.cmake
- src/game_interpreter.cpp
- src/tilemap_layer.cpp
The Drawable std::list -> std::vector change actually broke something because the stable sort of std::list.sort shadowed another bug introduced by the 2k3E z-layering code :/
The "+1" added matches what was there before (See e.g. 0.5.0).
> Regression fix

- src/scene_load.cpp
Fixes bugs when loading game debug menu. The stack would keep the old
maps and game state. This breaks when you try to load from battle.
> Pop all scenes when loading game

- src/game_player.cpp
- src/game_vehicle.cpp
The observation by Sormat was correct that one of the two SyncWithPlayer calls is redundant.
This change keeps his bugfix (Ship "jumps" to the player while entering) and resolves the flickering.
@fmatthew5876 please test.
> Fix a regression introduced in b7f307e which resulted in a glitchy airship sprite

- src/scene_battle.cpp
- src/scene_battle.h
- src/scene_battle_rpg2k.cpp
- src/scene_battle_rpg2k3.cpp
- src/scene_debug.cpp
- src/scene_map.cpp
- src/scene_map.h
Depends on #1430
This change treats the debug menu similar to the main menu. The screen transitions are made to be fast.
Currently in master normal transitions are used to and from debug menu which is jarring and slow. It makes it painful to use and it's not how `RPG_RT.exe` does it.
> Scene_Debug: Support debug menu in battles & use instant transition 

- src/game_temp.cpp
- src/player.cpp
- src/scene_load.cpp
When a game is loaded from the title screen, all of the Game_Temp statics are set to their default values.
This patch resets them any time a saved game is loaded. This provides consistently and rules out classes of bugs that could occur when loading games from different contexts.
> Reset Game_Temp globals when loading saved game.

- src/game_map.cpp
- src/game_map.h
Resolves: #1203 
I tested this by creating a new project in Steam RM2k.
A map event with this code:
```
Text: before save
OpenSaveMenu
Text: After Save
```
Another map event which walks around randomly.
And a parallel common event with this code:
```
Text: Start
Loop
Wait 4.0 seconds
EndLoop
```
This also correctly writes the database_save_count to the LSD file. Before it looks like it was never written to save games.
> Obey Map and Database save_count when loading games

- src/scene_debug.cpp
- src/scene_debug.h
- src/window_varlist.cpp
- src/window_varlist.h
This adds new features to the debug menu. This makes it less compatible with the original debug menu in rm2/3, but I don't think that's important compared to the benefit here.
* Uses a 2 level menu system instead of left - right scrolling through everything. Makes it faster to go through variables and switches.
* Add support for changing party gold
* Add support for changing party items
* Add support for starting battles
* Use instant transition, just like with call menu for faster response
> Additional features for DebugMenu

- src/sprite_character.cpp
Resolves: #1465
Test against `RPG_RT.exe` behavior of Lower, Same, and Upper layer sprites on terrain with bush depths using a test game.
I also tested these behaviors and the Player is already correct:
* When the event graphic is a chipset tile instead of a charset bush depth is not applied.
* When the player steps on the above event, the player still has bush depth applied.
> Only apply bush_depth when sprite layer is SameAsCharacters

- src/fps_overlay.cpp
- src/game_battle.cpp
- src/game_battlealgorithm.cpp
- src/game_battler.cpp
- src/game_character.cpp
- src/game_character.h
- src/game_interpreter.cpp
- src/game_interpreter_battle.cpp
- src/game_map.cpp
- src/game_map.h
- src/game_party.cpp
- src/game_party.h
- src/game_player.cpp
- src/game_temp.cpp
- src/game_vehicle.cpp
- src/game_vehicle.h
- src/message_overlay.cpp
- src/output.cpp
- src/scene_battle.cpp
- src/scene_battle_rpg2k3.cpp
- src/scene_debug.cpp
- src/scene_map.cpp
- src/utils.h
- src/window_battlestatus.cpp
- src/window_numberinput.cpp
- src/window_numberinput.h
- src/window_shopbuy.cpp
- src/window_targetstatus.cpp
These are RPT_RT compatibility fixes.
Fixes some of the issues in #1418
> Various engine logic fixes

- src/game_actor.cpp
- src/game_battlealgorithm.cpp
- src/game_battlealgorithm.h
- src/game_battler.cpp
- src/game_battler.h
- src/game_interpreter_battle.cpp
- src/scene_battle.cpp
- src/scene_battle_rpg2k.cpp
- src/scene_battle_rpg2k3.cpp
- src/scene_map.cpp
- src/window_item.cpp
Here is the first batch of rebased fixes from #1373
All of these are pretty simple changes so I'm making a first PR with these. They are not all in the same order as originally presented. I'm trying to pull out the ones that are simple and don't require a lot of merging so they can be quickly reviewed and merged into master.
Changes made:
* 2.7 - Using `Player::escape_char` instead of `"\\"`
* ~~4.1 - `Battle_BGM` was moved earlier so don't play it twice.~~
* 2.15 - Added back `const`
* 2.4 - Enhanced `Game_Actor::GetSkillName()` with skill selection logic.
These alone fix some issues from #1418 and #985
> Albeleons's Battle fixes 1 of N

- src/game_party.cpp
- src/game_party.h
- src/game_player.cpp
* Ticks when player moves with keyboard
* Ticks when plyaer moves with keyboard in a vehicle
* Does not tick for events forcing player movement
* Does not tick for moving once space to embark/disembark
* Tested and matches RPG_RT behavior
This counter ticks in RPG_RT and is stored in the save data, but outside of that it appears completely unused.
@CherryDT Is there anything we should be doing in the interpreter that depends on this?
> Increment SaveInventory::steps and fix state damage algo

- src/game_battlealgorithm.cpp
- src/scene_battle_rpg2k.cpp
- src/window_item.cpp
>    2.30: RM2000 + RM2003: Mark as "unusable" the objects of type "speci
>
>If I understand this correctly the purpose of the new line in ÌsitemUsable is to ensure that the items are always selectable semi-ot: occasion_field1 is btw confusing, maybe we should think about a better name
>
>I see multiple flaws here:
>item.actor_set could be also item.class_set, therefore we should fine a way to get this handled by IsItemUsable imo. (maybe move the check from IsItemUsable to CheckEnable, then the codepath is free)
>
> Also actor_set could be smaller than the ID, resulting in an out-of-bounds read.
> Fix Item usability in battle - Previously Albeleon 2.30

- src/game_actor.cpp
- src/game_battle.cpp
- src/game_battlealgorithm.cpp
- src/game_battlealgorithm.h
- src/game_battler.cpp
- src/scene_battle.cpp
- src/scene_battle.h
- src/scene_battle_rpg2k.cpp
- src/scene_battle_rpg2k3.cpp
More of the smaller commits from #1373.
Depends on #1447
Changes:
* 2.26 Renamed `weapon` local variable to `item`.
* 3.14 Minor refactor for code clarity
Dropped:
* 1.4 - Since Ghabry wanted to have a discussion about it. Let's move it to a later PR and not hold up this one.
* 4.15 - Algorithm is not correct as per: #1454 - New fix for this in #1455
---
Fixes #1102.
> Albeleon's Battle Fixes 2 of N

- src/game_actor.cpp
- src/game_actor.h
- src/game_battler.cpp
- src/game_enemy.cpp
- src/game_enemy.h
- src/game_interpreter.cpp
- src/game_interpreter_map.cpp
The way RPG_RT works:
- You cannot change a battler's HP when they're dead.
- If ChangeHP kills a character, it adds the Death state to that battler.
- When Death state is cured, even if alone, it always sets the HP to 1, instead of other functions.
- When a character is caused Death, all the other states are erased; the defense, charge, gauge and stat modifiers are reset, and the current attribute shifts erased.
We implement all of this, with these particular changes:
- Now there is no difference between Game_Actor::ChangeHP and Game_Enemy::ChangeHP, so we delete this function from both and add the ChangeHP characteristics to the superclass Game_Battler.
- In Game_Battler::UseItem, the function now doesn't have to set the HP. However, it needs to have an int "revived" that checks if the …
> ChangeHP, AddState and RemoveState changes - single commit

- src/game_battler.cpp
When a state is added, all states with priority <= max_priority - 10
should be cleared.
> Fix for AddState()

- src/game_interpreter.cpp
- src/scene.h
- src/scene_battle.cpp
- src/scene_battle.h
- src/scene_battle_rpg2k.cpp
~~…sage display window is needed to display, the status window should be able to refresh inmediately without skipping a frame (for example, if "Event page: (Turn 0x + 0); DecreaseHP(Player1, 999, Dead)"."~~
~~Solution: Game_Battle only knows when the event ends when using UpdateEvents in the next frame, which mean we can't depend on that, if we refresh the status window then, for a frame we would see the previous state. That's why, to solve that frame of space while UpdateEvents is not updated:~~
~~1. We add to Game_Interpreter a "finished_not_updated" bool, initialized to false.
2. In CommandEnd, we set the variable to "true". In Game_Battle::UpdateEvents, we set it to "false". This means this variable will be active while the interpreted is finished but the events aren't active.
3. …
> Refresh status window when battle events affect actors - Previously Albeleon 1.4

- src/game_map.cpp
- src/game_map.h
- src/game_player.cpp
Depends on:  #1441
Info from here: https://github.com/EasyRPG/liblcf/issues/261
* Correctly load encounter_rate from saved game
* Compute first strike chance on random encounter.
> Random Encounters fixes

- src/game_actor.cpp
- src/game_actor.h
- src/game_battlealgorithm.cpp
- src/game_map.cpp
- src/utils.cpp
- src/utils.h
> Critical Hit fixes - Previously Albeleon 3.17

- src/battle_animation.cpp
- src/battle_animation.h
- src/game_battle.cpp
- src/game_battle.h
- src/game_battlealgorithm.cpp
- src/game_battlealgorithm.h
- src/game_battler.cpp
- src/scene_battle.cpp
- src/scene_battle.h
- src/scene_battle_rpg2k.cpp
- src/scene_battle_rpg2k.h
- src/scene_battle_rpg2k3.cpp
- src/window_base.cpp
- src/window_base.h
A few larger commits
~~Depends on #1448~~
> Albeleon's Battle Fixes 3+4 of N

- src/game_event.cpp
I've added this PR as an easy way to allow `Player` to compile when https://github.com/EasyRPG/liblcf/pull/282 is merged.
This Fixup() call doesn't do anything useful, so this PR can be merged anytime.
> Remove SaveMapEvent::Fixup call

- src/game_map.cpp
* saves and loads scrolling panorama x and y position.
* Only supported by rm2k3e, but we enable for all modes.
I've tested and the numbers match rm2k3e. You can save and load a game between RPG_RT and Player and the panorama will have the same starting position.
One thing I don't understand is that the range of pan_x/pan_y are 2 times the size of the panorama picture. In order to make the numbers match rm2k3e I had to scale them by 2 in places.
This feature has a bug in rm2k3. If you edit the map, say to change the panorama or turn off scrolling and the load the game the offsets still get loaded. So you could have a non-scrolling panorama which is stuck at a weird offset. I reset the panorama data when `save_count` does not match.
> Support SavePanorama data

- src/game_battler.cpp
Logic was incorrect. Can be tested with a state that lasts
1 turn, 0 turns, N turns, etc...
I've pulled this out of #1508 as this is an obvious bug fix that can be merged to solve #1504 and #1506. The other states PR needs more work.
Fix #1504
> Fix state recovery turns logic

- src/game_actor.cpp
- src/game_actor.h
- src/game_battler.cpp
- src/game_battler.h
- src/game_party.cpp
- src/game_party.h
- src/game_party_base.cpp
- src/game_party_base.h
- src/scene_battle.h
- src/scene_battle_rpg2k.cpp
- src/scene_battle_rpg2k.h
Fixes all of the following scenarios from #1449. In master you see the battle menu flicker on the screen when these things happen.
1. Party starts the battle unable to move (recoverable) -> skip menu and start battle sequence
2. Party starts the battle unable to move (not recoverable) -> skip menu and start defeat sequence
3. Turn 0 event kills the party or immobilizes (not recoverable) the party -> skip menu and start defeat sequence
4. Turn 0 event immobilizes (recoverable) party -> skip menu and start battle sequence
5. Turn 0 event which creates a message window -> display message
6. Turn 0 event which waits -> battle window is empty while waiting
Also includes some minor cleanups
> Battle fixes - replaces some Albeleon battle 3 commits + new fixes

- src/audio.cpp
- src/audio.h
- src/audio_decoder.h
- src/audio_generic.cpp
- src/audio_sdl_mixer.cpp
- src/decoder_mpg123.cpp
- src/decoder_mpg123.h
- src/decoder_oggvorbis.cpp
- src/decoder_oggvorbis.h
- src/decoder_opus.cpp
- src/decoder_opus.h
Implemented for mpg123, libvorbisfile and libopusfile.
Works for EmptyAudio and SDLAudio by approximating it through the frame count.
When no BGM is playing the returned value is 0.
Fix #1517
> Implement Get MIDI Ticks for non-MIDI formats by returning position in sec

- src/game_battlealgorithm.cpp
- src/game_battlealgorithm.h
- src/game_battler.cpp
- src/game_battler.h
- src/scene_battle_rpg2k.cpp
From Cherry:
> RPG_RT defines something like a "battle agility" for each turn which is AGI+X. X is a random number below (AGI/4 + 3). However, if the attack is a basic attack with a weapon that has the "Start with Initiative" checkbox, this puts it into a class of its own which follows the same rules but can rival only other attacks with such weapons (I think this is done by simply adding a huge number like 100000 to the value in such a case). The turn order is then decided by this "battle agility", high to low.
> Correct battle turn order in rpg2k battle - previously Albeleon 2.42

- src/scene_file.cpp
- src/scene_file.h
- src/window_savefile.cpp
- src/window_skillstatus.cpp
> More ui fixes

- src/game_actor.cpp
- src/game_actor.h
- src/game_battlealgorithm.cpp
- src/game_battler.cpp
- src/game_battler.h
From Cherry:
>if target is not able to move, success probability = 100, otherwise: success probability = (skill success probability * (min(100, all the attacker's state accuracy rates)/100) and then only if weapon doesn't have "ignore enemy dodge rate" option is enabled: final success probability = 100 - (100 - success probability) * (1 + 0.5 * (target agility / attacker agility - 1)) and then only if target has an equipment with "increase dodge rate against physical attacks": final success probability -= 25 "this condition": only if the failure_message is 3 >and the target is an (or all) enemy not sure why the enemy thing though. that means that if an enemy casts >a spell, the agilities never matter...? I think the failure_message 3 classifies it as a physical attack in a way so you can …
> Fix to_hit calculation - Previously Albeleon 2.34 + Weapon sp cost fix

- src/game_map.cpp
Fix #1521 
* Units of 1/16th pixel
* Starts at (0,0) for new game
* Changes when the screen scrolls due to player movement
or panning commands.
* Doesn't change when you teleport.
* X is always modulo 20 * 256
* Y is always modulo 10 * 256 (Why not 15??)
* And thats it...?
Teleporting to different maps doesn't change the pan_x/pan_y. It just starts at (0,0) and increments/decrements forever as you walk around. 
I have no clue what this is supposed to be for but thats the behavior I've observed with RPG_RT.
> Implement SaveScreen::pan_x and SaveScreen::pan_y

- src/game_actor.cpp
From #1394
* Ensures all calls to SetLevel() and ChangeLevel() will clamp
hp/sp in all cases where max hp/sp goes down.
* Includes level down and level up but hp/sp is less
* Inspiried by Albeleon's commit, but we also fix it for SetLevel()
> Always clamp HP and SP on level change

- src/filefinder.cpp
e.g. //a/./ was transformed to //a/, not /a/
Fixes this fancy game I found on twitter 20 min ago: 
[viptmp1440.zip](https://github.com/EasyRPG/Player/files/2659794/viptmp1440.zip)
> Bugfix: MakeCanonical didn't skip empty path components

- src/game_character.cpp
- src/game_interpreter_map.cpp
- src/game_map.cpp
- src/game_map.h
- src/game_player.cpp
- src/game_player.h
**Don't merge until #1502 is merged**
Fixes saving and loading games in the following conditions. Saves were tested to be compatible between `RPG_RT` and `Player` for these behaviors.
* When the screen is panned.
* While the screen is panning.
* Loading correctly continues the panning. This is broken in `RPG_RT`.
* While screen is locked
I also tested these scenarios
* Screen behavior when event unlocks when screen is in default centered position.
* Screen behavior when event unlocks when screen is panned.
* Teleporting to same map does not change any panning state
* If pan lock is enabled, the screen will still change position when you teleport to the same map.
* Teleporting to different map resets pan position and speed, but not pan lock.
* Panning move screen event commands still work …
> Fix Saving and Loading of panning chunks

- src/game_picture.cpp
- src/game_screen.cpp
- src/game_screen.h
- src/scene_map.cpp
- src/utils.h
Fixes: #1547 
From Cherry:
```
and the Shake X comes from something like this:
ConvertedPower = 1 + 2*Power
Val = ConvertedPower * Sin((FrameCount * 4*(Speed + 2)) % 256) * pi / 128)
Cutoff = Speed * ConvertedPower/8
newX = min(prevX + Cutoff, max(prevX - cutoff, Val))
I'm not sure this is right because I don't understand why it's so complicated and includes the old value
and when frame count is zero (I guess it's also set to zero when shake is turned off?) it just resets shake X and Y to 0
```
I've tested the following cases so far and they are frame accurate with RPG_RT:
| Strength | Speed | Wait |
| --- | --- | --- |
| 1 | 1 | 2.0s |
| 1 | 9 | 2.0s |
| 9 | 1 | 2.0s |
| 9 | 9 | 2.0s |
Some data here:
[RPG_RT-shake_9_1_20.pdf](https://github.com/EasyRPG/Player/files/2660859/RPG_RT-shake_9 …
> Fix screen shake algo

- src/game_map.cpp
- src/game_map.h
Fixes: #1534 
Fixes: #1550
I don't emulate the save game behavior of `RPG_RT`.
> Panorama fixes

- src/game_actor.cpp
- src/game_actor.h
- src/game_battlealgorithm.cpp
- src/game_battlealgorithm.h
- src/game_battler.cpp
- src/game_battler.h
- src/game_party.cpp
- src/game_party.h
- src/scene_actortarget.cpp
Contains a commit from #1394. Also Sormat battle commit 3.16, which somehow got lost in the rebasing.
Sormat's observation that items that trigger skills always set the source battler as the highest level member of the party. If there are multiple members of the party with the highest level, the first is selected. From testing I found his observations to be correct, with the additional caveat that the source also has to be able to act (not dead or has a nomove state).
In `RPG_RT`, this logic is applied a bit too heavy handedly and has a bug. Skills with usage of "Self" also get their source set to the highest level member of the party. Since the target is self, that means the target also gets forced to the highest level member! When you use such an item the first actor is highlighted, you …
> Fixes for skills and attributes

- src/game_battlealgorithm.cpp
- src/game_battlealgorithm.h
- src/game_battler.cpp
- src/game_battler.h
- src/scene_battle.cpp
- src/scene_battle.h
- src/scene_battle_rpg2k.cpp
- src/scene_battle_rpg2k3.cpp
- src/scene_battle_rpg2k3.h
A simpler reimplementation of Albeleon 2.21.
To test these, create a 1x 1+ turn battle event which does:
```
Cure provoke, berserk, death, shock
Show Choice:
Death: Add dead
Provoke: Add provoke
Confuse: Add confuse
Shock: Add shock
Else:
```
To test the effects of multiple states, do the show choice twice.
To test state recovery, you can use the above event. You can also inflict states, and the have a very fast actor use a recovery item.
> Battle action and states fixes - Previous Albeleon 2.21 / 2.41 from battle 7

- src/game_actor.cpp
- src/game_actor.h
- src/game_battlealgorithm.cpp
- src/game_battler.cpp
- src/game_battler.h
- src/game_enemy.cpp
- src/game_enemy.h
Battle 7 commits related to battle algorithm calculations
> Battle Algorithm related fixes from battle 7

- src/game_battlealgorithm.cpp
- src/game_battler.cpp
- src/game_battler.h
I tested and confirmed in rm2k3 this takes precedence over the NoMove restriction -> 100% to_hit rule.
> Support 100% dodge States

- src/game_screen.cpp
If you load a save game which has fewer pictures than exist
currently, Game_Screen::Reset() will try to Erase() pictures
which don't exist and this causes a segfault.
No idea when this was introduced or how long it has existed.
> Crash Bugfix: Pictures not cleaned up

- src/game_battlealgorithm.cpp
- src/game_enemy.cpp
- src/game_enemy.h
- src/scene_battle_rpg2k.cpp
- src/sprite_battler.cpp
- src/sprite_battler.h
Changed:
* 3.13 - Remove printing states logic. This is already done in earlier PR.
* 2.21 - #1538 
* 2.41 - #1538
Dropped:
* 3.18 - already implemented in #1487
> Albeleon's Battle Fixes 7 of 7

- src/game_battlealgorithm.cpp
- src/game_battlealgorithm.h
- src/game_battler.cpp
- src/game_battler.h
- src/scene_battle.cpp
- src/scene_battle_rpg2k.cpp
- src/scene_battle_rpg2k3.cpp
I've tested 2.36. It looks good with no changes:
* State inflicted when you already have the state - success, already has msg
* State inflicted when you aready have the state, even when your state rate is E (0%) - success, already has msg
* State infliced when you don't have the state - sucess, state inflicted
* State inflict attempt missed - failure
* Heal state when you have state - success, was healed
* Heal state failure when you have state - failure
* Heal state you don't have - failure
> More battle states fixes + Defend

- src/game_map.cpp
- src/game_map.h
- src/spriteset_map.cpp
- src/tilemap.cpp
- src/tilemap.h
- src/tilemap_layer.cpp
- src/tilemap_layer.h
Tested:
* Loading tile substitutions from save game
* Change chipset event command after doing tile substitution
* Loading changed chipset
---
Fixes #1266.
> Handle saving and loading of tile substitutions

- src/rtp_table.h
Maybe you remember how I fixed the 3DS crash by replacing std::string with const char* in the std::map of the rtp-table. The result of this change was that the function size was significantly reduced (which was probably the crash reason, function section too large???).
Turns out std::map doesn't implement a proper operator < for char* which means our table didn't work anymore :-1: .
> Regression Fix: RTP table mapping japanese <-> other

- src/transition.h
This is used uininitialized on transition.cpp:74 the first
time it is called.
> Fix uninitialized Transition::screen_erase

- src/game_interpreter.cpp
List is from here:
https://rpgmaker.net/forums/topics/12790/?post=446908#post446908
Tested these and they occur at the end. Basically if you do one of these
and result is a dead party, then game over.
Edge Cases Tested:
* All party is dead, Remove all party -> Empty party, no game over
* All party is dead, Add live member -> No game over
* Party size >= 1 and all dead after any party change command -> Game Over
> Do game over checks for event commands

- src/cache.cpp
- src/game_interpreter.cpp
- src/game_interpreter.h
- src/game_player.cpp
- src/game_temp.cpp
- src/game_temp.h
- src/player.cpp
- src/scene_load.cpp
- src/scene_map.cpp
- src/scene_title.cpp
- src/scene_title.h
The title cache change removes one Game_Temp variable and should unbreak "Return To Title" event command.
> Fix 1574, 1576 and improve title reload

- src/game_interpreter.cpp
- src/game_map.cpp
- src/game_map.h
- src/game_screen.cpp
- src/game_screen.h
- src/player.cpp
Fixes: #1571
I tested and this also correctly loads the mountain background from Razas save game from #1498
> Save game and move route fixes

- src/game_character.cpp
- src/game_interpreter_map.cpp
- src/game_map.cpp
- src/game_map.h
- src/game_player.cpp
- src/game_player.h
- src/game_vehicle.cpp
- src/player.cpp
- src/spriteset_map.cpp
I found more issues with panorama.
So I've had to refactor this yet again!
I've retested this by trying different combinations of maps, saving the game in various spots, and comparing the pan_x and pan_y of Player vs RPG_RT.
Testing performed:
* Map with no looping, no scroll - Panorama is 2x size and moves with relative position on map 
* Map with looping, no scroll - Panorama is screen size and doesn't move
* Map with looping, scroll - Panorama is screen size and moves with player
* Map with no loop, scroll - Panorama is screen size and moves with player
* Map with loop, scroll, auto scroll - moves with player and moves by itself
I'm going to need to ask you guys to help test this one. Try some different size maps and panorama pictures. I don't want to keep finding bugs and refactoring …
> More panorama fixes

- src/game_character.cpp
- src/game_character.h
- src/game_player.cpp
- src/game_player.h
- src/game_vehicle.cpp
- src/game_vehicle.h
- src/sprite_airshipshadow.cpp
- src/sprite_airshipshadow.h
- src/sprite_character.cpp
- src/sprite_character.h
- src/spriteset_map.cpp
- src/spriteset_map.h
Alternative to https://github.com/EasyRPG/Player/pull/1401/commits/d11a906a196ecda412a7adf8fc731eba9746fe56  as you can see my solution is a bit simpler ;).
This depends on #1498 because the Screen scroll changes/fixes made it much easier to implement this.
Test case: https://easyrpg.org/play/pr1541/?start-map-id=44
> Support proper rendering of Sprites at map borders of looping maps

- src/game_map.cpp
Create a map as a child of another map. Set its save,
escape, and teleport flags to 0 (parent). Now move
this map to the root. The flags will remain 0 but the
actions will be enabled by RPG_RT as there is no parent map.
> Fix edge case with map save/escape/teleport flags

- builds/cmake/Modules/FindSDL2.cmake
- src/player.cpp
- src/scene_save.cpp
Have no idea if the Metal.framework dep breaks running on OSX < 10.11 but this is a SDL problem then and I have no way to test this. (ObjC does lazy binding... should work in theory)
> Fix emscripten & OSX build

- src/game_map.cpp
- src/game_player.cpp
- src/game_player.h
Fixes #1619 
Note: I use the aboard flag here because that's what tells us the player is actually inside the vehicle. You could have an event that teleports you while boarding and then the bgm effect would not happen.
I tested this parallel event:
```
GetOnOffVehicle
Wait 0.0s (x3)
Teleport other map
```
The player teleports to the other map, the other map music plays, and then the player boards the ship on that map and the vehicle bgm never plays.
I'll fix that behavior in #1601
> Vehicle bgm fix

- src/scene_shop.cpp
- src/window_actorinfo.cpp
- src/window_actorstatus.cpp
- src/window_equipstatus.cpp
- src/window_help.cpp
- src/window_paramstatus.cpp
- src/window_savefile.cpp
- src/window_shop.cpp
- src/window_shop.h
- src/window_shopparty.cpp
> Shop + Other UI Fixes

- CMakeLists.txt
- Makefile.am
- src/background.cpp
- src/game_battle.cpp
- src/game_battle.h
- src/game_map.cpp
- src/player.cpp
- src/player.h
- src/scene_battle.cpp
- src/scene_battle_rpg2k.cpp
- src/scene_battle_rpg2k3.cpp
- src/scene_battle_rpg2k3.h
- src/scene_logo.cpp
- src/scene_title.cpp
- src/spriteset_battle.cpp
- src/window_actorsp.cpp
- src/window_actorsp.h
- src/window_battlestatus.cpp
This needs more testing to determine the correct logic but it seems that the condition for choosing between background and terrain is the terrain ID, not a non-empty background.
CogDis animates the background in a fancy way: the front image is only black + transparent and the background is a moving (downwards) mask image which defines the color. And via that trick they get 3 frames of animated stars on the background.
the lack of ``background->Update()`` completely broke any background scrolling in battles (upps) and the scrolling was too slow.
The rest fixes issues between Traditional vs Alternative style (still not fully matching but gets closer).
> Battle 2k3: Visual fixes for CogDis

- resources/easyrpg-player.6.adoc
- src/filefinder.cpp
- src/filefinder.h
- src/player.cpp
- src/player.h
By telling the user everytime a RTP asset is missing. Sound and Music is also a visual warning, because we got already many reports that our Player fails to play sound...
Additionally when the RTP is not installed and the game never uses the RTP (but has no fullpackageflag=1) the user won't receive this annoying warning on startup.
Is kinda-RFC, maybe you have a better idea.
Also pretty sure I fixed a bug because search_paths.clear(); was not called when the game loaded has FullPackageFlag=1
Fixes #1274.
> Make RTP warnings more noticeable

- CMakeLists.txt
- Makefile.am
- src/cache.cpp
- src/cache.h
- src/exe_reader.cpp
- src/exe_reader.h
- src/options.h
- src/player.cpp
- src/scene_logo.cpp
- src/utils.cpp
- src/utils.h
While this code probably isn't perfect, it's hopefully simple and hopefully works (It seems to so far).
If no ExFont file is present as a known image, one will be written to the save directory.
NOTE: This occurs even if one is already in the save directory that is not recognized as a game directory image.
This quirk is so Emscripten-based game updates work properly.
Also, adds support for loading ExFont.bmp from the save directory.
So far, only tested with "Mother: Cognitive Dissonance", but EXFONT format does not appear to vary.
> EXE ExFont extraction.

- src/game_battlealgorithm.cpp
Action switches would be skipped if the attack failed
> BattleAlgorithm: always apply action switches

- src/game_actor.cpp
- src/game_battle.cpp
- src/scene_battle_rpg2k3.cpp
- src/window_help.cpp
- src/window_help.h
~~Don't merge yet, the heal/inflict logic still has some bug. I know where it is but touching battle at this time of the day is a bad idea~~ Decided to not fix this for skills, battlealgortihm needs a refactor first
and in #821 it ticks one more option:
- Items (Other): The 2nd option (heal instead of inflict) for states
This isn't really a battle thing, this just means that the item causes a permanent state that can't be removed except by unequipping.
Also improved the equip sanity check, handles now more corner cases.
> Battle 2k3: Bugfixes

- src/window_equipstatus.cpp
Related #1443
What I propose, centered ">":
Alternatives (imo -> what jp uses is ugly and I bet → starts to become problematic when we ever add freetype font support)
> Show arrow in equipment scene

- src/game_event.cpp
Fixes behavior for #1659, but not frame perfect as there are interpreter timing issues to be worked out.
This however is correct for horizontal / vertical move type
> Fixes for horizontal and vertical movement.

- src/game_interpreter.cpp
- src/game_interpreter.h
- src/game_interpreter_map.cpp
- src/scene_map.cpp
> Refactor scene calling

- src/filefinder.cpp
> Fix: Search Windows Registry for installed RTP

- src/game_character.cpp
- src/game_character.h
- src/game_event.cpp
- src/game_event.h
- src/game_map.cpp
- src/game_player.cpp
- src/game_player.h
- src/game_vehicle.cpp
- src/game_vehicle.h
- src/sprite_airshipshadow.cpp
- src/sprite_character.cpp
This PR is refactor `SaveMapEventBase` move route related chunks to behave more like `RPG_RT` and improve support loading save games correctly on any frame of movement.
This still needs a lot more testing and probably more changes to be correct. 
Detailed test cases and research can be found in #1567
Fix #1267 
Fix #1293
Fix #1346
Fix #1429
Fix #1585
Fix #1587
Fix #1593
Fix #1604
Fix #1654
Fix #1671
Breaks #579
Breaks #937
Behaviors of `stop_count`
Behaviors of `max_stop_count`
Behaviors of `move_frequency`
Behaviors of `move_commands`
Behaviors of `move_route_index`
Behaviors of `move_route_overwrite`
Behaviors of `jumping`
Behaviors of `remaining_step`
Behaviors of `anim_count`
Behaviors of `anim_frame`:
Animation of Vehicles:
Behaviors of spinning events:
Player Controls:
Vehicle Move …
> Move Route refactors

- src/game_player.cpp
Start player above boat
Setup parallel event with `GetOnOffVehicle`
The repeated calls will cause the player to board and unboard
while moving, resulting in a null pointer dereference when accessing
the current vehicle.
The fix is to disallow the action if we're currently boarding
> Fix vehicle related crash

- src/sdl_ui.cpp
The SdlUi::RequestVideoMode function is supposed to have a fallback to windowed mode when neither 320x240 nor 640x480 are available. Due to an oversight the loop always sets the SDL_FULLSCREEN flag at the beginning, so the windowed mode list is never checked, and it gets stuck in and endless loop. I moved the SDL_FULLSCREEN flag setting out of the loop to fix this. I noticed it on AROS, where the VESA driver only has one fixed resolution available after booting.
> Fix the windowed mode fallback for SDL1.2

- src/game_battler.cpp
* Fix for all versions of 2k3
* Allow in 2k (if the chunk is present) as an EasyRPG extension
Fix: #1684 
Vote: Do we feel unsafe enabling this chunk for 2k games in EasyRPG?
> Allow percent_sp feature for all 2k3 versions

- src/game_character.cpp
- src/game_event.cpp
- src/game_player.cpp
- src/game_player.h
Create a parallel event: `SetMoveRoute: Player, Turn Left`
RPG_RT, you can still walk around. Before this fix the player
was stuck.
Fix: #579
Fix: #937
> Allow player input on same frame move route ends

- src/game_character.cpp
> Correctly render events at negative coordinates in non-looping maps

- src/game_character.cpp
- src/game_character.h
- src/game_commonevent.cpp
- src/game_commonevent.h
- src/game_event.cpp
- src/game_event.h
- src/game_interpreter.cpp
- src/game_interpreter.h
- src/game_map.cpp
- src/game_map.h
- src/game_player.cpp
- src/game_player.h
- src/game_vehicle.cpp
- src/game_vehicle.h
- src/player.cpp
- src/scene.cpp
- src/scene.h
- src/scene_map.cpp
- src/scene_map.h
The PR refactors a number of interpreter and event related items
* Adds support for `triggered_by_decision_key` chunk
* Adds support for `pause` chunk
* Adds support for `waiting_execution` chunk
* Adds support for `processed` chunk
* Fixes the execution order of event update routines to match RPG_RT.
* Correctly handles "PreUpdate" which is the partial update routine done at startup which only updates events but not player or vehicles. This also happens when you teleport or use escape/teleport from the menu. *I haven't addressed the teleport PreUpdate() cases yet and may not do so in this PR*.
Fix: #1623 
Fix: #1247
Fix: #1595 
Fix: #663
Fix: #1664
Breaks: #937
> Refactor Event Update Ordering

- CMakeLists.txt
- src/decoder_wildmidi.cpp
- src/filefinder.cpp
- src/main_data.cpp
cherry-picking stuff out of the libretro branch
> CMake: Add libsamplerate + maintanance

- src/game_character.cpp
- src/game_character.h
- src/game_event.cpp
- src/game_event.h
- src/game_player.cpp
- src/game_player.h
- src/game_vehicle.cpp
- src/game_vehicle.h
~~Depends on #1694~~
Finally we bring back the `touch`, `collision`, and `autostart` trigger fix changes.
Tests #1626 
Fix: #886
Fix: #1626
Fix: #1696 
Fix: #1732
> Refactor event triggering

- src/scene_title.cpp
This PR replaces the default Color of the title screen to black if there is no background image available.
If the player is started with --hide-title the behavior remains unchanged.
Fixes: #1728
> Replace Default Color with Black if there is no title images

- src/window_message.cpp
In RPG_RT text color is not reset between multiple choices, this pr will apply this behavior to the player.
New Message boxes resets the color to default in rpg_rt and player.
Fix: #1361
> Fix Message Color is reset on multiple choices.

- src/game_character.cpp
- src/game_character.h
- src/game_event.cpp
- src/game_interpreter.cpp
- src/game_interpreter.h
- src/game_interpreter_map.cpp
- src/game_map.cpp
- src/game_map.h
- src/game_player.cpp
- src/game_player.h
- src/game_temp.cpp
- src/game_temp.h
- src/game_vehicle.cpp
- src/game_vehicle.h
- src/scene.h
- src/scene_battle.cpp
- src/scene_debug.cpp
- src/scene_map.cpp
- src/scene_map.h
~~Depends on #1697~~ 
Fix: #1691 
Fix: #1457 
Fixes the gameover part of #1642. The message vs gameover stuff is not fixed yet, but that looks like a message bug to be fixed in another PR.
I also haven't studied too deeply the immediate "to title" behavior.
2 more game temp variables killed!
> Refactor player update handling + scene calling

- src/game_temp.cpp
- src/game_temp.h
- src/scene.cpp
- src/scene.h
- src/scene_battle.cpp
- src/scene_battle.h
- src/scene_debug.cpp
- src/scene_gamebrowser.cpp
- src/scene_gamebrowser.h
- src/scene_gameover.cpp
- src/scene_gameover.h
- src/scene_item.cpp
- src/scene_item.h
- src/scene_map.cpp
- src/scene_map.h
- src/scene_menu.cpp
- src/scene_menu.h
- src/scene_skill.cpp
- src/scene_skill.h
- src/scene_teleport.cpp
- src/scene_teleport.h
- src/scene_title.cpp
- src/scene_title.h
~~Depends on #1714~~
Fixes some transition issues and provides a refactor that eliminates more `Game_Temp` variables.
> Scene + Transition fixes

- src/game_interpreter_map.cpp
> EnterHeroName on bad actor? Report error instead of crash

- src/audio_secache.cpp
- src/bitmap.cpp
- src/bitmap.h
- src/cache.cpp
- src/cache.h
- src/color.cpp
- src/color.h
- src/rect.cpp
- src/rect.h
- src/sprite.cpp
- src/sprite.h
- src/tone.h
not ready yet, have strange flickering.
Improved the caching strategy, before our Cache was unlimited and never cleared any recently (<5s) used assets. Now the clear is forced when the memory usage is 10 MB (+3 MB SE).
Which means the memory foodprint is in simple games (havn't used the MSVC memory profiler yet) ~20 MB plus Database. 
Besides reduced memory usage the effect cache should also help in some situations to make the effect faster because tone & flash are only calculated once now per same charset.
Related #1177
> Cache improvements and effect caching

- src/color.h
- src/fps_overlay.h
- src/message_overlay.h
- src/rect.h
- src/sprite.h
- src/tone.h
I failed to implement operator "<" correctly... this breaks the cache lookup and picks incorrect assets in some cases resulting in wrong colors. It uses now std::tie from tuple which is constexpr and offloads the proper operator implementation to the std.
Noticed this in Vampires Dawn, while testing the memory usage :/.
Didn't happen in Yume2kki, hmpf.
Removed system.h include from these files, requires including memory_management now in some.
> Amendment for "Cache improvements and effect caching"

- src/battle_animation.cpp
- src/battle_animation.h
- src/color.h
- src/game_character.cpp
- src/game_character.h
- src/game_event.cpp
- src/game_interpreter_map.cpp
- src/game_picture.cpp
- src/game_player.cpp
- src/game_screen.cpp
- src/game_screen.h
- src/game_vehicle.cpp
- src/screen.cpp
- src/sprite_character.cpp
Use event flash LSD chunks to save and load flash state.
Animate flash from characters update routine.
Fix #1768 
All test cases pass, except `wait_time` chunk which is handled in #1740
> Refactor character flash

- src/battle_animation.cpp
All this flash sprite stuff is due for a larger refactor, we need to remove that quad and flash the sprites individually. 
That will be a 6.2 thing. I'm putting this one in to fix #985 for 6.1
~~Depends on #1772~~
Fix #985
> Battle animation sprites affect by screen flash

- src/game_actor.cpp
- src/scene_save.cpp
* RM2k ignores these flags, so always reset them when loading
saved games.
* Don't write these flags in rm2k mode.
Fix: #1789
> Fix LSD SaveActor flags in rm2k

- src/game_battlealgorithm.cpp
- src/game_battlealgorithm.h
- src/scene_battle_rpg2k.cpp
- src/scene_battle_rpg2k.h
- src/scene_battle_rpg2k3.cpp
- src/sprite_battler.cpp
- src/sprite_battler.h
This is yet another 2k battle system refactor.
In order to emulate all of the waits RPG_RT does in #1677 I've had to add more states and substates.
I've also taken this opportunity to do some cleanup. In particular I've removed `GetResultMessages()` from `Game_BattleAlgorithm` and nearly all of the 2k message processing logic into `SceneBattleRpg2k`.
I also fixed a self-destruct bug and #1725 using a hack that hopefully can be dismantled later.
Related: #1725 
Related: #1677
Related: #1748
Related: #1770
Related: #821
Related: #1490
(they are all closed with #1785)
Tested:
> Refactor Battle2k message timings + state fixes 1 /  2

- src/game_battlealgorithm.cpp
- src/game_event.cpp
- src/game_interpreter.cpp
- src/game_party.cpp
- src/game_party.h
- src/scene_battle.cpp
- src/scene_battle.h
- src/window_shopstatus.cpp
Also includes a cleanup of item skill logic in scene_battle
Fix: #1722
> Fix Weapons invoking skills when only 1 of weapon and it's equipped

- src/game_interpreter.h
- src/game_map.cpp
Map and Common events take turns executing
in the foreground.
Fixes the game bug in #1761 and most of the test cases 
Proper solution is in #1779
> Fix foreground exec order (temporary workaround)

- src/scene_map.cpp
We don't yet emulate transitions that happen on preupdate,
but we should disable the erased by screen flag so that normal
fade in and out still works.
Fix: #1802
> Fix erased by event logic on show screen during preupdate

- CMakeLists.txt
- Makefile.am
- src/game_actor.cpp
- src/game_actor.h
- src/game_battle.cpp
- src/game_battlealgorithm.cpp
- src/game_battlealgorithm.h
- src/game_battler.cpp
- src/game_battler.h
- src/game_enemy.h
- src/game_interpreter.cpp
- src/game_interpreter_battle.cpp
- src/game_interpreter_map.cpp
- src/scene_battle.cpp
- src/scene_battle_rpg2k.cpp
- src/scene_battle_rpg2k3.cpp
- src/scene_equip.cpp
- src/state.cpp
- src/state.h
- src/window_battlemessage.cpp
- src/window_item.cpp
~~Depends on #1726~~
Fix: #1725 
Fix: #1677
Fix: #1748
Fix: #1770
Fix: #821
Fix: #1490
> Refactor Battle2k message timings + state fixes 2 / 2

- src/game_party.cpp
- src/game_player.cpp
- src/game_screen.cpp
- src/game_screen.h
> Map Stepping +/- HP/SP states fixes

- src/game_map.cpp
Fixes a divide by 0 bug when events change the panorama.
Fixes the crash in #1821 
Amazingly, this hack also matches the test cases there! But this is likely not correct for some edge cases of changing panoramas.
This panorama init code needs a serious refactor..
> Fix crash in panorama commands

- src/game_map.cpp
Really fixes the crash in #1821
The last one was incomplete.
> Fix divide by 0 crash in Parallax::Update()

- src/game_actor.cpp
- src/game_actor.h
- src/game_interpreter.cpp
- src/game_interpreter_map.cpp
- src/game_player.cpp
- src/scene_debug.cpp
- src/scene_debug.h
- src/scene_map.cpp
- src/window_varlist.cpp
- src/window_varlist.h
Fix: #1813 
Also adds some usability improvements to remember indices.
This code is nasty and due for a refactor. I would advise just testing it instead of trying to review some of these diffs...
> Debug menu improvements + Teleport to maps

- src/game_battlealgorithm.cpp
- src/game_battlealgorithm.h
- src/game_battler.cpp
- src/scene_battle.cpp
- src/scene_battle.h
- src/scene_battle_rpg2k.cpp
- src/scene_battle_rpg2k.h
- src/scene_battle_rpg2k3.cpp
A few more battle 2k fixes.
FIXME comments left for relevant 2k3 pieces..
> Battle2k: Always allow escape when first strike + unusable skills fix

- src/game_map.cpp
- src/map_data.h
* Add some new chipset BLOCK constants
* Add function for chip id -> chip index mapping
* If out of bounds coordinates are requested on non-looping map,
RPG_RT will use the terrain of the first tile.
* Fix bug where tile substitution for last few tiles
was broken for terrain lookups. Fix: #1834
> Terrain / Tile fixes

- src/scene_battle.cpp
Can we push a new beta with this one?
It should tell us where #1838 is happening
Fix #1838
> Fix crashing bug in RemoveActionsForNonExistantBattlers()

- src/game_battle.cpp
- src/game_commonevent.cpp
- src/game_commonevent.h
- src/game_event.cpp
- src/game_event.h
- src/game_interpreter.cpp
- src/game_interpreter.h
- src/game_interpreter_battle.cpp
- src/game_interpreter_battle.h
- src/game_interpreter_map.cpp
- src/game_interpreter_map.h
- src/game_map.cpp
- src/game_map.h
This PR modifies the interpreter to use `SaveEventExecState` and `SaveEventExecFrame` chunks so that it executes more accurately and allows correct saving and loading of LSD chunks while events are running.
Changes include
* Refactoring call stack to use frame array instead of child interpreters
* Fixing wait commands
* Fixing key input proc
* Fixing wait for all movement
* Other cleanups
Control flow refactors using `subcommand_path` chunks will come in the next PR.
~~Depends: #1717~~
~~Depends: #1739~~
~~Depends: https://github.com/EasyRPG/liblcf/pull/324~~
Fix: #757
Fix: #1777
Test Cases from #1707 addressed by this PR
> Refactor Interpreter command execution

- src/game_character.cpp
Fix repeat flag for move routes ending in non movement
Always set the repeat flag when we finish a move route.
Fixes a bug where a move route ending in a non movement
command such as Direction Fix would fail to set the
flag and cause "Wait For All Movement" commands to
soft lock.
Fix #1853
> Fix repeat flag for move routes ending in non movement

- src/game_battle.cpp
- src/game_commonevent.cpp
- src/game_event.cpp
- src/game_interpreter.cpp
- src/game_interpreter.h
- src/game_interpreter_battle.cpp
- src/game_map.cpp
- src/game_map.h
If both a common event and a map event are autostart and can
run on the current frame, RPG_RT will push both of them onto
the stack and execute the interpreter. This is very similar to
as if the common event called the map event.
* Rename Setup() to Push()
* Explicitly call Clear() before pushing
* Change CommandEnd() to pop the
stack instead of just clearing commands.
* Change IsRunning() to just check for empty stack.
~~Depends on: #1740~~
Fix: #1761 all test cases
>  Correct autostart events execution order

- src/cache.cpp
There is an issue with RPG Maker 2003 games (and likely others) when played in Easy RPG wherein the cache_effects map will hold on to Tile resources for events that use Tiles for their visual elements. You can observe this with the minimal example below:
https://drive.google.com/file/d/1hBFYKPiB0LaKrjAgkmxVj8hy3Qsh_Zjf/view?usp=sharing
Run the game and hit F12 to restart it; the Debug console will show:
`  Debug: possible leak in cached tilemap Snow/0`
This bug is caused by the "Snow/0" tile being cached in the '''key''' of the cache_effects map. I changed that key to use a weak_ptr, a.k.a.:
` using effect_key_type = std::tuple<std::weak_ptr<Bitmap>, Rect, bool, bool, Tone, Color>; `
The change required some additional structuring to use std::owner_less() to compare these two. This should …
> Fix Tile Memory Leak w.r.t the cache_effects map

- src/cache.cpp
- src/cache.h
- src/font.cpp
- src/game_interpreter.cpp
- src/game_interpreter.h
- src/game_system.cpp
- src/game_system.h
- src/player.cpp
- src/scene_battle_rpg2k3.cpp
- src/scene_battle_rpg2k3.h
- src/scene_file.cpp
- src/scene_gamebrowser.cpp
- src/scene_title.cpp
- src/sprite_airshipshadow.cpp
- src/sprite_timer.cpp
- src/text.cpp
- src/window.cpp
- src/window_base.cpp
- src/window_base.h
- src/window_battlestatus.cpp
- src/window_battlestatus.h
- src/window_shopparty.cpp
* RPG_RT compatible LSD chunks
* If graphics_name.empty(), message_stretch and font_id are 0
and we fallback to database
* If !graphics_name.empty(), all 3 parameters are taken literally
* Refactor the Game_System Set() interface to uphold these invariants
* Refactor the Game_System Get() interface to fallback
* Encapsulate graphic change logic within the Cache to simplify users of
system graphics.
* Reset system graphic when returning the to the title screen.
Depends on: https://github.com/EasyRPG/liblcf/pull/333
Tests:
> Refactor game system

- src/scene_battle_rpg2k.cpp
Self destruct would set the enemy as hidden, and then later
RemoveActionsForNonExistantBattlers() would remove it before
it completed, causing the next battle algorithm to start running
midway.
If the next algo was a defend or something with no target, it will
crash. If it's an attack, it can cause the battle not to finish.
Fix #1875
> Battle2k: Fix bug in self destruct logic

- src/game_battle.cpp
- src/game_commonevent.cpp
- src/game_commonevent.h
- src/game_event.cpp
- src/game_event.h
- src/game_interpreter.cpp
- src/game_interpreter.h
- src/game_map.cpp
- src/game_map.h
- src/game_player.cpp
- src/game_player.h
- src/game_temp.cpp
- src/game_temp.h
- src/scene.cpp
- src/scene.h
- src/scene_battle.cpp
- src/scene_map.cpp
- src/scene_map.h
- src/teleport_target.h
~~Depends on #1782~~
~~Depends on #1779~~
Fix: #1783
Fix: #1787 
Fix: #1819 
Part of fixing #1261 
This PR implements fully asynchronous transitions which correctly suspend and resume the `Game_Map::Update()` loop. Supports suspending and resuming common events, map events, and foreground events.
Also support the various graphical and timing behaviors of transitions done during pre-update.
> Implement fully async transitions

- src/game_interpreter_map.cpp
- src/game_map.h
- src/game_player.h
- src/player.cpp
- src/scene_debug.cpp
- src/scene_map.cpp
- src/scene_map.h
- src/teleport_target.h
~~Depends on #1784~~
When RPG_RT executes a TransferPlayer command..
From a foreground event -> FG events run in preupdate
From a parallel event -> FG events do not run in preupdate
From a parallel event in a preupdate chain started by a
foreground event -> FG events run in preupdate
FG events do *not* run in preupdate for new game
or after a teleport / escape skill.
Fix: #1261
Fix: #1840
>  Run foreground events during preupdate after teleport 

- src/game_map.cpp
The logic for resuming from the AsyncContext was inverted,
causing the loop index to not reset.
> Fix hang in Game_Map::UpdateForegroundEvents

- src/game_commonevent.cpp
- src/game_commonevent.h
- src/game_event.cpp
- src/game_interpreter.cpp
- src/game_interpreter.h
- src/game_interpreter_battle.cpp
- src/game_interpreter_map.cpp
Fix: #1871 
This should also fix: #1764  once we solve #1883
Supercedes #1879 If we merge this we don't need that one.
* Rename CommandEnd() to OnFinishStackFrame()
This name and it's nearby comment was very misleading. The
interpreter has actually always ignored `CommandEnd` commands.
This function was only called when the index ran past end of the stack
frame.
* Do OnFinishStackFrame() before execution loop.
Call this in one place and handle multiple stack pops. Also,
don't hang on empty events.
* Optimize parallel events
Reset the index and never pop the base stack frame. RPG_RT
does this and we avoid copying parallel event data every frame.
RPG_RT will always create a stack frame for parallel events,
even if they are empty.
> Refactor Interpreter Stack Frame Completion 

- src/game_interpreter.cpp
- src/game_interpreter.h
- src/game_interpreter_battle.cpp
- src/game_interpreter_battle.h
- src/game_interpreter_map.cpp
- src/game_interpreter_map.h
- src/game_temp.cpp
- src/game_temp.h
~~Depends on #1740~~
The PR refactors control flow to use `subcommand_path` chunks. The goal is to ensure that every event command is either executed or skipped the same as `RPG_RT`. The practical results of this are:
* Events which run 10k commands will abort the interpreter at the right time
* Save games that are saved and loaded during executing conditionals will load correctly and be compatible between RPG_RT and Player.
Fixes most of #1707
Retested: #1613
> Refactor interpreter control flow

- src/scene_debug.cpp
- src/scene_debug.h
- src/window_varlist.cpp
- src/window_varlist.h
~~Depends on: #1784~~
TBD:
TBD later Pr's:
When an event is forced onto the foreground interpreter, its like a call event was executed. This works as expected and survives saving and loading since the `forground_event_execstate.stack` will have the event commands pushed to it.
Saving and loading will break if an event is forced to run in parallel when it normally shouldn't. While we can push the event commands onto `parallel_event_execstate.stack`, there is no LSD chunk to save the fact that we want to force execution to happen even if the controlling conditions are not met (or the event trigger isn't parallel).
We could add a custom chunk for this, or just let save games break here since this is a debug feature.
> Add support for calling events from debug scene + Code Refactor

- CMakeLists.txt
- Makefile.am
- src/async_op.h
- src/game_commonevent.cpp
- src/game_commonevent.h
- src/game_event.cpp
- src/game_event.h
- src/game_interpreter.cpp
- src/game_interpreter.h
- src/game_interpreter_map.cpp
- src/game_interpreter_map.h
- src/game_map.cpp
- src/game_map.h
- src/game_system.cpp
- src/game_system.h
- src/game_temp.cpp
- src/game_temp.h
- src/scene.cpp
- src/scene.h
- src/scene_battle.cpp
- src/scene_map.cpp
- src/scene_map.h
~~Depends on #1742~~
The PR has 2 goals:
* Refactor the async framework:
* Don't use globals
* Kill `transition` game temp vars
* Support parameters for async ops
* Change Inn Fade Out, BGM, Fade In sequence to be asynchronous
Test Cases of #1689
> Async improvements + Async Inn Sequence

- src/game_event.cpp
Whenever we change the event page, we should clear
the interpreter if it was created.
Remove asserts that can be violated by the interpreter being
created from another page.
This is a regression from #1884
> Game_Event: Always clear interpreter on page change

- src/filefinder.cpp
- src/filefinder.h
- tests/filefinder.cpp
On linux, master won't let you point to a `--project-path` which is a symlink to a game directory.
> FileFinder: Support directory symlinks on linux

- src/async_handler.cpp
- src/filefinder.cpp
Emscripten makes now the path canonical before doing a lookup and the FileFinder does not flood the log with "Path adjusted" and "File not found bla.xyz", "File not Found bla.png" (when probing for the adjusted file) anymore.
This adds some minor enhancements: Picojson not included anymore outside of emscripten and added a async testing macro.
> Emscripten: Support non-canonical paths

- src/graphics.cpp
- src/graphics.h
- src/player.cpp
- src/player.h
When the Player runs at 0 FPS the next_frame will fall behind start_time which means the Player will continue running at 0 FPS even when the current screen could run faster.
next_frame and start_time are now properly reset when 0 FPS are reached.
For testing wait for ~10 sec in Frozen Triggers, then leave the screen to the left to enter the shop. With my patch the FPS go up to 60 again, in master it stays at 0 FPS for a long time until it recovers.
This should also fix some Android bug reports where the logfile was spammed with 0 FPS.
> Fix Player getting stuck at 0 FPS.

- CMakeLists.txt
- Makefile.am
- resources/shared/easyrpg.ini
- src/meta.cpp
- src/meta.h
- src/options.h
- src/player.cpp
- src/player.h
- src/scene_file.cpp
- src/scene_file.h
- src/scene_import.cpp
- src/scene_import.h
- src/scene_title.cpp
- src/scene_title.h
- src/window_import_progress.cpp
- src/window_import_progress.h
- src/window_savefile.cpp
- src/window_savefile.h
This PR adds support for "Multi-Game Saves", which are games like Legion Saga and The Way that allow you to import a previous game's save file when continuing into the next game. This requires some amount of metadata to be added to the game, which I created a class for (that uses the existing json parser). 
A larger discussion of features and motiviations is in Issue https://github.com/EasyRPG/Player/issues/1854
Tested building/running on Windows, OSX, Linux, and PS-Classic.
> Multi-Game save Import support and Metadata file

- src/battle_animation.cpp
- src/battle_animation.h
- src/game_battle.cpp
- src/game_battle.h
- src/game_battlealgorithm.cpp
- src/game_battler.cpp
- src/game_battler.h
- src/game_enemy.cpp
- src/game_interpreter.cpp
- src/game_interpreter.h
- src/game_interpreter_battle.cpp
- src/game_interpreter_map.cpp
- src/game_map.cpp
- src/game_map.h
- src/game_screen.cpp
- src/game_screen.h
- src/scene.cpp
- src/scene.h
- src/scene_battle.cpp
- src/scene_battle_rpg2k.cpp
- src/scene_map.cpp
- src/scene_map.h
- src/sprite_battler.cpp
Fix: #1757 
Fix: #1372
~~Depends on #1784~~
This supports RPG_RT compatible saving and loading of map battle animations
TBD:
> Refactor Battle Animations

- src/window_equipstatus.cpp
See screenshots.
RPG_RT on Windows:
EasyRPG Player (Unpatched):
EasyRPG Player (Patched):
> window_equipstatus: Draw fullwidth arrow in Japanese games

- src/game_commonevent.cpp
- src/game_commonevent.h
- src/game_event.cpp
- src/game_event.h
- src/game_interpreter.h
- src/game_map.cpp
* If a parallel common event disables it's switch and
then does an async operation, we need to force it to
rerun on resume, despite the switch being off.
* If a parallel common or map event resumes, we should not
reset the loop counter.
Fix: #1913
> Fixes for async operations and parallel events

- Makefile.am
- src/game_interpreter.cpp
- src/game_interpreter.h
- src/game_interpreter_map.cpp
- src/game_interpreter_map.h
- src/game_message.cpp
- src/game_message.h
- src/game_player.cpp
- src/player.cpp
- src/player.h
- src/scene_map.cpp
- src/utils.cpp
- src/utils.h
- src/window_message.cpp
- src/window_message.h
- tests/utf.cpp
- tests/utils.cpp
Depends on #1905
Fix: #1781 
I took the commits from #1876 which relate to the conditions which cause the interpreter to block. This is arguably one of the more important pieces of the message refactor. Also includes the LSD `show_message` chunk.
Related Test cases:
* https://github.com/EasyRPG/Player/issues/1706#issuecomment-525077134
There is an additional case where autostart events will wait for the message box to close if they run 1 frame after the previous message finishes. While I added the variable for this, it is not yet implemented. Implementing it correctly requires a lot of frame timing surgery in `Window_Message` and is deferred until later.
> Fix Message Blocking rules - Messages 1 of N

- src/game_screen.cpp
* Stoping shake doesn't clear the flag
* Flag is ignored if time == 0
Fix #1668
> Fix Shake Continuous LSD chunk behavior

- src/game_map.cpp
- src/game_map.h
- src/game_message.h
- src/scene_map.cpp
- src/window.cpp
- src/window.h
- src/window_message.cpp
- src/window_message.h
Depends on #1890 #1905 
This PR adds a bunch of changes to get frame accurate text rendering, open and closing of the text window, and timing of how foreground and parallel interpreters run w.r.t. messages.
There are some hacks added to this to fix regressions without adding more refactoring. They are removed in #1909
> Fix Message text and window animation timings - Messages 2 of N

- src/game_battle.cpp
- src/spriteset_battle.cpp
When a battle event does an animation as the first command, which
also triggers a flash effect on the first frame the game crashes.
This happens because SpriteSet_Battle::Update() is called within
it's constructor before the spriteset unique_ptr is set within
Game_Battle.
Fix: #1929
> Fix battle event battle animation crash

- src/game_interpreter.cpp
- src/game_system.cpp
- src/transition.h
Found a while ago (iirc it was smivan) in a Yume Nikki comparison video.
Not sure if other transitions have the same problem, but here it was obvious because the menu items were named "Random blocks from above/below" but we did "Random block Up/down" (Up/Down as in "upwards/downwards").
Tested with:
> Transition Random blocks up/down were down/up

- src/bitmap.cpp
- src/game_picture.cpp
* Animate LSD chunks accurately
* Fix visual effect speed, period, and displacement
Fix: #1946 
@Br4ssman please confirm
A good way to test this is with this event:
```
ShowPicture: Wave effect w/ some power
Loop:
HideScreen Fade Out
ShowScreen Fade In
Wait 0.5s
Wait 0.0s
Wait 0.0s
```
The screen fades will happen between 1 complete cycle (32 frames), regardless of wave power.
Here are some good images to test the fact that the wave effect period is 32 pixels:
I tested the following scenarios:
> Fix picture waver effect

- src/scene_map.cpp
- src/scene_map.h
Previous async refactor caused a regression where screen fade in would
occur for vehicle teleports. Add an extra flag to handle it.
> Fix Vehicle Teleport transition regression

- src/pixel_format.h
You will get a compile error if you try to instantiate some of the dynamic pixel formats in `pixel_format.h`. This fixes it.
I don't think we use these anywhere, so the error is hidden.
> pixel_format.h - Fix compile errors with DynamicAlpha formats

- CMakeLists.txt
- bench/bitmap.cpp
- bench/font.cpp
- bench/text.cpp
- src/cache.cpp
- src/cache.h
- src/color.h
- src/rect.h
- src/tone.h
https://github.com/google/benchmark
Enabled by `-DPLAYER_ENABLE_BENCHMARKS=ON` in cmake. Turned off by default.
Only when build is enabled, we pull in the libbenchmark dependency.
I used this to get the numbers in #1959
Also adds a bunch of smaller changes to make it easier to write automated tests
> Add micro benchmark framework

- src/bitmap.cpp
- src/bitmap.h
Put most common formats first and do a linear scan.
Shown to be faster than map, unordered_map, and
lower_bound on sorted array.
I have a google bench setup in another branch which is part of the message PR queue. I wanted to present this one earlier since it's standalone.
```
static void BM_FindFormatSingle(benchmark::State& state) {
const auto fmt = format_R8G8B8A8_a().format();
for (auto _: state) {
BitmapAccess::find_format(fmt);
}
}
BENCHMARK(BM_FindFormatSingle);
static void BM_FindFormat(benchmark::State& state) {
for (auto _: state) {
BitmapAccess::find_format(format_R8G8B8A8_a().format());
BitmapAccess::find_format(format_B8G8R8A8_a().format());
BitmapAccess::find_format(format_A8B8G8R8_n().format());
BitmapAccess::find_format(format_B8G8R8A8_n().format());
}
} …
```
> Flatten Bitmap formats_map into an array

- src/filefinder.cpp
- src/game_picture.cpp
- src/game_picture.h
- src/game_screen.cpp
- src/player.cpp
- src/player.h
MovePicture command doesn't change position of pictures
with fixed_to_map chunk set.
Used in Destined game See: #1741
Confirmed with Don's rm2k and Japanese rm2k3 RPG_RT 1.0.3
> Emulate legacy rm2k/3 move picture behavior + refactor engine accessors

- src/async_handler.cpp
- src/async_handler.h
Depends on: #1896 #1897 
These are some player optimizations to fix some of the issues in #1883 
Debug build in master
Debug build after "Don't reallocate Sprite"
Debug build after "Add Player::GetTicks()"
Debug build after "Add AsyncFileRequest::BindStart()"
Debug build after "Don't update picture sprites after load"
These show improvements, but I still get 0 FPS so far.
> Frozen Triggers Optimizations // Minor AsyncHandler Optimizations

- src/bitmap.cpp
- src/pixel_format.h
Depends on #1959 
Make this a separate PR because it likely breaks GCW0 build despite being C++14 compliant.
This allows us to remove lazy initialization. It also removes startup runtime code to construct the mapping.
> Make DynamicFormat and Bitmap formats_map constexpr

- src/game_interpreter.cpp
- src/game_picture.cpp
- src/game_picture.h
* spritesheet_frame from command starts with 1, but save data starts 0
* Optimize case for invalid frames, which can be caused by code
which uses variables to set the frame id
The bug can be noticed in Frozen Triggers. Right at the beginning the are visual glitches with the weapons.
> Fix spritesheet regression

- bench/draw.cpp
- src/background.cpp
- src/background.h
- src/battle_animation.cpp
- src/battle_animation.h
- src/drawable.cpp
- src/drawable.h
- src/fps_overlay.cpp
- src/fps_overlay.h
- src/frame.cpp
- src/frame.h
- src/graphics.cpp
- src/graphics.h
- src/message_overlay.cpp
- src/message_overlay.h
- src/plane.cpp
- src/plane.h
- src/screen.cpp
- src/screen.h
- src/sprite.cpp
- src/sprite.h
- src/tilemap_layer.cpp
- src/tilemap_layer.h
- src/transition.cpp
- src/transition.h
- src/weather.cpp
- src/weather.h
- src/window.cpp
- src/window.h
This devirtualizes `Drawable::GetZ()` resulting in 3x speed up when we sort the drawables.
Benchmark results on a Surface Go Tablet running Windows 10 / WSL.
Before:
```
---------------------------------------------------
Benchmark            Time           CPU Iterations
---------------------------------------------------
BM_DrawSort     320284 ns     313895 ns       2240
```
After:
```
---------------------------------------------------
Benchmark            Time           CPU Iterations
---------------------------------------------------
BM_DrawSort     103358 ns     104627 ns       7467
```
And for fun, if we keep `GetZ()` as non-virtual but don't inline it:
```
---------------------------------------------------
Benchmark            Time           CPU Iterations …
```
>  Optimization: Devirtualize Drawable attributes - Drawables 1 of N

- CMakeLists.txt
- Makefile.am
- src/game_actor.cpp
- src/game_interpreter.cpp
- src/game_interpreter.h
- src/game_interpreter_map.cpp
- src/game_interpreter_map.h
- src/game_map.cpp
- src/game_map.h
- src/game_message.cpp
- src/game_message.h
- src/game_temp.cpp
- src/game_temp.h
- src/pending_message.cpp
- src/pending_message.h
- src/scene_battle.cpp
- src/scene_battle_rpg2k.cpp
- src/scene_battle_rpg2k.h
- src/scene_battle_rpg2k3.cpp
- src/scene_map.cpp
- src/sprite_timer.cpp
- src/window_message.cpp
- src/window_message.h
Depends on: #1900 
Fix: #1908 
Fix: #1873 
Fix: #1909
This PR refactors the messaging interface to better separate concerns between Game_Message and Window_Message. It also fixes more frame timing edge cases from #1706 
Tests from #1706
Failing tests #1706:
* Doesn't crash when RPG_RT crashes
* Embedded variables supported in Player but not RPG_RT
* Embedded variables in actor name itself also supported in Player but not RPG_RT
Passing with/without minor glitches #1706:
* No Wait - Message box doesn't appear briefly
* Wait 0.5s - Box doesn't close when game over scene happens
> Refactor Game_Message / Window_Message interface - Messages 3 of N

- src/game_battle.cpp
* 2k wait for interpreter to finish
* 2k3 interupt and end immediately
Fix: #1998
There are some visual things in 2k3 battles observed in the tests that we don't implement properly. Punting on that until 2k3 battle system is done proper.
> Fix interaction of battle end conditions with running events

- CMakeLists.txt
- Makefile.am
- bench/bitmap.cpp
- src/background.cpp
- src/bitmap.cpp
- src/bitmap.h
- src/cache.cpp
- src/game_picture.cpp
- src/opacity.h
- src/pixman_image_ptr.h
- src/plane.cpp
- src/sprite.cpp
- src/sprite.h
- src/tilemap_layer.cpp
- src/transition.cpp
- src/weather.cpp
- src/window_base.cpp
- src/window_battlestatus.cpp
- src/window_shopparty.cpp
This creates a simple RAII wrapper around pixman images which uses pixman's reference counting and provides a `shared_ptr` like interface.
No material change other than code cleanup. But this will be used later to optimize Bitmap and remove the need for `BitmapRef`
Tested this by playing Frozen triggers and everything works.
> Bitmap Improvements: PixmanImagePtr and Opacity - Bitmaps 1 of N

- CMakeLists.txt
- Makefile.am
- src/game_quit.cpp
- src/game_quit.h
- src/main_data.cpp
- src/main_data.h
- src/player.cpp
- src/window.cpp
- src/window.h
- src/window_base.cpp
- src/window_base.h
- src/window_help.cpp
When you hold F12 a window appears and counts down. Once
countdown is complete, we reset to title screen.
Replaces 2k3e Alt+F12 feature. Enabled for all versions of the engine.
Also fixes a crash with F12, we capture old_scene before
checking for reset.
> Add F12 Quit window.

- bench/pixel_format.cpp
- src/baseui.h
- src/sdl2_ui.cpp
~~In our SDL rendering code we call `SDL_UpdateTexture` which is documented to be a very slow function and not intended for streaming textures.~~
~~https://wiki.libsdl.org/SDL_UpdateTexture~~
~~This PR uses the recommended Lock/Unlock methods instead.~~
Further testing shows at least on my machine despite what the docs say, `SDL_UpdateTexture` is faster on my machine.
> Optimize SDL2 Renderer

- src/scene_file.cpp
- src/window_savefile.cpp
- src/window_savefile.h
Save window would not display name, level, or hp when the first actor has no face graphic.
> Fix save window when party members have no face graphic

- Makefile.am
- src/game_actor.cpp
- src/game_actor.h
- src/game_interpreter.cpp
- src/game_interpreter.h
- src/game_message.cpp
- src/game_message.h
- src/game_party.cpp
- src/pending_message.cpp
- src/pending_message.h
- src/scene_battle_rpg2k.cpp
- src/scene_battle_rpg2k3.cpp
- src/window_message.cpp
- src/window_message.h
- tests/parse.cpp
Depends on #1909 
Moves param parsing methods to `Game_Message` so they can be used generically. Adds unit tests. It also changes `Window_Message::text` to be utf8 and uses `UTF8Next` to iterate the text. 
This optimizes our message processing by removing roundtrips between utf8 -> utf32 -> utf8. It reduces the memory footprint of the text and also spreads the cost of utf8 parsing over the frames of message rendering instead of doing it upfront.
In later PR's we'll eliminate `Window_Message::text` entirely and do everything from `PendingMessage`, removing the additional memory copies.
Fixes test cases of #1706:
> Refactor param parsing methods + use utf8 + level up msg fix - Messages 4 of N

- resources/emscripten/emscripten-post.js
- resources/emscripten/emscripten-pre.js
- src/async_handler.cpp
- src/player.cpp
- src/scene.h
- src/sdl2_ui.cpp
New build line is:
```
emcc -g0 -O2 -v --llvm-lto 1 -s ASSERTIONS=0 -s NO_EXIT_RUNTIME=1 \
-s ALLOW_MEMORY_GROWTH=1 -s DEMANGLE_SUPPORT=1 \
-s ASYNCIFY \
-lidbfs.js \
easyrpg-player.bc \
-o player-js/index.html \
--pre-js resources/emscripten/emscripten-pre.js \
--post-js resources/emscripten/emscripten-post.js \
--shell-file resources/emscripten/emscripten-shell.html
```
Needed to split the argument handling because the generated code changes:
Arguments must be prepared after the pre-js-file was executed.
Currently not added because of problems with the instrumentation (?): "-s ASYNCIFY_IGNORE_INDIRECT"
sleep_for: ``_ZNSt11this_thread9sleep_forIlSt5ratioILl1ELl1EEEEvRKNSt6chrono8durationIT_T0_EE``
> Preparations for new emscripten backend

- bench/bitmap.cpp
- src/bitmap.cpp
- src/bitmap.h
- src/game_interpreter.cpp
- src/game_picture.cpp
- src/game_picture.h
- src/game_screen.cpp
- src/game_screen.h
- src/scene_map.cpp
- src/scene_save.cpp
Fix #1093
Fix #1883 
* Remove sheet bitmap
* Fix Effect's blit to properly handle src_rect for rotations in pixman
Tests with normal picture
For these tests I created several pictures with different sprite sheet frames of the actor1 charset. I also created a picture without a spritesheet.
For the 75% / 25% test, you have to hack player code because top/bottom trans are not supported in 2k3e.
Test Cases
> Refactor and optimize Game_Picture + Wave fix - Bitmaps 2 of N

- CMakeLists.txt
- Makefile.am
- src/battle_animation.cpp
- src/color.h
- src/flash.h
- src/game_battle.cpp
- src/game_battle.h
- src/game_battler.cpp
- src/game_battler.h
- src/game_character.cpp
- src/game_character.h
- src/game_picture.cpp
- src/game_screen.cpp
- src/game_screen.h
- src/scene_battle.cpp
- src/scene_battle.h
- src/scene_battle_rpg2k.cpp
- src/scene_battle_rpg2k3.cpp
- src/scene_battle_rpg2k3.h
- src/shake.h
- src/sprite.cpp
- src/sprite.h
- src/sprite_airshipshadow.cpp
- src/sprite_battler.cpp
- src/sprite_battler.h
- src/sprite_character.cpp
This moves shake and flash animation logic to their own headers so they can be reused. It also eliminates the flash animation capability from `Sprite` and instead relies on game objects to do animation. This is important for timing as there is no guarantee of when sprites are updated vs game objects. It also makes `sizeof(Sprite)` smaller.
Finally, this fixes a bug I discovered in battle where some battle animations with flash effects would cause the flash to stick on the battler sprite and not fade away until another flash replaced it.
> Cleanup Shake and Flash logic

- src/scene_map.cpp
When a foreground event causes a teleport, foreground
events run during pre-update. If then during that preupdate
the fg event triggers another teleport, we need to handle it.
Fix: #2038
Leaving this as a draft as I want to do more testing around this scenario.
> Handle teleports run by foreground events in preupdate

- src/game_picture.cpp
Fix: #2036
Temporary fix for the crash until a proper refactor is made.
https://easyrpg.org/play/pr2051/?game=tdf2018wildcompodemo
> Fix crash when picture loading races with vector resize

- bench/bitmap.cpp
- src/bitmap.cpp
- src/bitmap.h
- src/compiler.h
- src/game_actor.cpp
- src/game_screen.cpp
- src/opacity.h
- src/pending_message.cpp
- src/rect.cpp
- src/rect.h
- src/scene_map.cpp
- src/spriteset_map.cpp
- src/spriteset_map.h
- src/tilemap_layer.cpp
- src/tilemap_layer.h
Retested #1417 
There was a performance regression introduced into tilemap when tone support was added. Basically we never actually use the `TileOpacity` value, resulting in us rendering every tile, even when they are fully transparent.
This PR fixes that and adds several other optimizations to TilemapLayer. 
The test case is a map with all transparent tiles and no background. Each optimization commit in this PR was measured and shown to have an improvement for this test.
For `ComputeImageOpacity()`
Master:
```
---------------------------------------------------------------------
Benchmark                              Time           CPU Iterations
---------------------------------------------------------------------
BM_ComputeImageOpacity            352849 ns     352851 ns       1969 …
```
> Optimize Tilemap

- Makefile.am
- bench/font.cpp
- bench/text.cpp
- src/bitmap.cpp
- src/bitmap.h
- src/font.cpp
- src/font.h
- src/game_message.cpp
- src/output.cpp
- src/pending_message.cpp
- src/player.cpp
- src/text.cpp
- src/text.h
- src/utils.cpp
- src/utils.h
- src/window_battlestatus.cpp
- src/window_message.cpp
- src/window_message.h
- tests/font.cpp
- tests/text.cpp
- tests/utf.cpp
~~Depend on: #1956~~
This PR refactors the underlying `Font` and `Text` interfaces to be more streamlined and efficient.
Current Test Results
--------------------------
After "Font::Render - remove query for system"
Font:
```
------------------------------------------------------
Benchmark               Time           CPU Iterations
------------------------------------------------------
BM_FontSizeStr        637 ns        637 ns    1107660
BM_Glyph              171 ns        171 ns    4005735
BM_Render            2481 ns       2480 ns     282438
```
Text:
```
---------------------------------------------------------
Benchmark                  Time           CPU Iterations
---------------------------------------------------------
BM_TextDrawStr         94971 ns      94971 ns       7365 …
```
> Refactor Text Rendering stack - Messages 5 of N

- src/graphics.cpp
- src/player.cpp
- src/player.h
- src/scene.cpp
Depends on #1973 
This pulls the first set of commits out of #2017 which just cleans up our current main loop without doing a major refactor. The main purpose of this is to move the time keeping and loop management all into `Player::MainLoop`. 
We also do drawing *after* suspending scenes, which is necessary for visual correctness of transitions initiated by `Scene::TransitionOut()`. It also makes sure transitions are updated with the rest of the game logic, so that they animate properly even under fast forward or frameskip. With respect to transitions, this PR has all the dependencies needed for #2019 
This also ensures sleep caused by vsync happens at near the same time as mandatory sleep.
Finally, this also fixes the framerate histogram in vtune.
This should be mergable sooner, while …
> Cleanup main loop - MainLoop 3 of N

- src/filefinder.cpp
- src/registry_wine.cpp
- src/utils.cpp
- src/utils.h
- tests/utils.cpp
Two improvements:
- The RTP is now initialized the first time a file is missing. This way there is no startup delay, instead the delay is now when the first RTP asset is requested. Yes this only moves the problem but for some games this means 0 delay.
- lcf INI parser replaced with a simple parser that just reads all lines and skips until the Key/Value pair is found. No extra caching, that's why I don't consider this a fix for #1903, likely can be improved more.
> Speedup Startup + RTP detection

- src/drawable_mgr.cpp
- src/drawable_mgr.h
- src/graphics.cpp
- src/graphics.h
- src/player.cpp
- src/scene.cpp
- src/scene.h
- src/transition.cpp
- tests/drawable_list.cpp
- tests/drawable_mgr.cpp
Depends on #2019
This PR removes the global drawable list. Now all drawables can be sorted and rendered in a cohesive way. The `TakeFrom` mechanism is used to transfer the globals between scenes during scene change.
Drawing still works as before, because all the global drawables also have higher Z values than local drawables.
> Remove global drawable list - Main Loop 5 of N

- CMakeLists.txt
- builds/cmake/Modules/ConfigureWindows.cmake
- src/drawable_mgr.cpp
- src/player.cpp
- src/text.cpp
- src/window_message.cpp
- tests/parse.cpp
- tests/utf.cpp
Fix: #2073
Fix: #2061 
Fix: #2045 
@elsemieni can you confirm this fixes the crash you found? I can't reproduce it so while I suspect this is the cause I can't prove it.
> Allow global drawables to be destroyed when there is no list + windows crash fixes

- src/scene_file.cpp
This behavior triggers a rare bug:
From map, open the debug menu, then open save menu.
The debug menu has a instant CutOut transition, which mean there is no
frame between exiting debug and starting save menu. Because of this,
Input::Update() is never called and so Scene_File::Update() immediately
saves and then pops the scene from Start(), which breaks the scene
stack.
Fixes second issue in #2080
> Don't call Scene_File::Update from Start()

- src/font.cpp
- src/pending_message.cpp
- src/utils.h
- src/window_message.cpp
- tests/font.cpp
Fix #2090
Unfortunately @fmatthew5876 was unlucky with the glyph he picked for the unit test, otherwise this would have been catched by it :(
iscntrl takes a int but the docs say "Like all other functions from cctype, the behavior of std::iscntrl is undefined if the argument's value is neither representable as unsigned char nor equal to EOF" Nice API
> Use custom implementation instead of iscntrl

- src/player.cpp
Input events were only processed once per frame. When the user only briefly presses a key this would queue a key-up and a key-down event. Both are processed at the same time, nullifying them.
Now they are polled in every Update.
Fix #2094
> Fix Inputs being lost when the game lags.

- src/cache.cpp
The dummy bitmap cache entry did not consider the transparency flag. When the system graphic is missing this spams extremely.
Minor: Remove entire cache entry instead of only deleting the bitmap. Allows removing the nullptr checks.
> Fix Cache regression for DummyBitmaps

- src/audio_3ds.cpp
- src/audio_decoder.cpp
- src/audio_decoder.h
- src/audio_generic.cpp
- src/audio_generic.h
- src/audio_resampler.cpp
- src/audio_resampler.h
- src/audio_sdl_mixer.cpp
- src/audio_sdl_mixer.h
- src/audio_secache.cpp
- src/audio_secache.h
- src/decoder_libsndfile.cpp
**a)** When playing a SE for the first time we
1. load the entire file
2. resample the entire file
3. cache it
The intention was to help slow hardware when many SE are played at once.
**b)** With the new code it is:
1. load the entire file
2. cache it
Resample/Pitch is now done in the Audio thread. So this is a trade-off where we pay the CPU time, at least the IO part is still only once.
For Witch's Heart (Limes game) the load time of SE is reduced from 90ms (with Medium resample quality 140ms) to 6ms.
Refactor: Instead of a buffer+length the SeCache returns now a real AudioDecoder. This gives us more flexibility later, e.g. short samples (TODO: What is short) could be handled as **a)** and longer samples could be handled as **b)**. This patch handles everything as **b)**.
Unfortunately …
> Fix lag when loading large SE files

- src/audio_generic.cpp
This one should be in 0.6.2 because it breaks BGM playback.
GenericAudio: Fix a race condition in BGM_Stop: When BGM_Play is executed too quickly there is no free BGM channel available because the audio thread had no time to destroy the BGM decoder.
Force the decoder deletion in BGM_Stop to ensure that there is always a channel.
Remove "Muted": there is no way to set this variable and all channels support pausing.
That's the first half for #2106.
> GenericAudio: Fix a race condition when BGM_Play is called too often

- src/game_battlealgorithm.cpp
- src/game_screen.cpp
- src/scene_battle.cpp
Not sure if there is a better location available for the crashfix (1st commit). The animation must be part of the transition screen, can't be removed in Scene_Battle constructor.
Stacktraces fixed by crashfix:
```
#00  pc 000000000024535c  lib/arm64/libmain.so (DrawableList::Draw(Bitmap&, int, int)+104)
#01  pc 00000000002f88c8  lib/arm64/libmain.so (Transition::Init(Transition::Type, Scene*, int, bool)+372)
#02  pc 00000000002d8788  lib/arm64/libmain.so (Scene::MainFunction()+452)
#03  pc 00000000002bcda8  lib/arm64/libmain.so (Player::MainLoop()+180)
#04  pc 00000000002bcc70  lib/arm64/libmain.so (Player::Run()+216)
#05  pc 00000000002a8a74  lib/arm64/libmain.so (SDL_main+12)
#06  pc 0000000000043964  lib/arm64/libSDL2.so (Java_org_libsdl_app_SDLActivity_nativeRunMain+696)
#07  pc …
```
> Battle: Crashfix and minor bugfix

- src/player.cpp
- src/scene.cpp
- src/transition.cpp
Prevents the load game's state from impacting the
currently visible screen.
Fix: #2111
> Do an early transition out before loading save

- src/transition.cpp
Transparent pixels blend improperly and cause visual glitches
Fix: #2117
> Transition bitmap - disable transparency

- src/input_buttons.h
- src/player.cpp
Still works fine because the button is pressed down and not just triggered.
> PLUS is not a system button (but is used by Fast forward)

- src/bitmap.cpp
Fix #2128
xform is true when there is a Flip, the conditional is wrong
> FlipBlit: Reset the transformation matrix correctly

- src/audio_sdl_mixer.cpp
- src/audio_sdl_mixer.h
The SE playback buffer was copied and not moved. The buffer used by SDL2 was invalid after returning from the function.
Not detected by ASAN because it happened in SDL :(
Fix #2130
> Fix use-after-free in Audio SDL Mixer

- src/registry_wine.cpp
Wine incorrectly redirected HKCU, but is fixed by now.
This reverts c7d41c01
> Wine: Disable Wow6432Node redirection for HKCU

- src/sprite_battler.cpp
Call ResetZ before SetAnimationState is called. Otherwise BattleAnimation-Battlers will be invisible at the beginning of the battle.
Just a cosmetic thing.
~~Is there an open issue about this?~~ (Yes there is #1826). Was mentioned in the VD discord.
> Battle 2k3: Fix BattleAnim-Battlers being invisible before first action

- src/audio_sdl.cpp
Our Mutex locking never worked :o
They always operated on the wrong audio device because SDL_LockAudio was used and not SDL_LockAudioDevice.
This was never noticed before because all the decoder destruction was in the Audio thread but now the BGM can be destroyed by the main thread.
But no idea how so many Android users encountered this, I had to add an artificial delay of 100ms and then it still didn't crash that often. But there are 20000 users and only 20 encountered it, so you have to be kinda unlucky :)
> SDL Audio: Fix Lock/UnlockMutex. 

- src/game_map.cpp
- src/game_message.cpp
- src/scene_name.cpp
- tests/parse.cpp
1st commit is unrelated to messages, detected by UbSan
2nd fixes a regression introduced by moving the Scene::Pop to a new location while removing Game_Temp: https://github.com/EasyRPG/Player/commit/993ef100e106c8f3d9845b92f29e8c0d3df11a77#diff-ad788c966e27c5a83ba8ac104b2b3c73R117-R121 (no idea why it was moved though)
3rd fixes \n[0]. Was broken during refactoring.
https://github.com/EasyRPG/Player/blob/0.6.1/src/window_message.cpp#L589-L605
> Message regression fixes

- src/audio_resampler.cpp
...  when the amount of samples read was exactly 0.
This should be last problem with the audio code...
The check didn't work because of size_t instead of int.
This is also a year old bug btw. In the old code the mono-to-stereo code was in SeCache where always the entire SE was decoded -> Buffer was never empty. :/
> Resampler: Fix buffer overflow in mono_to_stereo_resample

- builds/amiga/Makefile
- src/async_handler.h
- src/filefinder.cpp
- src/game_character.h
- src/output.h
I managed to get rid of the undefs I added to avoid namespace clashes on MorphOS. It turns out the inline macros can be safely replaced with linker stubs by defining _NO_PPCINLINE. This should take care of the Amiga part of #1428
---
Edit by carstene1ns: Fixes #1428
> Remove the MorphOS macro undefs

- bench/variables.cpp
- src/game_interpreter.cpp
- src/game_variables.cpp
- src/game_variables.h
- tests/parse.cpp
- tests/variables.cpp
When RPG_RT processes a command to set a range of variables to a
random value, it calls the RNG for each variable separately.
Fix: #2155 
Fix: #2156
@Ghabry can you please confirm it fixes the games in these issues? I don't have these japanese games working on my windows pc.
Confirmed this behavior in 2ke and 2k3e. Tested this with some example games.
> CommandControlVariables fixes

- src/game_screen.cpp
This crash can occur when loading a save game with an
invalid animation target.
Fixes crash #1 in #2166 
To test:
1. Make Ev01 show battle anim on EV02, no wait
2. Make Ev02
3. Start a new game
4. Trigger battle animation
5. save before animation completes
6. in editor, delete Ev02
7. Load your save
RPG_RT will  throw an invalid event exception. Player will crash.
This PR changes it so player will just show a warning and skip the animation
> Fix crash in ShowBattleAnimation() when target is invalid

- builds/amiga/Makefile
- src/image_png.cpp
I missed this one in my previous PR, this should reduce the Amiga specific clutter in the source files to the minimum.
> Move __MORPHOS_SHAREDLIBS into the Makefile for MorphOS

- src/scene_battle.cpp
- src/scene_battle_rpg2k.cpp
This adds warnings to the Battle2k code in an attempt to solve 2. in #2166 with the help of our users.
My guess is that the bug is caused by an actor/enemy with multiple battle actions but I can't find a way to generate such a situation.
This crash is very rare. It affected only two users but these users 10 times so it must be a very specific edge case that is not randomly hit. Therefore I think knowing game and monster party is enough to figure this out. By showing a visual warning and not crashing maybe we can motivate the users to send us a bug report with a logfile :).
This is for inclusion in 0.6.2, but the solution is obviously not.
> Battle 2k: Prevent crash when battle action is NULL

- src/bitmap.cpp
- src/filefinder.cpp
- src/game_interpreter.cpp
That's a flaw (well, the structure made sense because there is no way to read stuff from ./, but then "creative" games appeared...) with the FileFinder data structure: The root-directory files are stored in a different location than the submembers, so there must be extra handling for finding files in the root-dir.
Fix #2176
Regression caused by 7de54b62
> Regression fixes

- src/game_character.cpp
- src/game_character.h
- src/game_event.cpp
Fix #1638 
~~This is derived from what I've seen empirically, but the random algo may not be right.~~
The MV Algo of [0:1] Random, [2:4] Forward, [5] Reset is definately wrong.
~~I know for a fact we never reset stop count, but we do sometimes wait an extra frame.~~ The MV algo moves forward too much. This can be observed simply by watching an event walk around.
> Refactor move type random

- src/game_event.cpp
This fixes the direction issue reported by the user in #2183 It does not fix the other timing issues I found with movement in that issue.
> Reset facing lock flag on event page change

- src/sprite.cpp
Fixes a bug where graphic state changes would be skipped in some
cases when the sprite is off screen.
Fix: #2204
> Sprite: Don't reset bitmap_changed state when off screen

- src/scene_debug.cpp
* Full heal plays decision twice
* Full heal party members become unselectable under some conditions
* Allow calling common events > 100
* Gold should only be 6 digits
> Scene_Debug: Regression fixes

- src/game_interpreter.cpp
- src/game_message.cpp
- src/game_message.h
- src/scene_battle.cpp
- src/scene_map.cpp
- src/sprite_timer.cpp
- src/window_message.cpp
- src/window_message.h
Depends on #1964 
Fixes more cases of #1706
This is yet another refactor of Window_Message. I've tried to clean up the Update loop to make it more understandable.
Unfortunately the number of edge cases here is just insane. So making this code readable is a real challenge.
There are a number of notable issues
* RPG_RT animates open/close after the main loop. Since we don't do this, I had to put in hacks to emulate the timing.
* I've finally nailed down the exact timing (and the rationale for why it works this way) for window open, close, and the interpreter blocking. 
* There are many, many subtle edge cases previously unknown with character timing. Even more-so with speed=1. Many have been discovered and added.
For this PR I have a much improved workflow to measure accuracy. To time any …
> Improve Window_Message timing accuracy - Messages 6 of N

- src/output.h
Reduces the compile times to there previous state.
Fix #2229
> Use fmtlib core.h instead of format.h in Output logging.

- src/scene_gamebrowser.cpp
- src/scene_gamebrowser.h
Adds ability to start a game with debug flag enabled by pressing SHIFT (or its mappings) to launch it instead of ENTER. Also maps the Vita START button to F9 if running with debug flag instead of ESCAPE, which should allow you to open the debug menu with the Vita's START button if running in this mode.
This is useful for playing certain RPGMaker games that are buggy or are otherwise incomplete, since tweaking variables and switches would otherwise be the only method to get past certain events.
This is my first PR so I'm very keen to hear any feedback, especially if I've broken any style guides or other rules. I'm really keen to help out more with this project!
> Allow debug flag from gamebrowser

- src/decoder_fmmidi.cpp
- src/decoder_fmmidi.h
- src/decoder_libsndfile.cpp
- src/decoder_libsndfile.h
- src/decoder_wav.cpp
- src/decoder_wav.h
- src/decoder_wildmidi.cpp
- src/decoder_wildmidi.h
- src/midisequencer.cpp
- src/midisequencer.h
_libsndfile_ and our bad _wave decoder for slow platforms (FASTWAV)_ have no way to query the position. I added sample counting to get the position. This is hard to get right when "Seek" is used, so I kept this as a FIXME.
In _FmMidi_ I added the current tick count to the midi message. The value matches the harmony value with some margin of error (is a bit higher/lower, harmony somehow keeps the value constant). No idea yet how to make it match better.
_WildMidi_: This is problematic. Will probably create a PR to there library someday to export the values through there API. They only offer the samplerate (How many samples were created based on the Midi file, so this is indirectly calculated through tempo + division).
When the Midi has no tempo changes just knowing the current tempo is …
> Implement Ticks for: libsndfile, FmMidi, Wildmidi (kinda)

- src/decoder_fmmidi.cpp
- src/decoder_fmmidi.h
- src/midisequencer.cpp
- src/midisequencer.h
Pretty naive implementation but follows the same MIDI message that harmony/rm2k3 uses for looping, namely the `b06f` event, which is a Control Change event on channel 1 with value `111`. You can quickly look for that by seeing if the MIDI message is `0x6fb0`, which is what that magical number check is.
Unfortunately fmmidi looks like it's the only decoder that lets me inspect the MIDI messages as they're passing through like this, which is what made this such a simple patch.
> FmMidi: naive harmony-like loop support

- src/game_character.h
> Fix constexpr compilation in Game_Character

- src/async_handler.cpp
- src/graphics.cpp
- src/player.cpp
- src/scene.cpp
- src/scene.h
- src/scene_battle.cpp
- src/scene_battle.h
- src/scene_map.cpp
- src/scene_map.h
- src/transition.cpp
- src/transition.h
This PR improves support for asynchronous functions during scene initialization. It's required for 2k3 battle and also fixes some issues with maps.
> Transitions - wait for graphics loading if screen erased - dependency for battle2k3 PRs

- src/bitmap.h
- src/opacity.h
- src/scene_debug.cpp
The map uses a 1x1 tilemap. I also fixed the case for tilemaps that fit at least one tile (triggered a different assert)
Caused by too strict assert checks in 61f859ec4f935da9c13e85f58251e0291d42faa8
> Yume2kki: Fix tilemap assert on Map 196

- CMakeLists.txt
- Makefile.am
- src/battle_animation.cpp
- src/game_actor.cpp
- src/game_actor.h
- src/game_battle.cpp
- src/game_battle.h
- src/game_battlealgorithm.h
- src/game_battler.cpp
- src/game_battler.h
- src/game_enemy.cpp
- src/game_enemy.h
- src/game_enemyparty.cpp
- src/game_enemyparty.h
- src/game_party.cpp
- src/game_party.h
- src/game_party_base.h
- src/point.h
- src/scene_battle.cpp
- src/scene_battle_rpg2k3.cpp
- src/scene_battle_rpg2k3.h
- src/sprite_battler.cpp
- src/sprite_battler.h
- src/spriteset_battle.cpp
- src/spriteset_battle.h
- src/window_base.cpp
Depends on #2217 
Fix: #2141 
Fix: #278 
Battle Conditions
----------------
Placement
----------
Facing Direction
------------------
Row
----
Things to investigate
> Battle 2k3 2: Implement 2k3 battler placement

- CMakeLists.txt
- configure.ac
This is to allow building on debian stable, e.g. Raspberry Pi.
> Allow building with libfmt older than 5.3

- CMakeLists.txt
When performing an out-of-source build, that is instead of:
```
cmake ./
```
doing
```
mkdir build/
cd build/
cmake ../
```
The man page would fail to build and install. This changeset fixes those issues.
> Fix "man" target not working properly with out-of-source builds

- builds/cmake/Modules/FindFreetype.cmake
- builds/cmake/Modules/FindHarfbuzz.cmake
While packaging EasyRPG Player for the Fedora Linux distribution ([link](https://src.fedoraproject.org/rpms/easyrpg-player)), I stumbled across this problem with the circular dependency between Feeetype and Harfbuzz:
1) CMake would find Freetype
2) It would then try to find HarfBuzz, as wanted by FreeType
3) It would find HarfBuzz
4) It would then try to find FreeType, as wanted by HarfBuzz
5) This second search for FreeType would fail.
This patch adds some `if(NOT TARGET)` guards around the circular `find_package()` calls, solving the problem described above.
> Add if()s around circular find_package() calls

- src/game_config.cpp
- src/platform/3ds/3ds_audio.cpp
Fixes the 3DS build and adds the stream API to Game_Config.
Right now the stream API usage can't be enforced. When the FS stuff is finished not using the API will simply fail :)
> Filesystem [1.5/N]: Fixes & Updates

- src/game_interpreter.cpp
Fix: #2284
Confirmed behavior in RE tools.
I would consider this for backporting to stable.
> Block key input processing while message is active

- src/game_battlealgorithm.cpp
- src/game_battlealgorithm.h
- src/scene_battle_rpg2k3.cpp
- src/scene_battle_rpg2k3.h
This PR fixes #2251. Moreover a second commit has been added to check if an item has been used because skills invoked by items bypass spell reflection (compare with the Item "Heiliger Sand" in "Vampires Dawn II". Using that item removes all positive states on the enemies (including "Spiegel") and it doesn't get reflected in RPG_RT).
> Spell reflect fix

- AUTHORS.md
- src/scene_actortarget.cpp
- src/window_actortarget.cpp
Outside of battles the first party member is able to use self-target skills on the other party members too. This is because the ActorTarget scene checks for a negative index to lock the selection. But the first party member has the index zero and things like "negative zero" doesn't exist. This PR aims to fix this by shifting the party member index.
> Fix self-target skills outside of battles

- CMakeLists.txt
- configure.ac
- resources/emscripten/emscripten-post.js
- resources/emscripten/emscripten-shell.html
- src/player.cpp
- src/scene_logo.cpp
- src/sdl2_ui.cpp
- tests/cmdline_parser.cpp
- tests/config_param.cpp
- tests/directorytree.cpp
- tests/filefinder.cpp
- tests/platform.cpp
- tests/rtp.cpp
Fix #2228
How to build:
```
source EMSCRIPTEN_PATH/emsdk_env.fish
emcmake cmake . -GNinja -DPLAYER_JS_BUILD_SHELL=ON|OFF
```
```
cmake --build . --target check
[2/2] /bin/node /home/gabriel/code/easyrpg/easyrpg-player/test_runner.js
[doctest] doctest version is "2.3.5"
[doctest] run with "--help" for options
============================================
[doctest] test cases:     98 |     98 passed |      0 failed |     10 skipped
[doctest] assertions:   3391 |   3391 passed |      0 failed |
[doctest] Status: SUCCESS!
```
The ``LANGUAGES C`` is required for the ".js" files and I can't figure out a different way to enable C.
This allows changing the path with ``-DPLAYER_JS_GAME_URL`` and it will only recompile this one file! (at least when Ninja is used, Makefiles do a full recompile) …
> Add Emscripten support to CMake

- src/game_battlealgorithm.cpp
This PR tries to fix #1680. It checks if RPG Maker 2003 is used and if it's true, then the clamping on this->hp in game_battlealgorithm.cpp gets disabled when a healing spell or healing item is used. This makes the jumping number always show the amount of HP healed. The function SetHp in game_actor.cpp makes sure that the maximum HP doesn't get exceeded despite the disabled clamping.
> Fix healing display in RPG Maker 2003 battles

- CMakeLists.txt
- resources/emscripten/emscripten-shell.html
Multiple games on sites like rmarchiv itch.io and similar will benefit on this.
Additinally, remove the default 'Downloading...' text to prevent user confusion when robots show web content preview.
Closes: #804.
> Backport emscripten-core/emscripten#7631 for focus on iframes

- CMakeLists.txt
- Makefile.am
- builds/android/app/src/main/java/org/easyrpg/player/game_browser/GameBrowserHelper.java
- builds/android/app/src/main/java/org/easyrpg/player/game_browser/GameScanner.java
- resources/shared/easyrpg.ini
- src/fileext_guesser.cpp
- src/fileext_guesser.h
- src/filefinder.cpp
- src/filefinder.h
- src/game_map.cpp
- src/game_map.h
- src/meta.cpp
- src/meta.h
- src/options.h
- src/platform/libretro/libretro_ui.cpp
- src/player.cpp
- src/player.h
Ready to merge (from my point of view). 
This is my implementation for Issue #1920; please see the initial discussion there.
Regarding @Ghabry's comments:
1) Check only 2 files: Done, but see note
2) Assume larger==LDB: Done
3) LcfXXX checks: Done, but see note
Some notes on this fix:
1) What's the easiest way to cheaply check if a directory *might* be a game project? Right now I check for RPG_RT.ini, but as you said that's not always present. I expect RPG_RT.exe might also be stripped. Is there any good file to check, or should I just disable this minor performance hack?  ---Side note: it might be worth keeping if *all games with hacked extensions* have .ini files.
2) The Meta file now has "LmtHeaderString=XXX", which allows us to pass the "XXX" string in to liblcf (i.e., to tell it what …
> Fix for games with altered file extensions

- src/audio_decoder.cpp
- src/audio_midi.cpp
- src/audio_resampler.cpp
- src/audio_sdl_mixer.cpp
- src/audio_secache.cpp
- src/decoder_fluidsynth.cpp
This fixes the worst problem encountered after merging the FluidSynth branch:
- Bad audio quality ("vinyl") because I missed legacy code
- Buildfix for Fluidsynth v1.1.11 (Fedora seems to use this). There were already two reports about this so suppoting this is worth.
v1.1.11 has no VIO support for soundfonts this means that the nice-to-have feature "Load Soundfont from a ZIP/bundled in a APK/etc" will not work.
> Fluidsynth: Fix low audio samplerate and buildfix for v1.1.11

- src/game_actor.cpp
- src/game_battlealgorithm.cpp
- src/game_battler.cpp
- src/game_battler.h
- src/game_map.cpp
Depends on: https://github.com/EasyRPG/liblcf/pull/390
> Add support for DBBitArray

- src/scene_battle_rpg2k.cpp
No idea how we could miss this during testing :thinking: 
To reproduce you need at least 2 in your party:
- 1st Death
- 2nd Normal
When the "Normal" is selected press ESC, then select the "Normal" again and start a fight. You will get a warning.
> Battle 2k: When selecting a previous actor remove "NoMove" actions of dead actors

- src/battle_animation.cpp
- src/battle_animation.h
- src/game_battle.cpp
- src/game_battle.h
- src/game_battlealgorithm.cpp
- src/game_battlealgorithm.h
- src/game_system.cpp
- src/game_system.h
- src/scene_battle_rpg2k3.cpp
- src/scene_battle_rpg2k3.h
This PR takes on a more difficult task and fixes #1564. The changes look more intrusive so it is possible that changes are required on this PR. Anyway, this basically adds a optional invert parameter on the BattleAnimationBattle constructor, the ShowBattleAnimation method and the PlayAnimation methods which makes the animations display mirrored if the parameter is set to true. The new parameter gets used in Scene_Battle_Rpg2k3 only because this feature is used in RPG Maker 2003 only. Some particularities about the flipped animations: Animations get flipped only if the "Flip assets if facing the other direction" flag is set. If this condition is met then the animations will be flipped if either the battler sprite of the source is flipped or the source is belonging to the enemy party …
> Battle 2k3: Add support for flipped battle animations

- src/game_battlealgorithm.cpp
- src/game_battler.cpp
This PR fixes some minor bugs I came across in battles:
- States which recover HP and SP: HP and SP recovery is not restricted by the current amount of the mentioned stats.
- Random variance: In RPG Maker 2000 the variance calculation is even performed on zero damage. I know from playing RPG Maker 2000 games before that attacks sometimes do 1 damage despite too high defense or full magic immunity.
- Random variance of healing skills outside of battles: The old variance formula was still applied so it got replaced by the VarianceAdjustEffect function.
- Skills which do absorbing: Absorbing attack, defense, spirit and agility is only supported in RPG Maker 2003. In RPG Maker 2000 the stats only get decreased.
- Skill accuracy: Accuracy checks are performed on every affected stat. These …
> Battle algorithm changes

- src/game_battlealgorithm.cpp
This PR implements the damage and accuracy modifiers for normal attacks which depend on the battle condition and the row of the actors in RPG Maker 2003.
> Battle 2k3: Implement battle row damage and accuracy modifiers

- src/bitmap_hslrgb.h
- src/scene_battle_rpg2k3.cpp
This PR fixes #2266. If the hue value in the HSL_to_RGB function was greater than or equal to 1536, the color was not converted. Using modulo 1536 on the hue value fixes this because the hue ranges between 0 and 1536 in this function.
> Fix HSL to RGB overflow error

- src/scene_battle_rpg2k3.cpp
- src/scene_battle_rpg2k3.h
This PR adds the in-battle row command used in RPG Maker 2003. Merging this PR and #2321 into master fixes #680.
> Battle 2k3: Implement in-battle row command

- src/scene_battle_rpg2k.cpp
- src/scene_battle_rpg2k3.cpp
I stumbled upon an oddity in relation with the output text of enemy item drops: After the enemy party gets defeated and they drop items the output says funny things like "U received!" instead of the actual item name. Changing `item->name` to `item->name.c_str()` fixes the output but I would like to hear your opinions if this is the right way to fix this.
> Battle: Fix output text of item drops

- src/game_battlealgorithm.cpp
This is not strictly fixing anything. But from here on I think it's good style to always explicitly cast to `StringView` in ternary operators, to avoid bugs like #2333
> Add explicit StringView() on game_battlealgorithm ternary expressions

- src/game_enemy.cpp
The default state rank of an enemy is only "B" instead of "C". All the other default ranks (enemy attribute rank, player state rank and player attribute rank) are already correct.
> Fix enemy default state rank

- .gitignore
- CMakeLists.txt
- README.md
- builds/cmake/Modules/ConfigureWindows.cmake
- builds/libretro/.gitignore
- builds/libretro/CMakeLists.txt
(fix non-SDL2 build such as libretro core)
> macOS: Always link against Foundation framework 

- CMakeLists.txt
Otherwise this breaks the "OFF" setting for liblcf (see CMP0077)
Sorry, unexpected CMake behaviour :(
> CMake: Move BUILD_SHARED_LIBS back to the top

- src/game_interpreter.cpp
- src/game_switches.cpp
- src/game_switches.h
- src/game_system.cpp
- src/game_system.h
- src/game_variables.cpp
- src/game_variables.h
- src/player.cpp
- src/weather.cpp
Depends on https://github.com/EasyRPG/liblcf/pull/396
This PR changes Player to behave more like RPG_RT.
An empty name string in `SaveSystem` is used to tell the game to use the default `System` audio. When the BGM or SE is changed, if the thing changed to matches the default, then empty string is put back in.
This also means if a custom patch were to put empty string in the name, it would also tell RPG_RT to use the default system audio.
DynRPG Addresses:
----------------------
| Address | Class | Function | Comment |
| -- | -- | -- | -- |
| 004AE0D8 | RPG_Interpreter | CommandChangeSystemSE | |
| 004ADF90 | RPG_Interpreter | CommandChangeSystemBGM | |
| 0048B5BC | RPG_System | GetTitleBGM | * see next section | |
| 0048B5FC | RPG_System | SetBattleBGM | |
| 0048B5DC | RPG_System | …
> Remove SaveSystem Setup and Fixup - depends on liblcf #396

- src/game_battler.cpp
If an actor get damaged or recovered due to a state, the damage/recovery value is rounded down instead of up. This means that the damage/recovery value can even be zero if the damage/recovery percentage is set to a low value. Moreover a bug got fixed in SP damage/recovery: The SP damage/recovery percentage uses now the maximum SP instead of the maximum HP for the calculation.
> States: Damage and recovery is rounded down instead of up

- src/game_battlealgorithm.cpp
If a skill gets reflected the first animation (which plays on the original targets) was played even on dead or hidden targets. This PR fixes this behavior.
> Battle 2k3: Fix animation playing on original targets

- CMakeLists.txt
- Makefile.am
- src/algo.cpp
- src/async_handler.cpp
- src/game_actor.cpp
- src/game_battle.cpp
- src/game_battlealgorithm.cpp
- src/game_battler.cpp
- src/game_character.cpp
- src/game_enemy.cpp
- src/game_enemyparty.cpp
- src/game_event.cpp
- src/game_interpreter.cpp
- src/game_map.cpp
- src/game_party_base.cpp
- src/game_player.cpp
- src/game_screen.cpp
- src/game_variables.cpp
- src/player.cpp
- src/rand.cpp
- src/rand.h
- src/scene_battle.cpp
- src/scene_battle_rpg2k.cpp
- src/transition.cpp
- src/utils.cpp
- src/utils.h
- src/weather.cpp
- tests/algo.cpp
- tests/game_character.cpp
- tests/rand.cpp
This PR allows you to lock the rng to always return a single value. In order to maintain accurate semantics for callers to random, the value is clamped.
So for example:
```
Rand::LockRandom(5);
assert(Rand::GetRandomNumber(0, 10) == 5);
Rand::LockRandom(65);
assert(Rand::GetRandomNumber(0, 10) == 10);
Rand::LockRandom(-65);
assert(Rand::GetRandomNumber(0, 10) == 0);
```
My use case for this is to be able to accurately unit test battle variance in #2320, but I imagine we can also use this for the regression test system.
> Add Rand::API + allow locking the RNG

- src/game_battlealgorithm.cpp
- src/game_battlealgorithm.h
- src/game_battler.cpp
This PR implements the negative attribute modifiers used in RPG Maker 2003 which allows for damage absorbing (e.g. dragons absorbing fire-type skills) and the possibility for skills to inflict states outside of battles (this makes the "Regenerationstrank" in "Vampires Dawn II" work outside of battles). By the way, negative attribute modifiers even allow for "funny" things like taking damage through healing skills (but you cannot get killed this way, 1 HP remain - tested with RPG_RT). This is probably my "most insane" PR so I expect many changes needed. Feedback is very appreciated!
> Battle 2k3: Add negative attribute modifiers and allow state infliction by skills outside of battles

- src/game_battlealgorithm.cpp
- src/state.cpp
This PR fixes #2327. If an actor gets the death state every already inflicted state with a priority of >= 91 no longer gets removed. Moreover skills and weapons adds states only if the target does not get killed by the damage and weapons can remove states in RPG Maker 2003 now.
> States: Allow states simultaneously with death

- src/game_battlealgorithm.cpp
If a target gets killed by an absorption skill, then only the HP are absorbed.
> Battle: Absorb only HP if the target gets killed by the absorption

- src/game_actor.cpp
- src/game_actor.h
- src/game_party.cpp
- src/game_party.h
- src/player.cpp
- src/player.h
- src/scene_battle.cpp
- src/scene_save.cpp
- src/scene_title.cpp
- src/scene_title.h
Depends on: https://github.com/EasyRPG/liblcf/pull/399
DynRPG Addresses
---------------------
| Address | Class | Function | Comment |
| -- | -- | -- | -- |
| 004B5330 | Actor | Reset | Resets all fields to default values |
| 004B6DD8 | Actor | SetTitle |
| 004B7004 | Actor | SetFace |
| 004B6D34 | Actor | SetName |
| 004B6E58 | Actor | GetCharset |
| 004B6E94 | Actor | GetCharsetId |
| 004B6EBC | Actor | GetCharsetTransparency |
| 004B6D88 | Actor | GetTitle |
| 004B6FDC | Actor | GetFaceId |
| 004B6FA0 | Actor | GetFaceName |
| 004B6CE4 | Actor | GetName |
| 004B5A48 | Actor | InitSaveChunk | Maps save chunk ids to fields
> Remove SaveActor Fixup and Setup - depends on liblcf #399

- CMakeLists.txt
As this is not maintainable anymore I try to rewrite this now.
Marked as WIP, have to do many tests first.
Also updated libretro-common. Full of high quality "resync" commits.
https://github.com/libretro/libretro-common/commits/master
> Rework libretro support in CMake

- src/game_actor.cpp
When an actor leveled up, the name of the actor was not displayed in the level up message. This is fixed by changing `data.name` into `GetName()`.
> Fix level up message

- src/scene_battle_rpg2k3.cpp
This PR implements the ATB active mode. This fixes bullet point 3 of #2175.
> Implement ATB active mode

- src/window_item.cpp
- src/window_selectable.cpp
- src/window_shopbuy.cpp
- src/window_shopparty.cpp
- src/window_skill.cpp
This PR and #2361 provides partial fixes for #2216 and #2264. In #2216 the things mentioned in the checkboxes 1, 3, 4 and 5 get fixed. One major change is the addition of an optional "halfwidthspace" parameter in the Window_Base which is set to true by default. Setting it to false makes the help window draw full width spaces which is required in the ActorTarget scene for the skill/item name and in the EndGame scene for the confirmation message (this is handled in part 2: #2361). The second major change is the addition of a gap between the menu items in multi-column selection windows (this is handled in this part).
More changes in this part:
- The item count/skill cost is now displayed on the right end of the selector in the Item and Skill windows.
- Endless scrolling has been implemented. …
> UI changes (1/2)

- src/platform.cpp
This allows building the EasyRPG core on Haiku.
> Allow Haiku build

- CMakeLists.txt
- Makefile.am
- src/dynrpg.cpp
- src/dynrpg.h
- src/dynrpg_easyrpg.cpp
- src/dynrpg_easyrpg.h
- src/game_interpreter.cpp
- src/game_interpreter.h
- src/player.cpp
- src/player.h
- src/scene_load.cpp
- src/scene_logo.cpp
- src/scene_map.cpp
- src/scene_map.h
- src/scene_save.cpp
- src/spriteset_map.cpp
- tests/dynrpg.cpp
- tests/test_mock_actor.h
This PR has the goal to upstream the DynRPG Parser.
This one was written as part of commisioned work in 2017/18 for the Deep8 game.
The main motivation for the submission is that this code bitrots and always updating to latest Player code is a huge task and this is imo useful code.
Right now I won't submit any plugins.
The only plugin worth upstreaming right now is the DynTextPlugin, all others are of terrible code quality or custom modifications for Deep8.
Obviously there is no plugin system in the Player, a "plugin" is just a class inheriting from DynRpgPlugin and registred in ``create_all_plugins``.
The code is not very invasive, I only added the following "Hook points":
- Comment Event (parses and executes DynRPG commands)
- Load
- Save
- Update (Spriteset graphics update)
- Reset …
> Upstream DynRpg Parser

- src/game_battlealgorithm.cpp
If an enemy uses a skill which targets all his allies then his hidden allies are no longer targeted anymore.
> Skills which targets allies ignore hidden targets

- src/game_interpreter_battle.cpp
In RPG_RT the ChangeMonsterHP event command has got a lethal flag which must be set to get the monster killed by the damage. Otherweise 1 HP remain.
> Add lethal flag in ChangeMonsterHP event command

- src/window_shopbuy.cpp
In #2313 the item prices were repositioned because the prices were too far left. This was supposed to be fixed but I forgot to recheck the positioning after #2313 was rebased for the menu cursor changes so the prices got too far right and cropped. This PR fixes this.
> Shop window: Fix item price position regression from #2313

- src/dynrpg.h
- src/game_map.cpp
- src/input.cpp
- src/input.h
- src/input_source.cpp
- src/input_source.h
- src/meta.cpp
- src/player.cpp
- src/player.h
- src/utils.cpp
- src/utils.h
A new input recording format that suites the regression test requirements. (Dependency: #2288)
The current format is just a bitfield of the pressed buttons everytime Input::Update is called. This is bad. Is enough for playback in Player but not for anything else.
The code still needs some polish but the new format looks like this. I already used it to successfully playback inputs in RPG_RT.
Format:
- 1st line: Header
- 2nd line: Version
- ...nth line: Everything else
Structure: It is a simple flatfile with a linecode (1st char is the ID, 2nd char is whitespace).
The line must be empty or start with a known linecode.
- H Header identifier <- On line 1
- V Version identifier <- On line 2
- N Game name
- D Recording date
- L LDBHash LMTHash <- CRC32 of LDB and LMT
- C Command line
- F …
> Input Recording v2

- src/scene_battle_rpg2k3.cpp
The enemy actions are processed first in RPG Maker 2003 battles now. This is crucial if the actor and the enemy have the same agility, in this case the enemy goes first. This fixes the first bullet point of #2147.
> Battle 2k3: Process enemy actions first

- CMakeLists.txt
- Makefile.am
- resources/easyrpg-player.6.adoc
- resources/unix/bash-completion/easyrpg-player
- src/algo.cpp
- src/algo.h
- src/autobattle.cpp
- src/autobattle.h
- src/cmdline_parser.cpp
- src/cmdline_parser.h
- src/config_param.h
- src/dynrpg.cpp
- src/game_actor.cpp
- src/game_battler.cpp
- src/game_config.cpp
- src/game_config.h
- src/player.cpp
- src/player.h
- src/scene_battle.cpp
- src/scene_battle.h
- src/scene_battle_rpg2k.cpp
- src/scene_battle_rpg2k3.cpp
- src/utils.cpp
- src/utils.h
- tests/algo.cpp
- tests/autobattle.cpp
- tests/utils.cpp
Fix: #1586 
This implements RPG_RT compatible auto battle. I've designed auto battle to support different auto battle algorithms. The end goal will be Player ships a few algos that you can choose from. Game developers customizing player could also add their own to the `AutoBattle::CreateAlgorithm` factory function.
This PR provides 3 algorithms:
* `RPG_RT` - RPG_RT compatible including bugs - this is the default
* `ATTACK` - RPG_RT, only physical attacks, bug fixes included
* `RPG_RT+` - RPG_RT with bug fixes - Also open to further improvements
For now I just added a `--autobattle-algo` command line parameter to select the algo, later this can probably be part of `Scene_Settings` etc.. Or maybe even a custom save chunk.
TODO
-------
DynRPG Addresses
-------------------
| Address | Class | …
> Implement auto battle

- src/game_battler.cpp
This PR fixes #2169.
If a battler gets a restriction state added by an event his battle action gets canceled.
> Cancel battle action if getting restriction state added by an event

- src/scene_battle_rpg2k.cpp
If a monster gets revived on RPG Maker 2000 his sprite was still invisible. This PR fixes this.
> Battle 2k: Fix monster sprite display on revival

- src/algo.cpp
- src/algo.h
- src/game_actor.cpp
- src/game_battlealgorithm.cpp
- src/game_battler.cpp
- src/game_party.cpp
- src/scene_battle.cpp
- src/scene_skill.cpp
- src/window_skill.cpp
Taken from RE disassembly, which is a bit messy and hard to read here. Needs to be tested to verify.
Tests
-----------
Skill Usability Tests
Item Usability Tests:
RPG_RT bugs ❗ 
--------------
See here: https://github.com/EasyRPG/Player/issues/1486#issuecomment-703376641
> Refactor Skill and Item usability and fix some incompatibilities

- src/scene_battle_rpg2k3.cpp
Depends on #2364
If the escape command is used in RPG Maker 2003 battles, the actors do a run away animation now. This fixes the second bullet point of #2147.
Fix #2147
> Battle 2k3: Add run away animation on escape

- src/async_handler.cpp
Forgot this one
Test case, created with new gencache from gencache PR:
https://easyrpg.org/play/pr1729/?game=yume_nikki_test
Title screen is renamed to "１２３４５①.xyz" and NASU contains some １s.
Also works because of version check:
https://easyrpg.org/play/pr1729/?game=yume_nikki
Master, fails to load assets in the new normalized one:
https://easyrpg.org/play/master/?game=yume_nikki_test
> AsyncHandler: Normalize file requests

- CMakeLists.txt
Hardcoded the completion dir to "${CMAKE_INSTALL_DATADIR}/bash-completion/completions" as suggested in #2396 otherwise this is a mess because the one returned by bash is an absolute directory which makes "install" fail without sudo...
For Unix I always install it, for all other platforms I depend on bash-completion being installed. This way one can also get the completion on Msys2 or macOS if this makes any sense ^^
> CMake: Install bash-completion and add man and doxygen status message

- CMakeLists.txt
- Makefile.am
- src/filefinder.cpp
- src/filefinder.h
- src/game_ineluki.cpp
- src/game_ineluki.h
- src/game_interpreter.cpp
- src/game_system.cpp
- src/game_system.h
- src/input.cpp
- src/input.h
- src/input_source.cpp
- src/input_source.h
- src/main_data.cpp
- src/main_data.h
- src/player.cpp
- src/scene_logo.cpp
- src/scene_title.cpp
- src/sdl2_ui.cpp
Can we agree on that this fixes #1181 and  #1367 even though there are more problems here?
Imo there can be new issues opened when they occur.
For #1181 not all ExecProgram calls are supported.
#1367 also has a patches exe to skip the title screen and load the first save, not related to Ineluki.
Limitations:
- ``ExecProgram`` not supported except for some specific programs that are HLE'ed
- ``MciProgram`` not supported
- Only alphanumeric and some special keys supported. This doesn't map properly to the key codes because Ineluki was written with a German keyboard in mind
- Cheat support does not reset when wrong key is pressed, needs some kind of input callback API, polling is ugly and highly inefficient here.
Problems:
- Mouse support needs ``--enable-mouse`` argument and this binds …
> Implement (most of) Ineluki Key Patch

- src/cache.cpp
This PR fixes an [issue mentioned in #1524](https://github.com/EasyRPG/Player/issues/1524#issuecomment-707856405). The change here is that `system2_name` is cleared after exiting a game. This is necessary because as soon as you enter a RPG Maker 2003 battle, the `system2_name` will be set and "locked". This means the `system2_name` is only being set if the `system2_name` is not set when you enter a RPG Maker 2003 battle which leads to the bug mentioned in the link. Unsetting `system2_name` on game exit fixes this.
> Unset system2_name on game exit

- resources/emscripten/emscripten-post.js
- resources/emscripten/emscripten-pre.js
- resources/emscripten/emscripten-shell.html
This pull requests adds buttons to the player shell for touch input capable devices. The following keyboard inputs are bound:
- Arrow up
- Arrow right
- Arrow down
- Arrow left
- Enter
- Escape
Thus, RM2k games are now playable on e.g. mobile devices. For RM2k3 games it get's trickier, since Shift and Numpad keys are possibly used as well. The web player is unusable on touch-based devices at the moment, so in my opinion this is a step up even if some keys are still missing. Do you think further buttons shall be added? Speaking for myself, I'd like to keep the layout as clean as possible. 
You may see and test it in action here: https://realtroll.de/player/?game=el-dorado
**Further features**:
- Buttons are highlighted when touched.
- Operating the d-pad while holding down also works. …
> Add touch input support for web shell

- src/game_event.cpp
This PR fixes #2424. The cause where an event with movement behavior set the random moves more than one tile at a move frequency below 8 is because the random stop count multiplier sometimes returns a straight zero which means that the event will not wait before the next move. Changing the divisor from 5 (int) to 5.0 (double) stops the random stop count multiplier returning zero, which fixes the issue mentioned above. Move frequency 8 (uninterrupted movement) is not affected by #2424 and this PR because in this case the stop count is always zero regardless of the stop count multiplier.
> Change random movement behavior

- CMakeLists.txt
- Makefile.am
- src/filefinder.cpp
- src/game_map.cpp
- src/meta.cpp
- src/meta.h
- src/player.cpp
- src/player.h
- src/scene_title.cpp
- src/scene_title.h
- src/translation.cpp
- src/translation.h
- src/window_selectable.cpp
- src/window_selectable.h
~~DO NOT MERGE: This is for discussion only.~~
~~This is a draft PR;~~ see Issue #797 for the initial discussion. Further code discussion will go here.
> Initial Work on Using Translations Via LcfTrans

- builds/android/app/src/main/AndroidManifest.xml
(for now, until Google forces us to use API30)
Fix #2415
> Android: Opt out of scoped storage nonsense

- src/game_actor.cpp
This PR fixes a regression in relation to savegame loading: If a RPG Maker 2003 savegame gets loaded then any actors with changed classes used the default EXP table instead of the EXP table of the current class. Adding the `MakeExpList()` function fixes this.
> Fix EXP table on actors with changed classes on savegame loading

- src/filefinder.cpp
Fix #2437
It was suspicious that only Ineluki was leaking and only in games that had no Ineluki support.
After moving around a few lines of code I got a stack-overflow error.
Guess istream operating on a non-valid filebuf was doing something undefined and corrupted memory. (so the leak was hiding something worse)
Added an explicit error check to fix this.
> Improve error handling of OpenInputStream/OpenOutputStream.

- builds/snap/snapcraft.yaml
Last weekend, I added the EasyRPG Player to the Snap Store (https://snapcraft.io/easyrpg-player) in order to make current EasyRPG Player easily available on Ubuntu and other Linux distributions.
For reference, this is the recipe used to build the snap package.
I'm planning to keep this package up-to-date in the future (since I really like the EasyRPG player) and backport all changes into this repository.
However, if you prefer to publish this under your own name/organisation, please ping me and I'll arrange a transfer of the Snap ownership (yes, it's a bit unfortunate that the Snap Store calls me "Developer" rather than "Publisher").
> Add snapcraft recipe

- src/game_character.cpp
The random movement behavior uses the current move direction instead of the current face direction now if the face direction is locked. This fixes the bug which disallows the event moving towards the direction he is facing if the face direction is locked and the
movement type is set random movement.
Fixes: #2436
> Fix random movement behavior on locked face direction

- src/game_system.h
- src/scene_save.cpp
The PR aims to fix the save count incrementing on game save. For some reason the [save count increment in liblcf](https://github.com/EasyRPG/liblcf/blob/master/src/lsd_reader.cpp#L37) is no longer working some commits after the 0.6.2 release.
Fixes: #2450
> Fix save count incrementing on game save

- src/scene_shop.cpp
- src/window_shopbuy.cpp
In RPG_RT the player is not able to buy more items of a kind if the current amount in the player inventory would exceed 99 after
the transaction. Moreover the corresponding shop menu item gets disabled if you have got 99 from that item.
> Limit max item count on buying based on current inventory

- src/directory_tree.cpp
- src/directory_tree.h
@rueter37 can you confirm?
- RTP lookup: Reordered the logic, fixes RTP assets not found when game lacks folder
- Saving: The save scene constructed a path that lacked the root path. This is fixed by accident in #2455 because the stream opening is now handled by the VFS, not by FileFinder.
> Filesystem [2.5/3]: Fix regressions

- src/decoder_midigeneric.cpp
Was a bug in the pitch calculation.
Note that the looping is not seemless at the end, I don't consider this a bug, is just really hard to get the timing right because the midi messages and Wildmidi are independent of each other (sample based as you know...). So this is a gigantic hack that kinda works.
For gapless playback use FluidLite or FmMidi.
> Fix WildMidi becoming stuck

- src/scene_order.cpp
- src/window_actorinfo.cpp
- src/window_equipstatus.cpp
- src/window_item.cpp
- src/window_skill.cpp
This PR makes the following hardcoded terms customizable:
- Item number separator
- Skill cost separator
- Equipment window arrow
- Status scene Name
- Status scene Class
- Status scene Title
- Status scene Condition
- Status scene Front
- Status scene Back
- Order scene Confirm
- Order scene Redo
Related: #2362
> Make some hardcoded terms customizable

- src/game_battler.cpp
- src/game_battler.h
- src/scene_equip.cpp
- src/window_shopparty.cpp
This PR handles some edge cases in the equip value window and the shop window: In the equip value window, if you have equipped items which makes stats go above 999 (or below 1), then the new stat value is displayed wrong if you change equipment which affects stats which are "out of bounds". The shop window comparison indicators are affected as well. This one is hard to explain so I come up with an example in "Vampires Dawn II" with this savegame: [Save01.zip](https://github.com/EasyRPG/Player/files/5939178/Save01.zip). Take a look at Valnar's equipment: The defense stat sums up to 1090 with the equipment and the game clamps it to 999, which is correct. But if you want to equip the "Spiegelring", which gives a penalty of 30 to all stats, the preview shows a defense stat of 969. The …
> Equip and shop window: Fix display errors on edge cases

- src/scene_debug.cpp
- src/scene_menu.cpp
This was fixed in #2214 but got a regression by #2210 (the latter set the gold setting back to 7 digits). This PR "re-fixes" the gold setting digit count. Moreover the gold value in the gold value window in the main menu scene gets updated upon leaving the debug scene now.
> Debug scene: Set gold setting back to 6 digits

- src/decoder_fluidsynth.cpp
- src/decoder_midigeneric.cpp
- src/game_system.cpp
by processing messages in smaller chunks. This reduces the resolution from 4-8ms to 1ms.
[dk.zip](https://github.com/EasyRPG/Player/files/6137688/dk.zip)
- dkbad.ogg - Upstream
- dkgood.ogg - This patch
- dkorig.ogg - RPG_RT (different soundfont)
> Improve MIDI playback accuracy

- src/scene_actortarget.cpp
- src/scene_battle_rpg2k3.cpp
- src/scene_end.cpp
- src/window_help.cpp
- src/window_help.h
Depends on #2399 because of the help window changes made there.
The target status window and end game window and the RPG Maker 2003 battle notifications use full width spaces instead of half width spaces in RPG_RT. This PR does these changes.
Fixes the bug reported of the end screen in #2264.
> Help window space width changes

- src/audio_sdl_mixer.cpp
- src/decoder_midigeneric.cpp
This one is interesting and very old :(.
The good news: This only affects SDL Mixer (not SDL) and in June 2016 we added the Audio Decoder classes which resulted in this codepath being almost never used anymore (except for Native MIDI playback).
First: ``Load_MUS_RW`` of SDL Mixer 1.2 _never_ closes handles. So for SDL1.2 we leak them since June 2014:
https://github.com/EasyRPG/Player/commit/a441cbc16e7ca9fee42a9527536d824e657deaef
(I will not fix this, we do not use Mixer 1.2 anywhere anymore)
For SDL2 the bug was introduced here in Feb 2016:
https://github.com/EasyRPG/Player/commit/4f2b8c9cb5beb109c65e7838f71b986c3e6a2892
The commit messages links to #710 which discusses a fix for a double free in the SDL ADPCM loader.
I also think that this comment here is wrong "The crash can be worked …
> SDL mixer: Do not leak handles

- resources/easyrpg-player.6.adoc
- src/game_ineluki.cpp
- src/game_interpreter.cpp
- src/game_interpreter.h
- src/game_interpreter_battle.cpp
- src/game_interpreter_battle.h
- src/player.cpp
- src/player.h
This stubs Maniac Patch commands in the interpreter and emits warnings.
Can help in finding problematic games.
Also added a ``--patch`` cli arg because there is currently no way to configure this stuff in emscripten.
> Stub Maniac Patch commands, add --patch cli arg

- src/scene_battle_rpg2k3.cpp
- src/sprite_actor.cpp
This PR fixes the death animation loop by playing death animations only once (RPG_RT does this as well) and normal enemy attacks do not longer wait for the battle animation (you will see the animation and the damage number at the same time like in RPG_RT). This affects RPG Maker 2003 battles.
Fixes: #1681
Fixes: #2335
> Fixes for NovemberJoy's remaining battle issues

- src/game_battler.cpp
- src/game_battler.h
- src/scene_battle_rpg2k3.cpp
- src/state.cpp
- src/state.h
- src/window_help.cpp
- src/window_help.h
This PR makes the help window in RPG Maker 2003 battles show more than one state if you target an enemy. Up to 5 states are shown ordered by priority.
Fixes: #2487
> Show more than one state in help window

- src/game_battlealgorithm.cpp
- src/game_enemy.h
This PR allows to set the unarmed battle animation of an enemy via the "maniac_unarmed_animation" setting in the LCF database. This fixes the first bullet point in #2497.
> Implement customizable enemy unarmed battle animation

- src/scene_file.cpp
- src/scene_file.h
- src/scene_skill.cpp
- src/scene_skill.h
- src/window_actorstatus.cpp
- src/window_actorstatus.h
- src/window_actortarget.cpp
- src/window_battlestatus.cpp
- src/window_menustatus.cpp
- src/window_menustatus.h
- src/window_message.cpp
- src/window_savefile.cpp
- src/window_selectable.cpp
- src/window_selectable.h
- src/window_skillstatus.cpp
- src/window_targetstatus.cpp
This PR does the following changes:
- Fix positioning of the item count/skill cost in the Targetstatus window.
- The stats in the skill selection scene are updated now if the user leaves the ActorTarget scene.
- Change spacing and add arrows in the Savegame window.
- Moved HP a bit to the right in the Battlestatus and Skillstatus window.
- Some labels have been realigned in the RPG Maker 2003 ActorInfo window.
- Faces have been moved left in the RPG Maker 2003 main menu window.
- Fix cropped selection boxes in message windows.
Fixes: #2216
Fixes: #1617
> UI changes (2/2)

- src/battle_message.cpp
- src/battle_message.h
- src/game_battlealgorithm.cpp
- src/scene_battle_rpg2k3.cpp
This PR makes the hardcoded terms in RPG Maker 2003 battle customizable and adds skill and item start messages in RPG Maker 2003 battles.
Fixes: #2362
> Make RPG Maker 2003 battle hardcoded terms customizable

- src/scene_battle_rpg2k3.cpp
- src/scene_battle_rpg2k3.h
- src/window_actorsp.cpp
- src/window_base.cpp
- src/window_base.h
- src/window_battlestatus.cpp
This PR does the following changes:
- The status window components have been rearranged to match the RPG_RT style.
- The transparent windows use an alpha of 160 instead of 128 now (tested with truecolor RPG_RT).
- In traditional style battles two bugs have been fixed: The SP window got printed over when a skill which costs SP has been used and the HP value didn't change its color if the HP reached critical or zero.
- In alternative style battles the gauges are now shown transparent if the window is opaque.
- The ally cursor is always drawn 40 pixels above the Y-Position of the battler.
- The enemy cursor is always drawn on the same height as the Y-Position of the enemy.
- Flipped actors use now the correct walking animation on escaping.
- The battle status window gets refreshed on …
> RPG Maker 2003 battle scene changes

- src/battle_animation.cpp
- src/battle_animation.h
- src/scene_battle_rpg2k3.cpp
- src/sprite_actor.cpp
- src/sprite_actor.h
- src/sprite_battler.h
- src/sprite_enemy.cpp
- src/sprite_enemy.h
This PR intends to do the following fixes:
- Placement of battlers: The battlers were placed wrong (too much distance between each other and partially and full off-screen placing starting with the third party member) if battle animation sprites were used. BattleCharset sprites are working fine.
- Displaying state afflictions: While BattleCharset sprites are showing its state afflictions at the beginning of the battle, the battle animation sprite battlers did so not until their first turn.
- Battle animation sprites are flipped now if the flip flag is set.
- BattleAnimation height: Battle animations are displayed on the right height if the target is a battle animation sprite.
> Battle 2k3: Battle animation sprites changes

- src/game_actor.cpp
This PR removes out of range items from actor equipment upon initialization of the actor.
Fixes: #2506
> Remove out of range items from equipment on actor initialization

- src/game_battlealgorithm.cpp
- src/game_battlealgorithm.h
- src/game_party.cpp
- src/scene_battle_rpg2k3.cpp
- src/scene_battle_rpg2k3.h
- src/sprite_actor.cpp
- src/sprite_actor.h
This PR implements the CBA movement in RPG Maker 2003 battles.
Fixes: #1277
Fixes: #1708
All movement related checkboxes in #1269 are handled by this PR.
Addressing review comments will be handled now in subsequent commits unless stated otherwise by the reviewers in order to avoid confusion.
> Battle 2k3: Add CBA movement

- src/async_handler.cpp
Some servers (e.g. CloudFront) will not respond properly if the file name contains `+`, such as `a+b.png`.
Therefore, URL encoding is helpful. (See also #894)
> URL encode +

- src/exe_reader.cpp
- src/exe_reader.h
- src/image_bmp.cpp
- src/image_bmp.h
... by doing a more sophisticated Bitmap header building. Grimms Hollow used 4 palette entries but we hardcoded it to 256.
I checked the sourcecode of wrestool (line 303) https://fossies.org/linux/icoutils/wrestool/extract.c to ensure that this logic is correct.
Reported via
https://community.easyrpg.org/t/retroarch-easyrpg-bug-grimms-hollow-missing-star-glyph/952
> Fix ExFont extraction in Grimm's Hollow

- src/async_handler.cpp
- src/player.cpp
Check for certain files in the index.json and create empty versions of them.
This ensures that RPG Maker 2003 English, DynRPG Patch and Maniacs Patch are detected properly.
------
Yeah I know this solution is kinda hacky (like many parts of the Web Player :P). But it works.
(This conflicts with the VFS branch but this change is so minimal that adopting it is no huge problem)
------
Before: https://easyrpg.org/play/master/?game=frozen_triggers
After: https://easyrpg.org/play/pr2520/?game=frozen_triggers
Fix #2526
> Emscripten: Improve engine and patch detection.

- src/game_battlealgorithm.cpp
- src/game_battlealgorithm.h
- src/scene_battle_rpg2k3.cpp
- src/scene_battle_rpg2k3.h
- src/sprite_weapon.cpp
- src/sprite_weapon.h
This PR adds CBA ranged weapons which target a single enemy and travel straight to it. The following checkboxes from #1269 are handled by it: "Use" checkbox, Dagger "fly in a straight line like a knife", Single Enemy and all Flying speed checkboxes.
> Battle 2k3: Add CBA single target ranged weapons

- src/window_equipstatus.cpp
This PR reserves 4 digits for the stat values in the equipment scene in RPG Maker 2003 games. RPG Maker 2000 games reserves 3 digits for the stat values. Tested and confirmed with RPG_RT, this is probably meant to handle the display of the stat values if they go beyond 999 because of positive states.
> Equipment scene: Use 4 digits for stat values in RPG Maker 2003

- .github/workflows/stable-compilation.yml
- CMakeLists.txt
- README.md
- src/string_view.h
Analogous to easyrpg/liblcf#422.
~~This shows a problem btw.: We are currently not compatible to libfmt version 5 (since StringView is in).~~ Solved.
<details>
<summary>log with 5.2.1</summary>
```log
2021-05-14T19:23:08.8410634Z [15/342] Building CXX object CMakeFiles/EasyRPG_Player.dir/src/autobattle.cpp.o
2021-05-14T19:23:08.8412921Z FAILED: CMakeFiles/EasyRPG_Player.dir/src/autobattle.cpp.o 
2021-05-14T19:23:08.8417399Z /usr/bin/c++  -DHAVE_FREETYPE=1 -DHAVE_HARFBUZZ=1 -DHAVE_LIBSNDFILE=1 -DHAVE_LIBSPEEXDSP=1 -DHAVE_MPG123=1 -DHAVE_OGGVORBIS=1 -DHAVE_OPUS=1 -DHAVE_WINE=1 -DSUPPORT_AUDIO=1 -DUSE_SDL=2 -DWANT_FMMIDI=1 -I../src -Ilib/liblcf/src -I../lib/liblcf/src -I../lib/liblcf/src/generated -isystem /usr/include/SDL2 -isystem /usr/include/pixman-1 -isystem /usr/include/freetype2 …
```
> Support CMake 3.10-3.20

- src/scene_battle_rpg2k3.cpp
If an actor triggers a victory condition while doing multiple attacks in a row, the actor did not move back if it was not the last attack of the sequence. This PR should fix this.
> Battle 2k3: Fix CBA move back on victory in case of multi-attack

- src/input_buttons.h
- src/input_buttons_desktop.cpp
- src/player.cpp
This PR rebinds the fast forward x10 function from the `F` and `NumPlus` keys to the `G` key on desktop versions. This feature was suggested by rpgguest4188 and supported by Fran[e]1 on March 8, 2021 according to the [IRC chatlog](https://easyrpg.org/irc/log/2021/2021-03-08.html#msg-19:22:33). I'm supporting this feature request myself, because it is much more convenient not having to use two hands for the fast forward x10 function. One more advantage is that the change stops interferences with some RPG Maker 2003 games which use the `NumPlus` key for certain events. This change doesn't interfere with the current input scheme as the `G` key is currently unused.
> Input: Rebind key used for fast forward x10 on desktop versions

- src/scene_battle_rpg2k3.cpp
- src/scene_battle_rpg2k3.h
This PR adds CBA ranged weapons which targets multiple enemies and travel straight to them. The following checkboxes from #1269 are handled by it: "Center" and "All Enemies" from the "Ranged Attack range" section. Not handled by this PR is the "Attack in Sequence" ranged attack range, because this one is plain insane.
> Battle 2k3: Add CBA multi target ranged weapons

- resources/easyrpg-player.6.adoc
- resources/unix/bash-completion/easyrpg-player
- src/filefinder_rtp.cpp
- src/filefinder_rtp.h
- src/player.cpp
This PR adds a command line option which allows the user to add a custom RTP path. This path will be used with highest precedence.
Fixes: #2448
> Add --rtp-path command line option

- builds/cmake/Modules/FindSDL2.cmake
- src/game_system.cpp
This PR changes the volume scaling method of the sound and music effects from linear to a [logarithmic scale](https://github.com/easyrpg/player/issues/2236#issuecomment-803439029). This aims to fix some sound volume issues reported in #2236.
Related: #2236
> Change sound volume scaling

- src/platform/switch/switch_ui.cpp
This was overlooked in #2454.
Latest libnx version finally removes the old enums. Before they have been aliased so this worked.
> switch: Rename missing ZL key for new hid api

- src/game_actor.cpp
- src/game_actor.h
- src/scene_equip.cpp
- src/window_equipitem.cpp
- tests/game_actor.cpp
This PR hides the equippable items in the equipment scene if the selected actor has the fixed equipment flag set (According to [this comment](https://github.com/easyrpg/player/issues/1790#issuecomment-878496741) the equipment scene should behave this way).
> Equipment scene: Do not show equippable items on fixed equipment

- src/cache.cpp
In the end this resulted in a hugher cache code change.
Now everything is cached at a single location, reducing code duplication.
Tested cases:
> Fix Issue 2561

- src/filesystem_zip.cpp
- src/filesystem_zip.h
- src/utils.h
1. The language flag (Bit 11) is now respected for UTF-8
This is used by all zip programs except the Windows "compressed folder"
2. All files that are not ASCII and do not have Bit 11 are considered for encoding detection
The encoding detection will be only needed for Windows "compressed folder"
3. When the file is considered for encoding it is also stored in Codepage 437
7zip uses CP437 for Western European filenames
Fix #2562
----------
Umlauts in folder names won't work properly when 7zip created the archive. But this doesn't really matter as game directories do not contain umlauts.
When an upper folder contains umlauts (e.g. the Game directory itself "Unterwegs in Düsterburg") this doesn't matter.
> Improve ZIP handling

- src/audio_decoder_midi.cpp
- src/game_interpreter_map.cpp
- src/game_system.cpp
- src/platform/linux/midiout_device_alsa.cpp
This PR workarounds a crash in Yume2kki by clamping values (this is incorrect but better than crashing).
Also it removes all the volume adjustment code. There are multiple issues in here, especially when combined with "Fade".
Another problem is that MIDI volume messages are already logarithmic, so they are adjusted twice making MIDI almost silent when volume != 100.
So the logic varies depending on whether it is MIDI or Sampled and we did not expect this when adding AdjustVolume... And seems nobody tested MIDI with volumes != 100 so this was completely missed in the Midi PR. (so also only 100 -> 0 fade was tested which worked as expected.)
Fixing this properly needs at least a day and I'm on vacation by next week so I cannot fix this properly now. But I also do not want this broken code …
> Improve ALSA, workaround issues

- src/decoder_xmp.cpp
- src/game_interpreter_map.cpp
meh
seekg(0) only works when the stream is not in a failed state... Forgot this detail :/ (this breaks the MP3 in the TestGame test, but Witch's Heart and IB title music work without this patch).
> XMP: Reset stream properly, newlib fixes

- CMakeLists.txt
- Makefile.am
- README.md
- resources/easyrpg-player.6.adoc
- resources/unix/bash-completion/easyrpg-player
- src/external/rang.hpp
- src/output.cpp
- src/output.h
- src/player.cpp
Also, allow the browser to filter/colorize the console log.
Needs testing on:
- ~~Wii (usbgecko, may be emulated by dolphin)~~
- ~~3DS (debug build or with 3dslink)~~
- ~~Switch (nxlink)~~
Obligatory screenshot:
> Colorize terminal output, if possible

- src/game_pictures.cpp
- src/output.cpp
- src/sprite_picture.cpp
Yume2kki 0.116 started to show a picture with no filename on the PC-wallpaper map.
No idea why they are doing this but when this is not filtered it unloads a black picture that is used for a background effect.
See #2519
@purupurupuruin
> ShowPicture: Support empty names

- src/battle_message.cpp
In RPG_RT the name of the user of the skill is not displayed in the second start message of a skill (unless you use placeholders, versions 1.60+ only). But in EasyRPG you receive an output like (tested with "Unterwegs in Düsterburg", Dankwart using the skill "Stossgebet"):
`Dankwart stimmt einen heiligen`
`DankwartChoral an`
Expected output:
`Dankwart stimmt einen heiligen`
`Choral an`
The name of the user of the skill is displayed twice while in RPG_RT the name is only displayed in the first message. This PR fixes this.
> Fix skill start second message

- src/window_message.cpp
Transparent message windows use an alpha of 160 now. This change was already made for the transparent battle windows but had been forgotten for the transparent message windows.
> Change message window transparency

- src/game_map.cpp
This PR adds support for special battle conditions (initative, back, surround and pincers) in random battle encounters in RPG Maker 2003 games. The probabilities are determined by the terrain settings.
> Add support for special battle conditions in random battle encounters

- src/game_player.cpp
This PR adds support for negative terrain damage. RPG_RT supports this and the RPG Maker 2003 documentation says that the
editor allows setting negative terrain damage values.
> Add support for negative terrain damage

- src/input.cpp
This PR decreases the interval between two menu cursor scrolls to 4 frames and increases the initial delay to 23 frames.
This is a partial fix for #2574. Still missing is the "smooth scrolling" stuff in the shop window.
> Change menu cursor scrolling speed

- src/scene_battle_rpg2k3.cpp
- src/sprite_battler.cpp
This PR changes the Z-Value calculation and recalculates the Z-Value on every CBA move frame in RPG Maker 2003 battles.
Fixes: #2539
> Change Z-Value calculation in RPG Maker 2003 battles

- src/scene_title.cpp
This PR makes the BGM no longer being restarted upon returning to the title screen from the load screen.
Fixes: #2589
> Fix BGM play upon returning to the title screen from load screen

- src/game_system.cpp
- src/game_system.h
- src/player.cpp
This PR clears the current_music value when starting a new game. This fixes issue #2411.
Fixes: #2411
> Clear current_music on starting a new game (Fix issue #2411)

- configure.ac
needed for `vorbis_comment_query` (since #2618).
Found by AUR users: [1](https://aur.archlinux.org/packages/easyrpg-player/#comment-825300), [2](https://aur.archlinux.org/packages/easyrpg-player-git/#comment-825330). Reason is, Arch uses `--as-needed` in `LDFLAGS` by default.
> autoconf: add vorbis library

- src/player.cpp
RPG Maker 2003 English release is always "MajorUpdated"
In the command line handler the behaviour was already correct.
Fix #2531
> RPG Maker 2003 English release is always "MajorUpdated" (#2531)

- src/game_interpreter.cpp
Fix #2546
-----
Discussion that the other code was already fine:
I'm pretty sure the KeyInputProc code was already based on reverse engeniered code.
(code pasted here https://github.com/EasyRPG/Player/issues/2546#issuecomment-917435613)
- RPG2k compat mode is executed for cmd_len <= 10 and cmd_len > 9. So the only option is "10" here making our "param_size != 10" check correct (also no support for "all directions here", correct)
- Between legacy 2k3 and updated 2k3 the parameter 5, 6, 7, 8 are the same. this is unified in our code
- When param_size > 10, shift and arrow keys are enabled for updated (correct)
- When param_size > 10, "all direction" is unavailable (Correct)
- **Fixed**: For legacy "all directions" is always available, this param_size > 10 check broke it
> Fix broken check for "All directions" for RPG2k3 <1.05

- src/async_op.h
- src/game_interpreter.cpp
- src/game_interpreter.h
- src/game_pictures.cpp
- src/game_pictures.h
- src/output.cpp
- src/player.cpp
- src/scene_map.cpp
- src/scene_save.cpp
- src/scene_save.h
- src/utils.cpp
- src/utils.h
This implements the imo most useful commands of the Maniac Patch (except for String picture, this is also pretty cool!)
_Still have to do careful testing of this again. There shouldn't be regressions as the code is usually in ManiacPatch checks._
Discussion:
This does a Async Load (yields the interpreter), in Maniac it loads directly, this is incompatible with how our code works.
The parameter for checking whether the save exists is ignored, in RPG_RT loading a non-existant save simply crashes.
This does a Async save (Yields the interpreter), in Maniac this saves directly resulting in saving at an undefined state because there is stuff in temporaries. So yielding here is safer.
In Maniac this is implemented by setting the arguments (or not if the pic exists) and then doing a jump just …
> Maniac Patch: Implement Load, Save, SaveInfo and Mouse input

- src/game_interpreter_battle.cpp
- src/game_interpreter_battle.h
- src/scene_battle_rpg2k.cpp
- src/scene_battle_rpg2k3.cpp
- src/scene_battle_rpg2k3.h
fmatthew missed something ;) (well partially, there was a FIXME in the code but only for ``command_actor``)
When evaluating conditions RPG Maker 2003 passes the current active battler. This battler is evaluated for the page conditions:
- Battle Command: checked battler == current_battler (NULL-check missing because it makes no sense here)
- Actor / Enemy turn: battler is NULL (battle start) or checked battler == current battler
Test cases:
- Battle Command: #2535 . A page has run condition "Hero uses Attack". When the enemy attacks this page was activated again. This is _wrong_. It is only activated when the hero acts. **Works now**
- Actor / Enemy turn: Create two pages, one with "Actor 1 Turn Count x1" and one with "Enemy 1 Turn Count x1" (= run page everytime)
- When battle starts: …
> Battle 2k3: Consider acting battler for certain page conditions

- src/player.cpp
- src/utils.h
- Additional to title_name and system_name the cursor_se and the title_music are checked.
- title_name and title_music are skipped when their is no title screen
This is good enough for detecting the proper encoding of .flow (English translation).
Fix #2554
Fix #2604
needs https://github.com/EasyRPG/liblcf/pull/435
> Fix and improve encoding detection

- src/graphics.cpp
- src/scene.cpp
- src/scene.h
- src/scene_map.cpp
- src/scene_map.h
- src/scene_title.cpp
- src/scene_title.h
Invoke Scene::Suspend after the transition out before transfering drawables
There was no way before for scenes to execute any cleanup code here.
For cleanup before transitioning Scene::TransitionOut can be overwritten.
Only two classes used Suspend:
- Scene_Map to disable the BGM, this was moved to TransitionOut
- Scene_Shop for a callback that notifies if anything was bought. Here it does not matter.
Fix #2337
> Fix title graphic disappearing too early (#2337)

- src/scene_file.cpp
While the scroll speed in the menus had been fixed, the same fix unfortunately slowed down the scroll speed in the save/load scene. This PR fixes this.
> Fix save/load scene scroll speed regression

- CMakeLists.txt
- README.md
- builds/android/gradle.properties
- builds/release-helper.sh
- builds/switch/Makefile
- builds/wii/meta.xml
- configure.ac
- resources/osx/Info.plist
- resources/player.rc
- resources/psvita/template.xml
- src/filefinder_rtp.cpp
- src/version.h
- tests/doctest.h
Imo we should add the "relevant for maintainers" release notes to the github release page and for the rest link to the blog post.
Suggested release notes:
```
For full release notes see: https://blog.easyrpg.org/2021/10/easyrpg-player-0-7-0-sword
Do not forget to **update liblcf to 0.7**.
This is the **last version supporting C++14**. Right after this release we will move to C++17. The compiler support is good enough by now.
**libfmt** is a new **required** dependency that makes it much easier for us to fulfill all our text formatting needs. Every ancient version down to 5.0 will work. (#2181)
**SDL2_mixer** was **removed** and is not supported anymore because the API was too limited for our audio requirements.
**libxmp** (a **recommended** dependency for playing MOD/Tracker files) …
```
> Release 0.7.0

- src/baseui.cpp
This PR sets the frame_limit explicitly to zero if the fps_limit is set to zero to avoid a division by zero.
Fixes: #2679
> Set frame_limit to zero if fps_limit is set to zero

- src/bitmap.cpp
Rotation cannot be done with OP_SRC as it renders a black rectangle.
See also #1077 (surprisingly this issue did not regress)
Fix #2667
> Fix missing alpha when a picture is rotating and the screen fades out

- src/filesystem.cpp
- src/translation.cpp
The Meta.ini file in the translations has never been read because of path not being complete. This PR fixes this.
> Translations: Fix reading of Meta.ini

- src/scene_title.cpp
This PR makes the help window in the translation selection scene check the transparency setting of the database if RM2k3E is used.
Fixes: #2690
> Translation selection: Make help window respect transparency setting

- src/game_system.cpp
This PR extends the allowed tempo range for BGMs and SEs from 50-200% to 10-400%.
Fixes: #2590
> Extend allowed tempo range for BGMs and SEs

- src/game_actor.cpp
The shield is unequipped now upon equipping a two-handed weapon and vice versa. While the unequip check worked on actors which can wield two weapons, it did not work on actors which can wield a weapon and a shield.
> Unequip shield on equipping a two-handed weapon and vice versa

- src/scene_equip.cpp
- src/window_shopparty.cpp
This PR should make the stat preview work correctly now even with non-weapon equipment which has the "two handed" flag set.
> Fix stat preview with "two handed" non-weapon equipment

- src/game_screen.cpp
This PR makes sets the `battleanim_active` flag to false on map change. This change should avoid RPG_RT crashes with savegames made with EasyRPG which have an active battle animation which targets an invalid event because of a map change.
Fixes: #2597
> Set battleanim_active to false on map change

- src/game_map.cpp
Fixes a stuck Player in Yume2kki when teleporting from Christmas World to Exhibition.
The teleport target is out-of-bounds (maybe because the map was resized later) preventing leaving the tile.
This is not fully bug compatible to RPG_RT. Assuming the Y-Coordinate is out-of-bounds: When moving
left or right the invalid Y will stay in RPG_RT preventing events from being triggered, but we wrap it
inbounds after the first move.
Fix #2716
> Allow leaving tiles that are out-of-bounds

- src/async_op.h
- src/game_interpreter.cpp
- src/game_map.cpp
- src/game_map.h
- src/game_system.cpp
- src/scene_map.cpp
- src/spriteset_map.cpp
- src/spriteset_map.h
Panorama positioning depends on width and height of the panorama. 
In some cases (not scrolling or looping) the position is reset after loading the panorama.
Here was the bug: Multiple ChangePanorama commands overwrote the reset indicator.
Added a async yield op to the event and made the panorama image important to ensure that the image is loaded.
Refactored Spriteset_Map to prevent deletion as the panorama change is otherwise a dangling reference.
Fix #2195
> Yume2kki: Fix Panorama handling

- src/platform/switch/switch_ui.cpp
- src/platform/switch/switch_ui.h
- src/player.cpp
- Lock closing to allow cleanup
- manually pause and resume on focus lost
- do not check for docking/undocking anymore, use hook
- log firmware version
Trying to fix the first issue from the forum post: https://community.easyrpg.org/t/easy-rpg-switch-port-0-7/1038
> Switch: Change Applet handling

- src/font.cpp
As mentioned in https://github.com/EasyRPG/Player/issues/2724, this is not a perfect solution, but do solve the problem.
(Anyway it costs no side effect for other encoding) Note that some punctuations don't exist in WQY, so we still need to check Mincho when there is no code in WQY.
Tested passed in [webplayer](https://easyrpg.org/player/guide/webplayer/).
Fix #2724
> Raise the priority of WQY when encoding is Chinese Simplified.

- src/game_interpreter.cpp
- src/game_interpreter.h
_This will be the final Maniac Patch-patch for 0.7_. I still have _ControlVarArray_ and some stuff for _ControlVariable_ to offer but this stuff will be half-broken because the variable range is wrong (Maniac has 32bit range without overflow), so makes no sense to add this when calculation will get stuck at 9999999.
-----------
I still have to carefully recheck all the loop commands. There could be off-by-1 errors I missed :)
> Maniac: Implement Loop and Break Loop enhancements

- src/algo.cpp
- src/game_player.cpp
- src/scene_battle_rpg2k.cpp
- src/scene_battle_rpg2k.h
This PR enables the usage of the RPG Maker 2003 battle command feature in RPG Maker 2003 games, even if the RPG Maker 2000 battle system feature is enabled.
> Support RPG Maker 2003 battle commands in RPG Maker 2000 battles

- src/filesystem_zip.cpp
Can now directly launch broken archives with \\-delimiter and Shift-JIS in Player without using unar.
Beautiful <3
> Zip FS: Support ZIP archives created by broken archivers

- resources/emscripten/emscripten-shell.html
- src/sdl2_ui.cpp
- src/sdl2_ui.h
This PR adds _very_ rudimentary Web Gamepad support.
Some notes:
- It seems like Joystick support was broken because `SDL_JoystickOpen(0)` at init time doesn't work when running in emscripten.
- I haven't touched any of the button maps, but it's not great right now. The dpad is completely nonfunctional, and the X button on the Xbox is mapped to arrow down, Y is Esc, B is Enter, and so on. The left stick does work as expected though. I think we'll need to have a special default button map for when `#ifdef EMSCRIPTEN`...
- If there's any gamepad connected and active in the browser window, the on-screen touch controls will immediately disappear. They should reappear when the gamepad disconnects. I moved the logic for displaying the touch controls into JS since the logic is now more …
> Emscripten: basic Web Gamepad support

- src/decoder_mpg123.cpp
Untested, lets see what Jenkins says...
> Windows: Support mpg123 1.28.1 and newer

- src/async_op.h
- src/game_interpreter.cpp
- src/game_pictures.cpp
- src/game_pictures.h
One of the more basic commands.
Can be used to query picture positions.
Tested and confirmed working.
> Maniac Patch: Implement GetPictureInfo

- src/game_interpreter.cpp
- src/game_variables.cpp
- src/game_variables.h
- tests/variables.cpp
This adds the command "Control Var Array". This command allows to do vectorized operations (e.g. "Add Variable 1-5 to Variables 10-15).
Additionally added bit operations to "Control Variable"
> Maniac Patch: Add ControlVarArray and Bit Ops for Variables

- src/game_variables.cpp
- src/player.cpp
- src/window_numberinput.cpp
- src/window_numberinput.h
- tests/variables.cpp
When variables overflow the value is now correctly clamped.
Mostly required by Maniac Patch because it uses the entire integer range but also broke with multiply in normal maker (see fixed issue).
Also implemented the "Input numbers via numpad" extension from newer Maniac versions.
Fix #2650
> Proper overflow handling

- src/game_interpreter.cpp
- src/game_pictures.cpp
- src/game_pictures.h
- src/sprite_picture.cpp
Okay kinda clickbait. Origin is not supported yet because I cannot figure out some rounding errors.
But it will come this week ;)
Wanted an issue number already for the metabug (#1818)
> Maniac Pictures: Support Origin, Fixed Angle and Frames for duration

- src/algo.cpp
- src/algo.h
- src/autobattle.cpp
- src/autobattle.h
- src/game_battlealgorithm.cpp
- src/game_battlealgorithm.h
- src/game_battler.cpp
- src/scene_battle_rpg2k3.cpp
- tests/algo.cpp
This PR adds the "easyrpg_affected_by_row_modifiers" attribute for skills. If this attribute is set, then the damage and hit rate is affected by row modifiers. This feature is needed if you want to add skills which should act like normal physical attacks in RPG Maker 2003 games.
> Add "easyrpg_affected_by_row_modifiers" attribute for skills

- src/baseui.cpp
- src/baseui.h
- src/game_config.cpp
- src/game_config.h
- src/sdl2_ui.cpp
- src/sdl2_ui.h
Code is based on code from SDL2. I extracted it as this gives more flexibility.
Fix #720
Fix #1366
-----
DONE: ~~Not ready yet. Also want to add a 3rd scaling mode while at it:~~
~~When the viewport is a fractional then scale one higher than would fit and then do a bilinear downscale to the viewport size.~~
(Can somebody find the issue number where this was mentioned???)
> SDL2: Add integer scaling support

- src/audio_decoder_base.h
- src/audio_resampler.cpp
- src/audio_resampler.h
I "only" needed 4 hours to come up with this solution. Well, after debugging for 4 hours I finally understood how our resampler works. I was also able to simplify the code alot until I discovered where the crackles are coming from: The wrapped_decoder is not looping. 
Refactoring the resampler to get it merged with the decoder will take a while, so I provide here a workaround to get rid of the crackles for now.
------------
For a smooth looping without gaps the wrapped_decoder must be able to loop.
The solution is more of a hack / short-term solution:
All loop-related methods were forwarded to the wrapped_decoder
The better, more complex solution is refactoring the code by merging Decoder+Resampler
to give more control about the decoding process without all this ugly forwarding.
Fix #2666
> Resampler: Fix crackles when looping the audio

- src/scene_battle_rpg2k3.cpp
This PR no longer allows canceling in the command menu if the RPG Maker 2003 battle type is traditional. This fixes the flicker mentioned in issue #2775.
> Disallow canceling in command menu in traditional type battles

- src/window_base.cpp
This PR makes the number of level digits dependent on the global maximum level setting instead of the maximum level of the actor. This fixes a small optical issue with the level indent if you have actors in the party which can reach level 100 or greater and actors which can reach at most level 99.
> Make the number of level digits dependent on the global maximum level

- src/game_interpreter.cpp
- src/player.cpp
Reported by Soeufans, thanks.
Forgot a size check in Move Picture event. Show picture is unaffected because the code is structured different.
Also disabled the warning on startup as there is enough maniac support by now to consider it usable.
> Maniac Patch: Fix out of bounds read in Move Picture

- bench/rtp.cpp
- src/bitmap.cpp
- src/bitmap.h
- src/opacity.h
- src/weather.cpp
Better play some games that use lots of Tone and Saturation to ensure I did not miss an edge case :)
Using premultiplied alpha also fixed a bug in the weather tone blit. The problem is gone, so removed that special case.
As discussed in #2755 wanted to do some benchmarks.
Results:
tl;dr: About the same speed as before.
Surprisingly blitting premultiplied which has an extra multiply is faster than the non-multiplied version.
Though this appears to depend on branch prediction and compiler because when I restructure the code slightly then 1 Bit becomes faster BUT this also depends on the image so the restructure does not always work and makes other cases slower :D
Just hope that some embedded platforms will profit more from this. x86 multiplies fast enough it seems.
------
Checking …
> Use premultiplied alpha for Tone Blit

- src/filesystem_stream.cpp
- src/filesystem_stream.h
- src/filesystem_zip.cpp
- src/filesystem_zip.h
The Zip FS cached all the decompressed files in memory.
This is very wasteful in terms of RAM making this unusable on many devices.
In general a compressed read + decompress will be still faster than a uncompressed read because IO is much slower than CPU.
Also in most cases the decompress only happens once. We already have caching for assets. BGM is also never decompressed until the track changes.
> ZipFs: Disable built-in cache

- CMakeLists.txt
- src/platform/psvita/psp2_ui.cpp
This removes the shader support because this depends on 7 year old,
unmantained code.
If you want to readd it consider using libvita2d_ext or wait until the Player
receives a OpenGL renderer in 10 years ;)
> PS Vita: Update to latest libvita2d

- bench/bitmap.cpp
- bench/rtp.cpp
- src/directory_tree.cpp
- src/directory_tree.h
- src/filefinder_rtp.cpp
- src/rtp.cpp
- src/rtp.h
- tests/filesystem.cpp
- tests/rtp.cpp
As observed by @BlisterB and @carstene1ns the RTP detection is incredible slow on Android but even on other systems we are wasting time in the detector.
Added three layers of _speed_ to make the RTP detection on startup faster:
1. When the RTP folder is empty the folder is considered invalid and not scanned (Android will hit this one)
2. When not empty the RTP-type-scan will abort when for a certain RTP type there are 10 missing files (this makes RTP2k detect ``30%`` faster, RTP2k3 detect ``59%`` faster).
3. When a folder is missing this is cached making the lookup much faster  because the filesystem is not hit again (this makes the ``RTP::Detect`` Unit Test where almost all folders are missing and "abort after 10 misses" is disabled ``20%`` faster). On slow systems with shitty IPC (hello …
> Improve DirectoryTree & FileFinder_RTP performance

- src/directory_tree.cpp
- src/dynrpg.cpp
- src/game_character.cpp
- src/game_map.cpp
- src/game_map.h
- src/scene_map.cpp
- src/translation.cpp
This fixes various bugs encountered over the last weeks that are almost all one-line fixes.
- record-input was found by makodeoz on Discord
- facing by @TrunXGit (please retest!)
- the others were found by Jan (Deep 8) and are backported from the Deep8 fork
> Various minor bugfixes

- src/drawable.cpp
- src/drawable.h
- src/drawable_list.cpp
- src/drawable_list.h
- src/game_character.cpp
- src/game_character.h
- src/game_event.cpp
- src/game_event.h
- src/game_player.cpp
- src/game_player.h
- src/graphics.cpp
- src/graphics.h
- src/sprite_battler.cpp
- src/sprite_picture.cpp
- src/tilemap_layer.cpp
- src/tilemap_layer.h
- src/transition.cpp
- tests/drawable_list.cpp
- tests/game_character.cpp
Found in Il Mito. Reported by mokodeoz. Thanks!
------
This changes the Z-layer value from int32_t to uint64_t.
For correct render order of events it is necessary to put in Y, X and the ID in the Z value and this simply does not fit in ~28 Bit properly.
Now Z-Value is:
- Upper 8 bit = Layer
- Next 8 Bit = Unused yet :)
- Next 48 Bit: Layer specific, Event uses 16 Bit Y, 16 Bit X and 16 Bit ID.
It is possible that I missed a Z variable somewhere which will then overflow. So please test some games if you find rendering order bugs.
------
Performace impact: Likely a non-relevant amount of nanoseconds slower on 32 bit hardware
Also optimized the Tile cache structure, is now 4 byte instead of 8.
> Use 64 bit z-layer

- src/audio_decoder_midi.cpp
- src/audio_midi.h
- src/decoder_fmmidi.cpp
- src/decoder_fmmidi.h
- src/platform/libretro/midiout_device.cpp
- src/platform/libretro/midiout_device.h
- src/platform/linux/midiout_device_alsa.cpp
- src/platform/linux/midiout_device_alsa.h
- src/platform/macos/midiout_device_coreaudio.cpp
- src/platform/macos/midiout_device_coreaudio.h
- src/platform/windows/midiout_device_win32.cpp
- src/platform/windows/midiout_device_win32.h
This is the same RPG_RT does and was already used by some of the Midi implementations.
Was already working everywhere except on Windows because this is the documented way to reset a Midi device.
Fix #2732
---------
About midiOutReset moved to destructor: This function is only called by RPG_RT when shutting down, not when switching files.
About FmMidi change: reset() and GM sysex on invoke the same function.
> Midi: Properly reset Midi by sending SysEx GM On

- src/game_interpreter.cpp
Small oversight from the refactor.
Modulo operation is available in normal RPG_RT already.
> Control Variables: Enable modulo in vanilla RPG_RT

- CMakeLists.txt
Happens with newer versions of emscripten
> Emscripten: Prevent pulling in bundled SDL headers that break the build

- src/bitmap.cpp
- src/bitmap.h
- src/directory_tree.cpp
- src/directory_tree.h
- src/filefinder.cpp
- src/filefinder.h
- src/filefinder_rtp.cpp
- src/filefinder_rtp.h
- src/filesystem.cpp
- src/filesystem.h
- src/font.cpp
- src/font.h
- src/fps_overlay.cpp
- src/game_message.cpp
- src/game_message.h
- src/message_overlay.cpp
- src/output.cpp
- src/player.cpp
- src/player.h
- src/scene_logo.cpp
- src/text.cpp
- src/text.h
- src/translation.cpp
- src/window_help.cpp
- src/window_message.cpp
- tests/font.cpp
- tests/text.cpp
This adds experimental freetype rendering support.
Still marked as draft as I must test some stuff. But the basic rendering works.
When fonts are provided as "Font/Font.ttf" (gothic) or "Font/Font2.ttf" (mincho) these fonts are used instead of the built-in. Should also work for the web player and translations can provide custom fonts.
Also supports complex stuff like Thai (not using Harfbuzz though as Freetype is good enough to render Thai properly).
~~TODO: Testing testing testing. Fallback logic?~~
Fix #2857
> Add freetype font rendering

- src/game_map.h
- src/game_player.cpp
- src/options.h
- src/scene_debug.cpp
- src/scene_end.cpp
- src/scene_equip.cpp
- src/scene_file.cpp
- src/scene_item.cpp
- src/scene_logo.cpp
- src/scene_map.cpp
- src/scene_menu.cpp
- src/scene_name.cpp
- src/scene_order.cpp
- src/scene_shop.cpp
- src/scene_skill.cpp
- src/scene_status.cpp
- src/window_equipitem.cpp
- src/window_equipitem.h
- src/window_message.cpp
This PR make some element "responsive" by not being dependant of a fixed resolution : 
- Startup scene : The EasyRPG logo is now centered
- Loading/Saving scene : the bottom border dans the cursor are placed at the bottom of the screen, no matter the resolution
------------------
Just to track the status, not the tasklist of this PR :)
> Make UI/Map compatible with Custom Resolutions 

- bench/font.cpp
- builds/cmake/Modules/FindHarfbuzz.cmake
- src/async_handler.cpp
- src/bitmap.cpp
- src/font.cpp
- src/font.h
- src/fps_overlay.cpp
- src/game_message.cpp
- src/scene_battle_rpg2k3.cpp
- src/scene_end.cpp
- src/string_view.h
- src/text.cpp
- src/text.h
- src/utils.cpp
- src/window_base.cpp
- src/window_command.cpp
- src/window_command_horizontal.cpp
- src/window_equipstatus.cpp
- src/window_help.cpp
- src/window_keyboard.cpp
- src/window_message.cpp
- src/window_message.h
- src/window_name.cpp
- src/window_savefile.cpp
- src/window_settings.cpp
- tests/font.cpp
- tests/utf.cpp
~~WIP PR to test harfbuzz shaping support :)~~
First I refactored the ``Font`` and ``Text`` Api: ``Font`` is now only responsible for rendering single glyphs (``char32_t``). For any high level usage the ``Text`` Api must be used.
The exception to "single glyph" is the shaping Api which takes a ``u32string`` because this conditionally converts codepoints depending on the shaping rules. When Harfbuzz is enabled the ``Text`` Api will automatically handle this.
A special case is ``Window_Message``. It renders glyph-by-glyph instead of all-in-one-go. This requires usage of the low level ``Font`` Api directly because the shaping information must be known.
> Add Harfbuzz support

- .gitignore
- src/game_interpreter.cpp
- src/game_interpreter.h
Because Jetrotal uses them in the dev simulator :P
> Maniac: BGM/SE/Wait enhancements

- resources/emscripten/emscripten-shell.html
- src/platform/sdl/sdl2_ui.cpp
- src/player.cpp
This removes the media-queries and instead uses the entire available area.
Our SDL2 code handles it internally now since the settings PR
for best comparison I recommend opening https://easyrpg.org/play/master and https://easyrpg.org/play/pr2900 on a phone or any other very high dpi display and toggle fullscreen. The difference is extreme.
> Emscripten viewport

- src/scene_save.cpp
When a translation is loaded always store in Unicode to prevent data loss
Something for @Mimigris
Fix #2887
----------
It is still possible to lose data but this cannot be really avoided without becoming incompatible to RPG_RT:
1. Activate a translation
2. Save the game while some event with messages etc. is loaded (or custom hero name etc.)
3. Change back to native language setting
4. Load the previous savegame and save it again
5. The custom hero name will be lost because "native language" always writes in the game encoding, not in utf-8
The typical use case will be that they stay on the same translation so this will be usually safe
> Use Unicode saves when translations are loaded

- src/game_pictures.cpp
- src/game_pictures.h
- src/game_windows.cpp
Reported yesterday by @mimigris and @florianessl
Thanks!
> Bugfix: When loading a save do not recreate detached StringPictures

- src/exe_reader.cpp
- src/exe_reader.h
- src/filefinder.cpp
- src/player.cpp
wrote 90% of this code a year ago and just remembered that it exists.
Finished it. Please give it a test.
Useless for emscripten obviously.
The check is quite defensive so when there is anything that looks off the engine is reported as "None" and it uses the old check.
see ``FileInfo::GetEngineType()`` for the logic. Not explaining this again.
Also disabled the "heuristic" to detect 2k3 in the old codepath because this caused alot of problems because it only fixed .flow but broke many other games.
Detection results for some exes:
```
Debug: !! rpg2000/RPG_RT.2000.1.0.5.0.dons.eng.exe
Debug: version= logos=3 i386=true easyrpg=false
Debug: !! rpg2000/RPG_RT.2000.1.0.7.0.dons.eng.exe
Debug: version= logos=3 i386=true easyrpg=false
Debug: !! rpg2000/RPG_RT.2000.1.0.9.0.dons.eng.exe
Debug: …
```
> Use more Exe information for the version detection

- src/game_config_game.cpp
- src/game_map.cpp
- src/game_map.h
- src/spriteset_map.cpp
easyrpg.ini was created due to a copy paste error. Is fixed.
Added some fake resolution handling to panoramas. Makes them a bit more usable in legacy mode but complex stuff that relies on parallax mapping and where the screen scroll matters (e.g. this maid room in Yume2kki) are still broken and will likely stay broken.
> Add some Panorama legacy mode support

- src/font.cpp
The fonts appear to have some kind of shaping information but Harfbuzz always inserts a width of 0 and "glyph not found".
In that case the size of from FreeType is now inserted to fix the size calculation.
-----------------
This fixes the underlying bug however it is likely safer to not run FON fonts through Harfbuzz as they are usually a half-broken mess.
So instead I also disabled shaping for anything that is not a TrueType/OpenType font.
The first commit will be still useful in case there are any semi-broken TrueType fonts. Bet there are some...
> Font fixes

- builds/android/metadata/de-DE/full_description.txt
- builds/android/metadata/de-DE/short_description.txt
- builds/android/metadata/en-US/full_description.txt
- builds/android/metadata/en-US/short_description.txt
- builds/android/metadata/en-US/title.txt
- builds/android/metadata/ja-JP/title.txt
- builds/android/metadata/zh-CN/title.txt
- builds/android/metadata/zh-TW/title.txt
The app is now called "EasyRPG Player" to reduce confusion.
Short description:
> Play your RPG Maker 2000 and 2003 games everywhere.
Removed the "with EasyRPG Player." part. Is not really needed.
Long description (Old):
> EasyRPG Player is a program that allows to play games created with RPG Maker 2000 and RPG Maker 2003 (the newer RPG engines like XP, VX, VX Ace and MV are not supported).
>
> Homepage: https://easyrpg.org/
> Changelog: https://blog.easyrpg.org/
> Bug reports: https://github.com/EasyRPG/Player/issues/
> 
> This app is not affiliated with Kadokawa Corporation.
Long description (New):
> With EasyRPG Player you can play games created with RPG Maker 2000 and RPG Maker 2003. Newer engines such as XP, VX, MV and MZ are not supported.
>
> EasyRPG Player is not an editor. You …
> Android: Update app store text

- builds/android/app/src/main/java/org/easyrpg/player/Helper.java
- builds/android/app/src/main/java/org/easyrpg/player/InitActivity.java
- builds/android/app/src/main/java/org/easyrpg/player/game_browser/GameBrowserActivity.java
- builds/android/app/src/main/java/org/easyrpg/player/game_browser/GameBrowserHelper.java
- builds/android/app/src/main/java/org/easyrpg/player/settings/SettingsGamesFolderActivity.java
- builds/android/app/src/main/res/layout/activity_init.xml
- builds/android/app/src/main/res/layout/activity_settings_easyrpg_folders.xml
- builds/android/app/src/main/res/layout/browser_error_panel.xml
- builds/android/app/src/main/res/values/strings.xml
- src/platform/android/filesystem_saf.cpp
Most common problems are now detected and the user is notified.
Related #2943 which has more suggestions for better UX but I have no time right now to embed images etc.
**I invite all of you to test it.**
First start:
Errors detected:
Generic error when a quick sanity check (create a file and read it) fails:
The Download folder already hits the sanity check but here a better message for it:
This can cause false-positives on some systems (user is a messy :P) but is imo a good idea. It will trigger when the folder contains more than 3 regular files except ".nomedia" (folders do not count).
When no games found afterwards:
> Improve Android SAF UX a bit

- resources/unix/easyrpg-player.6.adoc
- src/async_handler.cpp
- src/audio.h
- src/audio_decoder_midi.cpp
- src/audio_generic.cpp
- src/audio_generic.h
- src/game_config_game.cpp
- src/game_config_game.h
- src/game_event.cpp
- src/game_interpreter.cpp
- src/game_interpreter_battle.cpp
- src/game_interpreter_control_variables.cpp
- src/game_interpreter_map.cpp
- src/game_player.cpp
- src/game_system.cpp
- src/game_system.h
- src/platform/3ds/audio.cpp
- src/platform/3ds/audio.h
- src/player.cpp
- src/player.h
- src/scene_map.cpp
- src/scene_title.cpp
- src/scene_title.h
- src/sprite_picture.cpp
- src/spriteset_map.cpp
First commit is unrelated to 2k/2k3 but it stops reporting the loop state for WAV. You know for what ;)
Ineluki Key Patch is now locked behind a "harmony.dll" file or ``KeyPatch=1`` in EasyRPG.ini.
When emulating RPG Maker 2000 then RPG Maker 2003 commands are not supported anymore. This makes sense in general. Could solve some bugs in games that were initially developed in 2k3 and moved to 2k. Opt-in is available: ``RPG2k3Commands=1`` in EasyRPG.ini.
> Do not support 2k3 features in 2k

- CMakeLists.txt
- Makefile.am
- src/game_interpreter.cpp
- src/game_interpreter_map.cpp
- src/output.h
- src/player.cpp
- src/string_view.cpp
- src/string_view.h
to_string_view is a private API since fmt10.
The new API only works properly since fmt8.
Added casts to enum formating as they are not converted automatically anymore.
Fix #3002
Tested this down until fmt 5.2: Still compiles (fmt 7 doesn't compile at all but 6 and 8 work, so must be an upstream issue)
> Fix building with fmtlib 10

- src/exe_reader.cpp
- src/exe_reader.h
- src/filefinder.cpp
- src/player.cpp
While looking for the resources I obtain now the sizes of the segments ``CODE``, ``CHERRY`` and ``GEEP``. The sizes of these segments are enough for fingerprinting.
Should detect old RPG Maker 2003 properly and all versions of Maniac I found on the harddrive.
(got a regression tag as old 2003 was properly detected before the new heuristic)
> Improve Engine detection

- CMakeLists.txt
- configure.ac
- src/decoder_drwav.cpp
- src/decoder_drwav.h
- src/platform.cpp
- src/window_settings.cpp
__has_include and [[maybe_unused]] are c++17 features so this will build-fail already when the compiler does not know it ;)
> Require C++17

- CMakeLists.txt
For building liblcf.
Required for the 0-8-0-stable branch to build the correct liblcf in the workflow
> CMake: Add PLAYER_BUILD_LIBLCF_BRANCH to provide a branch

- builds/android/app/src/main/java/org/easyrpg/player/player/SafFile.java
- src/platform/android/filesystem_saf.cpp
…in the native code wrapper
Also do not query anything when the entire goal is to open a file descriptor.
This should make opening of files for reading slightly faster as the DocumentFile roundtrip is gone.
However in my tests it doesn't feel faster. There are still awful lagspikes when a new file is being opened m(
------------
This also could break stuff so have fun sharing and testing ;).
> Android: Make SAF slightly faster by getting rid of DocumentFile

- builds/android/app/src/main/java/org/easyrpg/player/Helper.java
- builds/android/app/src/main/java/org/easyrpg/player/button_mapping/ButtonMappingActivity.java
- builds/android/app/src/main/java/org/easyrpg/player/button_mapping/VirtualButton.java
- builds/android/app/src/main/java/org/easyrpg/player/button_mapping/VirtualCross.java
- builds/android/app/src/main/java/org/easyrpg/player/player/EasyRpgPlayerActivity.java
I'm pretty annoyed right now but I think this is working >.>
Please also test on other devices to ensure my heuristic does not cause fall-positives.
-------
This happens when a game is running (GlSurface exists) and a touch happens across different views.
Our touch ui uses one view per button and is affected.
The culprit is a game optimisation that reduces the size of the surface.
Fix is based on https://github.com/F0RIS/SamsungMultitouchBugSample/tree/Fix1
See also: https://github.com/Swordfish90/Lemuroid/issues/178
Fix #2830
Fix https://github.com/EasyRPG/Player/issues/2915
> Fix Samsung Multitouch bug

- src/async_handler.cpp
From ynoclient: https://github.com/ynoproject/ynoclient/commit/095cf5bddb902478573b3b57a0fc4d4284a00587
TCP connections aren't reliable!
> Emscripten: retry download on uncommon failure

- src/battle_animation.cpp
- src/sprite_actor.cpp
- src/sprite_weapon.cpp
While fixing flipped spritesheets I forgot to consider that battle sprites can be also flipped.
The battle sprites contained adjustment for the src_rect when they were flipped. As I added a fix to the sprite class this means it was double-inverted and broke.
Solved this by removing all the adjustment code from the battle sprites.
(seeing these workarounds this means that this was a long-standing bug in the flip-code)
------
**Please test various 2k3 games and check if the battles look correct!**
I tested:
- Lufia V For the Savior
> Battle: Fix broken animation when the sprite is flipped

- CMakeLists.txt
- src/pixel_format.h
- src/platform/sdl/sdl_ui.cpp
- src/system.h
- src/utils.cpp
- src/utils.h
Needs at least CMake 3.20 to work properly
Removed runtime check as everything uses a build system now.
(untested)
> CMake: Fix Big endian detection when crosscompiling

- src/battle_animation.cpp
- src/drawable.h
- src/game_character.cpp
- src/game_map.cpp
- src/game_map.h
- src/game_player.cpp
- src/plane.cpp
- src/scene_battle.h
- src/scene_battle_rpg2k.cpp
- src/scene_battle_rpg2k.h
- src/scene_title.cpp
- src/screen.cpp
- src/screen.h
- src/sprite.cpp
- src/spriteset_map.cpp
- src/spriteset_map.h
- src/tilemap.cpp
- src/tilemap.h
- src/tilemap_layer.cpp
- src/tilemap_layer.h
- src/transition.cpp
Like everything else the map is now centered when fake resolution is active. Should improve the UX because it gets rid of some glitches :).
First two commits are not changing any behaviour.
3rd commit allows to change the resolution while in the title scene. Until now this didn't work without: Start game, press F12.
4th and 5th commit: 4th results in the screenshot in the middle and 5th results in the screenshot at the bottom. (top is before) Cropping the panorama makes sense here because technically it is drawn outside of the size of the map, nothing should be drawn their.
Another example using Fake Res for a custom resolution. That map is again 20x15. Cropping works.
> Widescreen improvements

- src/scene_debug.cpp
- src/scene_debug.h
because why not.
Legal values are from 1-7. Max speed via events is 6.
7 still works but 8 and higher break the screen scrolling :sweat_smile:
> Debug scene: Add option to set the hero movement speed

- CMakeLists.txt
- Makefile.am
- src/dynrpg.cpp
- src/dynrpg_textplugin.cpp
- src/dynrpg_textplugin.h
- src/game_message.cpp
- src/game_message.h
- src/game_pictures.h
- src/pending_message.cpp
- src/pending_message.h
- src/scene_map.cpp
- src/sprite_picture.cpp
This is mostly for discussion right now. I don't want this to be merged yet there are still bugs. This code is very old and didn't properly rebase.
https://www.multimediaxis.de/threads/135210-DynRPG-Plugin-Text-Plugin
Download with sample game: https://rpgmaker.net/engines/rt2k3/utilities/12/
[please wait for my review comments]
> Add DynText Plugin

- src/meta.cpp
- src/scene_import.cpp
Hi all,
I implemented the "multi game" functionality a while ago, and it seems that a recent-ish commit broke it. I've done a cursory fix of the functionality, and confirmed that it now works on "The Way: Episode 2". The fix uses "FileSystemView::Exists()" (rather than "FindFile") since it needs to access files outside of the save directory (e.g., from "Episode1" we need to read "../Episode2/<save_files>". 
This also fixes a few smaller issues: infinite looping in Update(), and failing to call Start() in the parent class. Tested on Windows.
Definitely open to suggestions and comments, but I'd like to get this feature back to (at least) what it was doing before.
Thanks!
> First attempt at a fix for multi-game functionality

- src/feature.cpp
- src/feature.h
- src/game_battler.h
- src/scene_battle_rpg2k3.cpp
- src/sprite_actor.cpp
- src/sprite_battler.h
- src/sprite_enemy.cpp
- src/window_battlestatus.cpp
- src/window_selectable.cpp
- src/window_selectable.h
Those features were originally intended for **Lufia V: For the Savior** to make it work on EasyRPG since it relied on some small EasyRPG plugin before, but I've seen a few people wishing they could do something similar, so I thought it might be a good idea include them in the original Player distribution.
Normally battlers turn around to face the unit they're currently attacking, which is undesirable if you're build an old school RPG like the aforementioned **Lufia V**. This feature adds an option to make sure the battlers only ever face a single direction no matter what. It only affects how sprites are displayed and is purely cosmetic, no changes to the actual battle processing.
This one is a logical consequence to the previous feature - if you're lining up all units horizontally next to …
> Battle 2k3: fixed battler facing direction + horizontal ally/enemy select

- src/filesystem_stream.cpp
- src/filesystem_stream.h
- src/game_system.cpp
- src/game_system.h
Only consider files as links when they are small (< 500 Byte). "Les aventures d'un avatar 6" uses files with such names for real audio files.
Support of links for sound effects with the same logic as BGM. Note that the "loop" statement is not supported.
Fix #2598
Fix #2609
> Ineluki MP3 patch improvements

- src/exe_reader.cpp
It is RPG Maker 2003 1.0.8.0 but their exe file lacks a VERSIONINFO.
The code segment size is checked instead to detect the version correctly.
----------
Segment size taken from this Makerpendium page: https://www.makerpendium.de/index.php/RPG_RT.exe
Finally a simple commit to review ;)
----------
Reported by samuel in the forum https://community.easyrpg.org/t/ahrimans-prophecy-battle-menu-problem-android/1332 Thanks!
> Detect the engine version for "Ahriman's Prophecy" correctly

- src/audio_decoder_midi.cpp
1. Clearing the tempo data should fix that the next song is faster than usual at the beginning (prior speed became normal after the first tempo event).
2. The fade code change solves the "sometimes Toilet in Wonderland music is mute" bug for me
3. I hooked the Windows Midi API to compare the events. Harmony never generated "all sound off", I removed this event. But what Harmony does is resetting the pitch bend. When you look at the code it looks awful. The reason is that Pbend is > 127, so it uses some weird "calling convention" of preregistering a number so a larger value like 256 can be set. Midi...
The pitch bend reset fixes the broken music after playing some Toilet in Wonderland tracks because these songs indeed alter the pitch bend.
There are some further inaccuracies: The timing …
> Fix broken native midiout playback after playing a song that alters pitch bend

- src/game_interpreter.cpp
- src/game_interpreter.h
- src/game_interpreter_battle.cpp
- src/game_interpreter_battle.h
- src/game_interpreter_map.cpp
- src/game_interpreter_map.h
Minor Change.
It's a variation of ExecuteCommand(); that accepts `com` as a parameter.
Ghabry commented that this would make the code faster. But, this also open possibilities to create a scripting language, since we can create `com` parameters from strings.
------------------
This implementation could also be used to attach code from dynRPG patches to new `com` stuff. Having both @comments and `com` commands share the same code.
> Add ExecuteCommand(com);

- src/external/dr_wav.h
This brings us crash fixes and AIFF/RIFX support.
> Update dr_wav to v0.13.12

- src/player.cpp
- src/player.h
- src/scene_gamebrowser.cpp
- src/scene_logo.cpp
- src/scene_logo.h
To add custom logos, you need to add image files named LOGO1, LOGO2, LOGO3, LOGO`n` to the Font folder. 
It will always load the next logo file, while sequential files exist in the Font folder.
~~You can skip having LOGO0, it loads default easyRPG logo when LOGO0 doesn't exists.~~
EasyRPG logo is always displayed at bootup, to avoid a blank screen while loading a heavy game.
Some reference files for testing:
> Custom Logos at Startup

- src/game_character.cpp
- src/game_character.h
- src/game_map.cpp
- src/game_map.h
This change revamps `MakeWay()` with the following changes that are meant for allowing pathfinding and more:
1. There is now a separate `CheckWay` which allows to just check collision but without causing possible map or state changes. `MakeWay` will cause event updates sometimes, trying to move an event out of the way that blocks movement. This is undesirable for e.g. path finding wwhere just some hypothetical plan is being made and no movement or map changes intended yet.
2. There is now a separate `CheckWayEx`, which has the additional more complex options to either ignore all events and vehicles (and just check underlying map geometry for collision) and the option to specify a list of event IDs to specifically ignore for collision. This can be required for pathfinding.
*Elaborate …
> Revamp MakeWay() and split it into CheckWay()/MakeWay()

- src/audio_generic.cpp
- src/audio_generic.h
- src/audio_generic_midiout.h
- src/audio_midi.cpp
- src/audio_midi.h
- src/decoder_fluidsynth.cpp
- src/decoder_fluidsynth.h
- src/decoder_wildmidi.cpp
- src/decoder_wildmidi.h
- src/scene_gamebrowser.cpp
First commit fixes an oversight in the shutdown logic of the Player: Most audio stuff was not deleted because they were static variables... 
This fixes the fluidsynth crashes on shutdown.
_Should also fix the libretro crash when playing a second game but I havn't tested this (yet)_.
-------------
Second commit is less serious: Fluidsynth and WildMidi are now reinitialized when loading a second game. This saves RAM (unloaded when not used by the game) and allows per-game soundfonts. Before only the first was loaded.
> Midi: Properly shutdown and reinitialize

- src/game_character.cpp
- src/game_character.h
- src/game_map.cpp
- src/game_map.h
This should fix the regression I introduced in #3120 into `MakeWay`, where some corner cases no longer call `MakeWayCollide` like before which breaks some movement routes that disable collision dynamically. This fix also removes the unnecessary `CheckWayEx` functions of GameMap and GameCharacter again, and just adds multiple signatures for `CheckWay`. It also removes all the `out_...` pointers since I managed to merge the core functionality of `MakeWay` and `CheckWay` once more, making this whole pointer passing around unnecessary.
Sorry again for the regression. I hope this one will fare better, I compared it directly against the original `MakeWay` before all my changes and hopefully this time, no unintended change slipped by.
Fixes #3129 (at least in my tests)
> Fix regression of MakeWay() from MakeWay()/CheckWay() split

- CMakeLists.txt
- Makefile.am
- README.md
- builds/cmake/Modules/Findlhasa.cmake
- configure.ac
- src/filefinder.cpp
- src/filefinder.h
- src/filesystem.cpp
- src/filesystem_lzh.cpp
- src/filesystem_lzh.h
- src/filesystem_zip.cpp
- src/game_strings.cpp
- src/window_gamelist.cpp
- src/window_settings.cpp
That is the archive format used by the "Create Game Disk" feature of the editor
This is totally not production ready. Needs code cleanup, (android support?), encoding detection etc.
Also new library needed (lhasa), so infrastructure work etcpp.
https://github.com/EasyRPG/Player/assets/1331889/b8d3dff1-a036-4bef-b4fc-953e6b54e0b3
> Support games in LZH archives

- src/game_interpreter.cpp
- src/game_message.cpp
- src/game_strings.cpp
- src/game_strings.h
- src/game_windows.cpp
- src/maniac_patch.cpp
- src/maniac_patch.h
Noteworthy changes:
- unordered_map instead of vector to reduce huge waste of memory for sparse string usage (e.g. starting at 1000)
- StringView used where possible to reduce copying
- Bugfix: Setting variables didn't refresh the interpreter
> Refactor String Vars

- .gitattributes
- builds/android/app/src/main/java/org/libsdl/app/HIDDeviceBLESteamController.java
- builds/android/app/src/main/java/org/libsdl/app/HIDDeviceManager.java
- builds/android/app/src/main/java/org/libsdl/app/HIDDeviceUSB.java
- builds/android/app/src/main/java/org/libsdl/app/SDL.java
- builds/android/app/src/main/java/org/libsdl/app/SDLActivity.java
- builds/android/app/src/main/java/org/libsdl/app/SDLAudioManager.java
- builds/android/app/src/main/java/org/libsdl/app/SDLControllerManager.java
- builds/android/app/src/main/java/org/libsdl/app/SDLSurface.java
btw they added event listeners for audio device add and remove.
Wasn't a problem with headphones hotplugging not working reported?
> Android SDL2: Update to 2.28.5

- CMakeLists.txt
- src/audio_midi.h
- src/decoder_wildmidi.cpp
- src/decoder_xmp.cpp
- src/filefinder_rtp.cpp
- src/game_config.cpp
- src/input_buttons_desktop.cpp
- src/platform/clock.h
- src/platform/sdl/sdl2_ui.cpp
- src/platform/sdl/sdl2_ui.h
- src/platform/sdl/sdl_audio.cpp
- src/platform/sdl/sdl_ui.cpp
- src/platform/wii/input_buttons.cpp
- src/platform/wiiu/input_buttons.cpp
- src/system.h
> Initial WiiU support

- CMakeLists.txt
- Makefile.am
- resources/emscripten/emscripten-post.js
- resources/emscripten/emscripten-pre.js
- resources/emscripten/emscripten-shell.html
- src/bitmap.cpp
- src/bitmap.h
- src/image_png.cpp
- src/image_png.h
- src/output.cpp
- src/output.h
- src/platform/clock.h
- src/platform/emscripten/clock.h
- src/platform/emscripten/interface.cpp
- src/platform/emscripten/interface.h
- src/platform/emscripten/main.cpp
- src/player.cpp
- src/scene.h
- src/scene_file.cpp
- src/scene_file.h
- src/scene_title.cpp
- src/scene_title.h
- src/window_savefile.cpp
- src/window_savefile.h
Already wrote this in February but never gave it the final touch... **Better for post 0.7.1, removing asynchify can cause problems**.
Had to remove Asynchify because it breaks the Api (you cannot call back into the Player while the endless async loop is running). Previously we had bad experiences when the browser does the mainloop timing. I hope this works better by now...
New feature: Save upload and download (fix: #1025).
New feature: Api under "easyrpgPlayer.api". Currently can do: Reset, Refresh (called after upload to refresh the scene), Upload, Download. Can be used as an extension point if you have a website that wants to access certain functionality of the Player.
> Emscripten: Add Api and remove Asynchify

- src/filefinder.cpp
- src/filefinder.h
- src/scene_gamebrowser.cpp
- src/scene_logo.cpp
If a game filename contains `gamedata.easyrpg` and there's only one game in player's folder, the player will autorun it.
It would be better if I could skip the game_browser scene or hide the screen with default system. But this is working fine.
> Game_Browser - Autorun a specific game

- src/cache.cpp
The BitmapRef reference counter never reached 0 because it was part of the key, preventing deletion. Changed it to a pointer. The value is never read so doesn't matter if it becomes stale.
Fix #3163
> Effects cache: Fix memory leak

- src/font.cpp
- src/game_interpreter.cpp
- src/game_windows.cpp
@Goburinbro
Fix #2953
Player before:
Player after:
RPG_RT:
> FreeType: Calculate font size correctly depending on whether it is a pixel or a truetype font.

- src/platform/3ds/main.cpp
- src/platform/switch/main.cpp
This should make the builders green again... :)
Unfortunately it became a bit convoluted, yet works now (tested on 3DS).
Let's not forget the switch PR builder this time.
> Fix custom logging on 3DS and Switch

- src/game_pictures.cpp
Self explanatory.
Normal RPG2k3e spritesheets have been working for a while now in RM2k games by using the .ini option.
Animation updates however, were still skipped.
> Enable animated RPG2k3e spritesheets when using RM2k engine with 'RPG2k3Commands=1'

- builds/flatpak/org.easyrpg.player.yml
- resources/unix/easyrpg-player.metainfo.xml
While adding 0.8 to flathub[^1] their linker gave 2 warnings:
"appstream-summary-too-long"[^2]
"appstream-screenshot-missing-caption"[^3]
This resolves both of them, but I am still unsure about the short[sic!] summary...
The now enabled URLs are untested, I just think this must be supported after 2 years. 🏂🏼
[^1]: https://github.com/flathub/flathub/pull/5088
[^2]: https://docs.flathub.org/docs/for-app-authors/metainfo-guidelines/quality-guidelines/#not-too-long-1
[^3]: https://docs.flathub.org/docs/for-app-authors/metainfo-guidelines/#screenshots
> Resolve metainfo linter warnings

- CMakeLists.txt
- CMakePresets.json
- builds/cmake/CMakePresets.json.template
btw the presets do not really work currently for our CI:
usually we do ``-DCMAKE_PREFIX_PATH="$TOOLCHAIN_DIR;$LIBLCF_DIR"`` but the preset only specifies ``"CMAKE_PREFIX_PATH": "$env{EASYRPG_BUILDSCRIPTS}/wiiu"``. So no way to provide liblcf.
How to solve this? Just add another env-var?
> CMake: Add WiiU preset

- src/game_interpreter_map.cpp
- src/game_interpreter_map.h
- src/game_player.cpp
- src/game_player.h
`@raw 2002, "", UseVarX,x UseVarY,y`
Activate an event in map remotely, based on its x and y coordinates.
Command made by @MackValentine,
I only refactored it to fit the player specifications.
> New Command: 2002 - Trigger Event At [x,y]

- src/game_interpreter.cpp
- src/game_pictures.cpp
- src/game_pictures.h
- src/sprite_picture.cpp
This commit allows for the use of separate Width/Height parameters for rendering pictures.
You can use this feature with ManiacPatch 211010 using the .scale2 parameter.
It also adds scaling support for "Maniac_ShowStringPic" and a quick fix for failed bitmap assertion.
https://github.com/EasyRPG/Player/assets/26819563/e8a6eb26-f7a9-4267-a4f1-e26e4c5e135c
Sister commit here: https://github.com/EasyRPG/liblcf/pull/473
Added:
- Added support for "scale_width" and "scale_height" for ShowPicture(), MovePicture() and Maniac_ShowStringPicture()
- Maniac_GetPictureInfo returns the separate values of "width" and "height"
- Set both Width and Height to Magnify if one of the following conditions are met:
- ManiacPatch is not enabled;
- Using the .scale parameter;
- Picture Effects are enabled …
> Maniacs Feature: Add separate Width/Height parameters for scaling pictures, Picture StringVar, Tint Variable

- resources/unix/easyrpg-player.6.adoc
- src/cmdline_parser.h
- src/game_config.cpp
- src/game_config_game.cpp
- src/game_config_game.h
- src/game_interpreter.cpp
- src/game_map.cpp
- src/game_map.h
- src/player.cpp
I wasn't sure if I should create a pull request yet, but as this is a good place for discussion I'm ready to share it..:
I tried optimizing the code responsible for map event page refreshes (MEPR):
This heavy-handed approach to refreshing the map state is a performance problem for games that do many switch & variable operations in the background, particularly for maps with a ton of events.
So much, that there a several patches already for RPG_RT itself, that try to mitigate this, by either disabling the refreshing logic on demand (AntiLagSwitch) or changing the behavior entirely (AntiLagFast, PF-Version of Maniacs).
I myself had this performance issue on two areas in my game project: Both the overworld and hub area have > 1500 events. They work fine on modern PCs, but the game will really …
> AntiLag measures

- .github/workflows/stable-compilation.yml
- CMakeLists.txt
- src/input_source.cpp
- src/input_source.h
- src/platform/sdl/main.cpp
- src/platform/sdl/sdl2_ui.cpp
The finger IDs sent seem to be different based on which device you use.
My Surface 4 sent 0 - 4 as ID. This Asus Laptop here increments the ID everytime. Removed the assumption from the code that the IDs are 0 - 4.
----
Disabled the window rounding on Win11 because its not nice when a few pixels of the game are simply lost...
> Windows: Fix touch input, disable window rounding

- src/game_strings.cpp
When saving a file, maniacs forces the File in Text/ folder with .txt extension. 
Through this PR, if '*' is at the end of filename, the file extension is relaxed.
> StringVariable's ToFile - Relax File extension and path

- src/platform/3ds/main.cpp
- src/platform/3ds/ui.cpp
- src/platform/3ds/ui.h
This has been factored out of #2875.
Allowing to use any resolution now (tested double height with enabled stretching to fit and full screen with 400px width)
Fixed the "turn backlight endlessly" bug.
TODO later: investigate why we need 10Mb more heap nowadays, could not get it to boot with less.
> 3DS render changes

- CMakeLists.txt
- Makefile.am
- src/game_commonevent.cpp
- src/game_commonevent.h
- src/game_event.cpp
- src/game_event.h
- src/game_interpreter.cpp
- src/game_interpreter.h
- src/game_map.cpp
- src/scene_debug.cpp
- src/scene_debug.h
- src/window_interpreter.cpp
- src/window_interpreter.h
- src/window_stringview.cpp
- src/window_stringview.h
- src/window_varlist.cpp
- src/window_varlist.h
Adds two new items to the F9 Debug Menu:
- "Strings"
- "Interpreter"
String display supports viewing multiline strings through a special new window "Window_StringView"
Two options can be toggled:
- Automatic linebreaks
- Command Evaluation ( default inserter with \v, \n, \t )
Viewing the current interpreter stacks
(right side: [current command] / [commands_size])
> Debug Menu extensions: Display strings & interpreter stacks

- src/platform/opendingux/opendingux_input_buttons.cpp
Otherwise, it will complain about undefined references to GetSdlAxis.
As far as i'm aware, this file is only being used if you specifically use SDL 1.2 together with OPENDINGUX flag. (OD builds now use SDL2 so this path is normally never used besides yours truly)
> Fix compiling OpenDingux code path with SDL 1.2

- src/audio_midi.cpp
If either of these is disabled in a Makefile, then it will result in errors during compiling.
> Fix compilation errors when Resamping is disabled

- src/bitmap.cpp
- src/bitmap.h
- src/cache.cpp
- src/game_interpreter.cpp
See commit messages for description.
Thanks to @Desdaemon for figuring this out.
----
@Desdaemon I cannot reproduce the cache key issue because I'm on Linux so it likely uses a different allocator.
Though I'm pretty sure my fix works ;).
Please test if this fixes it for you.
> Yume2kki fixes

- src/game_character.cpp
- src/game_character.h
- src/game_event.cpp
- src/game_interpreter.cpp
- src/game_interpreter_map.cpp
- src/game_interpreter_map.h
Originally by @jetrotal 
Redid the stuck check.
Also made the "waiting" similiar to how other events do it: E.g. "Wait for Key" will store all the keys it wants and no reread them from the event everytime. This is necessary because the values of variables can change. Storing them on first call avoids this issue.
> New command "Wait for Single Movement"

- src/cache.cpp
Makes the sizing warning more lenient for battle animations and adds support for big charsets. Also rearranged the Spec struct to fix some unnecessary padding (thanks clang).
> Improve debug image size warnings

- CMakeLists.txt
- Makefile.am
- src/game_event.cpp
- src/game_interpreter.cpp
- src/game_interpreter.h
- src/game_interpreter_control_variables.cpp
- src/game_interpreter_control_variables.h
- src/game_interpreter_map.cpp
- src/game_interpreter_shared.cpp
- src/game_interpreter_shared.h
- src/game_map.cpp
- src/game_map.h
- src/game_strings.h
- src/maniac_patch.cpp
- src/maniac_patch.h
- Refactors & restructures some of the logic of my "AntiLag" branch into a new "Caching" namespace.
- Moves some of the common helper function from the interpreter class to a new file "game_interpreter_shared.cpp"
- Adds a new abstract base class for the interpreter: "Game_BaseInterpreterContext"
-  This class holds the declarations for a few member functions which are used for evaluation logic across different sorts of commands
- All the moved helper functions (CheckOperator, ValueOrVariable, CommandStringOrVariable & others) are agnostic to the actual implementation of the interpreter itself
- Refactors "ValueOrVariable" & "ValueOrVariableBitfield" into template methods
- Might save some unecessary branching depending on the context in which they are used
New helper function: …
> Interpreter Refactor

- src/game_config.cpp
If you have a copy of config.ini saved at the same folder as the player app, it will load the game settings from it, instead of the global folder.
-------------------------------------
~~I used `std::filesystem` because couldn't figure another way of extracting the apps absolute path.~~
> New Feature - Local Settings

- src/game_interpreter.cpp
- src/game_interpreter_map.cpp
- src/platform/switch/ui.cpp
In Maniacs, CommandOpenSaveMenu is renamed to "Call System Function". I implemented what is closer to our code.
Also expanded the code to cover our custom submenus (Cases 8 to 12).
> Maniacs Patch - Call System Functions

- src/decoder_fluidsynth.cpp
> Fix issue 3135 (second try) by exhausting the fluidsynth buffer

- src/game_interpreter.cpp
- src/sprite_picture.cpp
From Maniac Patch version 240423:
```
[RPG_RT.exe]
Support for different magnification rates for special drawing of pictures (rotation, waveform, angle).
```
+ Added check if sprite's width/height is at zero. If so, skip the draw routine (helps avoid a glitchy sprite at the top-left when rotating an infinitely thin picture)
- Removed check for effect mode when setting zoom or width/height.
One thing to note when comparing Maniac and EasyRPG: the former doesn't seem to properly clip the sprite in the corners when rotating the sprite.
> Maniacs Feature - Remove scaling restrictions for pictures

- CMakeLists.txt
- Makefile.am
- src/filesystem_hook.cpp
- src/filesystem_hook.h
- src/player.cpp
The game uses a modified map tree that has all bytes shifted by one to the right.
That map tree is detected and shifted back (by using a streambuf that alters the bytes while reading the file).
Works through a new VFS (HookFilesystem). When the game requires no hooking there is no overhead (Filesystem not attached) besides the initial detection.
> Support The Sacred Tears: TRUE

- src/async_op.h
- src/battle_animation.cpp
- src/battle_animation.h
- src/game_character.h
- src/game_event.h
- src/game_interpreter.cpp
- src/game_interpreter.h
- src/game_map.cpp
- src/game_map.h
- src/game_player.cpp
- src/game_screen.cpp
- src/game_screen.h
- src/player.cpp
- src/scene_item.cpp
- src/scene_map.cpp
- src/scene_order.cpp
- src/scene_skill.cpp
- src/sprite_character.cpp
Command that clones Events from any map inside the current map.
`The syntax always comes in pairs. The first parameter of each pair indicates whether you are using a direct value or a variable/indirect variable, through ValueOrVariable().`
------------------------
```js
@raw 2056,
"",           // Rename the Target Event [Optional]
0, 1,        // Source Map's ID.
0, 2,        // Source Event's ID
0, 3,        // Target's x coordinate
0, 4,        // Target's y coordinate
0, 5,        // Target's Event's ID [Optional] 
// 👆 if a value is defined, it will replace an existing event.
```
> New Command 2056/2057 - Clone/Destroy Map Event

- resources/emscripten/emscripten-pre.js
- src/platform/emscripten/interface.cpp
- src/platform/emscripten/interface.h
- src/platform/emscripten/main.cpp
Adds a new API to be called when the `webglcontextrestored` event has been fired by the browser, after restoring the context to the canvas.
> Reset UI on WebGL context loss

- src/cache.cpp
- src/filesystem_zip.cpp
- src/game_interpreter.cpp
- src/main_data.cpp
- src/main_data.h
- src/player.cpp
Mostly about Maniac Patch and this one regression found in Yume2kki.
> Maniac Event command (regression) fixes

- src/game_interpreter_battle.cpp
- src/scene_battle.cpp
- src/scene_battle.h
- src/scene_battle_rpg2k3.cpp
Using the maniacs patch ChangeBaltteCommandEx with something like this:
Will now give you the expected behavior in EasyRPG:
And for the actors themselves (in my example the row command is turned off):
Developers can mix and match these features and all commands are supported. Including the "Win" and "Lose" commands.
> Implemented Maniacs Command 3011: ChangeBattleCommandEx

- src/game_interpreter_battle.cpp
Using the maniacs patch ControlATBGauge with something like this:
Will result in all party members having 1/3rd of a full gauge. 
Or using it with 100% ATB for the first party member:
Would result in this:
Of course developers can use any combination of parameters, I've tested all of them individually with all combinations. 
I've also recreated the functionality from maniacs where when a 0 index is passed in as an actor id, it just ignores the command entirely.
> Implemented Maniacs Command 3010: ControlATBGauge

- CMakeLists.txt
- Makefile.am
- src/dynrpg_easyrpg.cpp
- src/dynrpg_easyrpg.h
- src/dynrpg_textplugin.cpp
- src/dynrpg_textplugin.h
- src/game_dynrpg.cpp
- src/game_dynrpg.h
- src/game_interpreter.cpp
- src/main_data.cpp
- src/main_data.h
- src/player.cpp
- src/scene_map.cpp
- src/scene_save.cpp
- src/spriteset_map.cpp
- tests/dynrpg.cpp
- tests/test_mock_actor.h
Taken from "DynRPG whitelist + easyrpg_raw command" #3137  to get at least the refactor merged quickly. Will rebase #3137 when this is in to only contain the "raw" part.
> Refactor Dynrpg namespace into a class. Whitelist @easyrpg_ commands

- src/game_battler.h
- src/game_interpreter_battle.cpp
When we use the Maniacs GetBattleInfo command with settings like these:
And we setup our event to display to a picture command like this:
We get the exact same result in EasyRPG as we do in the Maniacs Exe:
All combination of event commands were thoroughly tested with different combinations, including:
- Target Types: Actor ID, Party Member, Entire Party, Enemy, Entire Enemy.
- Information Types: Parameter Buffs, States, Elements, Others
- Also tested with variables that are outside the defined range: this seems without error in both EasyRPG and Maniacs (surprisingly)
> Implemented Maniacs Command 3012: GetBattleInfo

- src/cache.cpp
- src/game_commonevent.cpp
- src/game_commonevent.h
- src/game_interpreter.cpp
- src/game_map.cpp
- src/game_pictures.cpp
- src/game_strings.cpp
- src/maniac_patch.cpp
- src/sprite_enemy.cpp
The work on the battle events motivated me to fix the non-battle issues :)
What this doesn't fix is the wrong font size, guess they replaced the font in the exe with a different one. So the metrics are different.
Fix #3128
> Fix Beloved Rapture Menu issues

- CMakeLists.txt
- Makefile.am
- src/game_interpreter.cpp
- src/game_interpreter.h
- src/game_strings.cpp
- src/game_strings.h
- src/json_helper.cpp
- src/json_helper.h
This command allows you to Get or Set values inside a JSON string.
(Requires Maniacs Patch)
`The syntax always comes in pairs. The first parameter of each pair indicates whether you are using a direct value or a variable/indirect variable, through ValueOrVariable().`
------------------------
```js
@raw 2055,
"",          // Path to the target value within the JSON data
0, 0,        // Operation (0-1) -  0: Get (extract value), 1: Set (update value)
0, 5,        // Source string variable ID containing the JSON data
0, 2,        // Target variable Type (0-2) - 0: Switch, 1: Variable, 2: StringVariable
0, 1,        // Target variable ID to receive data (for Get) or contain new value (for Set)
0, 100,      // Usage of string variable instead of the path string.
```
- Extract the value of …
> New Command 2055 - Process JSON Code

- src/game_player.cpp
By Ghabry's request, here's the missing function .relative & .centered scrolling.
When using .relative & .centered tags for PixelScrolling, do the following:
- Get half the width/height of the screen
- Move screen by ( h/v - screen_width/height ) divided by two.
Tested against Maniac Patch 240822, it works as expected.
Tested using different resolutions on Maniac and EasyRPG, works as expected.
> Maniacs Feature - Add .relative & .centered support on PixelPanScreen

- src/game_interpreter.cpp
- src/game_map.cpp
- src/game_map.h
- src/map_data.h
- src/spriteset_map.cpp
- src/spriteset_map.h
- src/tilemap.h
- src/tilemap_layer.cpp
- src/tilemap_layer.h
This PR introduces the Rewrite Map command from Maniacs Patch that enables changing selected map tiles. Unlike the vanilla Change Tile command, which only replaces one tile ID with another, the Rewrite Map command offers greater flexibility in modifying tiles. Changes applied by the command do not persist between save and load.
The implementation covers most of the command’s functionality, with the exception of AB autotile sprite fixups. Despite this limitation, games will remain playable as intended.
> Partially implement Maniacs Command 3015: RewriteMap

- src/game_interpreter.cpp
- src/game_interpreter_shared.cpp
- src/game_strings.cpp
- src/game_strings.h
- src/maniac_patch.cpp
- src/utils.cpp
- src/utils.h
- tests/utf.cpp
Updated the test game by @enewey to use extended latin characters like é everywhere:
https://easyrpg.org/play/pr3303/?game=string-var
In UTF-8 they require 2 bytes and 1 codepoint.
Correct is using 1 codepoint here (which matches the legacy encoding = 1 byte)
For あ it is 3 bytes UTF-8 or 1 codepoint. When running in shift-jis RPG_RT seems to use a multibyte character so it also reports 1. There is no shift-jis case in the project but I tested this locally.
Sooo we are just extremely lucky here that it _just works_ even though our encoding is completely different :)
> String Variables: Operate on Codepoints

- src/game_battle.cpp
- src/game_battle.h
- src/game_battlealgorithm.cpp
- src/game_battlealgorithm.h
- src/game_battler.cpp
- src/game_battler.h
- src/game_interpreter_battle.cpp
- src/game_interpreter_battle.h
- src/game_party_base.cpp
- src/game_party_base.h
- src/scene_battle.cpp
- src/scene_battle_rpg2k.cpp
- src/scene_battle_rpg2k3.cpp
- src/scene_battle_rpg2k3.h
With all of these Control Battle events set:
Game developers have a way to inject events hooks into the battle system that might look something like this:
This allows them to handle all kinds of events including:
- ATB Changes (parallel process like event)
- Health Changes (custom damage popup visualization)
- Targets being selected (before turn event)
- State Changes (custom status effects)
- Other Stat Changes (custom stat change popup visualization)
One small difference from the maniacs version (Maniacs 210414) I use:
🐛  I unintentionally fixed a bug: when the battle begins in Maniacs, it only fire an event for the first state to change (or maybe it's just not waiting for the message box to close for the others?).
✅  In EasyRPG it will definitely provide the callback for all state …
> Implement Maniacs Command 3009: ControlBattle

- src/game_interpreter.cpp
Tiny update based on @MackValentine's code.
In MP, Move Route supports using variables as the target event ID:
```js
//TPC SYNTAX:
v[1] = 2
@ev[v[1]].setAction .freq 8 .unskippable .act {
.moveDown
}
```
> MoveRoute - Support Variables as Event ID (Maniac patch feature)

- src/game_interpreter.cpp
Another smaller update:
Events can be disabled and enabled again through maniacs patch.
It also allows targeting an event by ID instead of only erasing the caller itself.
```js
//TPC SYNTAX
@ev[2].erase
@wait .input
v[1] = 2
@ev[ v[1] ].return
```
> Erase Event - Erase By ID + Recreate Event Option (Maniac Patch Feature)

- src/exe_reader.cpp
- src/exe_reader.h
Maniac Patch is now detected when the new exe is used.
----
The difference between 32bit PE and 64 bit PE is actually not _that_ huge when you only care about the resources.
The differences:
- The machine type is 0x8664
- In the optional header the magic at the beginning is 0x20b instead of 0x10b (0x20b is a "PE32+" header, 0x10b is a "PE32" header)
- The data direction offset is different because the PE32+ image file header is larger
The offset calculation was the major change:
Before the resource offset was hardcoded to ``0x88`` (136) which is actually ``size_of_optional_header (24) + size_of_image_file_header (96/112 [PE+]) + 16``.
All the resource format itself is the same. (lucky for us).
----
Tested it with:
Player.exe, both 32 Bit and 64 Bit: PASSED
Maniac exe: PASSED
Various …
> ExeReader: Support 64 Bit executables

- builds/android/app/src/gamebrowser/org_easyrpg_player_game_browser.cpp
- builds/android/app/src/main/java/org/easyrpg/player/button_mapping/VirtualButton.java
- builds/android/app/src/main/java/org/easyrpg/player/game_browser/Game.java
- builds/android/app/src/main/java/org/easyrpg/player/game_browser/GameBrowserActivity.java
- builds/android/app/src/main/java/org/easyrpg/player/settings/SettingsEnum.java
- builds/android/app/src/main/java/org/easyrpg/player/settings/SettingsInputActivity.java
- builds/android/app/src/main/java/org/easyrpg/player/settings/SettingsManager.java
- builds/android/app/src/main/res/drawable/ic_view_list_black.xml
- builds/android/app/src/main/res/drawable/ic_view_list_white.xml
- builds/android/app/src/main/res/layout/activity_settings_inputs.xml
- builds/android/app/src/main/res/menu/game_browser.xml
- builds/android/app/src/main/res/values/strings.xml
- src/exe_reader.cpp
- src/exe_reader.h
The displayed game name can now be configured:
- Use title from RPG_RT.ini (default), this is now more reliable in combination with https://github.com/EasyRPG/liblcf/pull/488
- In the chat somebody disliked this behaviour because they use the game name to differentiate between different versions of the game, so you can revert back to the old behaviour now
In #3311 they considered A and B confusing because all games use Z and X in dialogs. This is the new default but you can revert it in the settings if you dislike it.
> Android: Add game label configuration, rename buttons to X/Z

- src/game_actor.h
- src/game_interpreter.cpp
- src/game_interpreter.h
- src/game_interpreter_control_variables.cpp
- src/game_interpreter_map.cpp
- src/game_interpreter_shared.h
- src/game_strings.h
This commit partially implements command #3021 from Maniac Patch, which can returns things from screen coordinate/size to screen pixel data.
I've opted to implement most of its features, the reason for these omissions were:
1. Handling the tile/pixel functions would be better suited for someone who delves into these systems;
2. I do not have a good grasps on how the "Command Interpreter State" functions. There is a bit of documentation on the README.txt file in Maniacs;
I have implemented the following commands:
0- Get Map Size: returns the width and height of the map;
2- Get Window Info: returns the width and height of the screen;
5- Get Tileset ID: returns the current tileset ID;
6- Get Actor/Message Face: returns the face string/index for either the current message box or an actor. …
> Maniacs Feature - Partially implement command GetGameInfo (3021)

- builds/android/app/build.gradle
- builds/android/app/src/main/AndroidManifest.xml
- builds/android/app/src/main/java/org/easyrpg/player/BaseActivity.java
- builds/android/app/src/main/java/org/easyrpg/player/Helper.java
- builds/android/app/src/main/java/org/easyrpg/player/InitActivity.java
- builds/android/app/src/main/java/org/easyrpg/player/button_mapping/ButtonMappingActivity.java
- builds/android/app/src/main/java/org/easyrpg/player/button_mapping/VirtualButton.java
- builds/android/app/src/main/java/org/easyrpg/player/game_browser/GameBrowserActivity.java
- builds/android/app/src/main/java/org/easyrpg/player/game_browser/GameBrowserHelper.java
- builds/android/app/src/main/java/org/easyrpg/player/player/EasyRpgPlayerActivity.java
- builds/android/app/src/main/java/org/easyrpg/player/settings/SettingsAudioActivity.java
- builds/android/app/src/main/java/org/easyrpg/player/settings/SettingsEnum.java
- builds/android/app/src/main/java/org/easyrpg/player/settings/SettingsFontActivity.java
- builds/android/app/src/main/java/org/easyrpg/player/settings/SettingsGamesFolderActivity.java
- builds/android/app/src/main/java/org/easyrpg/player/settings/SettingsInputActivity.java
- builds/android/app/src/main/java/org/easyrpg/player/settings/SettingsMainActivity.java
- builds/android/app/src/main/java/org/easyrpg/player/settings/SettingsManager.java
- builds/android/app/src/main/java/org/easyrpg/player/settings/SettingsVideoActivity.java
- builds/android/app/src/main/res/layout/activity_settings_inputs.xml
- builds/android/app/src/main/res/values/strings.xml
- builds/android/app/src/main/res/xml/file_paths.xml
- builds/android/build.gradle
- builds/android/gradle.properties
- src/platform/android/org_easyrpg_player_player_EasyRpgPlayerActivity.cpp
- Bumped the SDK so Google will annoy us one year later about SDK updates ;)
- Fixed crashes existing since 0.8 (none of them was critical but good to have them resolved)
- Most crashes are related to the settings becoming null because the app restarts, I was able to simulate this and hopefully fixed it everywhere (by adding a new class which does this automatically)
- After a game crash the game list was empty, fixed this by refetching the easyrpgURI (which was also null...)
- Fixed a crash when opening the settings while another scene was currently opening (race condition)
- Fixed crashes reported after the latest APK update
- Fixed a crash in the new "sorting" option when the game list was empty
- Upon feedback the Z/X buttons are reverted back to A/B buttons but the setting is still …
> Android: Fix common crashes / various improvements

- src/game_interpreter.cpp
- src/game_map.cpp
- src/game_map.h
Support of `Get Game Info -> Get Tile`, started by @ToolMan2k 
Map of it:
[EasyRPG TileID Demo.zip](https://github.com/user-attachments/files/18349806/EasyRPG.TileID.Demo.zip)
> GetInfo - Support Tile ID

- src/game_interpreter_map.cpp
Supporting usage of variables when game uses maniac patch
and parameters size is bigger than 7.
```js
//TPC Example
@ev.flash .player .rgbv v[100], v[101], v[102], v[103] .time 100
```
> FlashEvent - Maniac Patch Parameters

- src/game_map.cpp
fixes #3327.
(i don't know how this patch interferes with #3293, but Init() is called only after reset, so not a very destructing change i guess)
> Map: initialize screen width and height on SetupCommon

- src/spriteset_map.cpp
- src/tilemap.h
- src/tilemap_layer.cpp
Fixed the issues described at #3323 
------------------
Also I Discovered one last quirk, from toggling autotiles ON/OFF: 
- On EasyRPG the autotile is changing a buch of its own neighbour tiles.
- On maniacs it changes only the closest to itsef.
This Quirk is not a dealbreakers, so didn't look at the code of it yet. 
---------------
Things are now very closer to the Maniacs version now, only missing that fix and the AB lower tiles support.
> Rewrite map fixes

- src/game_interpreter.cpp
- src/maniac_patch.cpp
- src/maniac_patch.h
Partial Change to cover the new variations of Maniac's "call command"
Those changes make it way easier when writing and maintaining new commands.
This could be merged, though it lacks the support of expressions.
Looks like Typical expressions only affects single outputs.
But this seems to manipulate an "array of expressions", which I failed to figure out how could this work.
> Maniac Patch - CallCommand Update

- builds/android/app/src/gamebrowser/org_easyrpg_player_game_browser.cpp
- builds/android/app/src/main/java/org/easyrpg/player/InitActivity.java
- builds/android/app/src/main/java/org/easyrpg/player/game_browser/Game.java
- builds/android/app/src/main/java/org/easyrpg/player/game_browser/GameBrowserActivity.java
- builds/android/app/src/main/java/org/easyrpg/player/game_browser/GameScanner.java
- builds/android/app/src/main/java/org/easyrpg/player/game_browser/ProjectType.java
- builds/android/app/src/main/res/layout/browser_game_card_landscape.xml
- builds/android/app/src/main/res/layout/browser_game_card_portrait.xml
- builds/android/app/src/main/res/values/strings.xml
- src/directory_tree.cpp
- src/directory_tree.h
- src/filefinder.cpp
- src/filefinder.h
- src/scene_gamebrowser.cpp
- src/window_gamelist.cpp
- src/window_gamelist.h
Fix #3198 
Some users, particularly on mobile, struggle to understand why EasyRPG doesn't detect any playable content when trying to run games made with unsupported engines like RPG Maker versions other than 2kX or similar software (e.g. Wolf RPG Editor).
This PR addresses this issue by implementing a feature that detects games created with commonly encountered unsupported engines. Affects both regular and Android version of the player. The list of known engines consists of:
- RPG Maker XP
- RPG Maker VX
- RPG Maker VX Ace
- RPG Maker MV/MZ
- Wolf RPG Editor
A few screenshots demonstrating the feature:
> QoL: detect unsupported engines

- src/game_interpreter_map.cpp
- src/game_player.cpp
- src/game_player.h
- src/tilemap_layer.cpp
@florianessl noticed a while ago that events always face the Player when being called via this command which is inconvenient.
I added a flag to disable it :).
The "Triggered By Decision Key" state is now forwarded from the source event.
-----
I'm hosting the Editor Plugin here now: https://github.com/Ghabry/EasyRpgCommands/releases/tag/2025-01-20
> TriggerEventAt: Add flag to configure "Face Player" behaviour

- builds/android/app/src/main/java/org/easyrpg/player/BaseActivity.java
- builds/android/app/src/main/java/org/easyrpg/player/game_browser/GameBrowserActivity.java
Otherwise gives UnsatisfiedLinkError when the app was killed due to OOM etc.
Is harmless as you can just restart the app and it will work but its the most common crash in the dev console, so lets fix it...
----
to reproduce you can just background the app while in the settings, then ``am kill org.easyrpg.player`` and selecting "EasyRPG folder" will crash.
> Android: Reload native libraries on resume

- CMakeLists.txt
- src/decoder_oggvorbis.cpp
- src/game_config.cpp
- src/game_interpreter.cpp
- src/options.h
- src/platform/sdl/sdl2_ui.cpp
- src/platform/sdl/sdl_ui.cpp
- src/platform/wii/audio.cpp
- src/platform/wii/input_buttons.cpp
- src/platform/wii/main.cpp
When targeting Wii the possible ``PLAYER_TARGET_PLATFORM`` are now ``SDL2`` (default) and ``SDL1``. SDL1 is still supported for testing purposes (and the code was already written ^^)
For ``PLAYER_AUDIO_BACKEND`` the default is as before ``AESND``, but ``SDL2/SDL1`` can be also selected (I moved the mutex code a bit, hopefully this fixes the random crashes when changing maps).
----
Besides the build system this is not very invasive, only had to change the button mapping and thats all.
_Note_: The CMakeLists changes are quite large because this is already the preparation for the SDL3 support. (initially I had Wii SDL2 and PC SDL3 commit combined)
----
Prebuilt for testing: https://easyrpg.org/downloads/tmp/wii-test.zip  (contains both a SDL2 and a SDL1 build)
- SDL2_Aesnd: The latest build …
> Wii: Add SDL2 support

- src/exe_reader.cpp
This PR adds some CRC hashes of known bootleg logos.
All of these were extracted from different RPG_RT versions which were originally bundled with setups from the French & Spanish communities.
(Retitled "PRO" version of Rm2k because they previously retitled their version of RM95 as "2000")
> Extend hash list of known startup logos

- src/window_gamelist.cpp
Fix memory corruption in the game browser when calling create while iterating file entries.
Looks like some memory reallocation issue because the cache receives new entries and the vector moves around.
> Fix game browser crash

- src/game_strings.cpp
Handles an edge case with the maniacs `t[a] .popLine t[b]` string function.
Per the spec, the first line of `t[a]` is removed, and written to `t[b]`. 
However, in cases where `a` equals `b`, easyrpg currently differs from easyrpg.
Maniacs will preserve the mutated base string (`t[a]`) and discard the popped line, whereas easyrpg will write the popped to the base string.
This merge handles the edge case to align with maniacs.
I.e.
`t[1] .asg "one
two
three"
t[1] .popLine t[1]
@msg.show "\t[1]"`
the Player currently would display:
```
one
```
and with this change, should now display:
```
two
three
```
which matches the maniacs implementation.
> StringVar: address popLine edge case behavior to match maniacs

- builds/android/app/src/main/java/org/easyrpg/player/player/EasyRpgPlayerActivity.java
- builds/android/app/src/main/java/org/easyrpg/player/player/EasyRpgSurface.java
- src/platform/sdl/sdl2_ui.cpp
- src/platform/sdl/sdl3_ui.cpp
ConfigurationChanged is not sent on all Android versions because of various bugs in the operating system. Instead SurfaceChanged is used which is consistent with what SDL does.
Also Window events are not filtered anymore when in the background. This is required on Android, otherwise rotations are lost.
---
Confirmed by lusciouslover in chat that the rotation issue is fixed.
> Android: Properly handle rotations

- CMakeLists.txt
- Makefile.am
- src/game_config.cpp
- src/game_config.h
- src/game_interpreter_map.cpp
- src/player.cpp
- src/player.h
- src/scene.cpp
- src/scene.h
- src/scene_gamebrowser.cpp
- src/scene_language.cpp
- src/scene_language.h
- src/scene_logo.cpp
- src/scene_map.cpp
- src/scene_settings.cpp
- src/scene_settings.h
- src/scene_title.cpp
- src/scene_title.h
- src/translation.cpp
- src/translation.h
- src/window_settings.cpp
- src/window_settings.h
This PR collects all the minor patches I've done recently on the Player´s translation feature.
Basically I've split my working branch into 3, depending on how deep the changes would go.
Pt.2 would contain some changes to liblcf, to be able to store the selected language setting inside savefiles
Pt.3 is highly experimental & does all the unsafe, live patching of the interpreter state, to be able to switch languages mid-game
And if Pt.3 works out, maybe I'll proceed to experiment with some sort of AI-based auto-translation feature. Let's see.  
Previously, the language selection has been hardcoded to be part of the title scene. This was an issue for games that use the "NewGame" flag & implemented their own title screen in-engine.
This PR implements a new scene type for the langue menu and …
> Translation Extensions & Issues Pt 1

- src/decoder_mpg123.cpp
I have some old Advocate RTP version installed locally, which shipped with a small _lame.exe_ utility & mp3-encoded sounds to save space.
Never bothered to run it & convert them back to wav. Now I'd get a "Format not supported" for some standard RTP sounds like "cursor1" when they should actually play normally.
Looking into the audio code I first suspected an encoding issue with the LAME version used to encode the files (3.93), but it looks like, the detection loop incorrectly handles the result of the read operation, which correctly delivers the internal "MPG123_DONE" code when its done reading.
This issue only applies to some very small files, like the menuing sounds.
[cursor_se.zip](https://github.com/user-attachments/files/19094375/cursor_se.zip)
> Fix:  MP3 detection would always return false for very small files

- src/game_ineluki.cpp
- src/game_ineluki.h
- src/input.cpp
- src/input.h
- src/input_source.cpp
- src/input_source.h
While going through different versions of harmony.dll, I found a few special versions of the Ineluki patch.
Most of them were just copy-protected preview versions, which were handed out to some devs, before the key patch was actually released to the public. Those have limited functionality & will refuse to work, if some of the game files do not match the expected values.
Just for documentation purposes, the unique versions I found on rmarchiv's data are:
- 1.2.0.50 **Gekiganger** (Used in the keypatch demo)
- 1.2.0.50 **Kelven** "a" (Used in "Die Bücher Luzifers 2")
- 1.2.0.50 **Kelven** "b" (Used in "Aliminator")
- 1.2.0.50 **Sunny** (Used in "Der Feind")
- 1.2.0.50 **KoA Angel** (Used in "Yoshis Maze Mania")
- 1.2.0.00 **Neo23** (Apparently used in a Moleboxed "Megaman" game by the …
> Implement undocumented mouse binding for the Ineluki patch

- src/game_character.cpp
- src/game_character.h
- src/game_interpreter_map.cpp
- src/game_interpreter_map.h
- src/game_map.cpp
- src/game_map.h
- src/game_variables.cpp
- src/game_variables.h
This adds a new path finding command with initial code by @MackValentine that I fixed up, and @jetrotal  helping out coordinating the whole thing. It's based on the new CheckWay command added in #3120 and #3130 and can be used via event command 2001. It has a few special options which are documented in the doc comment that allow ignoring other events in the pathing (they won't be ignored in the actual collision!). The command is intended to both work for a use case where it's used *once* and then sets a movement route that is just left to execute, as you would in an autorun event, and for a use case where it's used *repeatedly* in a parallel event to continuously update the route to a moving target.
**Behavior quirks:** The current algorithm is a breadth first search, so it's not full A* …
> Add new path finding command 2003

- src/platform/libretro/ui.cpp
- src/player.cpp
- src/scene_battle_rpg2k3.cpp
- src/tilemap_layer.cpp
Guess @Mimigris should also test this a bit.
I only hacked the frame counter to overflow after about two seconds. Works for me (it renders are usual, thats not the RPG_RT behaviour but who cares).
> Libretro fixes and one hotfix for YNOnline Users with loooong playtimes

- src/decoder_mpg123.cpp
Fixing two issues with the refactored MP3 heuristic check:
- For some files (I mostly noticed this with ModTracker files) the IsMp3() heuristic would now yield wrong positives, because for some reason _mpg123_read_ would immediately result in a status 'DONE without actually reading data.
- Other small non-mp3 files might yield a single error before resulting in a DONE & still pass the allowed err_count of '3'.
Fixes #3380
> Fix MP3 heuristic check

- builds/android/app/build.gradle
- builds/android/app/src/main/AndroidManifest.xml
- builds/android/app/src/main/java/org/easyrpg/player/player/EasyRpgPlayerActivity.java
- builds/android/app/src/main/java/org/easyrpg/player/settings/SettingsEnum.java
- builds/android/app/src/main/java/org/easyrpg/player/settings/SettingsManager.java
- builds/android/app/src/main/java/org/easyrpg/player/settings/SettingsVideoActivity.java
- builds/android/app/src/main/res/layout/activity_settings_video.xml
- builds/android/app/src/main/res/values/strings.xml
- builds/android/app/src/main/res/values/styles.xml
Our App is broken with SDK35 (#3373) now I just hope that Google Play allows this downgrade, otherwise we are kinda fcked :(
Since the last SDL2 update the systembar is green while in-game instead of black. SDL2 calls it "Fixed Immersive Mode". Imo this breaks immersion so I applied a custom theme to revert the behaviour.
Also added a Fullscreen option just because this works now with SDL2 instead. \*g\* (and maybe makes some users happy because the UI is not hidden anymore)
> Urgent Android fix

- .github/workflows/stable-compilation.yml
- src/utils.h
- tests/utils.cpp
Turns out "char" is not always signed. Instead it is "implementation defined". In all tests it went unnoticed because x86 is "signed". On ARM it appears to be "unsigned".
This is surprising. For int etc. it is specified to be signed.
Can we just burn the C standard? Who specifies this nonsense?
Fix #3401
> Fix StringIsAscii by explicitly setting the type to "signed char"

- CMakeLists.txt
- builds/cmake/CMakePresetsBase.json
- builds/cmake/Modules/PlayerConfigureWindows.cmake
Fixes a dumb typo in the Presets breaking RelWithDebInfo (Making it a Debug build >.>).
And Rinnegatamante told me to pass ``-fno-optimize-sibling-calls`` for the Vita build because that optimisation can cause crashes: Can confirm. With that flag set the MainLoop does not randomly crash anymore :shrug:  (that appears to be a general problem on Vita, other homebrew uses the same flag)
> Compiler fixes

- src/game_config.cpp
Options "_Logging_" & "_Screenshot scaling factor_" in the "_Engine_" section of the settings menu were never written to the INI file & would thus be reset when the Player is restarted.
> Fix: Two of new 0.8.1 engine options were not written to the config INI

- src/game_strings.cpp
- src/game_strings.h
- src/lcf/data.h
- src/lcf_data.cpp
- src/scene_debug.cpp
- src/scene_debug.h
- src/window_stringview.cpp
- src/window_stringview.h
- src/window_varlist.cpp
- src/window_varlist.h
Self-explanatory, but I also included some refactors of the existing var_window, to make it more useful for displaying certain kinds of data that might need more than a single line.
(My ScopedVars branch for example, would also display multiple lines per scoped variable type)
StringVar names have been added with ManiacPatch 241028 & also provide a useful way to detect this major update without having to rely on reading the EXE:
```
if (lcf::Data::maniac_string_variables.size() > 0) {
mp_version = MP_24;
}
```
(Even if no StringVars are used, at least one list entry will be included in this new LDB field by default)
By default, the view stays as before:
And by pressing SHIFT, it toggles to the new display mode that displays individual entries over two lines & includes the var name: …
> Extend the "Strings" view in debug screen to display names of StringVars (+ some debug screen adjustments)

- CMakeLists.txt
- Makefile.am
- src/game_actor.cpp
- src/game_actor.h
- src/game_battlealgorithm.cpp
- src/game_message_terms.cpp
- src/game_message_terms.h
- src/scene_battle_rpg2k.cpp
- src/scene_battle_rpg2k3.cpp
A few new term fields have been added in the latest version of Maniacs, to provide more customization options for some in-game texts:
- Experience gained
- Level Up
- Items received
- Skill learned
I would have preferred some template strings similar to the ones found in RPG2KE, but they do the job..
I moved those message texts to "battle_commands" which I then renamed to "game_message_terms". The terms code is all over the place & a lot of refactoring should be done here to make localization less of a hassle.
I'm sure this issue came up before & we could use this PR to do also some housekeeping here. 🤔
Maybe move everything related to in-game terms to its own naming scheme? (terms_battle.cpp, terms_actor.cpp, etc.)
New custom fields for _liblcf_:
``` …
```
> New Database terms for Maniacs

- src/game_config.cpp
- src/game_config.h
- src/output.cpp
- src/output.h
- src/platform/emscripten/interface.cpp
- src/platform/emscripten/interface.h
- src/player.cpp
- src/utils.h
- src/window_settings.cpp
This was also requested recently & is pretty easy to implement, so I added this option as well:
If there is a naming conflict (multiple presses of the screenshot key in a single second), file names will still be indexed (starting with "_1.png", rather than "_0.png")
> New setting options for screenshots: Periodically take auto-screenshots + option for timestamps in file names

- src/feature.cpp
- src/game_interpreter.cpp
- src/game_interpreter.h
- src/game_interpreter_shared.cpp
- src/game_interpreter_shared.h
- src/player.cpp
- src/player.h
- src/scene_debug.cpp
- src/window_interpreter.cpp
- src/window_interpreter.h
This PR refactors the EasyRPG feature "**SetInterpreterFlag**" (#3123), similar to the way @Ghabry suggested there, by making use of some new state flags that have been merged into _liblcf_.
See _liblcf_ PRs:
- https://github.com/EasyRPG/liblcf/pull/491
- https://github.com/EasyRPG/liblcf/pull/492
Rather than setting the global config options directly as before, a new field "**easyrpg_runtime_flags**" in the **SaveEventExecState**" struct is used, to make these overrides persist across save/load boundaries.
This makes these config overrides apply only to the Interpreter instance where they have been set, and when the end of the base frame is reached, all of the flags are reset automatically. To make this possible, a new global field "active_interpreter_flags" has been introduced, so the …
> Change EasyRPG's "SetInterpreterFlag" to make patch overrides temporary

- builds/android/app/src/main/java/org/libsdl/app/SDLActivity.java
Slowly these bumps become annoying because there is 0 API change...
Also cleaned up some stuff in SDLActivity (marked it as a easyrpg modification) that was added due to the dark mode and Android 36 edits.
> SDL: Bump Android version

- src/scene_battle_rpg2k.cpp
- src/scene_battle_rpg2k.h
Fixes the Player crash described in issue #3415
I haven't looked further if a similar problem could occur in the 2k3 battle scene. But I guess the execution of scripts would look quite different there. (And I remember playing plenty of 2k3 games that switch out characters in the standard battle system & never having a similar issue)
> Fix #3415 (Access violation in RM2K battle scene)

- src/filefinder.cpp
- src/filefinder.h
- src/player.cpp
- src/player.h
I noticed this after migrating a lot of harcoded strings into json files & trying to translate them..
Files which are fetched via `OpenText()` (Everything inside the _Text_ game folder) would not get translated at all due to their function variant not checking for active translations.
Here's a quick fix...
> Translation fix: Files inside "Text" folder were not translated

- src/game_interpreter.cpp
- src/game_map.cpp
Fixes following issues with these EasyRPG-commands:
- Cloned & destroyed events were not considered by the map setup code which is responsible for loading savegame data. This was especially dangerous if a pre-existing map event has been destroyed because the code assumed both the original & the savegame data vectors of events to be both the same size & in the same order, with no skipping of IDs.
- Added check before refresh of "scene": If the **CloneMapEvent** function was called from inside the map setup code, the map scene might not be created yet.
- Fix #3393 
- Sometimes **CloneMapEvent** would write garbage data into the field "_easyrpg_clone_event_id_" due to an invalid pointer (Vector reallocation issue)
[CloneDestroyMapEventTest.zip](https://github.com/user-attachments/files/199671 …
> Several fixes for the CloneMapEvent/DestroyMapEvent commands

- CMakeLists.txt
- Makefile.am
- src/filefinder.h
- src/game_commonevent.cpp
- src/game_commonevent.h
- src/game_event.cpp
- src/game_event.h
- src/game_interpreter.cpp
- src/game_interpreter.h
- src/game_interpreter_battle.cpp
- src/game_interpreter_debug.cpp
- src/game_interpreter_debug.h
- src/game_interpreter_shared.h
- src/game_map.cpp
- src/input_buttons.h
- src/rtp.h
- src/scene_debug.cpp
- src/scene_debug.h
- src/window_gamelist.cpp
- src/window_interpreter.cpp
- src/window_interpreter.h
First two commits of this PR were already included with my recent PR [:Debug_AssertWay](https://github.com/florianessl/Player/tree/Debug_AssertWay). Basically summed up with refactoring work on existing functionality I implemented in the Interpreter Debug Window that has already been merged for a while; and setting the base with a new Debug namespace inside a new file "game_interpreter_debug.cpp"...
Next up (Commit #3): _"Game_Interpreter_Inspector"_ 
Also some refactoring work. This is to clear out some of the "_friend classes_" I've defined previously. The idea is to only allow access to internal interpreter states via this interface & make it clear that any use of these functions is considered unsafe. (I use this for my new experimental work on trying to translate/patch content of …
> Maniac´s debugging features: GetCommandInterpreterState (GetGameInfo), maniac_event_info & more debugging extensions

- src/bitmap.cpp
When using pixel format ABGR (prefered on Big Endian) instead of RGBA and the image is considered opaque (no alpha channel), pixman makes the alpha pixels 0x00 instead of 0xFF.
Technically the alpha values are undefined as the image is opaque but our opacity function considered this image as full transparent (because A is 0 everywhere).
This triggered a fast path in the ToneBlit which does nothing when the image is full transparent and causes a "trippy trail" rendering glitch.
Additionally this fixes a glitched Fog effect in the beginning of "Unterwegs in Düsterburg" which only flickered between transparent and full opaque before.
Fix #3436
---
The fix for UiD is cool because that was a long-standing bug where I had no idea where it comes from :)
The ToneBlit rendering bug in IB was not …
> Fix 3436: Consider images with no alpha as Opaque in ComputeImageOpacity.

- src/game_interpreter.cpp
Fix:
```
easyrpg-player/src/game_interpreter.cpp:4848:28: error: ‘RuntimePatches’ has not been declared
4848 |                 auto key = RuntimePatches::VirtualKeys::VirtualKeyToInputKey(key_id);
|                            ^~~~~~~~~~~~~~
```
> Fix build on Arch

- resources/unix/easyrpg-player.6.adoc
- src/filefinder.cpp
- src/filefinder.h
- src/player.cpp
- src/translation.cpp
This pull request adds a command line option, --language-path, which allows users to specify where the folder with all of the different language translations is.
The folder containing translations is currently only accessible in the Language folder inside of the game folder, but this often isn't convenient when the game files and the translations files are downloaded from different places. I often make a symlink to resolve this issue, but symlink support is dubious on Windows.
> Allow specifying where the languages folder is

- bench/rtp.cpp
- src/exe_reader.cpp
- src/exe_reader.h
- src/game_interpreter.cpp
- src/game_interpreter_control_variables.cpp
- src/game_system.h
- src/player.cpp
This game has various checks which makes the game fail to run with a loud jump scare when EasyRPG is detected...
```
// Maniac Patch version check
// This PR: Implemented in "Maniac Patch: Extract the patch version number out of the EXE section"
@> Control Variables: V[0104] = Version of Maniac Patch
@> Conditional Branch: Playtest mode is active
@> Conditional Branch: V[0104] != 230831
// Call Command (already supported)
@> Call Command: 10220, , [0, 104, 0, 0, 0, 80085]
// Useless Output check (This PR)
@> Conditional Branch: Can output file
// Tileset Get Game Info (added by jetrotal a while ago)
@> Get Game Info: Tileset ID -> V[0104]
// Interpreter State (recently added by florianessl)
@> Get Game Info: Interpreter, Current(0) -> V[0104]
// This is not supported because it uses a …
```
> Fixes for "OFF Forgotten Dreams"
